From clutch.prob_eff_lang.probblaze Require Export notation valgroup.


Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context {Leak Sender Receiver channel : label}.

  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).
  Definition enc : expr := λ: "pk" "m" "r" "s", let, ("g", "h", "u", "v") := "pk" in
                                                ("g"^"r" * "h"^"s", "m" * ("u"^"r") * ("v"^"s")).
  Definition dec : expr := λ: "x" "e", let, ("e0", "e1") := "e" in "e1" * ("e0"^- "x").
  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.

  Definition Protocol_Done (eff : label) (e : expr) : expr :=
    handle: e with effect eff "x", rec "k" => "k" #()%V | return "y" => "y" end.

  Definition OT_Real f : expr :=
    let, ("g0", "h0", "g1", "h1") := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in
    let: "crs" := ("g0", "h0", "g1", "h1") in
    handle: handle: f with
            | effect Receiver "b", "k" =>
                let: "x" := sample #()%V in
                let, ("gb", "hb") := if: "b" then ("g0", "h0") else ("g1", "h1") in
                let: "uv" := ("gb"^"x", "hb"^"x") in
                (do: channel (Send ("uv", bob)));;
                     let: "r" := (do: channel (RecvV bob)) in
                     match: "r" with
                       NONE => Protocol_Done Receiver ("k" NONE)
                     | SOME "cd" =>
                         let, ("cd0", "cd1") := "cd" in
                         let: "m" := if: "b" then (dec "x" "cd0") else (dec "x" "cd1") in
                         Protocol_Done Receiver ("k" (SOME "m"))
                     end 
             | return "y" => "y" end
    with
    | effect Sender "m", "k" =>
        let: "r" := (do: channel (Recv alice)) in
        match: "r" with
          SOME "uv" =>
            let, ("u", "v") := "uv" in 
            if: ("u" = #1) then Protocol_Done Sender ("k" #()%V) else
              let: "pk0" := ("g0", "h0", "u", "v") in
              let: "pk1" := ("g1", "h1", "u", "v") in
              let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
              let: "e0" := enc "pk0" "m0" "r0" "s0" in
              let: "e1" := enc "pk1" "m1" "r1" "s1" in
              (do: channel (Send (("e0", "e1"), alice)));;
              Protocol_Done Sender ("k" #()%V)
        | NONE => Protocol_Done Sender ("k" #()%V)
        end
    | return "y" => "y" end. 

  (* Assumes an authenticated channel *)
  Definition OT_Real_Receiver_Corrupted f (c : expr) : expr :=
    let, ("g0", "h0", "g1", "h1") := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in
    let: "crs" := ("g0", "h0", "g1", "h1") in
    handle: f "crs" with
    | effect Sender "m", "k" =>
        let: "r" := (do: channel (Recv alice)) in
        match: "r" with
          SOME "uv" =>
            let, ("u", "v") := "uv" in
            if: ("u" = #1) then Protocol_Done Sender ("k" #()%V) else
              let: "pk0" := ("g0", "h0", "u", "v") in
              let: "pk1" := ("g1", "h1", "u", "v") in
              let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
              let: "e0" := enc "pk0" "m0" "r0" "s0" in
              let: "e1" := enc "pk1" "m1" "r1" "s1" in
              (do: channel (Send (("e0", "e1"), alice)));;
             Protocol_Done Sender ("k" #()%V)
        | NONE => Protocol_Done Sender ("k" #()%V)
        end
    | return "y" => "y" end.

  Definition F_OT f : expr :=
    (λ: <>,
    let: "message0" := ref NONEV in
    let: "message1" := ref NONEV in

    let: "foth" := (λ: <>, handle: f with
                   (* The continuations should be incapsulated in Protocol_Done *)
                   | effect Sender "mm", "k" =>
                       (* Honest sender inlined in ideal functionality *)
                       let, ("m0", "m1") := "mm" in
                       "message0" <- "m0";; "message1" <- "m1";;
                       (do: Leak #()%V);;
                       Protocol_Done Sender ("k" #()%V) 
                   | return "y" => "y" end) in
    let: "fots" := (λ: "b", if: "b" then !"message0" else !"message1") in
    ("foth", "fots")).

  (* A simulator also simulating the authenticated channel *)
  Definition OT_SIM_Receiver_Corrupt (f : expr) : expr :=
    (* sampling crs with a trapdoor to compute b from (u,v) *)
    let, ("g0", "g1") := (g^(sample #()%V), g^(sample #()%V)) in
    let, ("t0", "t1") := (sample #()%V, sample #()%V) in
    let, ("h0", "h1") := ("g0"^"t0", "g1"^"t1") in
    let: "crs" := ("g0", "h0", "g1", "h1") in
    
    (* setting up *)
    let: "mb" := ref NONE in
    let: "b" := ref NONE in
    let: "s" := ref NONE in
    let: "e" := ref NONE in
    
    (* unfolding the ideal functionality - foth exposes the honest sender to the environment and allows Fot to leak information to SIM, fots allows SIM to ask for mb *)
    let, ("foth", "fots") := (F_OT (f "crs")) #()%V in

    handle: handle: "foth" #()%V with
    (* Continuations in the channel branch are allowed to try again, as in the ideal functionality of the AUTH channel. *)
    | effect channel "p", rec "k" =>
         match: "p" with
        (* SEND *)
         | InjL "payload" =>
             match: !"s" with
             | SOME "m" => "k" #()%V (* A message has already been sent *)
             | NONE =>
                 let, ("m", "dst") := "payload" in (* We know we only get messages from the Sender, so dst is always bob *)
                 let, ("u","v") := "m" in
                 let: "td" :=  if: "v" = ("u" ^ "t0") then #true else if: "v" = ("u"^"t1") then #false else #true in(* trapdoor - essentially if v = u^t0 then b = 0 otherwise b = 1 *)
                 "b" <- SOME "td";;
                 "s" <- SOME ("u", "v");;     (* Record that (u,v) has been sent *)
                 (do: channel "p");; (* Forward the message to simulate the network *)
                 "k" #()%V
             end   
         (* Recv *)
         | InjR "from" =>
             let: "r" := (do: channel (Recv "from")) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "x" => match: !"s" with
                           | NONE => "k" NONEV
                           | SOME "m" => match: !"e" with
                                         | NONE => "k" NONEV
                                         | SOME "ee" => "k" "ee"
                                         end
                           end
             end
         end
    | return "y" => "y"
    end with
    (* only the ideal functionality can use this effect *)
    | effect Leak "x", "k" =>  let: "r" := (do: channel (Recv alice)) in
                               match: "r" with
                               | NONE => "k" NONEV
                               | SOME "x" =>
                                   match: !"s" with
                                   | NONE => "k" NONEV
                                   | SOME "uv" => let, ("u","v") := "uv" in
                                                  match: !"b" with
                                                  | NONE => "k" NONEV
                                                  | SOME "b'" => let: "m" := "fots" "b'" in
                                                                 "mb" <- SOME "m";; 
                                                                 let, ("m0", "m1") := if: "b'" then ("m", #0) else (#0, "m") in
                                                                 let: "pk0" := ("g0", "h0", "u", "v") in
                                                                 let: "pk1" := ("g1", "h1", "u", "v") in
                                                                 let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
                                                                 let: "e0" := enc "pk0" "m0" "r0" "s0" in
                                                                 let: "e1" := enc "pk1" "m1" "r1" "s1" in
                                                                 "e" <- SOME ("e0", "e1");;
                                                                 (do: channel (Send (("e0", "e1"), alice)));;
                                                                 "k" #()%V
                                                  end
                                   end
                               end
  | return "y" => "y"
  end.

  (* A simulator that uses the authenticated channel *)
  Definition OT_SIM_Receiver_Corrupt_with_auth (f : expr) : expr :=
    (* sampling crs with a trapdoor to compute b from (u,v) *)
    let, ("g0", "g1") := (g^(sample #()%V), g^(sample #()%V)) in
    let, ("t0", "t1") := (sample #()%V, sample #()%V) in
    let, ("h0", "h1") := ("g0"^"t0", "g1"^"t1") in
    let: "crs" := ("g0", "h0", "g1", "h1") in
    
    (* setting up *)
    let: "b" := ref #false in    (* dummy value *)
        
    (* unfolding the ideal functionality - foth exposes the honest sender to the environment and allows Fot to leak information to SIM, fots allows SIM to ask for mb *)
    let, ("foth", "fots") := (F_OT (f "crs")) #()%V in

    handle: handle: "foth" #()%V with
    (* Continuations in the channel branch are allowed to try again, as in the ideal functionality of the AUTH channel. *)
    | effect channel "p", rec "k" =>
         match: "p" with
        (* SEND *)
         | InjL "payload" =>
             let, ("m", "dst") := "payload" in (* we only get messages from the Sender, so dst is always bob *)
             let, ("u","v") := "m" in
             (* trapdoor-essentially if v = u^t0 then b = 0 otherwise b = 1 *)
             let: "td" :=  if: "v" = ("u" ^ "t0") then #true else if: "v" = ("u"^"t1") then #false else #true in
             "b" <- "td";;
             (do: channel "p");; (* Forward the message to simulate the network *)
             "k" #()%V
             
           
         (* RECV - just forward receives *)
         | InjR "from" => let: "r" := (do: channel (Recv "from")) in "k" "r"
         end 
    | return "y" => "y"
    end with
    (* only the ideal functionality can use this effect *)
    | effect Leak "x", "k" =>  let: "r" := (do: channel (Recv alice)) in
                               match: "r" with
                               | NONE => "k" NONEV
                               | SOME "uv" => let, ("u","v") := "uv" in
                                              let: "mb" := "fots" !"b" in
                                              let, ("m0", "m1") := if: !"b" then ("mb", #0) else (#0, "mb") in
                                              let: "pk0" := ("g0", "h0", "u", "v") in
                                              let: "pk1" := ("g1", "h1", "u", "v") in
                                              let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
                                              let: "e0" := enc "pk0" "m0" "r0" "s0" in
                                              let: "e1" := enc "pk1" "m1" "r1" "s1" in
                                              (do: channel (Send (("e0", "e1"), alice)));;
                                              "k" #()%V
                                              end
                                   end
                               end
  | return "y" => "y"
  end.

End implementation.
