From clutch.prob_eff_lang.probblaze Require Export notation valgroup.
From clutch.prob_eff_lang.probblaze Require Import mutual_handlers_composition.

Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context {CRS Leak Sender Receiver channel : label}.

  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition gensample : expr := λ: <>, (rand #(n - 1)) + #(1%nat).
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).
  Definition enc : expr := λ: "pk" "m" "r" "s", let, ("g", "h", "u", "v") := "pk" in
                                                ("g"^"r" · "h"^"s", "m" · ("u"^"r") · ("v"^"s")).
  Definition dec : expr := λ: "x" "e", let, ("e0", "e1") := "e" in "e1" · ("e0"^- "x").
  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.

  Definition Protocol_Done (eff : label) (e : expr) : expr :=
    handle: e with effect eff "x", rec "k" => "k" #()%V | return "y" => "y" end.

  (* This is wrapped around the protocol like F_AUTH and provides the ideal functionality of a crs *)
  Definition F_CRS : val :=
    (λ: "f",
    (* We should  add a check that the last two samples are distinct or add a bit of error to ensure it *)
    let: "crs" := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in 
    handle: "f" #()%V with
    | effect CRS "x", rec "k" => "k" "crs"
    | return "y" => "y" end).
                                                                                            
  (* Assumes an authenticated channel *)
  Definition OT_Real_Receiver_Corrupted : val :=
    (λ: "f" "chan",
       let, ("doRecv", "doSend") := "chan" in
       effect "sender" 
       let: "doSender" := (λ: "mm", do: "sender" "mm") in
       handle: "f" "doSender"  with
       | effect "sender" "mm", "k" =>
           let, ("h1", "h0", "g1", "g0") := (do: CRS #()%V) in
           let, ("m0", "m1") := "mm" in
           let: "r" := "doRecv" alice in
           match: "r" with
             SOME "uv" =>
               let, ("u", "v") := "uv" in
               if: veq "u" vunit then Protocol_Done Sender ("k" #()%V) else 
                 let: "pk0" := ("g0", "h0", "u", "v") in
                 let: "pk1" := ("g1", "h1", "u", "v") in
                 let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
                 let: "e0" := enc "pk0" "m0" "r0" "s0" in
                 let: "e1" := enc "pk1" "m1" "r1" "s1" in
                 "doSend" (("e0","e1"), alice);;
                 Protocol_Done Sender ("k" #()%V)
           | NONE => Protocol_Done Sender ("k" #()%V)
           end
       | return "y" => "y" end).
  

  Definition store_if_none : val := λ: "l" "m", match: !"l" with
                                                 | SOME "x" => #()%V
                                                 | NONE => "l" <- SOME "m"
                                                 end.

  (* the functionality is setup with two locations apriori *)
  Definition F_OT (message0 message1 : locations.loc) : expr :=
    effect "sender"
      effect "receiver"
      let: "doSender" := (λ: "mm", do: "sender" "mm") in
      let: "doReceiver" := (λ: "b", do: "receiver" "b") in
      λ: "f" "doLeak", 
      handle: handle: "f" ("doReceiver", "doSender") with
      | effect "sender" "mm", "k" => let, ("m0", "m1") := "mm" in (store_if_none #message0 "m0");; (store_if_none #message1 "m1");; 
                                                                  ("doLeak" bob);; Protocol_Done Sender ("k" #()%V)
      | return "y" => "y" end with
      | effect "receiver" "b", "k" => ("doLeak" alice);; "k" (if: "b" then !#message0 else !#message1)
      | return "y" => "y" end.

  Definition OT_SIM_logic : expr :=
    effect "leak" 
      let: "doLeak" := (λ: "p", do: "leak" "p") in

      λ: "g0" "g1" "t0" "t1" "h0" "h1" "mhandler" "f" "effs",
      let, ("doSend", "doRecv", "doReceiver") := "effs" in
      handle: "f" "doLeak" with
      | effect "leak" "x", "k" => "mhandler"
           (λ: <>, (λ: "x" "k" , 
            match: "x" with
            | InjL <> => 
                let: "r" := "doRecv" alice in
                match: "r" with
                | NONE => "k" NONEV
                | SOME "uv" => let, ("u","v") := "uv" in
                               if: veq "u" vunit then "k" #()%V else
                                 (* in paper: if v = u^t0 then true else if v = u^t1 then false else false *)
                                 let: "td" :=  if: veq "v" ("u" ^ "t0") then #true else #false in
                                 (* handle the other leakage -- this is not too pretty *)
                                 let: "mb" := "doReceiver" "td" in
                                 let: "mb" := match: "mb" with
                                              | NONE => "k" #()%V
                                              | SOME "m" => "m"
                                              end in 
                                 (* replace #1 with sample to get a random group element or just use the unit of the group *)
                                 let, ("m0", "m1") := if: "td" then ("mb", g ^ #(Z.of_nat 1)) else (g ^ #(Z.of_nat 1), "mb") in
                                 let: "pk0" := ("g0", "h0", "u", "v") in
                                 let: "pk1" := ("g1", "h1", "u", "v") in
                                 let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
                                 let: "e0" := enc "pk0" "m0" "r0" "s0" in
                                 let: "e1" := enc "pk1" "m1" "r1" "s1" in
                                 ("doSend" (("e0", "e1"), alice));;
                                 "k" #()%V
                end
            | InjR <> => "k" #()%V
            end) "x" "k")
    | return "y" => "y"
     end.

  Definition mut_handler_constructor : val :=
    λ: "h1" "h2",
      
      rec: "mhandler" "f" :=
      (* instantiate the first handler-branch with the mutually recursive handler *)
      let: "mh1" := "h1" "mhandler" in 
      (* handle: handle: f with ... with ... *)
      "mh1" (λ: <>, "h2" "f").

  Definition OT_SIM : val := 
    (λ: "FOT" "f", 
    (* sampling crs with a trapdoor to compute b from (u,v) *)
    let, ("g1", "g0") := (g^(sample #()%V), g^(sample #()%V)) in
    (* as in the real protocol, these should be distinct *)
    let, ("t1", "t0") := (sample #()%V, sample #()%V) in
    let, ("h0", "h1") := ("g0"^"t0", "g1"^"t1") in
    let: "crs" := ("h1", "h0", "g1", "g0") in
    
    let: "mh" := mut_handler_constructor (OT_SIM_logic "g0" "g1" "t0" "t1" "h0" "h1") "FOT" in 
    effect "crs" 
    let: "doCRS" := (λ: <>, do: "crs" #()%V) in
    handle: "mh" "f" "doCRS" with
    | effect "crs" "x", rec "k" => "k" "crs"
    | return "y" => "y" end). 

  Definition OT_SIM_FOT message0 message1 : val :=
    (λ: "f", OT_SIM (F_OT message0 message1) "f"). 
                              
End implementation.
