From clutch.prob_eff_lang.probblaze Require Export notation valgroup.
From clutch.prob_eff_lang.probblaze Require Import mutual_handlers_composition.

Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  
  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition gensample : expr := λ: <>, (rand #(n - 1)) + #(1%nat).
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).
  Definition enc : expr := λ: "pk" "m" "r" "s", let, ("g", "h", "u", "v") := "pk" in
                                                ("g"^"r" · "h"^"s", "m" · ("u"^"r") · ("v"^"s")).
  Definition dec : expr := λ: "x" "e", let, ("e0", "e1") := "e" in "e1" · ("e0"^- "x").
  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.

  Definition Protocol_Done (eff : eff_val) (e : expr) : expr :=
    handle: e with effect eff "x", rec "k" => "k" #()%V | return "y" => "y" end.

  (* This is wrapped around the protocol like F_AUTH and provides the ideal functionality of a crs *)
  Definition F_CRS : val :=
    (λ: "f",
    (* We should  add a check that the last two samples are distinct or add a bit of error to ensure it *)
    let: "crs" := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in
    effect "getCRS"
    let: "doGetCRS" := (λ: <>, do: (EffName "getCRS") #()%V) in
    handle: "f" "doGetCRS" with
    | effect (EffName "getCRS") "x", rec "k" => "k" "crs"
    | return "y" => "y" end).


  Definition OT_Real_Sender_corrupt : val :=
    λ: "f" "effs",
      let, ("doCRS", "doSend", "doRecv") := "effs" in
      effect "receiver"
        let: "doReceiver" := (λ: "b", do: (EffName "receiver") "b") in
        handle: "f" ("doReceiver", "effs") with
    | effect (EffName "receiver") "b", "k" =>
        let, ("h1", "h0", "g1", "g0") := ("doCRS" #()%V) in
        (* to avoid sampling the unit, as otherwise the protocol fails *)
        let: "x" := sample #()%V in
        let, ("gb", "hb") := if: "b" then ("g0", "h0") else ("g1", "h1") in
        let: "uv" := ("gb"^"x", "hb"^"x") in
        ("doSend" ("uv", bob));;
        let: "r" := ("doRecv" bob) in
        match: "r" with
          NONE => Protocol_Done (EffName "receiver") ("k" NONE)
        | SOME "cd" =>
            let, ("cd0", "cd1") := "cd" in
            let: "m" := if: "b" then (dec "x" "cd0") else (dec "x" "cd1") in
            Protocol_Done (EffName "receiver") ("k" (SOME "m"))
        end
    | return "y" => "y" end.


  Definition store_if_none : val := λ: "l" "m", match: !"l" with
                                                | SOME "x" => #()%V
                                                | NONE => "l" <- SOME "m"
                                                end.

  Definition mut_handler : val := 
    λ: "idealhandler" "simhandler", 
       effect "ideal"
       effect "leak"
       let: "doReceiver" := (λ: "b", do: "ideal" (InjL "b")) in
       let: "doSender" := (λ: "mm", do: "ideal" (InjR "mm")) in
       let: "doLeak" := (λ: "p", do: "leak" "p") in
       let: "h1" := "idealhandler" "doLeak" in
       let: "h2" := "simhandler" "doSender" in
       rec: "mh" "f" :=
       handle: handle: "f" "doReceiver" with
       | effect "ideal" "x", "k" => "idealhandler" "x" "k"
       | return "y" => "y" end with
       | effect "leak" "x", "k" => "mh" (λ: <>, "simhandler" "x" "k")
       | return "y" => "y" end.

  Definition idealhandler : expr :=
    let: "l0" := ref NONE in
    let: "l1" := ref NONE in
    λ: "doLeak" "x" "k",
      match: "x" with
      | InjL "b" => ("doLeak" alice) ;; "k" (if: "b" then !"l0" else !"l1")
      | InjR "mm" => let, ("m0", "m1") := "mm" in (store_if_none "l0" "m0");; (store_if_none "l1" "m1");; 
                                                  ("doLeak" bob);; "k" #()%V
      end.

  Definition simhandler : val :=
    λ: "y" "crs" "doSend" "doRecv" "doSender" "x" "k",
      let, ("h1", "h0", "g1", "g0") := "crs" in
      match: "x" with
      | InjL <> => "k" NONEV
      | InjR <> => 
          let: "α1" := sample #()%V in
          let: "α0" := "α1" * "y" in
          let: "uv" := ("g0"^"α0", "h0"^"α0") in
          ("doSend" ("uv", bob));; 
          let: "r" := ("doRecv" bob) in
          match: "r" with 
          | NONE => "k" NONEV
          | SOME "mm" => 
              let, ("cd0","cd1") := "mm" in
              let, ("c0", "d0") := "cd0" in 
              let, ("c1", "d1") := "cd1" in
              let, ("m0", "m1") := ("d0" · ("c0"^- "α0"),"d1" · ("c1"^- "α1")) in
              ("doSender" ("m0","m1"));;
              "k" #()%V
          end 
      end.

  Definition OT_SIM_FOT_thunk : val :=
    λ: "f" "effs",
      let, ("doSend", "doRecv") := "effs" in
      let: "g0" := g^(sample #()%V) in
      let: "y" := sample #()%V in
      let: "g1" := "g0"^"y" in
      let: "x" := sample #()%V in 
      let, ("h0", "h1") := ("g0"^"x", "g1"^"x") in
      let: "crs" := ("h1", "h0", "g1", "g0") in
      effect "CRS" 
      let: "doCRS" := (λ: <>, do: "CRS" #()%V) in
      let: "mh" := mut_handler idealhandler (simhandler "y" "crs" "doSend" "doRecv") in
      handle: "mh" "f" with
      | effect "CRS" "x", rec "k" => "k" "crs"
      | return "y" => "y" end. 
      


End implementation.

Section DDH_reduction.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

  #[local] Notation n := (S n'').

  (* This is wrapped around the protocol like F_AUTH and provides the ideal functionality of a crs *)
  Definition reduction : val :=
    (λ: "DH" "f",
    let: "crs" := "DH" #()%V in
    effect "CRS" 
    let: "doCRS" := (λ: <>, do: "CRS" #()%V) in
    handle: "f" "doCRS" with
    | effect "CRS" "x", rec "k" => "k" "crs"
    | return "y" => "y" end).

  Definition DH_real : val :=
    λ: <>,
    let: "g" := g ^ sample #()%V in
    let: "a" := sample #()%V in
    let: "b" := sample #()%V in
    ("g"^("a" * "b"), "g"^"b", "g"^"a", "g").

  Definition DH_rand : val :=
    λ: <>,
    let: "g" := g ^ sample #()%V in
    let: "a" := sample #()%V in
    let: "b" := sample #()%V in
    let: "c" := sample #()%V in
    ( "g"^"c", "g"^"b", "g"^"a", "g").

End DDH_reduction.
