From clutch.prob_eff_lang.probblaze Require Export notation valgroup.


Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context {CRS Leak Sender Receiver channel : label}.

  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition gensample : expr := λ: <>, (rand #(n - 1)) + #(1%nat).
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).
  Definition enc : expr := λ: "pk" "m" "r" "s", let, ("g", "h", "u", "v") := "pk" in
                                                ("g"^"r" · "h"^"s", "m" · ("u"^"r") · ("v"^"s")).
  Definition dec : expr := λ: "x" "e", let, ("e0", "e1") := "e" in "e1" · ("e0"^- "x").
  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.

  Definition Protocol_Done (eff : label) (e : expr) : expr :=
    handle: e with effect eff "x", rec "k" => "k" #()%V | return "y" => "y" end.

  (* This is wrapped around the protocol like F_AUTH and provides the ideal functionality of a crs *)
  Definition F_CRS f : expr :=
    (* We should  add a check that the last two samples are distinct or add a bit of error to ensure it *)
    let: "crs" := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in 
    handle: f with
    | effect CRS "x", rec "k" => "k" "crs"
    | return "y" => "y" end.
                                                                                            
  (* Assumes an authenticated channel *)
  Definition OT_Real_Receiver_Corrupted f : expr :=
    handle: f  with
    | effect Sender "mm", "k" =>
        let, ("h1", "h0", "g1", "g0") := (do: CRS #()%V) in
        let, ("m0", "m1") := "mm" in
        let: "r" := (do: channel (Recv alice)) in
        match: "r" with
          SOME "uv" =>
            let, ("u", "v") := "uv" in
            if: veq "u" vunit then Protocol_Done Sender ("k" #()%V) else 
              let: "pk0" := ("g0", "h0", "u", "v") in
              let: "pk1" := ("g1", "h1", "u", "v") in
              let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
              let: "e0" := enc "pk0" "m0" "r0" "s0" in
              let: "e1" := enc "pk1" "m1" "r1" "s1" in
              (do: channel (Send (("e0", "e1"), alice)));;
             Protocol_Done Sender ("k" #()%V)
        | NONE => Protocol_Done Sender ("k" #()%V)
        end
    | return "y" => "y" end.
  
  (* Dummy sender that just forwards messages from Env to F_OT *)
  Definition D_Sender f : val :=
    (λ: "FOT", 
       handle: f with
    | effect Sender "mm", "k" => let, ("m0", "m1") := "mm" in "FOT" "m0" "m1";; Protocol_Done Sender ("k" #()%V)
    | return "y" => "y"
     end).

  Definition store_if_none : val := λ: "l" "m", match: !"l" with
                                                 | SOME "x" => #()%V
                                                 | NONE => "l" <- SOME "m"
                                                 end.
  
  Definition F_OT : val :=
    (λ: <>,
       let: "message0" := ref NONEV in
       let: "message1" := ref NONEV in
       let: "fots" := (λ: "m0" "m1", (store_if_none "message0" "m0");; (store_if_none "message1" "m1");; (do: Leak bob)) in
       let: "fotr" := (λ: "b", (do: Leak alice) ;; if: "b" then !"message0" else !"message1") in
       ("fots", "fotr")).

 

  (* A simulator that uses the authenticated channel *)
  (* Need to figure out how to handle the cont when the protocol has been executed (eg. Protocol_Done) *)
  (* The simulator implements its own functionality for CRS *)
  Definition OT_SIM_Receiver_Corrupt_with_auth (f : expr) : expr :=
    (* sampling crs with a trapdoor to compute b from (u,v) *)
    let, ("g1", "g0") := (g^(sample #()%V), g^(sample #()%V)) in
    (* as in the real protocol, these should be distinct *)
    let, ("t1", "t0") := (sample #()%V, sample #()%V) in
    let, ("h0", "h1") := ("g0"^"t0", "g1"^"t1") in
    let: "crs" := ("h1", "h0", "g1", "g0") in
           
    (* unfolding the ideal functionality - foth exposes the honest sender to the environment and allows Fot to leak information to SIM, fots allows SIM to ask for mb *)
    let, ("fots", "fotr") := F_OT #()%V in

    (* since (D_Sender f) is a value, "crs" is technically not substituted into f when sampled, because of our implementation of subst *)
   handle: handle: (D_Sender f) "fots" with
    (* only the ideal functionality can use this effect *) 
    | effect Leak "x", "k" =>
        match: "x" with
        | InjL <> => 
            let: "r" := (do: channel (Recv alice)) in
            match: "r" with
            | NONE => "k" NONEV
            | SOME "uv" => let, ("u","v") := "uv" in
                           if: veq "u" vunit then "k" #()%V else
                             (* in paper: if v = u^t0 then true else if v = u^t1 then false else false *)
                           let: "td" :=  if: veq "v" ("u" ^ "t0") then #true else #false in
                           (* handle the other leakage -- this is not too pretty *)
                           let: "mb" := (handle: "fotr" "td" with effect Leak "x", "k" => "k"  #()%V | return "y" => "y" end) in
                           let: "mb" := match: "mb" with
                                        | NONE => "k" #()%V
                                        | SOME "m" => "m"
                                        end in 
                             (* replace #1 with sample to get a random group element or just use the unit of the group *)
                           let, ("m0", "m1") := if: "td" then ("mb", g ^ #(Z.of_nat 1)) else (g ^ #(Z.of_nat 1), "mb") in
                           let: "pk0" := ("g0", "h0", "u", "v") in
                           let: "pk1" := ("g1", "h1", "u", "v") in
                           let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
                           let: "e0" := enc "pk0" "m0" "r0" "s0" in
                           let: "e1" := enc "pk1" "m1" "r1" "s1" in
                           (do: channel (Send (("e0", "e1"), alice)));;
                           "k" #()%V
            end
        | InjR <> => "k" #()%V
        end 
  | return "y" => "y"
  end with
  (* the adversary (f) can throw CRS as well as Send/Recv *)
  | effect CRS "x", rec "k" => "k" "crs"
  | return "y" => "y" end.
                              
End implementation.
