From clutch.prob_eff_lang.probblaze Require Export notation valgroup.


Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).
  Definition enc : expr := λ: "pk" "m" "r" "s", let, ("g", "h", "u", "v") := "pk" in
                                                ("g"^"r" * "h"^"s", "m" * ("u"^"r") * ("v"^"s")).
  Definition dec : expr := λ: "x" "e", let, ("e0", "e1") := "e" in "e1" * ("e0"^- "x").
  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.

  Definition OT_Real (Sender Receiver channel : label) f : expr :=
    let, ("g0", "h0", "g1", "h1") := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in
    let: "crs" := ("g0", "h0", "g1", "h1") in
    handle: handle: (f "crs") with
            | effect Receiver "b", "k" =>
                let: "x" := sample #()%V in
                let, ("gb", "hb") := if: "b" then ("g0", "h0") else ("g1", "h1") in
                let: "uv" := ("gb"^"x", "hb"^"x") in
                (do: channel (Send ("uv", bob)));;
                     let: "r" := (do: channel (RecvV bob)) in
                     match: "r" with
                       NONE => "k" NONE
                     | SOME "cd" =>
                         let, ("cd0", "cd1") := "cd" in
                         let: "m" := if: "b" then (dec "x" "cd0") else (dec "x" "cd1") in
                         "k" (SOME "m")
                     end 
             | return "y" => "y" end
    with
    | effect Sender "m", "k" =>
        let: "r" := (do: channel (Recv alice)) in
        match: "r" with
          SOME "uv" =>
            if: ("u" = #1) then "k" #()%V else
              let: "pk0" := ("g0", "h0", "uv") in
              let: "pk1" := ("g1", "h1", "uv") in
              let, ("r0", "s0", "r1", "s1") := (sample #()%V, sample #()%V, sample #()%V, sample #()%V) in
              let: "e0" := enc "pk0" "m0" "r0" "s0" in
              let: "e1" := enc "pk1" "m1" "r1" "s1" in
              (do: channel (Send (("e0", "e1"), alice)));;
              "k" #()%V
        | NONE => "k" #()%V
        end
    | return "y" => "y" end. 

