From clutch.prob_eff_lang.probblaze Require Export notation valgroup.
From clutch.prob_eff_lang.probblaze Require Import mutual_handlers_composition.

Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  
  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition gensample : expr := λ: <>, (rand #(n - 1)) + #(1%nat).
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).
  Definition enc : expr := λ: "pk" "m" "r" "s", let, ("g", "h", "u", "v") := "pk" in
                                                ("g"^"r" · "h"^"s", "m" · ("u"^"r") · ("v"^"s")).
  Definition dec : expr := λ: "x" "e", let, ("e0", "e1") := "e" in "e1" · ("e0"^- "x").
  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.

  Definition Protocol_Done (eff : label) (e : expr) : expr :=
    handle: e with effect eff "x", rec "k" => "k" #()%V | return "y" => "y" end.

  (* This is wrapped around the protocol like F_AUTH and provides the ideal functionality of a crs *)
  Definition F_CRS CRS : val :=
    (λ: "f",
    (* We should  add a check that the last two samples are distinct or add a bit of error to ensure it *)
    let: "crs" := (g^(sample #()%V), g^(sample #()%V), g^(sample #()%V), g^(sample #()%V)) in 
    handle: "f" #()%V with
    | effect CRS "x", rec "k" => "k" "crs"
    | return "y" => "y" end).


   Definition OT_Real_Sender_corrupt (CRS Receiver channel : label) : val :=
     λ: "f" <>,
    (* This should be encapsulated in the CRS effect *)
    handle: "f" #()%V with
    | effect Receiver "b", "k" =>
        let, ("h1", "h0", "g1", "g0") := (do: CRS #()%V) in
        (* to avoid sampling the unit, as otherwise the protocol fails *)
        let: "x" := sample #()%V in
        let, ("gb", "hb") := if: "b" then ("g0", "h0") else ("g1", "h1") in
        let: "uv" := ("gb"^"x", "hb"^"x") in
        (do: channel (Send ("uv", bob)));;
        let: "r" := (do: channel (RecvV bob)) in
        match: "r" with
          NONE => Protocol_Done Receiver ("k" NONE)
        | SOME "cd" =>
            let, ("cd0", "cd1") := "cd" in
            let: "m" := if: "b" then (dec "x" "cd0") else (dec "x" "cd1") in
            Protocol_Done Receiver ("k" (SOME "m"))
        end 
    | return "y" => "y" end.


   Definition store_if_none : val := λ: "l" "m", match: !"l" with
                                                 | SOME "x" => #()%V
                                                 | NONE => "l" <- SOME "m"
                                                 end.

  (* the functionality is setup with two locations apriori *)
  Definition F_OT (Sender Receiver Leak : label)  (message0 message1 : locations.loc) : val :=
    (λ: "f", 
        handle: handle: "f" #()%V with
        | effect Sender "mm", "k" => let, ("m0", "m1") := "mm" in (store_if_none #message0 "m0");; (store_if_none #message1 "m1");; 
                                                                  (do: Leak bob);; Protocol_Done Sender ("k" #()%V)
        | return "y" => "y" end with
        | effect Receiver "b", "k" => (do: Leak alice);; Protocol_Done Receiver ("k" (if: "b" then !#message0 else !#message1))
        | return "y" => "y" end).


  
  Definition OT_SIM_Sender_corrupt_logic (Leak channel Sender : label) : val :=
    (λ: "y" "crs" "mhandler" "f",
       let, ("h1","h0", "g1","g0") := "crs" in
       handle: "f" #()%V with
    | effect Leak "x", "k" => "mhandler"
                                (λ: <>, (λ: "x" "k" , 
                                           match: "x" with
                                           | InjL <> => "k" #()%V
                                           | InjR <> => 
                                               let: "α1" := sample #()%V in
                                               let: "α0" := "α1" * "y" in
                                               let: "uv" := ("g0"^"α0", "h0"^"α0") in
                                               (do: channel (Send ("uv", bob)));; 
                                               let: "r" := (do: channel (Recv bob)) in
                                               match: "r" with 
                                               | NONE => "k" NONEV
                                               | SOME "mm" => 
                                                   let, ("cd0","cd1") := "mm" in
                                                   let, ("c0", "d0") := "cd0" in 
                                                   let, ("c1", "d1") := "cd1" in
                                                   let, ("m0", "m1") := ("d0" · ("c0"^- "α0"),"d1" · ("c1"^- "α1")) in
                                                   (do: Sender ("m0","m1"));;
                                                   "k" #()%V
                                               end 
                                           end ) "x" "k")
    | return "y" => "y"
     end).


  
  Definition OT_SIM CRS Leak channel Sender : val := 
    (λ: "FOT" "f", 
    let: "g0" := g^(sample #()%V) in
    let: "y" := sample #()%V in
    let: "g1" := "g0"^"y" in
    let: "x" := sample #()%V in 
    let, ("h0", "h1") := ("g0"^"x", "g1"^"x") in
    let: "crs" := ("h1", "h0", "g1", "g0") in
    
    let: "mh" := mut_handler_constructor (OT_SIM_Sender_corrupt_logic Leak channel Sender "y" "crs") "FOT" in 
    handle: "mh" "f" with
    | effect CRS "x", rec "k" => "k" "crs"
    | return "y" => "y" end). 

  Definition OT_SIM_FOT channel CRS Sender Receiver Leak message0 message1 : val :=
    (λ: "f", OT_SIM CRS Leak channel Sender (F_OT Sender Receiver Leak  message0 message1) "f"). 

End implementation.

Section DDH_reduction.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

  #[local] Notation n := (S n'').

  (* This is wrapped around the protocol like F_AUTH and provides the ideal functionality of a crs *)
  Definition reduction CRS : val :=
    (λ: "DH" "f",
    let: "crs" := "DH" #()%V in
    handle: "f" #()%V with
    | effect CRS "x", rec "k" => "k" "crs"
    | return "y" => "y" end).

  Definition DH_real : val :=
    λ: <>,
    let: "g" := g ^ sample #()%V in
    let: "a" := sample #()%V in
    let: "b" := sample #()%V in
    ("g"^("a" * "b"), "g"^"b", "g"^"a", "g").

  Definition DH_rand : val :=
    λ: <>,
    let: "g" := g ^ sample #()%V in
    let: "a" := sample #()%V in
    let: "b" := sample #()%V in
    let: "c" := sample #()%V in
    ( "g"^"c", "g"^"b", "g"^"a", "g").

End DDH_reduction.
