From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances sem_types
  sem_def sem_row
  tactics.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_thunk_receiver_corrupt ot_bijection.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.

(* Import valgroup_notation. *)
Import valgroup_tactics.

Section resources.
  Context `{!probblazeRGS Σ}.
  Context `{!inG Σ (dfrac_agreeR valO)}.

  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition crs_empty γ := own γ (to_dfrac_agree (DfracOwn 1) #()%V).
  Definition crs γ v := own γ (to_dfrac_agree (DfracDiscarded) v).
  
  Lemma crs_alloc : ⊢ |==> ∃ γ, crs_empty γ.
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma crs_upd γ v : ⊢ crs_empty γ -∗ |==>  crs γ v.
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma crs_agree γ v v' :
    ⊢ crs γ v -∗ crs γ v' -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

End resources.

Section theories.
 Context `{!probblazeRGS Σ}.
 Context `{!inG Σ (dfrac_agreeR valO)}.
 Context {vg : val_group}.           (* A group on a subset of values. *)
 Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
 Context {G : clutch_group (vg:=vg) (cg:=cg)}.
 Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

 (* Theories for the Receiver *)
  (*------------------------------------------------------------*)

  Program Definition ReceiverTheory_to_sig (RECVl RECVr : label) : iThy Σ :=
    λ e1 e2, (λne Q, ∃ b : bool,
                 ⌜ e1 = do: RECVl (InjLV #b) ⌝%E ∗
                 ⌜ e2 = do: RECVr (InjLV #b) ⌝%E ∗
                 ((Q NONEV NONEV) ∗ (∀ m : vgG, Q (SOMEV m) (SOMEV m)) )  
             )%I.
  Next Obligation. solve_proper. Qed.
  
  Program Definition recvmono (RECVl RECVr : label) :=  {| pmono_prot_car := @ReceiverTheory_to_sig RECVl RECVr; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. 
    iIntros (????) "#HΦ (%&->&->&(H1&H2))"; iExists _; repeat iSplit; try done. iSplitL "H1"; [by iApply "HΦ"|].
    iIntros (m); by iApply "HΦ".
    (* iSplitL "H2"; [iIntros (m)|]; by iApply "HΦ". *)
  Qed. 

  Definition recv (RECVl RECVr : label) := @SemSig Σ (recvmono RECVl RECVr) (RECVl,RECVr).
  
  Program Definition recvrow RECVl RECVr LEAKr := SemRow [([RECVl],[RECVr;LEAKr],recv RECVl RECVr)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition recvrow2 RECVl RECVr := SemRow [([RECVl],[RECVr],recv RECVl RECVr)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_.
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H".
  Qed.

  (* Mirrored receiver row: the LEAK label sits on the left, for the
     refinements where the simulator runs on the left-hand side. *)
  Program Definition recvrowl RECVl RECVr LEAKl := SemRow [([RECVl;LEAKl],[RECVr],recv RECVl RECVr)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_.
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H".
  Qed.

  (* Theories for the Sender *)
  (*------------------------------------------------------------*)

 Program Definition SenderTheoryR (SENDERl SENDERr : label) : iThy Σ :=
    λ e1 e2, (λne Q, ∃ g1 g2 g1' g2', ℕ%T g1 g2 ∗ ℕ%T g1' g2' ∗
                 ⌜ e1 = do: SENDERl (g1,g1')%V ⌝%E ∗
                 ⌜ e2 = do: SENDERr (InjRV (g2, g2')) ⌝%E ∗
                 Q #()%V #()%V
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition sendermono (SENDERl SENDERr : label) :=  {| pmono_prot_car := @SenderTheoryR SENDERl SENDERr; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. 
    iIntros (????) "#HΦ (%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ)"; iExists _,_,_,_; repeat iSplit; try done.
    1,2 : by iExists _.
    by iApply "HΦ".
  Qed. 

  Definition sender (SENDERl SENDERr : label) := @SemSig Σ (sendermono SENDERl SENDERr) (SENDERl,SENDERr).
  
  Program Definition senderrow SENDERl SENDERr LEAK := SemRow [([SENDERl],[SENDERr;LEAK],sender SENDERl SENDERr)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition senderrow2 SENDERl SENDERr := SemRow [([SENDERl],[SENDERr],sender SENDERl SENDERr)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed.

  Program Definition SenderTheoryL (SENDERl SENDERr : label) : iThy Σ :=
    λ e1 e2, (λne Q, ∃ g1 g2 g1' g2', ℕ%T g1 g2 ∗ ℕ%T g1' g2' ∗
                 ⌜ e1 = do: SENDERl (InjRV (g1,g1')) ⌝%E ∗
                 ⌜ e2 = do: SENDERr (g2, g2')%V ⌝%E ∗
                 Q #()%V #()%V
             )%I.
  Next Obligation. solve_proper. Qed.

 Program Definition sendermonol (SENDERl SENDERr : label) :=  {| pmono_prot_car := @SenderTheoryL SENDERl SENDERr; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. 
    iIntros (????) "#HΦ (%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ)"; iExists _,_,_,_; repeat iSplit; try done.
    1,2 : by iExists _.
    by iApply "HΦ".
  Qed. 

  Definition senderl (SENDERl SENDERr : label) := @SemSig Σ (sendermonol SENDERl SENDERr) (SENDERl,SENDERr).
  
  Program Definition senderrowl SENDERl SENDERr LEAK := SemRow [([SENDERl;LEAK],[SENDERr],senderl SENDERl SENDERr)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition senderrowl2 SENDERl SENDERr := SemRow [([SENDERl],[SENDERr],senderl SENDERl SENDERr)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed.

  (* Theories for the CRS *)
  (*------------------------------------------------------------*)


  Program Definition CRSThy (CRSl CRSr : label) {γcrs}: iThy Σ :=
    λ e1 e2, (λne Q,            (* this resource we need to keep as a proof tool *)
                (⌜ e1 = do: CRSl #()%V ⌝%E ∗ ⌜ e2 = do: CRSr #()%V ⌝%E ∗ (∀ v, crs γcrs v -∗ Q (Val v) (Val v))))%I.
  Next Obligation. solve_proper. Qed.

  Program Definition crsmono (CRSl CRSr : label) γcrs :=  {| pmono_prot_car := @CRSThy CRSl CRSr γcrs; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ???. 
    iIntros (????) "#HΦ (->&->&H)"; repeat iSplit; try done; iIntros (?) "Hcrs"; iApply "HΦ"; by iApply "H".
  Qed. 

  Definition crs_sig (CRSl CRSr : label) γcrs := @SemSig Σ (crsmono CRSl CRSr γcrs) (CRSl,CRSr).
  
  Program Definition crsrow CRSl CRSr γcrs := SemRow [([CRSl],[CRSr],crs_sig CRSl CRSr γcrs)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  (* allows the real protocol (LHS) to throw additional CRS operations *)
  Program Definition CRSThyL (CRSl : label) {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e1 = do: CRSl #()%V ⌝%E ∗ (∀ v, crs γcrs v -∗ Q (Val v) e2)))%I.
  Next Obligation. solve_proper. Qed.

  Program Definition CRSThyR crs1 {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e2 = do: crs1 #()%V ⌝%E ∗ (∀ v, crs γcrs v -∗ ▷ Q e1 (Val v))))%I.
  Next Obligation. solve_proper. Qed.

End theories.

Section lemmas.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

  Lemma fin_not_0 (x : fin n) : x ∉ [0%fin] → (0 < x)%nat.
  Proof using G n_prime.
    intros Hin. apply Nat.neq_0_le_1. intros Hcontra.
    apply Hin. set_unfold. left. apply fin_to_nat_inj. done.
  Qed. 
  
  Lemma f_cancel_g (x : fin n) y :
    x ∉ [0%fin] →
    (y < n)%nat →
    (g ^+ x ^+ f n'' x y = g ^+ y)%g.
  Proof using G n_prime.
    intros Hxin Hlt.
    rewrite -expgM. unfold f.
    apply Nat.ltb_lt in Hlt. erewrite Hlt.
    rewrite -(@expg_mod _ n (ssrnat.muln x (div.modn (ssrnat.muln y (ssrnat.expn x n'')) n))).
    2 : rewrite -g_nontriv; apply expg_order.
    rewrite crs_bij_cancel; [|done | |].
    3 : pose proof (fin_to_nat_lt x) as Hg0le; apply Rcomplements.SSR_leq; lia.
    2 : { apply Rcomplements.SSR_leq. by apply fin_not_0. }
    rewrite expg_mod; [done|].
    rewrite -g_nontriv; apply expg_order.
  Qed.

  Lemma Fp_of_fin_ne_zero_2 (t : fin n) :
    t ≠ nat_to_fin (Nat.lt_0_succ (S n'')) → ~~ (@eqtype.eq_op (fintype.fintype_ordinal__canonical__eqtype_Equality (S (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg)))))))) (Fp_of_fin t) (@nmodule.Algebra.zero (zmodp.fintype_ordinal__canonical__Algebra_BaseAddUMagma (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg))))))))) = true.
  Proof using n_prime.
    intros Ht. 
    eapply eqtype.contraNneq.
    2 : { apply negb_true_iff. done. }
    intros. unfold Fp_of_fin in H.  
    have Hnat := f_equal (@fintype.nat_of_ord _) H.
    rewrite /= zmodp.Zp_nat /= in Hnat.
    have Hfp : S (S (zmodp.Zp_trunc (prime.pdiv n))) = n. { rewrite zmodp.Fp_cast; done. }
    rewrite Hfp in Hnat.
    have Hlt := fin_to_nat_lt t.
    rewrite div.modn_small in Hnat. 2: apply Rcomplements.SSR_leq; exact Hlt.
    exfalso. apply Ht.
    apply fin_to_nat_inj. rewrite Hnat fin_to_nat_to_fin //.
  Qed.

  Lemma to_iThyIfMono_app m (L1 L2 : iLblThy Σ) :
    to_iThyIfMono m L1 ++ to_iThyIfMono m L2 = to_iThyIfMono m (L1 ++ L2).
  Proof.
    induction L1 as [| X L1' IH]; first done.
    simpl. by rewrite IH.
  Qed.

  Lemma vgG_expg_n (x : vgG) : (x ^+ n)%g = 1%g.
  Proof.
    rewrite -g_nontriv.
    assert (∃ ck : fin n, x = (g ^+ ck)%g) as (ck & ->) by (edestruct log_g as [v H]; by exists v).
    by rewrite expgAC expg_order expg1n.
  Qed.


End lemmas.

(* Receiver corrupt *)
(* ------------------------------------------------------------------ *)
Ltac sender_forward_loop :=
  iClear "Hl0 Hl1";
  iRevert (k1' k2' Hnk1 Hnk2) "Hfill";
  iLöb as "IH"; iIntros (????) "Hfill";
  iApply (brel_exhaustion' OS (fill _ #()%V) (fill _ #()%V) with "Hfill");
  [set_solver|set_solver|];
  iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|];
  iIntros (???????) "(%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ) Hkont";
  iApply brel_handle_os_l; [apply neutral_ectx; set_solver|];
  iIntros (rl) "!> Hrl";
  iApply brel_handle_os_r; [apply neutral_ectx; set_solver|];
  iIntros (rr) "Hrr";
  brel_pures';
  iApply (brel_cont_l with "[$]"); iModIntro;
  iApply (brel_cont_r with "[$]");
  iDestruct ("Hkont" with "HQ") as "Hfill";
  by iApply "IH".

(* Feed the client's result to its continuation and resume both sides. *)
Ltac protocol_done_pre :=
  brel_pures';
  iDestruct ("Hkont" with "HQ") as "Hfill";
  iApply (brel_cont_l with "[$]"); iModIntro;
  iApply (brel_cont_r with "[$]");
  brel_pures'.

(* [pop_r] / [pop_l] additionally pop the pending LEAK continuation:
     on the right in OT_real_ideal, on the left in OT_ideal_real. *)
Tactic Notation "protocol_done" :=
  protocol_done_pre; sender_forward_loop.
Tactic Notation "protocol_done" "pop_r" :=
  protocol_done_pre; iApply (brel_cont_r with "[$]"); sender_forward_loop.
Tactic Notation "protocol_done" "pop_l" :=
  protocol_done_pre; iApply (brel_cont_l with "[$]"); iModIntro;
  sender_forward_loop.

(* Sender corrupt *)
(* ------------------------------------------------------------------ *)

Ltac protocol_done_loop_ms :=
  iLöb as "IH";
  iSplit; [iIntros (v1 v2) "!# (->&->)";by brel_pures'|];
  iIntros (k1'' k2'' ?????) "!# (%&->&->&(HQNone & HQSome)) #Hkont";
  iApply brel_handle_os_l; [apply neutral_ectx; set_solver|];
  iIntros (rl) "!> Hrl";
  iApply (brel_handle_os_r _ _); [apply neutral_ectx; set_solver|];
  iIntros (rr) "Hrr"; brel_pures';
  iApply (brel_cont_l with "[$]"); iModIntro;
  iApply (brel_cont_r with "[$]");
  iDestruct ("Hkont" with "HQNone") as "Hfill";
  iApply (brel_exhaustion (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill");
  [set_solver|set_solver|by iApply "IH"].

Ltac protocol_done_loop :=
  iLöb as "IH";
  iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|];
  iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome)) Hkont";
  iApply brel_handle_os_l; [apply neutral_ectx; set_solver|];
  iIntros (rl) "!> Hrl";
  iApply (brel_handle_os_r _ _); [apply neutral_ectx; set_solver|];
  iIntros (rr) "Hrr"; brel_pures';
  iApply (brel_cont_l with "[$]"); iModIntro;
  iApply (brel_cont_r with "[$]");
  iDestruct ("Hkont" with "HQNone") as "Hfill";
  iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hfill");
  [set_solver|set_solver|];
  by iApply "IH".

Tactic Notation "protocol_done" "ms" :=
  iDestruct ("Hreturn" with "HQNone") as "Hfill";
  iApply (brel_cont_l with "[$]"); iModIntro;
  iApply (brel_cont_r with "[$]"); brel_pures';
  iClear "HQSome";
  iApply (brel_exhaustion (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill");
  [set_solver|set_solver|];
  protocol_done_loop_ms.

Tactic Notation "protocol_done" "cache_r" :=
  iDestruct ("Hkont" with "HQNone") as "Hfill";
  iApply (brel_cont_l with "[$]"); iModIntro;
  iApply (brel_cont_r with "[$]"); brel_pures';
  brel_load_r; brel_pures';
  iApply (brel_cont_r with "[$]");
  iClear "Hl0 Hl1 HQSome";
  iApply (brel_exhaustion' OS (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill");
  [set_solver|set_solver|];
  protocol_done_loop.

Tactic Notation "protocol_done" "cache_l" :=
  iDestruct ("Hkont" with "HQNone") as "Hfill";
  iApply (brel_cont_r with "[$]");
  iApply (brel_cont_l with "[$]"); iModIntro; repeat foldkont; brel_pures';
  brel_load_l; brel_pures';
  iApply (brel_cont_l with "[$]"); iModIntro;
  iClear "Hl0 Hl1 HQSome";
  iApply (brel_exhaustion' OS (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill");
  [set_solver|set_solver|];
  protocol_done_loop.
