From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances definition sem_types.
From clutch.clutch Require ElGamal_bijection.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_os ot_bijection.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.
Import ElGamal_bijection.bij_nat.

Import valgroup_notation.
Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (CRS Leak Sender Receiver channel : label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

    (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  Program Definition SenderTheory : iThy Σ :=
    λ e1 e2, (λne Q, ∃ m0 m1 : vgG,
                ⌜ e1 = do: Sender (m0, m1)%V ⌝%E ∗
                ⌜ e2 = do: Sender (m0, m1)%V ⌝%E ∗
                (Q #()%V #()%V)
             )%I.
  Next Obligation. solve_proper. Qed.


  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  Program Definition SendBobImpl γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,            
                ∃ v1 v2 v1' v2': val, (* Consider moving (u,v) into first message branch to allow for more general behaviour *)
                   ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (v1, v2)%V) ∗ ⌜(v1, v2) = (v1', v2')⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                            (⌜ e1 = do: channel (SendV ((v1, v2), alice)) ⌝%E ∗
                             ⌜ e2 = do: channel (SendV ((v1',v2'), alice)) ⌝%E)  ∗ 
                            (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImpl γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                 ⌜ e1 = do: channel (RecvV alice) ⌝%E ∗
                 ⌜ e2 = do: channel (RecvV alice) ⌝%E ∗
                 ▷ (Q NONEV NONEV ∧ (∀ u v : vgG, own γauth (to_dfrac_agree DfracDiscarded (u, v)%V) -∗ Q (SOMEV (u,v)) (SOMEV (u, v))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImpl γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m' : val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                             (⌜ e1 = do: channel (SendV (m, bob)) ⌝%E ∗
                              ⌜ e2 = do: channel (SendV (m', bob)) ⌝%E)  ∗ 
                             ▷ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBobImpl γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV bob) ⌝%E ∗
                (* Added a later, since RHS doesn't take a step *)
                ▷ (Q NONEV NONEV ∗ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed.



  Program Definition CRSThy {γcrs}: iThy Σ :=
    λ e1 e2, (λne Q,
                (⌜ e2 = do: CRS #()%V ⌝%E ∗ ⌜ e1 = do: CRS #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) (Val crs))))%I.
  Next Obligation. solve_proper. Qed.

  (* allows the real protocol (LHS) to throw additional CRS operations *)
  Program Definition CRSThyL {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e1 = do: CRS #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) e2)))%I.
  Next Obligation. solve_proper. Qed.

  Definition LblAdv γcrs γtokb γfracb γauthb btokN := [([CRS],[CRS], @CRSThy γcrs);([channel], [channel],
                                                                           (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvBobImpl γauthb)));
                                                                         ([Sender],[Sender;Leak],SenderTheory)].
  Definition LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := [([channel],[channel], (iThySum (iThySum (SendAliceImpl γtoka γfraca γautha atokN) (RecvBobImpl γauthb))
                                                                        (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvAliceImpl γautha))))].
  (* TODO: move all of the above to a common authenticated channel file. *)

  Lemma fin_not_0 (x : fin n) : x ∉ [0%fin] → (0 < x)%nat.
  Proof using G n_prime.
    intros Hin. apply Nat.neq_0_le_1. intros Hcontra.
    apply Hin. set_unfold. left. apply fin_to_nat_inj. done.
  Qed. 
  
  Lemma f_cancel_g (x : fin n) y :
     x ∉ [0%fin] →
    (y < n)%nat →
    (g ^+ x ^+ f n'' x y = g ^+ y)%g.
  Proof using G n_prime.
    intros Hxin Hlt.
    rewrite -expgM. unfold f.
    apply Nat.ltb_lt in Hlt. erewrite Hlt.
    rewrite -(@expg_mod _ n (ssrnat.muln x (div.modn (ssrnat.muln y (ssrnat.expn x n'')) n))).
    2 : rewrite -g_nontriv; apply expg_order.
    rewrite crs_bij_cancel; [|done | |].
    3 : pose proof (fin_to_nat_lt x) as Hg0le; apply Rcomplements.SSR_leq; lia.
    2 : { apply Rcomplements.SSR_leq. by apply fin_not_0. }
    rewrite expg_mod; [done|].
    rewrite -g_nontriv; apply expg_order.
  Qed.

  (* Lemma f_cancel_g_ring (x : fin n) y :
       (y < n)%nat →
       (g ^+ x ^+ f_ring n'' (@Fp_of_fin n'' n_prime x) y = g ^+ y)%g.
     Proof using G n_prime.
       intros Hlt.
       rewrite -expgM. unfold f_ring.
       rewrite Rcomplements.SSR_leq. in Hlt.
       unfold f_ring.
       apply Nat.ltb_lt in Hlt. erewrite Hlt.
       rewrite -(@expg_mod _ n (ssrnat.muln x (div.modn (ssrnat.muln y (ssrnat.expn x n'')) n))).
       2 : rewrite -g_nontriv; apply expg_order.
       rewrite crs_bij_cancel; [|done | |].
       3 : pose proof (fin_to_nat_lt x) as Hg0le; apply Rcomplements.SSR_leq; lia.
       2 : { apply Rcomplements.SSR_leq. by apply fin_not_0. }
       rewrite expg_mod; [done|].
       rewrite -g_nontriv; apply expg_order.
     Qed.  *)

  

  Lemma DH_KE_C_DH_real f1 f2 γcrs γtoka γtokb γfraca γfracb γautha γauthb L :
    Sender ≠ Receiver →
    channel ≠ Sender →
    (* Receiver ≠ Leak →
       Leak ≠ CRS →
       CRS ≠ channel → *)
    let AuthChannel := LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
    let Adv := LblAdv γcrs γtokb γfracb γauthb btokN in
         is_closed_expr ∅ f1 →
         is_closed_expr ∅ f2 →
         token γtokb -∗
         own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
           own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
           BREL f1 ≤ f2 <| (Adv ++ L)|> {{ (λ v1 v2, ⌜v1 = #()%V ∧ v2 = #()%V⌝) }} -∗
           (* n instead of S n since we are not sampling 0 *)
           ↯ (3 / n) -∗
           BREL (@F_CRS _ _ _ CRS (@OT_Real_Receiver_Corrupted _ _ _ CRS Sender channel f1)) (* iThyBot can be replaced with an arbitrary theory X *)
             ≤ (@OT_SIM_Receiver_Corrupt_with_auth _ _ _ CRS Leak Sender channel f2) <|to_iThyIfMono OS (([CRS],[CRS], iThyBot) :: ([Sender],[Sender; Leak],iThyBot) :: AuthChannel ++ L)|> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}.
  Proof using G. 
    iIntros (???? Hf1closed Hf2closed) "Htokb Hcrs Hauthb Hff Herr".

    brel_pures.
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    assert ((3/n) = 1/n + 1/n + 1/n) as -> by lra.
    iDestruct (ec_split with "Herr") as "(Herr & Herr')"; [apply Rplus_le_le_0_compat; apply Rdiv_INR_ge_0|apply Rdiv_INR_ge_0|].
    iFrame. iIntros (g0 Hg0) "!>".
    brel_pures. brel_exp_l. brel_exp_r.
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iDestruct (ec_split with "Herr") as "(Herr & Herr')".
    1, 2: apply Rdiv_INR_ge_0. iFrame.
    iIntros (g1 Hg1) "!>".
    brel_exp_l. brel_exp_r.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin g0))).
    1 : { unshelve eapply f_bij_ring; first done. admit. (* TODO: prove g0 != 0 *) }
    (* 1: apply f_bij; [done|by apply fin_not_0|apply fin_to_nat_lt]. *)
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (t0 Ht0). brel_pures.
    assert (t0 < n)%nat as Ht0' by lia.
    epose proof (brel_couple_couple_avoid _ _ [Fin.of_nat_lt Ht0'] (f_ring (Fp_of_fin g1)) ) as h'.
    iApply h'; [apply NoDup_singleton| |] ; clear h'.
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    Unshelve.
    2 : (unshelve eapply f_bij_ring; [done|admit]). (* [done|by apply fin_not_0|apply fin_to_nat_lt]). *)
    iFrame. iIntros (t1 Hneq) "!>".
    brel_pures. 
    do 2brel_exp_r.
    rewrite -expgM. rewrite -(@expg_mod _ n (ssrnat.muln g0 (f_ring (Fp_of_fin g0) t0))).
    2 : rewrite -g_nontriv; apply expg_order.
    rewrite crs_fin_cancel //.
    3 : apply Rcomplements.SSR_leq; lia.
    2 : admit.                  (* TODO: prove g0 != 0 in the field *)

    assert (t1 < n)%nat as Ht1' by apply fin_to_nat_lt.
    rewrite -expgM. rewrite -(@expg_mod _ n (ssrnat.muln g1 (f_ring (Fp_of_fin g1) t1))).
    2 : rewrite -g_nontriv; apply expg_order.
    rewrite crs_fin_cancel //.
    3 : apply Rcomplements.SSR_leq; lia.
    2 : admit.                  (* TODO: prove g1 != 0 in the field *)

    rewrite !expg_mod.
    2,3: rewrite -g_nontriv; apply expg_order.
    
    iApply fupd_brel.
    iMod (auth_upd (vgval (g ^+ t1), vgval (g ^+ t0), vgval (g ^+ g1), vgval (g ^+ g0))%V with "Hcrs") as "Hcrs".
    iMod (auth_persist with "Hcrs") as "#Hcrs".
    iModIntro.

    unfold F_OT. brel_pures.
    iApply brel_alloc_r. iIntros (lm0) "Hlm0". brel_pures_r.
    iApply brel_alloc_r. iIntros (lm1) "Hlm1". brel_pures_r.
    repeat (rewrite (subst_is_closed_empty f1); last done).
    unfold D_Sender. brel_pures_r.
    repeat (rewrite (subst_is_closed_empty f2); last done).

    iApply fupd_brel.
    iMod (inv_alloc btokN _ (token γtokb ∗ own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) ∨ own γfracb DfracDiscarded)%I with "[Htokb Hauthb]") as "#Hinvtb".
    { iNext; iLeft;iFrame. }
    iModIntro.

    iApply brel_introduction_mono. 
    1 : iApply (to_iThy_le_to_iThyIfMono_idemp ((([CRS],[CRS], iThyBot) :: ([Sender],[Sender; Leak],iThyBot) :: AuthChannel ++ L)) OS).

    (* All resources should be in an invariant *)
    iApply (brel_exhaustion' OS _ _ [_] [_] (iThyMono (iThySum CRSThy CRSThyL)) _
                             (to_iThyIfMono OS (([Sender], [Sender;Leak], _) :: AuthChannel ++ L))
             with "[Hff Hlm0 Hlm1]"); [done|done| |].

    (* CRS handler *)
    2 : { iLöb as "IH".
          iSplit; [iIntros (v1 v2) "H"; by brel_pures|].
          iIntros (???????) "(%&[(->&->&HQ) | (->&HQ)]&HQQ) Hkont".
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl".
            iApply brel_handle_os_r; [apply neutral_ectx; set_solver|].
            iIntros (rr) "Hrr".
            brel_pures.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iApply (brel_cont_r with "[$]").
            iSpecialize ("HQ" $! (vgval (g ^+ t1), vgval (g ^+ t0), vgval (g ^+ g1), vgval (g ^+ g0))%V).
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion' OS _ _ [_] [_] (iThyMono (iThySum CRSThy CRSThyL)) _
                      (to_iThyIfMono OS (([Sender], [Sender;Leak], _) :: AuthChannel ++ L))
                     with "[H]"); [set_solver|set_solver|done|done].
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl". brel_pures.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iSpecialize ("HQ" $! (vgval (g ^+ t1), vgval (g ^+ t0), vgval (g ^+ g1), vgval (g ^+ g0))%V).
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion' OS _ _ [_] [_] (iThyMono (iThySum CRSThy CRSThyL)) _
                      (to_iThyIfMono OS (([Sender], [Sender;Leak], _) :: AuthChannel ++ L))
                     with "[H]"); [set_solver|set_solver|iApply "H"|iApply "IH"]. }

    
    iApply brel_introduction_mono. { iApply to_iThy_le_intro'. eapply submseteq_swap. }
    iDestruct (brel_introduction_mono _ with "[][$Hff]") as "Hff".
    { iApply to_iThy_le_trans.
      (* add CRSThyL to the row of ff just to match the row of the context in the rest of the proof. It's fine since we've already factored out the CRS handler *)
      - iSplit.
        { iApply iThy_le_trans; first iApply (iThy_le_to_iThy_sum [CRS] [CRS]).
          iApply iThy_le_trans; last iApply (iThy_le_sum_to_iThy [CRS] [CRS] ((iThySum CRSThy CRSThyL))).
          iApply iThy_le_sum_l. iIntros (???) "!# (%&%&%&%&%&?&?&?&?&H&?)". iExists e1',e2',k1,k2,_. iFrame. }
        iSplit; iModIntro; [iIntros "#Hvalid"; iApply valid_to_iThy_bot; by (iDestruct (valid_to_iThy_bot with "Hvalid") as "?")| (iIntros (Hdistinct); iPureIntro)]; simpl.
        apply distinct_to_iThy_bot. by apply distinct_to_iThy_bot in Hdistinct. 
      - iApply to_iThy_le_intro'. eapply submseteq_trans; last first.
           +  eapply submseteq_skip. eapply submseteq_swap.
           +  eapply submseteq_swap. }

    iDestruct (brel_introduction_mono _ (AuthChannel ++ [([Sender],[Sender;Leak], SenderTheory); ([CRS], [CRS], iThySum CRSThy CRSThyL)] ++ L) with "[][$Hff]") as "Hff". 
    {  iSplit.
       + iApply iThy_le_trans; [iApply iThy_le_to_iThy_sum|].
         iApply iThy_le_trans; [|iApply iThy_le_sum_to_iThy].
         iApply iThy_le_sum_l. iIntros (???) "!#  (%&%&%&%&%&?&?&H)". iExists _,_,_,_,_. iFrame.
         iDestruct "H" as "(?&?&HX&#HSQ)". iFrame. iSplitL "HX"; [|iApply "HSQ"].
         iDestruct "HX" as "[HX | HX]"; [iRight;iLeft;done|iLeft;iRight;done].
       + iSplit; iModIntro; [iApply valid_submseteq'|iIntros (Hdistinct'); iPureIntro; eapply distinct_submseteq'; last done]; simpl;
           try rewrite !labels_l_cons; try rewrite !labels_r_cons; set_solver.
    }
    
    iDestruct (brel_introduction_mono _ with "[][$Hff]") as "Hff".
    { iApply to_iThy_le_intro'. eapply submseteq_trans; first eapply submseteq_swap.
      eapply submseteq_skip. eapply submseteq_swap. }
    
    (* iApply (brel_na_alloc
                 ((lm0 ↦ₛ NONEV ∗ lm1 ↦ₛ NONEV) ∨ (∃ m0 m1 : vgG, lm0 ↦ₛ□ SOMEV m0 ∗ lm1 ↦ₛ□ SOMEV m1))%I
                 atokN).
       iSplitL "Hlm0 Hlm1"; [iNext; iLeft; iFrame|].
       iIntros "#Hinvmm". *)

    iApply (brel_exhaustion' OS _ _ [_] [_;_] with "[$Hff]"); [done|set_solver|].
    iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
    iIntros (???????) "(%&%&->&->&HQ) Hkont".
    iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
    iIntros (cl) "!> Hcl".
    iApply brel_handle_os_r; [apply neutral_ectx;set_solver|].
    iIntros (cr) "Hcr".
    brel_pures.

    iApply (brel_introduction' [CRS]). { repeat constructor. }
    iExists _, _, [AppRCtx _], [], _.  iSplit; [done|].
    iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|].
    iSplit; [done|]. iSplit; [iPureIntro; apply NeutralEctx_nil|].
    iSplit; last (iModIntro; iIntros (??) "H"; done).
    iExists _.
    iSplitL; last (iIntros (??) "!> H"; iApply "H").
    iRight. iSplit; [done|]. iIntros (?) "Hcrs'".
    iDestruct (auth_agree with "[$][$]") as "->". iClear "Hcrs'".
    brel_pures.
    unfold store_if_none. brel_pures_r.
    iApply (brel_load_r with "Hlm0"). iIntros "Hlm0".
    iApply (brel_store_r with "Hlm0"). iIntros "Hlm0".
    brel_pures.
    iApply (brel_load_r with "Hlm1"). iIntros "Hlm1".
    iApply (brel_store_r with "Hlm1"). iIntros "Hlm1".
    brel_pures.

    iApply (brel_handle_os_r _ [AppRCtx _]); [set_solver|].
    iIntros (rLeak) "HrLeak". brel_pures.

    iApply (brel_introduction' [channel]). { repeat constructor. }
    iExists _,_,[AppRCtx _],[AppRCtx _],_.
    do 2 (iSplit; [done|];
          iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|]).
    iSplitL; [|iIntros (??) "!# H"; iApply "H"].
    iExists _.
    iSplitL; last (iIntros (??) "!> H"; iApply "H").
    iRight. iRight. do 2 (iSplit; [done|]).
    iModIntro.
    iSplit.
    
    (* Protocol done loop *)
    { brel_pures.
      iDestruct ("Hkont" with "HQ") as "Hfill".
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_cont_r with "[$]").
      iClear "Hlm0 Hlm1".
      iRevert (k1' k2' H1 H2) "Hfill".
      iLöb as "IH". iIntros (????) "Hfill".
      iApply (brel_exhaustion' OS _ _ [_] [_] _ _
             (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
      iIntros (???????) "(%&%&->&->&HQ) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl".
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
      iIntros (rr) "Hrr". 
      brel_pures.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQ") as "Hfill".
      by iApply "IH". }
    
      iIntros (??) "#Hag". brel_pures. rewrite is_unit.
      iApply brel_eq_l. iApply brel_eq_r. 
      destruct (bool_decide (u = 1%g)) eqn:Heq.
      
      (* Protocol done loop *)
      { brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures.
        iApply (brel_cont_r with "[$]").
        iClear "Hlm0 Hlm1".
        iRevert (k1' k2' H1 H2) "Hfill".
        iLöb as "IH". iIntros (????) "Hfill".
        iApply (brel_exhaustion' OS _ _ [_] [_] _ _
                  (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
        iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
        iIntros (???????) "(%&%&->&->&HQ) Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl".
        iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
        iIntros (rr) "Hrr". 
        brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "HQ") as "Hfill".
        by iApply "IH". }

      brel_pures.
      iApply brel_eq_r.
      destruct (bool_decide (v = (u ^+ (f_ring (Fp_of_fin g0) t0))%g)) eqn:Heq1; brel_pures.
      (* (e1, e2) = (enc(m0), enc(g)) - couple enc(m1) to enc(g) *)
      + iApply (brel_handle_os_r [AppRCtx _] [AppRCtx _]); [set_solver|].
        iIntros (?) "Hcont". brel_pures.
        iApply (brel_cont_r with "[$]").
        brel_pures.
        iApply (brel_load_r with "[$Hlm0]"). iIntros "Hlm0". 
        brel_pures. brel_exp_r. brel_pures.
        destruct (log_g m1) as (km & ->).
        destruct (log_g u) as (ku & ->).
        destruct (log_g v) as (kv & ->).

        set c1 := c1' (zmodp.inZp (fin_to_nat t1)) (Fp_of_fin g1) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

        set f' := minus_ring c1.

        set c2 := c2' (zmodp.inZp (fin_to_nat t1)) (Fp_of_fin g1) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

        set g' := plus_ring c2.
        iApply (brel_couple_rand_rand _ _ g' (H:=plus_bij_ring c2)).
        { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
        iIntros (s1 Hs1). brel_pures.

        iApply (brel_couple_rand_rand _ _ f' (H:=minus_ring_bij c1)).
        { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
        iIntros (r1 Hr1). brel_pures.
        
        iApply brel_couple_rand_rand; [done|]. iIntros (s0 Hs0). brel_pures.
        iApply brel_couple_rand_rand; [done|]. iIntros (r0 Hr0). brel_pures.
        iApply brel_exp_l. iApply brel_exp_r. brel_pures.
        brel_exp_r. brel_mult_r. brel_mult_l. brel_mult_r. brel_exp_r.
        brel_exp_r. brel_mult_r.
        brel_mult_l. do 2 brel_exp_l. brel_mult_l. brel_pures.
        brel_exp_l. brel_mult_l. brel_mult_l. brel_exp_l. brel_exp_l.
        brel_mult_l. 
        do 2 brel_exp_r. do 2 brel_mult_r. do 2brel_exp_r. brel_mult_r.
        brel_pures.

        rewrite -!expgM.
        rewrite -!expgnDr.
        rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g1 r1) (ssrnat.muln t1 s1))).
        1 : rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g1 (f' r1)) (ssrnat.muln t1 (g' s1)))).
        2,3 : rewrite -g_nontriv; apply expg_order.
        unshelve rewrite enc_fin_cancel1 //.
        2,3 : rewrite Rcomplements.SSR_leq; lia.
        rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.addn 1 _) _)).
        2: rewrite -g_nontriv; apply expg_order.
        rewrite enc_fin_cancel2 //.
        3, 4 : rewrite Rcomplements.SSR_leq; lia.
        2 : admit.
        rewrite !expg_mod.
        2,3 : rewrite -g_nontriv; apply expg_order.
        brel_pures.
        iApply (brel_introduction' [channel]). { repeat constructor. }
        iExists _,_,[AppRCtx _],[AppRCtx _ ],_.
        do 2 (iSplit; [done|];
              iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|]).
        iSplitL; [|iIntros (??) "!# H"; iApply "H"].
        iExists _.
        iSplitL; last (iIntros (??) "!> H"; iApply "H").
        iRight. iLeft.
        iExists _,_,_,_.
        iSplitR.
        { iMod (inv_acc with "Hinvtb") as "([>(Htok & Hagree) | >#Hfrac] & Hclose)"; try done.
          - iModIntro. iLeft. iIntros "#Hfrac".
            iMod (auth_upd ((vgval (g ^+ ssrnat.addn (ssrnat.muln g0 r0) (ssrnat.muln t0 s0)),
                               vgval (m0 * g ^+ ssrnat.muln ku r0 * g ^+ ssrnat.muln kv s0)),
                              (vgval (g ^+ ssrnat.addn (ssrnat.muln g1 r1) (ssrnat.muln t1 s1)),
                                 vgval (g ^+ ssrnat.addn (ssrnat.addn km (ssrnat.muln ku r1)) (ssrnat.muln kv s1))))%V
                   with "Hagree") as "Hagree".
            iMod (auth_persist with "Hagree") as "#Hagree".
            iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#".
            by iModIntro.
          - iRight. iFrame "#".
            iModIntro. iApply "Hclose". iNext.
            by iRight. }
        iSplit; first (iSplit; done).
        (* Protocol done loop *)
        { brel_pures.
          iDestruct ("Hkont" with "HQ") as "Hfill".
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          brel_pures.
          iApply (brel_cont_r with "[$]").
          iClear "Hlm0 Hlm1".
          iRevert (k1' k2' H1 H2) "Hfill".
          iLöb as "IH". iIntros (????) "Hfill".
          iApply (brel_exhaustion' OS _ _ [_] [_] _ _
                    (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
          iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
          iIntros (???????) "(%&%&->&->&HQ) Hkont".
          iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
          iIntros (rl) "!> Hrl".
          iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
          iIntros (rr) "Hrr". 
          brel_pures.
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          iDestruct ("Hkont" with "HQ") as "Hfill".
          by iApply "IH". }
      (* (e1,e2) = (enc(g), enc(m1)) - couple enc(m0) and enc(g) *)
      + iApply (brel_handle_os_r [AppRCtx _] [AppRCtx _]); [set_solver|].
        iIntros (?) "Hcont". brel_pures.
        iApply (brel_cont_r with "[$]").
        brel_pures.
        iApply (brel_load_r with "[$Hlm1]"). iIntros "_". 
        brel_pures. brel_exp_r. brel_pures.
        iApply brel_couple_rand_rand; [done|]. iIntros (s1 Hs1). brel_pures.
        iApply brel_couple_rand_rand; [done|]. iIntros (r1 Hr1). brel_pures.
        destruct (log_g m0) as (km & ->).
        destruct (log_g u) as (ku & ->).
        destruct (log_g v) as (kv & ->).
        
        set c1 := c1' (zmodp.inZp t0) (Fp_of_fin g0) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

        set f' := minus_ring c1.

        set c2 := c2' (zmodp.inZp t0) (Fp_of_fin g0) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

        set g' := plus_ring c2.
        
        iApply (brel_couple_rand_rand _ _ g' (H:=plus_bij_ring c2)).
        { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
        iIntros (s0 Hs0). brel_pures.

        iApply (brel_couple_rand_rand _ _ f' (H:=minus_ring_bij c1)).
        { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
        iIntros (r0 Hr0). brel_pures.
        
        iApply brel_exp_l. iApply brel_exp_r. brel_pures.
        brel_exp_r. brel_mult_r. brel_mult_l. brel_mult_r. brel_exp_r.
        brel_exp_r. brel_mult_r.
        brel_mult_l. do 2 brel_exp_l. brel_mult_l. brel_pures.
        brel_exp_l. brel_mult_l. brel_mult_l. brel_exp_l. brel_exp_l.
        brel_mult_l. 
        do 2 brel_exp_r. do 2 brel_mult_r. do 2brel_exp_r. brel_mult_r.
        brel_pures.

        rewrite -!expgM.
        rewrite -!expgnDr.
        rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g0 r0) (ssrnat.muln t0 s0))).
        1 : rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g0 (f' r0)) (ssrnat.muln t0 (g' s0)))).
        2,3 : rewrite -g_nontriv; apply expg_order.
        unshelve rewrite enc_fin_cancel1 //.
        2,3 : rewrite Rcomplements.SSR_leq; lia.
        rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.addn 1 _) _)).
        2: rewrite -g_nontriv; apply expg_order.
        rewrite enc_fin_cancel2 //.
        3, 4 : rewrite Rcomplements.SSR_leq; lia.
        2 : admit.
        rewrite !expg_mod.
        2,3 : rewrite -g_nontriv; apply expg_order.
        brel_pures.
        iApply (brel_introduction' [channel]). { repeat constructor. }
        iExists _,_,[AppRCtx _],[AppRCtx _ ],_.
        do 2 (iSplit; [done|];
              iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|]).
        iSplitL; [|iIntros (??) "!# H"; iApply "H"].
        iExists _.
        iSplitL; last (iIntros (??) "!> H"; iApply "H").
        iRight. iLeft.
        iExists _,_,_,_.
        iSplitR.
        { iMod (inv_acc with "Hinvtb") as "([>(Htok & Hagree) | >#Hfrac] & Hclose)"; try done.
          - iModIntro. iLeft. iIntros "#Hfrac".
            iMod (auth_upd ((vgval (g ^+ ssrnat.addn (ssrnat.muln g0 r0) (ssrnat.muln t0 s0)),
                               vgval (g ^+ ssrnat.addn (ssrnat.addn km (ssrnat.muln ku r0)) (ssrnat.muln kv s0))),
                              (vgval (g ^+ ssrnat.addn (ssrnat.muln g1 r1) (ssrnat.muln t1 s1)),
                                 vgval (m1 * g ^+ ssrnat.muln ku r1 * g ^+ ssrnat.muln kv s1)))%V
                   with "Hagree") as "Hagree".
            iMod (auth_persist with "Hagree") as "#Hagree".
            iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#".
            by iModIntro.
          - iRight. iFrame "#".
            iModIntro. iApply "Hclose". iNext.
            by iRight. }
        iSplit; first (iSplit; done).
        (* Protocol done loop *)
        { brel_pures.
          iDestruct ("Hkont" with "HQ") as "Hfill".
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          brel_pures.
          iApply (brel_cont_r with "[$]").
          iClear "Hlm0".
          iRevert (k1' k2' H1 H2) "Hfill".
          iLöb as "IH". iIntros (????) "Hfill".
          iApply (brel_exhaustion' OS _ _ [_] [_] _ _
                    (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
          iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
          iIntros (???????) "(%&%&->&->&HQ) Hkont".
          iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
          iIntros (rl) "!> Hrl".
          iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
          iIntros (rr) "Hrr". 
          brel_pures.
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          iDestruct ("Hkont" with "HQ") as "Hfill".
          by iApply "IH". }
        Unshelve. all: done.
  Admitted.

End handlee_verification.
