From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances definition sem_types
  sem_def sem_row.
From clutch.clutch Require ElGamal_bijection.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_thunk_receiver_corrupt ot_bijection.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.
Import ElGamal_bijection.bij_nat.

(* Import valgroup_notation. *)
Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

    (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  (* Program Definition SenderTheory (s1 s2 : label) : iThy Σ :=
       λ e1 e2, (λne Q, ∃ m0 m1 : vgG,
                   ⌜ e1 = do: s1 (m0, m1)%V ⌝%E ∗
                   ⌜ e2 = do: s2 (m0, m1)%V ⌝%E ∗
                   (Q #()%V #()%V)
                )%I.
     Next Obligation. solve_proper. Qed. *)


  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  (* Program Definition SendBobImpl c1 c2 γtok γfrac γauth ι : iThy Σ :=
       λ e1 e2, (λne Q,            
                   ∃ v1 v2 v1' v2': val, (* Consider moving (u,v) into first message branch to allow for more general behaviour *)
                      ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (v1, v2)%V) ∗ ⌜(v1, v2) = (v1', v2')⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                               (⌜ e1 = do: c1 (SendV ((v1, v2), alice)) ⌝%E ∗
                                ⌜ e2 = do: channel (SendV ((v1',v2'), alice)) ⌝%E)  ∗ 
                               (Q (Val #()%V) (Val #()%V)))
                )%I.
     Next Obligation. solve_proper. Qed.
     
     Program Definition RecvAliceImpl γauth : iThy Σ :=
       λ e1 e2, (λne Q,
                    ⌜ e1 = do: channel (RecvV alice) ⌝%E ∗
                    ⌜ e2 = do: channel (RecvV alice) ⌝%E ∗
                    ▷ (Q NONEV NONEV ∧ (∀ u v : vgG, own γauth (to_dfrac_agree DfracDiscarded (u, v)%V) -∗ Q (SOMEV (u,v)) (SOMEV (u, v))))
                )%I.
     Next Obligation. solve_proper. Qed.
     
     Program Definition SendAliceImpl γtok γfrac γauth ι : iThy Σ :=
       λ e1 e2, (λne Q,
                   ∃ m m' : val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                                (⌜ e1 = do: channel (SendV (m, bob)) ⌝%E ∗
                                 ⌜ e2 = do: channel (SendV (m', bob)) ⌝%E)  ∗ 
                                ▷ (Q (Val #()%V) (Val #()%V)))
                )%I.
     Next Obligation. solve_proper. Qed.
     
     Program Definition RecvBobImpl γauth : iThy Σ :=
       λ e1 e2, (λne Q,
                   ⌜ e1 = do: channel (RecvV bob) ⌝%E ∗
                   ⌜ e2 = do: channel (RecvV bob) ⌝%E ∗
                   (* Added a later, since RHS doesn't take a step *)
                   ▷ (Q NONEV NONEV ∗ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
                )%I.
     Next Obligation. solve_proper. Qed. *)

  
  Definition sem_ty_group : sem_ty Σ := (λ v1 v2, ∃ g : vgG, ⌜ v1 = g ⌝ ∗ ⌜ v2 = g ⌝)%I.
  Notation "'𝔾'" := sem_ty_group.   


  Program Definition SenderTheory (SENDERl SENDERr : label) : iThy Σ :=
    λ e1 e2, (λne Q, ∃ g1 g2 g1' g2', 𝔾 g1 g2 ∗ 𝔾 g1' g2' ∗
                 ⌜ e1 = do: SENDERl (g1,g1')%V ⌝%E ∗
                 ⌜ e2 = do: SENDERr (InjRV (g2, g2')) ⌝%E ∗
                 Q #()%V #()%V
             )%I.
  Next Obligation. solve_proper. Qed.
  
  Program Definition sendermono (SENDERl SENDERr : label) :=  {| pmono_prot_car := @SenderTheory SENDERl SENDERr; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. 
    iIntros (????) "#HΦ (%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ)"; iExists _,_,_,_; repeat iSplit; try done.
    1,2 : by iExists _.
    by iApply "HΦ".
  Qed. 

  Definition sender (SENDERl SENDERr : label) := @SemSig Σ (sendermono SENDERl SENDERr) (SENDERl,SENDERr).
  
  Program Definition senderrow SENDERl SENDERr LEAK := SemRow [([SENDERl],[SENDERr;LEAK],sender SENDERl SENDERr)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition senderrow2 SENDERl SENDERr := SemRow [([SENDERl],[SENDERr],sender SENDERl SENDERr)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed.

  Program Definition CRSThy (CRSl CRSr : label) {γcrs}: iThy Σ :=
    λ e1 e2, (λne Q,            (* this resource we need to keep as a proof tool *)
                (⌜ e1 = do: CRSl #()%V ⌝%E ∗ ⌜ e2 = do: CRSr #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) (Val crs))))%I.
  Next Obligation. solve_proper. Qed.

  Program Definition crsmono (CRSl CRSr : label) γcrs :=  {| pmono_prot_car := @CRSThy CRSl CRSr γcrs; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ???. 
    iIntros (????) "#HΦ (->&->&H)"; repeat iSplit; try done; iIntros (?) "Hcrs"; iApply "HΦ"; by iApply "H".
  Qed. 

  Definition crs (CRSl CRSr : label) γcrs := @SemSig Σ (crsmono CRSl CRSr γcrs) (CRSl,CRSr).
  
  Program Definition crsrow CRSl CRSr γcrs := SemRow [([CRSl],[CRSr],crs CRSl CRSr γcrs)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  (* allows the real protocol (LHS) to throw additional CRS operations *)
  Program Definition CRSThyL crs1 {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e1 = do: crs1 #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) e2)))%I.
  Next Obligation. solve_proper. Qed.

  (* Definition LblAdv γcrs γtokb γfracb γauthb btokN := [([CRS],[CRS], @CRSThy γcrs);([channel], [channel],
                                                                              (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvBobImpl γauthb)));
                                                                            ([Sender],[Sender;Receiver;Leak],SenderTheory)].
     Definition LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := [([channel],[channel], (iThySum (iThySum (SendAliceImpl γtoka γfraca γautha atokN) (RecvBobImpl γauthb))
                                                                           (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvAliceImpl γautha))))]. *)
  (* TODO: move all of the above to a common authenticated channel file. *)

  Lemma fin_not_0 (x : fin n) : x ∉ [0%fin] → (0 < x)%nat.
  Proof using G n_prime.
    intros Hin. apply Nat.neq_0_le_1. intros Hcontra.
    apply Hin. set_unfold. left. apply fin_to_nat_inj. done.
  Qed. 
  
  Lemma f_cancel_g (x : fin n) y :
     x ∉ [0%fin] →
    (y < n)%nat →
    (g ^+ x ^+ f n'' x y = g ^+ y)%g.
  Proof using G n_prime.
    intros Hxin Hlt.
    rewrite -expgM. unfold f.
    apply Nat.ltb_lt in Hlt. erewrite Hlt.
    rewrite -(@expg_mod _ n (ssrnat.muln x (div.modn (ssrnat.muln y (ssrnat.expn x n'')) n))).
    2 : rewrite -g_nontriv; apply expg_order.
    rewrite crs_bij_cancel; [|done | |].
    3 : pose proof (fin_to_nat_lt x) as Hg0le; apply Rcomplements.SSR_leq; lia.
    2 : { apply Rcomplements.SSR_leq. by apply fin_not_0. }
    rewrite expg_mod; [done|].
    rewrite -g_nontriv; apply expg_order.
  Qed.

 Lemma Fp_of_fin_ne_zero_2 (t : fin n) :
      t ≠ nat_to_fin (Nat.lt_0_succ (S n'')) → ~~ (@eqtype.eq_op (fintype.fintype_ordinal__canonical__eqtype_Equality (S (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg)))))))) (Fp_of_fin t) (@nmodule.Algebra.zero (zmodp.fintype_ordinal__canonical__Algebra_BaseAddUMagma (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg))))))))) = true.
  Proof using n_prime.
    intros Ht. 
    eapply eqtype.contraNneq.
    2 : { apply negb_true_iff. done. }
    intros. unfold Fp_of_fin in H.  
    have Hnat := f_equal (@fintype.nat_of_ord _) H.
    rewrite /= zmodp.Zp_nat /= in Hnat.
    have Hfp : S (S (zmodp.Zp_trunc (prime.pdiv n))) = n. { rewrite zmodp.Fp_cast; done. }
    rewrite Hfp in Hnat.
    have Hlt := fin_to_nat_lt t.
    rewrite div.modn_small in Hnat. 2: apply Rcomplements.SSR_leq; exact Hlt.
    exfalso. apply Ht.
    apply fin_to_nat_inj. rewrite Hnat fin_to_nat_to_fin //.
    Qed.

  (* Lemma f_cancel_g_ring (x : fin n) y :
       (y < n)%nat →
       (g ^+ x ^+ f_ring n'' (@Fp_of_fin n'' n_prime x) y = g ^+ y)%g.
     Proof using G n_prime.
       intros Hlt.
       rewrite -expgM. unfold f_ring.
       rewrite Rcomplements.SSR_leq. in Hlt.
       unfold f_ring.
       apply Nat.ltb_lt in Hlt. erewrite Hlt.
       rewrite -(@expg_mod _ n (ssrnat.muln x (div.modn (ssrnat.muln y (ssrnat.expn x n'')) n))).
       2 : rewrite -g_nontriv; apply expg_order.
       rewrite crs_bij_cancel; [|done | |].
       3 : pose proof (fin_to_nat_lt x) as Hg0le; apply Rcomplements.SSR_leq; lia.
       2 : { apply Rcomplements.SSR_leq. by apply fin_not_0. }
       rewrite expg_mod; [done|].
       rewrite -g_nontriv; apply expg_order.
     Qed.  *)


 Definition τC θ := (∀ᵣ θ__SENDER, ∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾)) × ((𝔾 × 𝔾) -{ θ__SENDER }-> 𝟙)) 
                                         -{ sem_row_union θ__SENDER (sem_row_union θ__CRS θ) }-∘ 𝟙)%T.

  Lemma OT_real_ideal : 
    ⊢ ↯ (3 / n) -∗
    (∀ᵣ θ, τC θ ⊸ ((((𝔾 × 𝔾) × (𝔾 × 𝔾)) -{ θ }-> 𝟙) × (𝟙 -{ θ }-> Option (𝔾 × 𝔾)))
            -{ ¡[OS] θ}-∘ 𝟙)%T 
      (λ: "f" "effs", F_CRS (λ: "doCRS", OT_Real_Receiver_Corrupted "f" ("effs", "doCRS"))%E)%V
      OT_SIM_FOT_thunk.
  Proof using G cg inG2 n_prime probblazeRGS0 vg vgg Σ.
    iIntros "Herr %θ %f1 %f2 Hff".
    rewrite /OT_Real_Receiver_Corrupted /OT_SIM_FOT_thunk /F_CRS. brel_pures'. 
    iModIntro.
    iIntros (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)".
    brel_pures'.
    
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    assert ((3/n) = 1/n + 1/n + 1/n) as -> by lra.
    iDestruct (ec_split with "Herr") as "(Herr & Herr')"; [apply Rplus_le_le_0_compat; apply Rdiv_INR_ge_0|apply Rdiv_INR_ge_0|].
    iFrame. iIntros (g0 Hg0) "!>".
    apply not_elem_of_cons in Hg0 as [Hg0 _].
    
    brel_pures'. 
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iDestruct (ec_split with "Herr") as "(Herr & Herr')".
    1, 2: apply Rdiv_INR_ge_0. iFrame.
    iIntros (g1 Hg1) "!>".
    apply not_elem_of_cons in Hg1 as [Hg1 _].

    brel_pures'.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin g0))).
    { unshelve eapply f_bij_ring; first done.  by apply Fp_of_fin_ne_zero_2. }
    { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (t0 Ht0). brel_pures'. brel_pures.
    assert ((h_ring (Fp_of_fin g1) (f_ring (Fp_of_fin g0) t0)) < n)%nat as Ht0'.
    { apply Rcomplements.SSR_leq. unshelve eapply h_lt_ring; first done. 
      unshelve eapply f_lt_ring; first done. apply Rcomplements.SSR_leq. lia. }

    epose proof (brel_couple_couple_avoid _ _ [Fin.of_nat_lt Ht0'] (f_ring (Fp_of_fin g1)) ) as h'.
    iApply h'; [apply NoDup_singleton| |] ; clear h'.
    { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    Unshelve.
    2 : (unshelve eapply f_bij_ring; [done|by apply Fp_of_fin_ne_zero_2]).
    iFrame. iIntros (t1 Hneq) "!>".
    brel_pures'. 
    rewrite -!expgM. rewrite -(@expg_mod _ n (ssrnat.muln g0 (f_ring (Fp_of_fin g0) t0))).
    2 : rewrite -g_nontriv; apply expg_order.
    rewrite crs_fin_cancel //; [|by apply Fp_of_fin_ne_zero_2|apply Rcomplements.SSR_leq; lia].
    rewrite -(@expg_mod _ n (ssrnat.muln g1 (f_ring (Fp_of_fin g1) t1))).
    2 : rewrite -g_nontriv; apply expg_order.
    assert (t1 < n)%nat as Ht1' by apply fin_to_nat_lt.
    rewrite crs_fin_cancel //; [|by apply Fp_of_fin_ne_zero_2|apply Rcomplements.SSR_leq; lia].
    rewrite !expg_mod.
    2,3: rewrite -g_nontriv; apply expg_order.
    iApply brel_effect_l. iIntros (CRSl) "!> Hcrsl !>".
    iApply brel_effect_r. iIntros (CRSr) "Hcrsr !>".
    rewrite /mut_handler /simhandler.
    brel_pures_l. brel_pures_r.
    iApply brel_alloc_r. iIntros (l0) "Hl0".
    iApply brel_alloc_r. iIntros (l1) "Hl1".
    brel_pures'.

    iApply brel_effect_l. iIntros (IDEALl) "!> Hideall !>".
    iApply brel_effect_r. iIntros (IDEALr) "Hidealr !>".
    iApply brel_effect_r. iIntros (LEAK) "Hleak !>".
    brel_pures_l. brel_pures_r.
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hideall").
    iApply (brel_add_label_r with "Hleak").
    iApply (brel_add_label_r with "Hidealr"). 

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    iApply fupd_brel.
    iDestruct auth_alloc as ">(%γcrs&Hcrs)".
    iDestruct (auth_upd (vgval (g ^+ t1), vgval (g ^+ t0), vgval (g ^+ g1), vgval (g ^+ g0))%V with "Hcrs") as ">Hcrs".
    iDestruct (auth_persist with "Hcrs") as ">Hcrs". 
    iDestruct "Hcrs" as "#Hcrs". 
    iModIntro.
    set θCRS := crsrow CRSl CRSr γcrs.
    set θSENDER := senderrow IDEALl IDEALr LEAK.
    
    iAssert (((𝟙 -{ θCRS }-> ((𝔾 × 𝔾) × 𝔾) × 𝔾) × (𝔾 × 𝔾) -{ θSENDER }-> 𝟙)%T
                (λ: <>, do: CRSl #(), λ: "mm", do: IDEALl "mm")%V   
                (λ: <>, do: CRSr #(), λ: "mm", do: IDEALr InjR "mm")%V) as "Hgg".
    { iExists _,_,_,_. repeat (iSplit; try done); rewrite /sem_ty_mbang //=.
      - iIntros (??) "!# (->&->)". brel_pures'.
        iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_;do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]); iSplit; try (iIntros (??) "!# H"; iApply "H").
        do 2 (iSplit; [by iPureIntro|]). iIntros (crs) "Hcrs'". iDestruct (auth_agree with "[$][$]") as "->". 
        iApply brel_value. iIntros "$ !>". 
        do 3 (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]);
                            iSplit; last (iExists _; done)). iExists _; done.
      - iIntros (??) "!# (%&%&%&%&->&->&(%h1&->&->)&(%h2&->&->))". brel_pures'.
        iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_;do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]); iSplit; try (iIntros (??) "!# H"; iApply "H").
        iExists h1,h1,h2,h2. do 2 (iSplit; first by iExists _).
        do 2 (iSplit; [by iPureIntro|]). 
        iApply brel_value. by iIntros "$ !>". }
    
    iDestruct ("Hff" with "Hgg") as "Hff".
    rewrite /sem_row_union !iLblSig_to_iLblThy_app iLblSig_to_iLblThy_proj.
    rewrite /sem_row_flip_mbang iThyIfMono_iLblSig_to_iThyIfMono.
    iApply brel_introduction_mono.
    { iSplit.
      - iApply iThy_le_trans; first iApply iThy_le_to_iThy_sum.
        iApply iThy_le_trans; last iApply iThy_le_sum_to_iThy.
        iApply iThy_le_sum_l.
        instantiate (1 := iThyMono iThyBot).
        instantiate (1 := [CRSr]). 
        instantiate (1 := [CRSl]).
        iIntros (???) "!# (%&%&%&%&%&_&_&_&_&(%&H&_)&_)". done. 
      - iSplit; iModIntro; first iApply valid_submseteq'; 
          last (iIntros (Hdistinct); iPureIntro; eapply distinct_submseteq'; try done); solve_submseteq. }
    iApply brel_introduction_mono.
    { iSplit.
      - iApply iThy_le_trans; first iApply iThy_le_to_iThy_sum.
        iApply iThy_le_trans; last iApply iThy_le_sum_to_iThy.
        iApply iThy_le_sum_r.
        iApply iThy_le_trans; first iApply iThy_le_to_iThy_sum.
        iApply iThy_le_trans; last iApply iThy_le_sum_to_iThy.
        iApply iThy_le_sum_l.
        instantiate (1 := iThyMono iThyBot).
        instantiate (1 := [IDEALr; LEAK]).
        instantiate (1 := [IDEALl]). 
        iIntros (???) "!# (%&%&%&%&%&_&_&_&_&(%&H&_)&_)". done. 
      - iSplit; iModIntro; first iApply valid_submseteq'; 
          last (iIntros (Hdistinct); iPureIntro; eapply distinct_submseteq'; try done); solve_submseteq. }

    iApply brel_introduction_mono. 
    1 : iApply (to_iThy_le_to_iThyIfMono_idemp (([CRSl],[CRSr], iThyBot) :: ([IDEALl],[IDEALr;LEAK],iThyBot) :: (iLblSig_to_iLblThy θ)) OS).
    
     (* All resources should be in an invariant *)
    iApply (brel_exhaustion' OS _ _ [_] [_] (iThyMono (iThySum (CRSThy CRSl CRSr) (CRSThyL CRSl)))
             with "[Hff Hl0 Hl1]"); [done|done| |].

    (* CRS handler *)
    2 : { iLöb as "IH".
          iSplit; [iIntros (v1 v2) "H"; by brel_pures|].
          iIntros (???????) "(%&[(->&->&HQ) | (->&HQ)]&HQQ) Hkont".
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl".
            iApply brel_handle_os_r; [apply neutral_ectx; set_solver|].
            iIntros (rr) "Hrr".
            brel_pures.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iApply (brel_cont_r with "[$]").
            iSpecialize ("HQ" $! (vgval (g ^+ t1), vgval (g ^+ t0), vgval (g ^+ g1), vgval (g ^+ g0))%V).
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion' OS _ _ [_] [_] (iThyMono (iThySum (CRSThy CRSl CRSr) (CRSThyL CRSl))) _
                      ((([IDEALl], [IDEALr;LEAK], _) :: _))
                     with "[H]"); [done|done|done|done].
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl". brel_pures.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iSpecialize ("HQ" $! (vgval (g ^+ t1), vgval (g ^+ t0), vgval (g ^+ g1), vgval (g ^+ g0))%V).
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion' OS _ _ [_] [_] (iThyMono (iThySum (CRSThy CRSl CRSr) (CRSThyL CRSl))) _
                             ((([IDEALl], [IDEALr;LEAK], _) :: _))
             with "[H]"); [done|done|iApply "H"|iApply "IH"]. }
    
    (* Manipulation of theories *)
    iApply brel_introduction_mono. { iApply to_iThy_le_intro'. eapply submseteq_swap. }
    iDestruct (brel_introduction_mono _ with "[][$Hff]") as "Hff".
    { (* iApply to_iThy_le_trans. *)
      (* add CRSThyL to the row of ff just to match the row of the context in the rest of the proof. It's fine since we've already factored out the CRS handler *)
      iSplit.
      { iApply iThy_le_trans; first iApply iThy_le_to_iThy_app_inv. 
        iApply iThy_le_trans; last iApply iThy_le_to_iThy_app. 
        iApply iThy_le_sum_r.
        iApply iThy_le_trans; last iApply (iThy_le_sum_to_iThy [CRSl] [CRSr] ((iThySum (CRSThy CRSl CRSr) (CRSThyL CRSl)))).
        iApply iThy_le_trans; first iApply iThy_le_to_iThy_sum.
        iApply iThy_le_sum_l. iIntros (???) "!# (%&%&%&%&%&?&?&?&?&H&?)". iExists e1',e2',k1,k2,_. iFrame. }
      iSplit; iModIntro; [iIntros "#Hvalid"; iApply valid_to_iThy_bot; by (iDestruct (valid_to_iThy_bot with "Hvalid") as "?")| (iIntros (Hdistinct); iPureIntro)]; simpl.
      apply distinct_to_iThy_bot. by apply distinct_to_iThy_bot in Hdistinct. }
    
    iApply (brel_exhaustion' OS (f1 _) (f2 _) with "[$Hff]"); [done|set_solver|].
    iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
    iIntros (???????) "(%&%&%&%&(%m0&->&->)&(%m1&->&->)&->&->&HQ) Hkont".
    iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
    iIntros (cl) "!> Hcl".
    iApply brel_handle_os_r; [apply neutral_ectx;set_solver|].
    iIntros (cr) "Hcr".
    brel_pures_l. brel_pures_r.
    
    iApply (brel_introduction' [CRSl]). { repeat constructor. }
    iExists _, _, [AppRCtx _], [], _.  iSplit; [done|].
    iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|].
    iSplit; [done|]. iSplit; [iPureIntro; apply NeutralEctx_nil|].
    iSplit; last (iModIntro; iIntros (??) "H"; done).
    iExists _.
    iSplitL; last (iIntros (??) "!> H"; iApply "H").
    iRight. iSplit; [done|]. iIntros (?) "Hcrs'".
    iDestruct (auth_agree with "[$][$]") as "->". iClear "Hcrs'".
    brel_pures_l. 
    unfold store_if_none. brel_pures_r.
    iApply (brel_load_r with "Hl0"). iIntros "Hl0".
    iApply (brel_store_r with "Hl0"). iIntros "Hl0".
    brel_pures'.
    iApply (brel_load_r with "Hl1"). iIntros "Hl1".
    iApply (brel_store_r with "Hl1"). iIntros "Hl1".
    brel_pures'.
    
    iApply (brel_handle_os_r _ [AppRCtx _]); [set_solver|].
    iIntros (rLeak) "HrLeak". brel_pures'.

    iApply brel_learn. iIntros (Hdistinct) "_".
    
    iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
    { iApply traversable_ectx_labels; last first; [eapply distinct_submseteq; [|apply Hdistinct]; solve_submseteq|set_solver|set_solver]. }
    { iApply to_iThy_le_intro'; solve_submseteq. }
    iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
    { rewrite /sem_ty_arr /sem_ty_mbang /=. by iApply "Hrecv". }
    iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])".
    
     (* Protocol done loop *)
    { brel_pures_l. brel_pures_r.
      iDestruct ("Hkont" with "HQ") as "Hfill".
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_cont_r with "[$]").
      iClear "Hl0 Hl1".
      iRevert (k1' k2' H H0) "Hfill".
      iLöb as "IH". iIntros (????) "Hfill".
      iApply (brel_exhaustion' OS (fill _ #()%V) (fill _ #()%V) with "Hfill"); [set_solver|set_solver|].
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|].
      iIntros (???????) "(%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl".
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
      iIntros (rr) "Hrr". 
      brel_pures_l. brel_pures_r.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQ") as "Hfill".
      by iApply "IH". }

    iDestruct "H" as (????) "(->&->&(%u&->&->)&(%v&->&->))".
    brel_pures_l.
    brel_pures_r.
    
    rewrite is_unit.
    iApply brel_eq_l. iApply brel_eq_r. 
    destruct (bool_decide (u = 1%g)) eqn:Heq.

 (* Protocol done loop *)
    { brel_pures_l. brel_pures_r.
      iDestruct ("Hkont" with "HQ") as "Hfill".
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_cont_r with "[$]").
      iClear "Hl0 Hl1".
      iRevert (k1' k2' H H0) "Hfill".
      iLöb as "IH". iIntros (????) "Hfill".
      iApply (brel_exhaustion' OS (fill _ #()%V) (fill _ #()%V) with "Hfill"); [set_solver|set_solver|].
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|].
      iIntros (???????) "(%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl".
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
      iIntros (rr) "Hrr". 
      brel_pures_l. brel_pures_r.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQ") as "Hfill".
      by iApply "IH". }
    
    brel_pures_l. brel_pures_r. brel_pures'.
    iApply brel_eq_r.
    destruct (bool_decide (v = (u ^+ (f_ring (Fp_of_fin g0) t0))%g)) eqn:Heq1; brel_pures'.

(* (e1, e2) = (enc(m0), enc(g)) - couple enc(m1) to enc(g) *)
    + iApply (brel_handle_os_r [_] [AppRCtx _]); [set_solver|].
      iIntros (rRecv) "Hr". brel_pures'.
      
      iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|].
      iIntros (rAlice) "HAlice". brel_pures.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_load_r with "[$Hl0]"). iIntros "Hl0". 
      iApply (brel_cont_r with "[$]").
      brel_pures'. 
      destruct (log_g m1) as (km & ->).
      destruct (log_g u) as (ku & ->).
      destruct (log_g v) as (kv & ->).

      set c1 := c1' (zmodp.inZp (fin_to_nat t1)) (Fp_of_fin g1) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

      set f' := minus_ring c1.

      set c2 := c2' (zmodp.inZp (fin_to_nat t1)) (Fp_of_fin g1) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

      set g' := plus_ring c2.
      iApply (brel_couple_rand_rand _ _ g' (H:=plus_bij_ring c2)).
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
      iIntros (s1 Hs1). brel_pures_l. brel_pures_r.

      iApply (brel_couple_rand_rand _ _ f' (H:=minus_ring_bij c1)).
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
      iIntros (r1 Hr1). brel_pures_l. brel_pures_r.
      
      iApply brel_couple_rand_rand; [done|]. iIntros (s0 Hs0). brel_pures_l. brel_pures_r.
      iApply brel_couple_rand_rand; [done|]. iIntros (r0 Hr0). brel_pures_l. brel_pures_r.
      iApply brel_exp_l. repeat brel_exp_r. 
      do 2 brel_mult_r. do 2 brel_exp_r.
      brel_exp_l. brel_mult_l. brel_mult_l. brel_exp_l. brel_exp_l.
      brel_mult_l. brel_pures. brel_exp_r. brel_exp_r. brel_mult_r. brel_mult_r.
      brel_exp_r. brel_exp_r. brel_mult_r. brel_pures_r.
      brel_exp_l. do 2 brel_mult_l. do 2 brel_exp_l. brel_pures. brel_mult_l. brel_pures_l.
      rewrite -!expgM.
      rewrite -!expgnDr.
      rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g1 r1) (ssrnat.muln t1 s1))).
      1 : rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g1 (f' r1)) (ssrnat.muln t1 (g' s1)))).
      2,3 : rewrite -g_nontriv; apply expg_order.
      unshelve rewrite enc_fin_cancel1 //.
      2,3 : rewrite Rcomplements.SSR_leq; lia.
      rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.addn 1 _) _)).
      2: rewrite -g_nontriv; apply expg_order.
      rewrite enc_fin_cancel2 //.
      3, 4 : rewrite Rcomplements.SSR_leq; lia.
      2 : { apply: (enc_nondeg_other (n_prime := n_prime) g0 g1 ku kv t0 t1).
            { apply Rcomplements.SSR_leq; lia. }
            { apply Rcomplements.SSR_leq; lia. }
            { by apply Fp_of_fin_ne_zero_2. }
            { apply Fp_of_fin_ne_zero_2 => Hc0.
              move: Heq => /bool_decide_eq_false_1 Hne0.
              apply: Hne0. by rewrite Hc0 fin_to_nat_to_fin expg0. }
            { apply bool_decide_eq_true_1 in Heq1.
              rewrite -expgM in Heq1.
              move/eqtype.eqP: Heq1. rewrite cyclic.eq_expg_mod_order g_nontriv.
              by move/eqtype.eqP. }
            { apply not_elem_of_cons in Hneq as [Hne' _].
              move=> Hc. apply: Hne'. apply: fin_to_nat_inj.
              by rewrite fin_to_nat_to_fin. } }
      rewrite !expg_mod.
      2,3 : rewrite -g_nontriv; apply expg_order.
      brel_pures'.
      
      iApply (brel_bind [_] [_;_;_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply traversable_ectx_labels; last first; [eapply distinct_submseteq; [|apply Hdistinct]; solve_submseteq|set_solver|set_solver]. }
      { iApply to_iThy_le_intro'; solve_submseteq. }
      iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
      { rewrite /sem_ty_arr /sem_ty_mbang /=. iApply "Hsend".
        iExists _,_,_,_. do 2 (iSplit; try done).
        iSplit; iExists _,_,_,_; try (do 2 (iSplit; try done));
                              iSplit; iExists _; done.
      }
      iIntros (??) "(->&->)".
      brel_pures'.

      (* Protocol done loop *)
    { brel_pures'.
      iDestruct ("Hkont" with "HQ") as "Hfill".
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_cont_r with "[$]").
      iClear "Hl0 Hl1".
      iRevert (k1' k2' H H0) "Hfill".
      iLöb as "IH". iIntros (????) "Hfill".
      iApply (brel_exhaustion' OS (fill _ #()%V) (fill _ #()%V) with "Hfill"); [set_solver|set_solver|].
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|].
      iIntros (???????) "(%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl".
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
      iIntros (rr) "Hrr". 
      brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQ") as "Hfill".
      by iApply "IH". }

    + iApply (brel_handle_os_r [_] [AppRCtx _]); [set_solver|].
      iIntros (rRecv) "Hr". brel_pures.
      
      iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|].
      iIntros (rAlice) "HAlice". brel_pures.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_load_r with "[$Hl1]"). iIntros "Hl1". 
      iApply (brel_cont_r with "[$]").
      brel_pures. brel_exp_r. brel_pures'.
      iApply brel_couple_rand_rand; [done|]. iIntros (s1 Hs1). brel_pures.
      iApply brel_couple_rand_rand; [done|]. iIntros (r1 Hr1). brel_pures.
      brel_pures.
      destruct (log_g m0) as (km & ->).
      destruct (log_g u) as (ku & ->).
      destruct (log_g v) as (kv & ->).
      
      set c1 := c1' (zmodp.inZp t0) (Fp_of_fin g0) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

      set f' := minus_ring c1.

      set c2 := c2' (zmodp.inZp t0) (Fp_of_fin g0) (Fp_of_fin km) (Fp_of_fin ku) (Fp_of_fin kv).

      set g' := plus_ring c2.
      
      iApply (brel_couple_rand_rand _ _ g' (H:=plus_bij_ring c2)).
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
      iIntros (s0 Hs0). brel_pures'.

      iApply (brel_couple_rand_rand _ _ f' (H:=minus_ring_bij c1)).
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply plus_ring_lt; first done. apply Rcomplements.SSR_leq. lia. }
      iIntros (r0 Hr0). brel_pures_l. brel_pures_r.

      iApply brel_exp_l. iApply brel_exp_r. brel_exp_r. 
      brel_mult_r. brel_mult_r. brel_exp_r.
      brel_exp_r. brel_mult_r.
      brel_exp_l. brel_mult_l. brel_mult_l.
      brel_exp_l. brel_exp_l. brel_mult_l. 
      do 2 brel_exp_r. do 2 brel_mult_r. do 2brel_exp_r. brel_mult_r.
      brel_pures. brel_exp_l. do 2 brel_mult_l. repeat brel_exp_l.
      repeat brel_mult_l. brel_pures_l. 

      rewrite -!expgM.
      rewrite -!expgnDr.
      rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g0 r0) (ssrnat.muln t0 s0))).
      1 : rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.muln g0 (f' r0)) (ssrnat.muln t0 (g' s0)))).
      2,3 : rewrite -g_nontriv; apply expg_order.
      unshelve rewrite enc_fin_cancel1 //.
      2,3 : rewrite Rcomplements.SSR_leq; lia.
      rewrite -(expg_mod (p:=n) (ssrnat.addn (ssrnat.addn 1 _) _)).
      2: rewrite -g_nontriv; apply expg_order.
      rewrite enc_fin_cancel2 //.
      3, 4 : rewrite Rcomplements.SSR_leq; lia.
      2 : { apply: (enc_nondeg_self (n_prime := n_prime) g0 ku kv t0).
            { apply Rcomplements.SSR_leq; lia. }
            { by apply Fp_of_fin_ne_zero_2. }
            { rewrite -expgM in Heq1. apply bool_decide_eq_false_1 in Heq1.
              move=> Hc. apply: Heq1.
              rewrite -(expg_mod_order g (fin.fin_to_nat kv))
                      -(expg_mod_order g (fin.fin_to_nat ku * f_ring (Fp_of_fin g0) t0)).
              by rewrite !g_nontriv Hc. } }
      rewrite !expg_mod.
      2,3 : rewrite -g_nontriv; apply expg_order.
      brel_pures'.
      
      iApply (brel_bind [_] [_;_;_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply traversable_ectx_labels; last first; [eapply distinct_submseteq; [|apply Hdistinct]; solve_submseteq|set_solver|set_solver]. }
      { iApply to_iThy_le_intro'; solve_submseteq. }
      iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
      { rewrite /sem_ty_arr /sem_ty_mbang /=. iApply "Hsend".
        iExists _,_,_,_. do 2 (iSplit; try done).
        iSplit; iExists _,_,_,_; try (do 2 (iSplit; try done));
                              iSplit; iExists _; done.
      }
      iIntros (??) "(->&->)".
      brel_pures'.

      (* Protocol done loop *)
    { brel_pures'.
      iDestruct ("Hkont" with "HQ") as "Hfill".
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      brel_pures.
      iApply (brel_cont_r with "[$]").
      iClear "Hl0 Hl1".
      iRevert (k1' k2' H H0) "Hfill".
      iLöb as "IH". iIntros (????) "Hfill".
      iApply (brel_exhaustion' OS (fill _ #()%V) (fill _ #()%V) with "Hfill"); [set_solver|set_solver|].
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|].
      iIntros (???????) "(%&%&%&%&(%&->&->)&(%&->&->)&->&->&HQ) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl".
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver| ].
      iIntros (rr) "Hrr". 
      brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQ") as "Hfill".
      by iApply "IH". }
    Unshelve. all : done.
Qed.

End handlee_verification.
