From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances sem_types
  sem_judgement sem_row sem_def 
  p_composition
  fundamental
  tactics.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_thunk_sender_corrupt ot_bijection ot_common.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.

Import valgroup_notation.
Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

  Lemma fcrs_dh_ideal γcrs :
    ↯ (1 / n) -∗
    crs_empty γcrs -∗
    (* BREL f1 #()%V ≤ f2 #()%V <| ([CRS],[CRS], @CRSThy γcrs) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }} -∗ *)
    (* BREL F_CRS f1 ≤ (reduction DH_rand) f2 <| ([CRS],[CRS],iThyBot) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}. *)
    BREL F_CRS ≤ (reduction DH_rand) <|⊥|> {{ λ v1 v2, (∀ᵣ θ__L, (∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))) -{ sem_row_union (¡ θ__CRS) θ__L}-∘ 𝟙) -{ θ__L }-∘ 𝟙)%T v1 v2}}.
  Proof with (repeat foldkont; brel_pures') using n_prime G. 
    iIntros "Herr Hcrs".
    
    unfold F_CRS, reduction, DH_rand...
    iModIntro.
    iIntros (L f1 f2) "Hff"...

    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (t Ht) "!>"...
    apply not_elem_of_cons in Ht as [Ht _].
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by unshelve eapply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (a Ha)...
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by unshelve eapply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (b Hb)...
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by unshelve eapply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (c Hc)...

    iDestruct (crs_upd γcrs (vgval (g ^+ c), vgval (g ^+ b), vgval (g ^+ a), vgval (g ^+ t))%V with "Hcrs") as ">#Hcrs".
    
    brel_effect_l CRSl as "Hcrsl".
    brel_effect_r CRSr as "Hcrsr"...
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    iAssert (sem_val_typed (λ: <>, do: CRSl #()%V)%V (λ: <>, do: CRSr #()%V)%V (𝟙 -{ crsrow CRSl CRSr γcrs }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. 
      iIntros (??) "!# (->&->)". brel_pures'.
      iApply brel_introduction'; first constructor.
      iExists _,_,[],[],_;do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]); iSplit; try (iIntros (??) "!# H"; iApply "H").
      do 2 (iSplit; [by iPureIntro|]). iIntros (crs) "Hcrs'". iDestruct (crs_agree with "[$][$]") as "->". 
      iApply brel_value. iIntros "$ !>". 
      do 3 (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]);
      iSplit; last (iExists _; done)). iExists _; done. }
    rewrite /sem_val_typed /=. 
    iSpecialize ("Hff" with "Hgg"). 
        
    iApply (brel_exhaustion (f1 _) (f2 _) with "Hff"); [done|done|].
    iLöb as "IH".
    iSplit; [by iIntros (??) "!# (->&->)"; brel_pures'|].
    iIntros (?????) "!# %Hk1' %Hk2 (%&(->&->&HQ)&HQ'Q) #HQkont".
    iApply brel_handle_os_l; [apply neutral_ectx;constructor|]. iIntros (ul) "!> Hul".
    iApply brel_handle_os_r; [apply neutral_ectx;constructor|]. iIntros (ur) "Hur"...
    iApply (brel_cont_l with "[$]"). iModIntro.
    iApply (brel_cont_r with "[$]"). 
    
    iDestruct ("HQ" with "Hcrs") as "HQ".
    iDestruct ("HQ'Q" with "HQ") as "HQ".
    iDestruct ("HQkont" with "HQ") as "Hkont"...
    
    rewrite -!expgM. 
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ c))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ b))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ a))).
    rewrite g_nontriv.
    rewrite !crs_fin_cancel //.
    3,5,7: rewrite Rcomplements.SSR_leq; lia.
    2,3,4 : by unshelve eapply Fp_of_fin_ne_zero_2.
    rewrite !expg_mod; try (rewrite -g_nontriv; apply expg_order).
    
    iApply (brel_exhaustion with "Hkont"); [done|done|iApply "IH"].
  Qed.    

  Definition τC θ := (∀ᵣ θ__RECV, ∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾)) × (𝔹 -{ θ__RECV }-> (Option 𝔾))) 
                                         -{ sem_row_union θ__RECV (sem_row_union θ__CRS θ) }-∘ 𝟙)%T.

 

  (* OT_Real_Sender_corrupt is related to itself, given related effect
     implementations and a related adversary. This is the part shared by
     OT_real_DH_real and DH_real_OT_real. *)
  Lemma OT_Real_Sender_corrupt_self θ (f1 f2 doSend1 doSend2 doRecv1 doRecv2 : val) :
    ⊢ ((𝔾 × 𝔾) -{ θ }-> 𝟙)%T doSend1 doSend2 -∗
      (𝟙 -{ θ }-> Option ((ℕ × ℕ) × (ℕ × ℕ)))%T doRecv1 doRecv2 -∗
      τC θ f1 f2 -∗
      (∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))) -{ sem_row_union (¡ θ__CRS) (¡[OS] θ) }-∘ 𝟙)%T
        (λ: "doCRS", OT_Real_Sender_corrupt f1 ((doSend1, doRecv1)%V, "doCRS"))%V
        (λ: "doCRS", OT_Real_Sender_corrupt f2 ((doSend2, doRecv2)%V, "doCRS"))%V.
  Proof with (repeat foldkont;brel_pures') using G n_prime.
    iIntros "#Hsend #Hrecv Hff".
    rewrite /OT_Real_Sender_corrupt /=.
    iIntros (θCRS). iUnfold sem_ty_arr, sem_ty_mbang. simpl.
    iIntros (doCRS1 doCRS2) "#HCRS"...
    brel_effect_l IDEALl as "Hideall".
    brel_effect_r IDEALr as "Hidealr"...
    eset (recv := recvrow2 IDEALl IDEALr).
      iAssert ((((𝟙 -{ θCRS }-> ((𝔾 × 𝔾) × 𝔾) × 𝔾)) × (𝔹 -{ recv }-> Option 𝔾))%T
                 (doCRS1, λ: "b", do: IDEALl InjL "b")%V
                 (doCRS2, λ: "b", do: IDEALr InjL "b")%V) as "Hgg".
      { repeat (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]); iSplit); rewrite /sem_ty_mbang //=; iIntros (??) "!#". iIntros "(%&->&->)". brel_pures'.
          iApply brel_introduction'; first constructor.
          iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
          iSplitL; last (iIntros (??) "!# H"; iApply "H").
          iExists _.
          do 2 (iSplit; first by iPureIntro). simpl.
          iSplitL; [iApply brel_value; iIntros "$ !>"; iExists _,_; by iLeft|].
          iIntros (?); brel_pures'; iApply brel_value; iIntros "$ !>"; iExists _,_; iRight; repeat iSplit; try done; iExists _; done. }
      iDestruct ("Hff" with "Hgg") as "Hfbrel".
      
      iApply brel_new_theory.
      iApply (brel_add_label_l with "Hideall").
      iApply (brel_add_label_r with "Hidealr").
      
      iApply (brel_exhaustion _ _ [_] [_] with "[Hfbrel]"); try set_solver.
      { iDestruct (brel_introduction_mono with "[][$Hfbrel]") as "Hfb"; last iApply "Hfb".
        rewrite /recv /sem_row_union //= !iLblSig_to_iLblThy_proj !iLblSig_to_iLblThy_app.
        iSplit.
        - iApply iThy_le_trans;
          first iApply (iThy_le_to_iThy_app_inv [([IDEALl], [IDEALr], ot_common.recv IDEALl IDEALr : iThy Σ)]).
          iApply iThy_le_trans; last iApply (iThy_le_to_iThy_app [([IDEALl], [IDEALr], ot_common.recv IDEALl IDEALr : iThy Σ)]).
          iApply iThy_le_sum_r.
          rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
          rewrite to_iThyIfMono_app.
          iApply iThy_le_trans; last iApply iThy_le_to_iThy_to_iThyIfMono.
          iIntros (???) "!# Hthy /=".
          iExists Q. iFrame. iIntros (??) "!> $".
        - iSplit.
          + iIntros "!# (Hl&Hr)".
            rewrite /logic.valid /valid_l /valid_r. 
            rewrite !labels_l_cons !labels_r_cons.  
            rewrite !labels_l_app !labels_r_app.
            rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
            rewrite !labels_l_to_iThyIfMono !labels_r_to_iThyIfMono.
            iSplit; done.
          + rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
            rewrite /distinct' /distinct /distinct_l /distinct_r. 
            rewrite !labels_l_cons !labels_r_cons. 
            rewrite !labels_l_app !labels_r_app.
            rewrite !labels_l_to_iThyIfMono !labels_r_to_iThyIfMono.
            by iIntros "!# (%Hl&%Hr)". 
      }
      iSplit; [by iIntros (v1 v2) "!# (->&->)"; brel_pures'|].
      iIntros (?????) "!# %Hk1 %Hk2 (%b&->&->&(HQNone&HQSome)) #Hreturn".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
      iIntros (cl) "!> Hcl"...
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver|].
      iIntros (cr) "Hcr"...

      iApply (brel_bind [_] [_] _ (iLblSig_to_iLblThy (¡ θCRS)%R)).
      { iApply traversable_to_iThy. }
      { iApply to_iThy_le_intro'.  
        rewrite iLblSig_to_iLblThy_app.
        solve_submseteq. }
      unfold sem_row_flip_mbang. 
      rewrite iLblSig_to_iLblThy_app.
      rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
      iApply (brel_mono OS); [iApply to_iThy_le_refl|by iApply "HCRS"|simpl].
      iIntros (??) "(%&%&%&%&->&->&(%&%&%&%&->&->&(%&%&%&%&->&->&(%&->&->)&(%&->&->))&(%&->&->))&(%&->&->))"...
      iApply brel_couple_rand_rand; first done.
      iIntros (n Hlt)...
      destruct b...
      - iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))); [iApply traversable_to_iThy|iApply to_iThy_le_intro'; solve_submseteq|].
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
        { rewrite /sem_ty_arr /sem_ty_mbang /=. iApply "Hsend".
          iExists _,_,_,_. do 2 (iSplit; try done).
          iSplit; iExists _; do 2 (iSplit; done). }
        iIntros (??) "(->&->)"...
        iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))); [iApply traversable_to_iThy|iApply to_iThy_le_intro'; solve_submseteq|].
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].        
        { rewrite /sem_ty_arr /sem_ty_mbang /=. by iApply "Hrecv". }
        iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])"...
        { protocol_done ms. }

        iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
        iDestruct "H1" as "(%&%&%&%&(->&->&(%c0z&->&->)&(%d0z&->&->)))".
        iDestruct "H2" as "(%&%&%&%&(->&->&(%c1z&->&->)&(%d1z&->&->)))"...

        (* Deserialize a group element from c0 *)
        destruct (vg_of_int_sem c0z) as [c0|] eqn:Hc0z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        (* Deserialize a group element from d0 *)
        destruct (vg_of_int_sem d0z) as [d0|] eqn:Hd0z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        (* Deserialize a group element from c1 *)
        destruct (vg_of_int_sem c1z) as [c1|] eqn:Hc1z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        (* Deserialize a group element from d1 *)
        destruct (vg_of_int_sem d1z) as [d1|] eqn:Hd1z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        iDestruct ("Hreturn" with "HQSome") as "Hfill";
          iApply (brel_cont_l with "[$]"); iModIntro;
          iApply (brel_cont_r with "[$]")...
        iClear "HQNone";
          iApply (brel_exhaustion (fill _ _) (fill _ _) with "Hfill");
          [set_solver|set_solver|];
          protocol_done_loop_ms.
      - iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))); [iApply traversable_to_iThy|iApply to_iThy_le_intro'; solve_submseteq|].
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].  
        { rewrite /sem_ty_arr /sem_ty_mbang /=. iApply "Hsend".
          iExists _,_,_,_. do 2 (iSplit; try done).
          iSplit; iExists _; do 2 (iSplit; done). }
        iIntros (??) "(->&->)"...
        iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))); [iApply traversable_to_iThy|iApply to_iThy_le_intro'; solve_submseteq|].
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].  
        { rewrite /sem_ty_arr /sem_ty_mbang /=. by iApply "Hrecv". }
        iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])"...
        { protocol_done ms. }

        iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
        iDestruct "H1" as "(%&%&%&%&(->&->&(%c0z&->&->)&(%d0z&->&->)))".
        iDestruct "H2" as "(%&%&%&%&(->&->&(%c1z&->&->)&(%d1z&->&->)))"...

        (* Deserialize a group element from c0 *)
        destruct (vg_of_int_sem c0z) as [c0|] eqn:Hc0z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        (* Deserialize a group element from d0 *)
        destruct (vg_of_int_sem d0z) as [d0|] eqn:Hd0z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        (* Deserialize a group element from c1 *)
        destruct (vg_of_int_sem c1z) as [c1|] eqn:Hc1z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        (* Deserialize a group element from d1 *)
        destruct (vg_of_int_sem d1z) as [d1|] eqn:Hd1z.
        2 : {
          iApply brel_vg_of_int_none_l; first done.
          iApply brel_vg_of_int_none_r; first done...

          (* Protocol done loop *)
          protocol_done ms. }

        iApply brel_vg_of_int_correct_l; first done.
        iApply brel_vg_of_int_correct_r; first done...

        iDestruct ("Hreturn" with "HQSome") as "Hfill";
          iApply (brel_cont_l with "[$]"); iModIntro;
          iApply (brel_cont_r with "[$]")...
          iClear "HQNone";
          iApply (brel_exhaustion (fill _ _) (fill _ _) with "Hfill");
          [set_solver|set_solver|];
          protocol_done_loop_ms.
    Qed.

  Definition τ_sc := (∀ᵣ θ, τC θ ⊸ (((𝔾 × 𝔾) -{ θ }-> 𝟙) × (𝟙 -{ θ }-> Option ((ℕ × ℕ) × (ℕ × ℕ))))
            -{ ¡[OS] θ}-∘ 𝟙)%T.
  
  Lemma OT_real_DH_real : 
     ⊢ ↯ (1 / n) -∗
     BREL (λ: "f" "effs", F_CRS (λ: "doCRS", OT_Real_Sender_corrupt "f" ("effs", "doCRS")))%V ≤
          OT_REDUCTION DH_rand <| ⊥ |> {{ τ_sc}}.
  Proof using G n_prime inG0.
    iIntros "Herr". unfold OT_REDUCTION. brel_pures'.
    iIntros "!> %θ %f1 %f2 Hff".
    brel_pures'.
    iModIntro.
    iIntros (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)".
    brel_pures'.
    iApply (brel_bind' [AppLCtx _] [AppLCtx _]).
    { iApply traversable_to_iThy. }
    iApply brel_introduction_mono; [iApply to_iThy_le_bot|].
    iDestruct crs_alloc as ">(%γcrs&Hcrs)".
    assert (to_iThyIfMono OS [] = ⊥) as <-; first done.
    iApply (brel_mono OS with "[][Herr Hcrs]"); [iApply to_iThy_le_refl|iApply (fcrs_dh_ideal with "[$][$]")|simpl].
    iIntros (g1 g2) "Hgg /=".
    iApply "Hgg".
    iApply (OT_Real_Sender_corrupt_self with "Hsend Hrecv Hff").
  Qed.

  Lemma DH_OT_sim :
    ⊢ ↯ (1 / n) -∗
    BREL OT_REDUCTION DH_real ≤ OT_SIM_FOT_thunk <| ⊥ |> {{ τ_sc }}.
  Proof with (repeat foldkont; brel_pures') using G n_prime inG0. 
    iIntros "Herr". unfold OT_REDUCTION...
    iIntros "!> %θ %f1 %f2 Hff".
    rewrite /reduction /DH_real /OT_Real_Sender_corrupt /OT_SIM_FOT_thunk...
    iIntros "!#" (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)"...

    iApply brel_couple_rand_rand; first done. iIntros (t Ht)...
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (y Hy) "!>"...
    apply not_elem_of_cons in Hy as [Hy _]. 
    iApply brel_couple_rand_rand; first done. iIntros (x Hx)...
    rewrite -Nat2Z.inj_mul...
    rewrite expgnA.

    unfold mut_handler, simhandler, idealhandler...
    brel_effect_l CRSl as "Hcrsl"...
    brel_effect_r CRSr as "Hcrsr"...
    brel_alloc_r l0 as "Hl0"...
    brel_alloc_r l1 as "Hl1"...
    brel_effect_l IDEALl as "Hideall"...
    brel_effect_r IDEALr as "Hidealr"...
    brel_effect_r LEAK as "Hleakr"...

    iDestruct crs_alloc as ">(%γcrs&Hcrs)".
    iDestruct (crs_upd γcrs (vgval (g ^+ t ^+ y ^+ x), vgval (g ^+ t ^+ x), vgval (g ^+ t ^+ y), vgval (g ^+ t))%V with "Hcrs") as ">#Hcrs".

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum (CRSThy CRSl CRSr) (CRSThyL CRSl))) with "[Hff Hl0 Hl1 Hideall Hidealr Hleakr]"); try done.  

    (* CRS handler *)
    2 : { iLöb as "IH".
          iSplit; [iIntros (v1 v2) "!# H"; by brel_pures'|].
          iIntros (???????) "!# (%&[(->&->&HQ)| (->&HQ)]&HQQ) #Hkont".
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl".
            iApply brel_handle_os_r; [apply neutral_ectx; set_solver|].
            iIntros (rr) "Hrr"...
            iApply (brel_cont_l with "[$]"). iModIntro.
            iApply (brel_cont_r with "[$]").
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum  (CRSThy CRSl CRSr) (CRSThyL CRSl))) with "[H]"); done.
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl"...
            iApply (brel_cont_l with "[$]"). iModIntro.
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum  (CRSThy CRSl CRSr) (CRSThyL CRSl))) with "[H]"); done. }

    eset (recv := recvrow IDEALl IDEALr LEAK).
    set crs := crsrow CRSl CRSr γcrs.
    iAssert ((((𝟙 -{ crs }-> ((𝔾 × 𝔾) × 𝔾) × 𝔾)) × (𝔹 -{ recv }-> Option 𝔾))%T
               (λ: <>, do: CRSl #(), λ: "b", do: IDEALl InjL "b")%V
               (λ: <>, do: CRSr #(), λ: "b", do: IDEALr InjL "b")%V) as "Hgg".
    { repeat (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]); iSplit); rewrite /sem_ty_mbang //=; iIntros (??) "!#".
      - iIntros "(->&->)". brel_pures'. iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
        iSplitL; last (iIntros (??) "!# H"; iApply "H").
        do 2 (iSplit; first by iPureIntro).
        iIntros (?) "Hcrs'". iDestruct (crs_agree with "Hcrs Hcrs'") as "<- /=". 
        iApply brel_value. iIntros "$ !>". 
        do 3 
          (iExists _,_,_,_;
                         do 2 (iSplit; first by iPureIntro);
                         iSplit; last (iExists _; iSplit; by iPureIntro)).
        iExists _; iSplit; by iPureIntro. 
      - iIntros "(%&->&->)". brel_pures'.
        iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
        iSplitL; last (iIntros (??) "!# H"; iApply "H").
        iExists _.
        do 2 (iSplit; first by iPureIntro). simpl.
        iSplitL; [iApply brel_value; iIntros "$ !>"; iExists _,_; by iLeft|].
        iIntros (?); brel_pures'; iApply brel_value; iIntros "$ !>"; iExists _,_; iRight; repeat iSplit; try done; iExists _; done. }
    
    iDestruct ("Hff" with "Hgg") as "Hfbrel". (* rewrite /sem_row_union //=. *)
    iDestruct (brel_introduction_mono with "[][$Hfbrel]") as "Hfb".
    { iApply to_iThy_le_trans.
      - iApply to_iThy_le_intro'. apply submseteq_swap.
      - iApply to_iThy_le_trans.
        + iSplit.
          * iApply iThy_le_trans; first iApply (iThy_le_to_iThy_sum [CRSl] [CRSr]).
            iApply iThy_le_trans; last iApply (iThy_le_sum_to_iThy [CRSl] [CRSr] ((iThySum (CRSThy CRSl CRSr) (CRSThyL CRSl)))).
            iApply iThy_le_sum_l. iIntros (???) "!# (%&%&%&%&%&?&?&?&?&H&?)". iExists e1',e2',k1,k2,_. iFrame. 
          * iSplit; iModIntro; [iIntros "#Hvalid"; iApply valid_to_iThy_bot; 
                                by (iDestruct (valid_to_iThy_bot with "Hvalid") as "?")
                               | (iIntros (Hdistinct); iPureIntro)]; simpl.
            apply distinct_to_iThy_bot. by apply distinct_to_iThy_bot in Hdistinct. 
        + iApply to_iThy_le_intro'; apply submseteq_swap. }
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hideall").
    iApply (brel_add_label_r with "Hleakr").
    iApply (brel_add_label_r with "Hidealr").


    iApply brel_learn. iIntros ((HdistinctL&HdistinctR)) "_ /=". 
    unfold sem_row_flip_mbang. 
    rewrite iLblSig_to_iLblThy_proj.
    rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. 

    iApply (brel_exhaustion' OS (f1 _) (f2 _) with "[$Hfb]"); [done|set_solver|].
    iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
    iIntros (k1' k2' e1' e2' Q Hk1' Hk2') "(%&->&->&(HQNone & HQSome)) Hkont".
    iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
    iIntros (cl) "!> Hcl"...
    iApply (brel_handle_os_r [_] (k2')). 
    { apply neutral_ectx; set_solver. }
    iIntros (cr) "Hcr"...
    iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|simpl].
    iIntros (cleak) "Hleak"...

    iApply brel_learn. iIntros (Hdistinct) "_".

    iApply (brel_introduction' [CRSl]). { repeat constructor. }
    iExists _, _, [AppRCtx _], [HandleCtx _ _ _ _ _; HandleCtx _ _ _ _ _; AppRCtx _], _.  iSplit; [done|].
    iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|].
    iSplit; [done|]. iSplit; [iPureIntro|].
    { eapply distinct_submseteq in Hdistinct; [|apply submseteq_swap].
         eapply (distinct_r_app_NeutralEctx _ _ _ _ [([CRSr],_,iThyMono iThyBot)]); [(destruct Hdistinct as [_ Hd]; apply Hd)| |constructor].
         set_solver. }
    iSplit; last (iModIntro; iIntros (??) "H"; done).
    iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
    iLeft. do 2 (iSplit; [done|]). iIntros (?) "Hcrs'".
    iDestruct (crs_agree with "[$][$]") as "->". iClear "Hcrs'"...

     (* Should be refactored into one branch *)
    destruct b.
    - epose proof brel_couple_rand_rand as h'.
      unshelve iApply (h' _ _ (f_ring (Fp_of_fin y)) (f_bij_ring (Fp_of_fin y))); try done.
      { by unshelve eapply Fp_of_fin_ne_zero_2. }
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
        by apply Rcomplements.SSR_leq. }
      iIntros (α Hα)...
      rewrite -Nat2Z.inj_mul...
      rewrite -expgM. rewrite ssrnat.multE. rewrite (ssrnat.mulnC _ y).
      rewrite -!(@expg_mod _ n (ssrnat.muln y (f_ring (Fp_of_fin y) α))).
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      rewrite !crs_fin_cancel; try done.
      2 : { by unshelve eapply Fp_of_fin_ne_zero_2. }
      2 : { apply Rcomplements.SSR_leq. lia. }
      rewrite !expg_mod. 
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
       { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hsend". simpl. 
        iApply "Hsend". iExists _,_,_,_. 
        do 2 (iSplit; first done).
        iSplit; iExists _; iSplit; done. }
      simpl.
      iIntros (??) "(->&->)"...
      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hrecv". simpl. 
        by iApply "Hrecv". }
      simpl.
      iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])"...

      (* Protocol done loop *)
      { protocol_done cache_r. }

      iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
      iDestruct "H1" as "(%&%&%&%&(->&->&(%c0z&->&->)&(%d0z&->&->)))".
      iDestruct "H2" as "(%&%&%&%&(->&->&(%c1z&->&->)&(%d1z&->&->)))"...
      
      (* Deserialize a group element from c0 *)
      destruct (vg_of_int_sem c0z) as [c0|] eqn:Hc0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r.  }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d0 *)
      destruct (vg_of_int_sem d0z) as [d0|] eqn:Hd0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from c1 *)
      destruct (vg_of_int_sem c1z) as [c1|] eqn:Hc1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d1 *)
      destruct (vg_of_int_sem d1z) as [d1|] eqn:Hd1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...
      
      iApply brel_int_of_vg_sem_correct_r.
      iApply brel_int_of_vg_sem_correct_r.
  
      iApply (brel_handle_os_r [_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "HrS"...
      unfold store_if_none.
      
      do 2 (iApply brel_vg_of_int_correct_r; first apply int_of_vg_of_int_sem)...
      
      brel_load_r...
      brel_store_r...
      brel_load_r...
      brel_store_r...
      iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver |].
      iIntros (rL) "HrL"...
      iApply (brel_cont_r with "[$]")...
      iApply (brel_cont_r with "[$]")...
      rewrite -!(@expg_mod _ n (ssrnat.muln y (f_ring (Fp_of_fin y) α))).
      2 : { apply vgG_expg_n. }
      rewrite !crs_fin_cancel; try done.
      2 : { by unshelve eapply Fp_of_fin_ne_zero_2. }
      2 : { apply Rcomplements.SSR_leq. lia. }
      rewrite expg_mod.
      2 : { apply vgG_expg_n. }
      
      (* Protocol done loop *)
      iDestruct ("Hkont" with "HQSome") as "Hkont".
      iApply (brel_cont_l with "[$]"); iModIntro.
      iApply (brel_cont_r with "[$]")...
      brel_load_r...
      iApply (brel_cont_r with "[$]")...
      iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hkont"); [first [done|set_solver]|set_solver|].
      iClear "HQNone Hl1 Hl0".
      protocol_done_loop.
      
    - iApply brel_couple_rand_rand; first done. iIntros (α Hα)...
      rewrite -Nat2Z.inj_mul...

      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hsend". simpl. 
        iApply "Hsend". iExists _,_,_,_. 
        do 2 (iSplit; first done).
        rewrite !expgnA. rewrite expgnAC.
        rewrite (expgnAC _ α y). rewrite (expgnAC _ x y).
        iSplit; iExists _; iSplit; done. }
      simpl. 
      iIntros (??) "(->&->)"...

      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hrecv". simpl. 
        by iApply "Hrecv". }
      simpl.
      iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])"...
            
      (* Protocol done loop *)
      { protocol_done cache_r. }
      
      iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
      iDestruct "H1" as "(%&%&%&%&(->&->&(%c0z&->&->)&(%d0z&->&->)))".
      iDestruct "H2" as "(%&%&%&%&(->&->&(%c1z&->&->)&(%d1z&->&->)))"...

      (* Deserialize a group element from c0 *)
      destruct (vg_of_int_sem c0z) as [c0|] eqn:Hc0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r.  }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d0 *)
      destruct (vg_of_int_sem d0z) as [d0|] eqn:Hd0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from c1 *)
      destruct (vg_of_int_sem c1z) as [c1|] eqn:Hc1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d1 *)
      destruct (vg_of_int_sem d1z) as [d1|] eqn:Hd1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_r. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      iApply brel_int_of_vg_sem_correct_r.
      iApply brel_int_of_vg_sem_correct_r.
  
      iApply (brel_handle_os_r [_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "HrS"...
      unfold store_if_none.

      do 2 (iApply brel_vg_of_int_correct_r; first apply int_of_vg_of_int_sem)...

      brel_load_r...
      brel_store_r...
      brel_load_r...
      brel_store_r...
      iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|].
      iIntros (rL) "HrL". brel_pures'.
      iApply (brel_cont_r with "[$]")...
      iApply (brel_cont_r with "[$]")...
  
      (* Protocol done loop *)
      iDestruct ("Hkont" with "HQSome") as "Hkont".
      iApply (brel_cont_l with "[$]"); iModIntro.
      iApply (brel_cont_r with "[$]")...
      brel_load_r...
      iApply (brel_cont_r with "[$]")...
      iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hkont"); [first [done|set_solver]|set_solver|].
      iClear "HQNone Hl1 Hl0".
      protocol_done_loop.
  Qed.

  
  Lemma OT_sim_DH :
    ⊢ ↯ (1 / n) -∗
    BREL OT_SIM_FOT_thunk ≤ OT_REDUCTION DH_real <| ⊥ |> {{ τ_sc }}.
  Proof with (repeat foldkont; brel_pures') using All. 
    iIntros "Herr". unfold OT_REDUCTION...
    iIntros "!> %θ %f1 %f2 Hff".
    rewrite /reduction /DH_real /OT_Real_Sender_corrupt /OT_SIM_FOT_thunk...
    iIntros "!#" (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)"...

    iApply brel_couple_rand_rand; first done. iIntros (t Ht)...
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (y Hy) "!>".
    apply not_elem_of_cons in Hy as [Hy _]. brel_pures'.
    iApply brel_couple_rand_rand; first done. iIntros (x Hx)...
    rewrite -Nat2Z.inj_mul...
    rewrite expgnA...
    
    brel_effect_l CRSl as "Hcrsl"...
    brel_effect_r CRSr as "Hcrsr"...
    unfold mut_handler, simhandler, idealhandler...
    brel_alloc_l l0 as "Hl0"...
    brel_alloc_l l1 as "Hl1"...
    brel_effect_l IDEALl as "Hideall"...
    brel_effect_l LEAK as "Hleakl"...
    brel_effect_r IDEALr as "Hidealr"...

    iDestruct crs_alloc as ">(%γcrs&Hcrs)".
    iDestruct (crs_upd γcrs (vgval (g ^+ t ^+ y ^+ x), vgval (g ^+ t ^+ x), vgval (g ^+ t ^+ y), vgval (g ^+ t))%V with "Hcrs") as ">#Hcrs".

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    iApply (brel_exhaustion _ _ [_] [_] (iThyMono (CRSThy CRSl CRSr)) with "[Hff Hl0 Hl1 Hideall Hidealr Hleakl]"); try done.

    2 : { iLöb as "IH".
          iSplit; [iIntros (v1 v2) "!# H"; by brel_pures'|].
          iIntros (???????) "!# (%&(->&->&HQ)&HQQ) #Hkont".
          iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
          iIntros (rl) "!> Hrl".
          iApply brel_handle_os_r; [apply neutral_ectx; set_solver|].
          iIntros (rr) "Hrr"...
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          iDestruct ("HQ" with "Hcrs") as "HQ'".
          iDestruct ("HQQ" with "HQ'") as "HQ".
          iDestruct ("Hkont" with "HQ") as "H".
          iApply (brel_exhaustion _ _ [_] [_] (iThyMono (CRSThy CRSl CRSr)) with "[H]"); done. }

    eset (recv := recvrowl IDEALl IDEALr LEAK).
    set crs := crsrow CRSl CRSr γcrs.
    iAssert ((((𝟙 -{ crs }-> ((𝔾 × 𝔾) × 𝔾) × 𝔾)) × (𝔹 -{ recv }-> Option 𝔾))%T
               (λ: <>, do: CRSl #(), λ: "b", do: IDEALl InjL "b")%V
               (λ: <>, do: CRSr #(), λ: "b", do: IDEALr InjL "b")%V) as "Hgg".
    { repeat (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]); iSplit); rewrite /sem_ty_mbang //=; iIntros (??) "!#".
      - iIntros "(->&->)"... iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
        iSplitL; last (iIntros (??) "!# H"; iApply "H").
        do 2 (iSplit; first by iPureIntro).
        iIntros (?) "Hcrs'". iDestruct (crs_agree with "Hcrs Hcrs'") as "<- /=".
        iApply brel_value. iIntros "$ !>".
        do 3
          (iExists _,_,_,_;
                         do 2 (iSplit; first by iPureIntro);
                         iSplit; last (iExists _; iSplit; by iPureIntro)).
        iExists _; iSplit; by iPureIntro.
      - iIntros "(%&->&->)"...
        iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
        iSplitL; last (iIntros (??) "!# H"; iApply "H").
        iExists _.
        do 2 (iSplit; first by iPureIntro). simpl.
        iSplitL; [iApply brel_value; iIntros "$ !>"; iExists _,_; by iLeft|].
        iIntros (?); brel_pures'; iApply brel_value; iIntros "$ !>"; iExists _,_; iRight; repeat iSplit; try done; iExists _; done. }
    iDestruct ("Hff" with "Hgg") as "Hfbrel".

    iDestruct (brel_introduction_mono with "[][$Hfbrel]") as "Hfb".
    { iApply to_iThy_le_trans.
      - iApply to_iThy_le_intro'. apply submseteq_swap.
      - iApply to_iThy_le_trans.
        + iSplit.
          * iApply iThy_le_trans; first iApply (iThy_le_to_iThy_sum [CRSl] [CRSr]).
            iApply iThy_le_trans;
              last iApply (iThy_le_sum_to_iThy [CRSl] [CRSr] (CRSThy CRSl CRSr)).
            iApply iThy_le_sum_l. iIntros (???) "!# (%&%&%&%&%&?&?&?&?&H&?)".
            iExists e1',e2',k1,k2,_. iFrame.
          * iSplit; iModIntro; [iIntros "#Hvalid"; iApply valid_to_iThy_bot;
                                by (iDestruct (valid_to_iThy_bot with "Hvalid") as "?")
                               | (iIntros (Hdistinct); iPureIntro)]; simpl.
            apply distinct_to_iThy_bot. by apply distinct_to_iThy_bot in Hdistinct.
        + iApply to_iThy_le_intro'; apply submseteq_swap. }

    iApply brel_new_theory.
    iApply (brel_add_label_r with "Hidealr").
    iApply (brel_add_label_l with "Hleakl").
    iApply (brel_add_label_l with "Hideall").

    iApply brel_learn. iIntros ((HdistinctL&HdistinctR)) "_ /=".
    unfold sem_row_flip_mbang.
    rewrite iLblSig_to_iLblThy_proj.
    rewrite iThyIfMono_iLblSig_to_iThyIfMono //=.

    iApply (brel_exhaustion' OS (f1 _) (f2 _) with "[$Hfb]"); [set_solver|set_solver|].
    iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures'|].
    iIntros (k1' k2' e1' e2' Q Hk1' Hk2') "(%b&->&->&(HQNone & HQSome)) Hkont".
    iApply brel_handle_os_r; [apply neutral_ectx;set_solver|].
    iIntros (cr) "Hcr"...
    iApply (brel_handle_os_l [_] (k1')).
    { apply neutral_ectx; set_solver. }
    iIntros (cl) "!> Hcl"...
    iApply (brel_handle_os_l [] [AppRCtx _]); [set_solver|simpl].
    iIntros (cleak) "!> Hleak"...

    iApply brel_learn. iIntros (Hdistinct) "_".

    iApply (brel_introduction' [CRSl]). { repeat constructor. }
    iExists _, _, [HandleCtx _ _ _ _ _; HandleCtx _ _ _ _ _; AppRCtx _], [AppRCtx _], _.
    iSplit; [done|].
    iSplit; [iPureIntro|].
    { eapply distinct_submseteq in Hdistinct; [|apply submseteq_swap].
      eapply (distinct_l_app_NeutralEctx _ _ _ _ [([CRSl],_,iThyMono iThyBot)]);
        [(destruct Hdistinct as [Hd _]; apply Hd)| |constructor].
      set_solver. }
    iSplit; [done|].
    iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|].
    iSplit; last (iModIntro; iIntros (??) "H"; done).
    iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
    do 2 (iSplit; [done|]). iIntros (?) "Hcrs'".
    iDestruct (crs_agree with "[$][$]") as "->". iClear "Hcrs'"...

    destruct b.
    - epose proof brel_couple_rand_rand as h'.
      unshelve iApply (h' _ _ (h_ring (Fp_of_fin y)) (h_bij_ring (Fp_of_fin y))); try done.
      { by unshelve eapply Fp_of_fin_ne_zero_2. }
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply h_lt_ring; first done.
        by apply Rcomplements.SSR_leq. }
      iIntros (α Hα)...
      rewrite -Nat2Z.inj_mul...
      rewrite ssrnat.multE. rewrite (ssrnat.mulnC α y).
      rewrite -!(@expg_mod _ n (h_ring (Fp_of_fin y) α)).
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      assert (div.modn (h_ring (Fp_of_fin y) α) n = div.modn (ssrnat.muln y α) n) as ->.
      { unshelve eapply h_fin_cancel; first done. apply Rcomplements.SSR_leq. lia. }
      rewrite !expg_mod.
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      iApply (brel_bind [_;_;_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl; LEAK] [IDEALr] iThyBot); try set_solver.
        eapply distinct_submseteq; last by split.
        unfold sem_row_flip_mbang.
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hsend". simpl.
        iApply "Hsend". iExists _,_,_,_.
        do 2 (iSplit; first done).
        iSplit; iExists _; iSplit; done. }
      simpl.
      iIntros (??) "(->&->)"...
      iApply (brel_bind [_;_;_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl; LEAK] [IDEALr] iThyBot); try set_solver.
        eapply distinct_submseteq; last by split.
        unfold sem_row_flip_mbang.
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hrecv". simpl.
        by iApply "Hrecv". }
      simpl.
      iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])"...

      (* Protocol done loop *)
      { protocol_done cache_l. }

      iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
      iDestruct "H1" as "(%&%&%&%&(->&->&(%c0z&->&->)&(%d0z&->&->)))".
      iDestruct "H2" as "(%&%&%&%&(->&->&(%c1z&->&->)&(%d1z&->&->)))"...

      (* Deserialize a group element from c0 *)
      destruct (vg_of_int_sem c0z) as [c0|] eqn:Hc0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l.  }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d0 *)
      destruct (vg_of_int_sem d0z) as [d0|] eqn:Hd0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from c1 *)
      destruct (vg_of_int_sem c1z) as [c1|] eqn:Hc1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d1 *)
      destruct (vg_of_int_sem d1z) as [d1|] eqn:Hd1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      iApply brel_int_of_vg_sem_correct_l.
      iApply brel_int_of_vg_sem_correct_l.

      iApply (brel_handle_os_l [_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "!> HrS"...
      unfold store_if_none.

      do 2 (iApply brel_vg_of_int_correct_l; first apply int_of_vg_of_int_sem)...

      brel_load_l...
      brel_store_l...
      brel_load_l...
      brel_store_l...
      iApply (brel_handle_os_l [] [AppRCtx _]); [set_solver |].
      iIntros (rL) "!> HrL". brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro...
      iApply (brel_cont_l with "[$]"). iModIntro...
      rewrite -!(@expg_mod _ n (h_ring (Fp_of_fin y) α)).
      2 : { apply vgG_expg_n. }
      assert (div.modn (h_ring (Fp_of_fin y) α) n = div.modn (ssrnat.muln y α) n) as ->.
      { unshelve eapply h_fin_cancel; first done. apply Rcomplements.SSR_leq. lia. }
      rewrite expg_mod.
      2 : { apply vgG_expg_n. }

      (* Protocol done loop *)
      iDestruct ("Hkont" with "HQSome") as "Hkont".
      iApply (brel_cont_r with "[$]").
      iApply (brel_cont_l with "[$]"); iModIntro...
      brel_load_l...
      iApply (brel_cont_l with "[$]"); iModIntro...
      iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hkont"); [first [done|set_solver]|set_solver|].
      iClear "HQNone Hl1 Hl0".
      protocol_done_loop.
    - iApply brel_couple_rand_rand; first done. iIntros (α Hα)...
      rewrite -Nat2Z.inj_mul...

      iApply (brel_bind [_;_;_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl; LEAK] [IDEALr] iThyBot); try set_solver.
        eapply distinct_submseteq; last by split.
        unfold sem_row_flip_mbang.
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hsend". simpl.
        iApply "Hsend". iExists _,_,_,_.
        do 2 (iSplit; first done).
        rewrite !expgnA. rewrite expgnAC.
        rewrite (expgnAC _ α y). rewrite (expgnAC _ x y).
        iSplit; iExists _; iSplit; done. }
      simpl.
      iIntros (??) "(->&->)"...

      iApply (brel_bind [_;_;_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl; LEAK] [IDEALr] iThyBot); try set_solver.
        eapply distinct_submseteq; last by split.
        unfold sem_row_flip_mbang.
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hrecv". simpl.
        by iApply "Hrecv". }
      simpl.
      iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])"...

      (* Protocol done loop *)
      { protocol_done cache_l. }

      iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
      iDestruct "H1" as "(%&%&%&%&(->&->&(%c0z&->&->)&(%d0z&->&->)))".
      iDestruct "H2" as "(%&%&%&%&(->&->&(%c1z&->&->)&(%d1z&->&->)))"...

      (* Deserialize a group element from c0 *)
      destruct (vg_of_int_sem c0z) as [c0|] eqn:Hc0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d0 *)
      destruct (vg_of_int_sem d0z) as [d0|] eqn:Hd0z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }
      
      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from c1 *)
      destruct (vg_of_int_sem c1z) as [c1|] eqn:Hc1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      (* Deserialize a group element from d1 *)
      destruct (vg_of_int_sem d1z) as [d1|] eqn:Hd1z.
      2 : {
        iApply brel_vg_of_int_none_l; first done.
        iApply brel_vg_of_int_none_r; first done...

        (* Protocol done loop *)
        protocol_done cache_l. }

      iApply brel_vg_of_int_correct_l; first done.
      iApply brel_vg_of_int_correct_r; first done...

      iApply brel_int_of_vg_sem_correct_l.
      iApply brel_int_of_vg_sem_correct_l.

      iApply (brel_handle_os_l [_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "!> HrS"...
      unfold store_if_none.

      do 2 (iApply brel_vg_of_int_correct_l; first apply int_of_vg_of_int_sem)...

      brel_load_l...
      brel_store_l...
      brel_load_l...
      brel_store_l...
      iApply (brel_handle_os_l [] [AppRCtx _]); [set_solver|].
      iIntros (rL) "!> HrL"...
      iApply (brel_cont_l with "[$]"). iModIntro...
      iApply (brel_cont_l with "[$]"). iModIntro...

      (* Protocol done loop *)
      iDestruct ("Hkont" with "HQSome") as "Hkont".
      iApply (brel_cont_r with "[$]").
      iApply (brel_cont_l with "[$]"); iModIntro...
      brel_load_l...
      iApply (brel_cont_l with "[$]"); iModIntro...
      iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hkont"); [first [done|set_solver]|set_solver|].
      iClear "HQNone Hl1 Hl0".
      protocol_done_loop.
      Unshelve.
      { exact []. }
  Qed.

  Lemma dh_ideal_fcrs γcrs :
    ↯ (1 / n) -∗
    crs_empty γcrs -∗
    BREL (reduction DH_rand) ≤ F_CRS <|⊥|> {{ λ v1 v2, (∀ᵣ θ__L, (∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))) -{ sem_row_union (¡ θ__CRS) θ__L}-∘ 𝟙) -{ θ__L }-∘ 𝟙)%T v1 v2}}.
  Proof with (repeat foldkont; brel_pures') using All. 
    iIntros "Herr Hcrs".
    unfold F_CRS, reduction, DH_rand...
    iIntros "!#" (L f1 f2) "Hff"...

    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (t Ht) "!>".
    apply not_elem_of_cons in Ht as [Ht _]...
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (h_ring (Fp_of_fin t))).
    1 : { unshelve eapply h_bij_ring; first done. by unshelve eapply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply h_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (a Ha)...
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (h_ring (Fp_of_fin t))).
    1 : { unshelve eapply h_bij_ring; first done. by unshelve eapply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply h_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (b Hb)...
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (h_ring (Fp_of_fin t))).
    1 : { unshelve eapply h_bij_ring; first done. by unshelve eapply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply h_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (c Hc)...

    (* Normalize both sides' CRS to the common form
       (g^(t·c), g^(t·b), g^(t·a), g^t) using the inverse bijection h. *)
    rewrite -!expgM.
    rewrite -!(@expg_mod _ n (h_ring (Fp_of_fin t) c)); try (rewrite -g_nontriv; apply expg_order).
    rewrite -!(@expg_mod _ n (h_ring (Fp_of_fin t) b)); try (rewrite -g_nontriv; apply expg_order).
    rewrite -!(@expg_mod _ n (h_ring (Fp_of_fin t) a)); try (rewrite -g_nontriv; apply expg_order).
    assert (div.modn (h_ring (Fp_of_fin t) a) n = div.modn (ssrnat.muln t a) n) as ->.
    { unshelve eapply h_fin_cancel; first done. apply Rcomplements.SSR_leq. lia. }
    assert (div.modn (h_ring (Fp_of_fin t) b) n = div.modn (ssrnat.muln t b) n) as ->.
    { unshelve eapply h_fin_cancel; first done. apply Rcomplements.SSR_leq. lia. }
    assert (div.modn (h_ring (Fp_of_fin t) c) n = div.modn (ssrnat.muln t c) n) as ->.
    { unshelve eapply h_fin_cancel; first done. apply Rcomplements.SSR_leq. lia. }
    rewrite !expg_mod; try (rewrite -g_nontriv; apply expg_order).

    iDestruct (crs_upd γcrs (vgval (g ^+ ssrnat.muln t c), vgval (g ^+ ssrnat.muln t b), vgval (g ^+ ssrnat.muln t a), vgval (g ^+ t))%V with "Hcrs") as ">#Hcrs".

    brel_effect_l CRSl as "Hcrsl"...
    brel_effect_r CRSr as "Hcrsr"...

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    unfold sem_val_typed. simpl.
    set (CRSrow := crsrow CRSl CRSr γcrs).
    iSpecialize ("Hff" $! CRSrow).
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    iAssert (sem_val_typed (λ: <>, do: CRSl #()%V)%V (λ: <>, do: CRSr #()%V)%V (𝟙 -{ CRSrow }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=.
      iIntros (??) "!# (->&->)". brel_pures'.
      iApply brel_introduction'; first constructor.
      iExists _,_,[],[],_;do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]); iSplit; try (iIntros (??) "!# H"; iApply "H").
      do 2 (iSplit; [by iPureIntro|]). iIntros (crs) "Hcrs'". iDestruct (crs_agree with "[$][$]") as "->".
      iApply brel_value. iIntros "$ !>".
      do 3 (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]);
      iSplit; last (iExists _; done)). iExists _; done. }

    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg").

    iApply (brel_exhaustion (f1 _) (f2 _) with "Hff"); [done|done|].
    iLöb as "IH".
    iSplit; [iIntros (??) "!# (->&->)"; by brel_pures'|].
    iIntros (?????) "!# %Hk1' %Hk2 (%&(->&->&HQ)&HQ'Q) #HQkont".
    iApply brel_handle_os_l; [apply neutral_ectx;constructor|]. iIntros (ul) "!> Hul".
    iApply brel_handle_os_r; [apply neutral_ectx;constructor|]. iIntros (ur) "Hur"...
    iApply (brel_cont_l with "[$]"). iModIntro.
    iApply (brel_cont_r with "[$]").

    iDestruct ("HQ" with "Hcrs") as "HQ".
    iDestruct ("HQ'Q" with "HQ") as "HQ".
    iDestruct ("HQkont" with "HQ") as "Hkont".

    iApply (brel_exhaustion _ _ [_] [_] with "Hkont"); [done|done|].
    iApply "IH".
  Qed.


  Lemma DH_real_OT_real : 
     ⊢ ↯ (1 / n) -∗
     BREL OT_REDUCTION DH_rand ≤ (λ: "f" "effs", F_CRS (λ: "doCRS", OT_Real_Sender_corrupt "f" ("effs", "doCRS")))%V <| ⊥ |> {{ τ_sc }}.
  Proof using All.
      iIntros "Herr". unfold OT_REDUCTION. brel_pures'.
      iIntros "!> %θ %f1 %f2 Hff".
      brel_pures'.
      iModIntro.
      iIntros (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)".
      brel_pures'.
      iApply (brel_bind' [AppLCtx _] [AppLCtx _]).
      { iApply traversable_to_iThy. }
      iApply brel_introduction_mono; [iApply to_iThy_le_bot|].
      iDestruct crs_alloc as ">(%γcrs&Hcrs)".
      assert (to_iThyIfMono OS [] = ⊥) as <-; first done.
      iApply (brel_mono OS with "[][Herr Hcrs]"); [iApply to_iThy_le_refl|iApply (dh_ideal_fcrs with "[$][$]")|simpl].
      iIntros (g1 g2) "Hgg /=".
      iApply "Hgg".
      iApply (OT_Real_Sender_corrupt_self with "Hsend Hrecv Hff").
    Qed.

End handlee_verification.    
    

