From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances sem_types
  sem_judgement sem_row sem_def 
  p_composition
  fundamental .
From clutch.clutch Require ElGamal_bijection.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_thunk_sender_corrupt ot_bijection.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.
Import ElGamal_bijection.bij_nat.

(* Import valgroup_notation. *)
Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

    (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)

  Program Definition ReceiverTheory_to_sig (RECVl RECVr : label) : iThy Σ :=
    λ e1 e2, (λne Q, ∃ b : bool,
                 ⌜ e1 = do: RECVl (InjLV #b) ⌝%E ∗
                 ⌜ e2 = do: RECVr (InjLV #b) ⌝%E ∗
                 ((Q NONEV NONEV) ∗ (∀ m : vgG, Q (SOMEV m) (SOMEV m)) )  
             )%I.
  Next Obligation. solve_proper. Qed.
  
  Program Definition recvmono (RECVl RECVr : label) :=  {| pmono_prot_car := @ReceiverTheory_to_sig RECVl RECVr; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. 
    iIntros (????) "#HΦ (%&->&->&(H1&H2))"; iExists _; repeat iSplit; try done. iSplitL "H1"; [by iApply "HΦ"|].
    iIntros (m); by iApply "HΦ".
    (* iSplitL "H2"; [iIntros (m)|]; by iApply "HΦ". *)
  Qed. 

  Definition recv (RECVl RECVr : label) := @SemSig Σ (recvmono RECVl RECVr) (RECVl,RECVr).
  
  Program Definition recvrow RECVl RECVr LEAKr := SemRow [([RECVl],[RECVr;LEAKr],recv RECVl RECVr)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition recvrow2 RECVl RECVr := SemRow [([RECVl],[RECVr],recv RECVl RECVr)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  (* Theories for the implementations *)
  (*------------------------------------------------------------*)

  Definition sem_ty_group : sem_ty Σ := (λ v1 v2, ∃ g : vgG, ⌜ v1 = g ⌝ ∗ ⌜ v2 = g ⌝)%I.
  Notation "'𝔾'" := sem_ty_group.   

  Definition alicep := InjRV.
  Definition bobp := InjLV. 

  Program Definition SendBobImpl_to_sig c1 c2 : iThy Σ :=
    λ e1 e2, (λne Q,            
                ∃ u v u' v' : val, 𝔾 u u' ∗ 𝔾 v v' ∗ 
                   (⌜ e1 = do: c1 (SendV (alicep (u, v))) ⌝%E ∗
                    ⌜ e2 = do: c2 (SendV (alicep (u', v'))) ⌝%E)  ∗ 
                   ▷ (Q (Val #()%V) (Val #()%V))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImpl_to_sig c1 c2 : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV alice) ⌝%E ∗
                ▷ (Q NONEV NONEV ∧ (∀ u v : vgG, Q (SOMEV (InjLV (u,v))) (SOMEV (InjLV (u, v)))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImpl_to_sig c1 c2 : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m' : val, ⌜ m = m' ⌝ ∗
                               (⌜ e1 = do: c1 (SendV (bobp m)) ⌝%E ∗
                                ⌜ e2 = do: c2 (SendV (bobp m')) ⌝%E)  ∗ 
                               ▷ (Q (Val #()%V) (Val #()%V))
             )%I.
  Next Obligation. solve_proper. Qed. 

  Program Definition RecvBobImpl_to_sig c1 c2 : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV bob) ⌝%E ∗
                (* Added a later, since RHS doesn't take a step. Conjunction is because a one-shot cont is resumed in either branch *)
                ▷ (Q NONEV NONEV ∧ (∀ c0 d0 c1 d1 : vgG, Q (SOMEV (InjRV ((c0,d0),(c1,d1)))) (SOMEV (InjRV ((c0,d0),(c1,d1))))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition CRSThy_to_sig (CRSl CRSr : label) {γcrs}: iThy Σ :=
    λ e1 e2, (λne Q,            (* this resource we need to keep as a proof tool *)
                (⌜ e1 = do: CRSl #()%V ⌝%E ∗ ⌜ e2 = do: CRSr #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) (Val crs))))%I.
  Next Obligation. solve_proper. Qed.

  Program Definition crsmono (CRSl CRSr : label) γcrs :=  {| pmono_prot_car := @CRSThy_to_sig CRSl CRSr γcrs; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ???. 
    iIntros (????) "#HΦ (->&->&H)"; repeat iSplit; try done; iIntros (?) "Hcrs"; iApply "HΦ"; by iApply "H".
  Qed. 

  Definition crs (CRSl CRSr : label) γcrs := @SemSig Σ (crsmono CRSl CRSr γcrs) (CRSl,CRSr).
  
  Program Definition crsrow CRSl CRSr γcrs := SemRow [([CRSl],[CRSr],crs CRSl CRSr γcrs)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

 Program Definition CRSThyL_to_sig (CRSl : label) {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e1 = do: CRSl #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) e2)))%I.
  Next Obligation. solve_proper. Qed.

  (* Program Definition crslmono (CRSl : label) γcrs := {| pmono_prot_car := @CRSThyL_to_sig CRSl γcrs; pmono_prot_prop := _ |}. 
     Next Obligation.
      intros ??. 
      iIntros (????) "#HΦ (->&H)"; repeat iSplit; try done; iIntros (?) "Hcrs"; iApply "HΦ"; by iApply "H".
     Qed. 
     
     Definition crsl (CRSl : label) γcrs : @SemSig Σ (crslmono CRSl γcrs) ( *)

  (* Definition LblAdv γcrs γtokb γfracb γauthb btokN := [([CRS],[CRS], @CRSThy γcrs);([channel], [channel],
                                                                              (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvBobImpl γauthb)));
                                                                            ([Receiver],[Sender;Receiver;Leak],ReceiverTheory)].
     Definition LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := [([channel],[channel], (iThySum (iThySum (SendAliceImpl γtoka γfraca γautha atokN) (RecvBobImpl γauthb))
                                                                           (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvAliceImpl γautha))))]. *)

  (* semantic types *)
  (*------------------------------------------------------------*)

 

  Program Definition authchan_mono (c1 c2 : label) :=
    {| pmono_prot_car := (iThySum (iThySum (SendAliceImpl_to_sig c1 c2) (RecvBobImpl_to_sig c1 c2))
                            (iThySum (SendBobImpl_to_sig c1 c2) (RecvAliceImpl_to_sig c1 c2))); pmono_prot_prop := _|}.
  Next Obligation.
    intros ??. 
    iIntros (????) "#HΦ [[H| H]|[H|H]]".
    1 : iLeft;iLeft. 2: iLeft; iRight.
    3 : iRight;iLeft. 4: iRight;iRight.
    1 : unfold SendAliceImpl_to_sig; simpl; iDestruct "H" as (??) "(Himpl&H&H1)"; iExists _,_; iFrame; iModIntro; by iApply "HΦ".
    2 : unfold SendBobImpl_to_sig; simpl; iDestruct "H" as (????) "(HG&HG'&H1&H2)"; iExists _,_,_,_; iFrame "HG HG'"; iFrame; by iApply "HΦ".
    all : iDestruct "H" as (??) "H"; repeat (iSplit; simplify_eq; try done); iModIntro; do 2(try iIntros (??)); iApply "HΦ".
    1, 3 : iDestruct "H" as "($&_)".
    all : iDestruct "H" as "(_&H)"; iApply "H".
  Qed.    

  Definition authchan c1 c2 := @SemSig Σ (authchan_mono c1 c2) (c1, c2).
  Program Definition authchan_row c1 c2  := SemRow [([c1],[c2], authchan c1 c2 )] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  

  (*------------------------------------------------------------*)

  Lemma to_iThyIfMono_app m (L1 L2 : iLblThy Σ) :
    to_iThyIfMono m L1 ++ to_iThyIfMono m L2 = to_iThyIfMono m (L1 ++ L2).
  Proof.
    induction L1 as [| X L1' IH]; first done.
    simpl. by rewrite IH.
  Qed.
  

  Lemma Fp_of_fin_ne_zero_2 (t : fin n) :
      t ≠ nat_to_fin (Nat.lt_0_succ (S n'')) → ~~ (@eqtype.eq_op (fintype.fintype_ordinal__canonical__eqtype_Equality (S (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg)))))))) (Fp_of_fin t) (@nmodule.Algebra.zero (zmodp.fintype_ordinal__canonical__Algebra_BaseAddUMagma (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg))))))))) = true.
  Proof using n_prime.
    intros Ht. 
    eapply eqtype.contraNneq.
    2 : { apply negb_true_iff. done. }
    intros. unfold Fp_of_fin in H.  
    have Hnat := f_equal (@fintype.nat_of_ord _) H.
    rewrite /= zmodp.Zp_nat /= in Hnat.
    have Hfp : S (S (zmodp.Zp_trunc (prime.pdiv n))) = n. { rewrite zmodp.Fp_cast; done. }
    rewrite Hfp in Hnat.
    have Hlt := fin_to_nat_lt t.
    rewrite div.modn_small in Hnat. 2: apply Rcomplements.SSR_leq; exact Hlt.
    exfalso. apply Ht.
    apply fin_to_nat_inj. rewrite Hnat fin_to_nat_to_fin //.
  Qed.

  Lemma vgG_expg_n (x : vgG) : (x ^+ n)%g = 1%g.
  Proof.
    rewrite -g_nontriv.
    assert (∃ ck : fin n, x = (g ^+ ck)%g) as (ck & ->) by apply log_g.
    by rewrite expgAC expg_order expg1n.
  Qed.

  Lemma fcrs_dh_ideal γcrs :
    ↯ (1 / n) -∗
    own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    (* BREL f1 #()%V ≤ f2 #()%V <| ([CRS],[CRS], @CRSThy γcrs) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }} -∗ *)
    (* BREL F_CRS f1 ≤ (reduction DH_rand) f2 <| ([CRS],[CRS],iThyBot) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}. *)
    BREL F_CRS ≤ (reduction DH_rand) <|⊥|> {{ λ v1 v2, (∀ᵣ θ__L, (∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))) -{ sem_row_union (¡ θ__CRS) θ__L}-∘ 𝟙) -{ θ__L }-∘ 𝟙)%T v1 v2}}.
  Proof using n_prime G. 
    iIntros "Herr Hcrs".
    
    unfold F_CRS, reduction, DH_rand. brel_pures.
    iModIntro.
    iIntros (L f1 f2) "Hff". brel_pures'.

    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (t Ht) "!>".
    apply not_elem_of_cons in Ht as [Ht _].
    brel_exp_l. brel_exp_r.
    brel_pures. 
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by apply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (a Ha). brel_pures.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by apply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (b Hb). brel_pures.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by apply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (c Hc). brel_pures'.

    iApply fupd_brel.
    iDestruct (auth_upd (vgval (g ^+ c), vgval (g ^+ b), vgval (g ^+ a), vgval (g ^+ t))%V with "Hcrs") as ">Hcrs".
    iDestruct (auth_persist with "Hcrs") as ">Hcrs". 
    iDestruct "Hcrs" as "#Hcrs". 
    iModIntro.
    
    iApply brel_effect_l. iIntros (CRSl) "!> Hcrsl !>".
    iApply brel_effect_r. iIntros (CRSr) "Hcrsr !>".
    brel_pures'.    
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    unfold sem_val_typed. simpl. (* iDestruct "Hff" as "#Hff". *)
    set (CRSrow := crsrow CRSl CRSr γcrs).
    iSpecialize ("Hff" $! CRSrow).  
    (* iDestruct "Hff" as "#Hff". *)
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    (* iDestruct "Hff" as "#Hff".  *)
    iAssert (sem_val_typed (λ: <>, do: CRSl #()%V)%V (λ: <>, do: CRSr #()%V)%V (𝟙 -{ CRSrow }-> (𝔾 × 𝔾 × 𝔾 × 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. 
      iIntros (??) "!# (->&->)". brel_pures'.
      iApply brel_introduction'; first constructor.
      iExists _,_,[],[],_;do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]); iSplit; try (iIntros (??) "!# H"; iApply "H").
      do 2 (iSplit; [by iPureIntro|]). iIntros (crs) "Hcrs'". iDestruct (auth_agree with "[$][$]") as "->". 
      iApply brel_value. iIntros "$ !>". 
      do 3 (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]);
      iSplit; last (iExists _; done)). iExists _; done. }
  
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 
        
    iApply (brel_exhaustion (f1 _) (f2 _) with "Hff"); [done|done|].
    iLöb as "IH".
    (* iSplit; [iIntros (??) "!# ->"; by brel_pures|]. *)
    iSplit; [iIntros (??) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1' %Hk2 (%&(->&->&HQ)&HQ'Q) #HQkont".
    iApply brel_handle_os_l; [apply neutral_ectx;constructor|]. iIntros (ul) "!> Hul".
    iApply brel_handle_os_r; [apply neutral_ectx;constructor|]. iIntros (ur) "Hur".
    brel_pures. 
    iApply (brel_cont_l with "[$]"). iModIntro.
    iApply (brel_cont_r with "[$]"). 
    
    iDestruct ("HQ" with "Hcrs") as "HQ".
    iDestruct ("HQ'Q" with "HQ") as "HQ".
    iDestruct ("HQkont" with "HQ") as "Hkont".
    
    repeat brel_exp_r. rewrite -!expgM. 
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ c))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ b))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ a))).
    rewrite g_nontriv.
    rewrite !crs_fin_cancel //.
    3,5,7: rewrite Rcomplements.SSR_leq; lia.
    2,3,4 : by apply Fp_of_fin_ne_zero_2.
    rewrite !expg_mod; try (rewrite -g_nontriv; apply expg_order).
    
    iApply (brel_exhaustion _ _ [_] [_] with "Hkont"); [done|done|].
    iApply "IH".
  Qed.    

  Definition τC θ := (∀ᵣ θ__RECV, ∀ᵣ θ__CRS, ((𝟙 -{ θ__CRS }-> (𝔾 × 𝔾 × 𝔾 × 𝔾)) × (𝔹 -{ θ__RECV }-> (Option 𝔾))) 
                                         -{ sem_row_union θ__RECV (sem_row_union θ__CRS θ) }-∘ 𝟙)%T.

  Lemma OT_real_DH_real : 
     ⊢ ↯ (1 / n) -∗
     (∀ᵣ θ, τC θ ⊸ (((𝔾 × 𝔾) -{ θ }-> 𝟙) × (𝟙 -{ θ }-> Option ((𝔾 × 𝔾) × (𝔾 × 𝔾))))
            -{ ¡[OS] θ}-∘ 𝟙)%T 
       (λ: "f" "effs", F_CRS (λ: "doCRS", OT_Real_Sender_corrupt "f" ("effs", "doCRS")))%V
       (λ: "f" "effs", (reduction DH_rand) (λ: "doCRS", OT_Real_Sender_corrupt "f" ("effs", "doCRS")))%V. 
    Proof using G n_prime inG2. 
      iIntros "Herr %θ %f1 %f2 Hff".
      unfold OT_Real_Sender_corrupt. brel_pures'. 
      iModIntro.
      iIntros (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)".
      brel_pures'.
      iApply (brel_bind' [AppLCtx _] [AppLCtx _]).
      { iApply traversable_to_iThy. } 
      iApply brel_introduction_mono; [iApply to_iThy_le_bot|].
      iApply fupd_brel.
      iDestruct auth_alloc as ">(%γcrs&Hcrs)".
      iModIntro.
      assert (to_iThyIfMono OS [] = ⊥) as <-; first done.
      iApply (brel_mono OS with "[][Herr Hcrs]"); [iApply to_iThy_le_refl|iApply (fcrs_dh_ideal with "[$][$]")|simpl].
      iIntros (g1 g2) "Hgg /=".
      iApply "Hgg".
      (* Prove that OT_Real_Sender_corrupt is related to it self *)
      iIntros (θCRS). iUnfold sem_ty_arr, sem_ty_mbang. simpl.
      iIntros (doCRS1 doCRS2) "#HCRS".
      brel_pures'.
      iApply brel_effect_l.
      iIntros (IDEALl) "!> Hideall".
      iApply brel_effect_r. iModIntro.
      iIntros (IDEALr) "Hidealr".
      iModIntro.
      brel_pures'.
      set recv := recvrow2 IDEALl IDEALr.
      iAssert ((((𝟙 -{ θCRS }-> ((𝔾 × 𝔾) × 𝔾) × 𝔾)) × (𝔹 -{ recv }-> Option 𝔾))%T
                 (doCRS1, λ: "b", do: IDEALl InjL "b")%V
                 (doCRS2, λ: "b", do: IDEALr InjL "b")%V) as "Hgg".
      { repeat (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]); iSplit); rewrite /sem_ty_mbang //=; iIntros (??) "!#". iIntros "(%&->&->)". brel_pures'.
          iApply brel_introduction'; first constructor.
          iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
          iSplitL; last (iIntros (??) "!# H"; iApply "H").
          iExists _.
          do 2 (iSplit; first by iPureIntro). simpl.
          iSplitL; [iApply brel_value; iIntros "$ !>"; iExists _,_; by iLeft|].
          iIntros (?); brel_pures'; iApply brel_value; iIntros "$ !>"; iExists _,_; iRight; repeat iSplit; try done; iExists _; done. }
      iDestruct ("Hff" with "Hgg") as "Hfbrel".
      
      iApply brel_new_theory.
      iApply (brel_add_label_l with "Hideall").
      iApply (brel_add_label_r with "Hidealr").
      
      iApply (brel_exhaustion _ _ [_] [_] with "[Hfbrel]"); try set_solver.
      { iDestruct (brel_introduction_mono with "[][$Hfbrel]") as "Hfb"; last iApply "Hfb".
        rewrite /recv /sem_row_union //= !iLblSig_to_iLblThy_proj !iLblSig_to_iLblThy_app.
        iSplit.
        - iApply iThy_le_trans;
          first iApply (iThy_le_to_iThy_app_inv [([IDEALl], [IDEALr], handlee_verification.recv IDEALl IDEALr : iThy Σ)]).
          iApply iThy_le_trans; last iApply (iThy_le_to_iThy_app [([IDEALl], [IDEALr], handlee_verification.recv IDEALl IDEALr : iThy Σ)]).
          iApply iThy_le_sum_r.
          rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
          rewrite to_iThyIfMono_app.
          iApply iThy_le_trans; last iApply iThy_le_to_iThy_to_iThyIfMono.
          iIntros (???) "!# Hthy /=".
          iExists Q. iFrame. iIntros (??) "!> $".
        - iSplit.
          + iIntros "!# (Hl&Hr)".
            rewrite /logic.valid /valid_l /valid_r. 
            rewrite !labels_l_cons !labels_r_cons.  
            rewrite !labels_l_app !labels_r_app.
            rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
            rewrite !labels_l_to_iThyIfMono !labels_r_to_iThyIfMono.
            iSplit; done.
          + rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
            rewrite /distinct' /distinct /distinct_l /distinct_r. 
            rewrite !labels_l_cons !labels_r_cons. 
            rewrite !labels_l_app !labels_r_app.
            rewrite !labels_l_to_iThyIfMono !labels_r_to_iThyIfMono.
            by iIntros "!# (%Hl&%Hr)". 
      }
      iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
      iIntros (?????) "!# %Hk1 %Hk2 (%b&->&->&(HQNone&HQSome)) #Hreturn".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
      iIntros (cl) "!> Hcl". brel_pures'.
      iApply brel_handle_os_r; [apply neutral_ectx;set_solver|].
      iIntros (cr) "Hcr". brel_pures'.

      iApply (brel_bind [_] [_] _ (iLblSig_to_iLblThy (¡ θCRS)%R)).
      { iApply traversable_to_iThy. }
      { iApply to_iThy_le_intro'.  
        rewrite iLblSig_to_iLblThy_app.
        solve_submseteq. }
      unfold sem_row_flip_mbang. 
      rewrite iLblSig_to_iLblThy_app.
      rewrite !iThyIfMono_iLblSig_to_iThyIfMono //=.
      iApply (brel_mono OS); [iApply to_iThy_le_refl|by iApply "HCRS"|simpl].
      iIntros (??) "(%&%&%&%&->&->&(%&%&%&%&->&->&(%&%&%&%&->&->&(%&->&->)&(%&->&->))&(%&->&->))&(%&->&->))".
      brel_pures'.
      iApply brel_couple_rand_rand; first done.
      iIntros (n Hlt). brel_pures'.
      destruct b.
      - brel_pures'.
        iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
        { iApply traversable_to_iThy. }
        { iApply to_iThy_le_intro'; solve_submseteq. }
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
        { rewrite /sem_ty_arr /sem_ty_mbang /=. iApply "Hsend".
          iExists _,_,_,_. do 2 (iSplit; try done).
          iSplit; iExists _; do 2 (iSplit; done). }
        iIntros (??) "(->&->)". brel_pures'.
         iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
        { iApply traversable_to_iThy. }
        { iApply to_iThy_le_intro'; solve_submseteq. }
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
        { rewrite /sem_ty_arr /sem_ty_mbang /=. by iApply "Hrecv". }
        iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])". 
        { brel_pures'.
          iDestruct ("Hreturn" with "HQNone") as "Hfill".
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          brel_pures'.
          iClear "HQSome".
          iApply (brel_exhaustion (fill k1' (InjLV #()%V)) (fill k2' (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|].
          iLöb as "IH". 
          iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
          iIntros (k1'' k2'' ?????) "!# (%&->&->&(HQNone & HQSome)) #Hkont".
          iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
          iIntros (rl) "!> Hrl". 
          iApply (brel_handle_os_r _ k2''); [apply neutral_ectx;set_solver|].
          iIntros (rr) "Hrr". 
          brel_pures'.
          iApply (brel_cont_l with "[$]"). iModIntro. 
          iApply (brel_cont_r with "[$]").
          iDestruct ("Hkont" with "HQNone") as "Hfill".
          iApply (brel_exhaustion (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|by iApply "IH"]. }

        iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
        iDestruct "H1" as "(%&%&%&%&(->&->&(%c0&->&->)&(%d0&->&->)))".
        iDestruct "H2" as "(%&%&%&%&(->&->&(%c1&->&->)&(%d1&->&->)))".
        brel_pures'.
        iDestruct ("Hreturn" with "HQSome") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures'.
        iClear "HQNone".
        iApply (brel_exhaustion (fill k1' _) (fill k2' _) with "Hfill"); [set_solver|set_solver|].
        iLöb as "IH". 
        iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
        iIntros (k1'' k2'' ?????) "!# (%&->&->&(HQNone & HQSome)) #Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl". 
        iApply (brel_handle_os_r _ k2''); [apply neutral_ectx;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures'.
        iApply (brel_cont_l with "[$]"). iModIntro. 
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_exhaustion (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|by iApply "IH"]. 
      - brel_pures'.
        iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
        { iApply traversable_to_iThy. }
        { iApply to_iThy_le_intro'; solve_submseteq. }
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
        { rewrite /sem_ty_arr /sem_ty_mbang /=. iApply "Hsend".
          iExists _,_,_,_. do 2 (iSplit; try done).
          iSplit; iExists _; do 2 (iSplit; done). }
        iIntros (??) "(->&->)". brel_pures'.
         iApply (brel_bind [_] [_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
        { iApply traversable_to_iThy. }
        { iApply to_iThy_le_intro'; solve_submseteq. }
        iApply (brel_mono OS); [iApply to_iThy_le_refl| |simpl].
        { rewrite /sem_ty_arr /sem_ty_mbang /=. by iApply "Hrecv". }
        iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])". 
        { brel_pures'.
          iDestruct ("Hreturn" with "HQNone") as "Hfill".
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]").
          brel_pures'.
          iClear "HQSome".
          iApply (brel_exhaustion (fill k1' (InjLV #()%V)) (fill k2' (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|].
          iLöb as "IH". 
          iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
          iIntros (k1'' k2'' ?????) "!# (%&->&->&(HQNone & HQSome)) #Hkont".
          iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
          iIntros (rl) "!> Hrl". 
          iApply (brel_handle_os_r _ k2''); [apply neutral_ectx;set_solver|].
          iIntros (rr) "Hrr". 
          brel_pures'.
          iApply (brel_cont_l with "[$]"). iModIntro. 
          iApply (brel_cont_r with "[$]").
          iDestruct ("Hkont" with "HQNone") as "Hfill".
          iApply (brel_exhaustion (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|by iApply "IH"]. }

        iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
        iDestruct "H1" as "(%&%&%&%&(->&->&(%c0&->&->)&(%d0&->&->)))".
        iDestruct "H2" as "(%&%&%&%&(->&->&(%c1&->&->)&(%d1&->&->)))".
        brel_pures'.
        iDestruct ("Hreturn" with "HQSome") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures'.
        iClear "HQNone".
        iApply (brel_exhaustion (fill k1' _) (fill k2' _) with "Hfill"); [set_solver|set_solver|].
        iLöb as "IH". 
        iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
        iIntros (k1'' k2'' ?????) "!# (%&->&->&(HQNone & HQSome)) #Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl". 
        iApply (brel_handle_os_r _ k2''); [apply neutral_ectx;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures'.
        iApply (brel_cont_l with "[$]"). iModIntro. 
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_exhaustion (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|by iApply "IH"]. 
    Qed.



  Lemma DH_OT_sim :
    ⊢ ↯ (1 / n) -∗
    (∀ᵣ θ, τC θ ⊸ (((𝔾 × 𝔾) -{ θ }-> 𝟙) × (𝟙 -{ θ }-> Option ((𝔾 × 𝔾) × (𝔾 × 𝔾))))
                  -{ ¡[OS] θ}-∘ 𝟙)%T (λ: "f" "effs", (reduction DH_real) (λ: "doCRS", OT_Real_Sender_corrupt "f" ("effs", "doCRS")))%V OT_SIM_FOT_thunk.
  Proof using G n_prime inG2. 
    iIntros "Herr %θ %f1 %f2 Hff".
    rewrite /reduction /DH_real /OT_Real_Sender_corrupt /OT_SIM_FOT_thunk.
    brel_pures'. iModIntro.
    iIntros (??) "(%doSend1&%doSend2&%doRecv1&%doRecv2&->&->&#Hsend&#Hrecv)".
    brel_pures'.

    iApply brel_couple_rand_rand; first done. iIntros (t Ht). brel_pures'.
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (y Hy) "!>".
    apply not_elem_of_cons in Hy as [Hy _]. brel_pures'.
    iApply brel_couple_rand_rand; first done. iIntros (x Hx). brel_pures'.
    rewrite -Nat2Z.inj_mul. brel_pures'.
    rewrite expgnA.

    iApply brel_effect_l. iIntros (CRSl) "!> Hcrsl !>".
    iApply brel_effect_r. iIntros (CRSr) "Hcrsr !>". 
    unfold mut_handler, simhandler, idealhandler.
    brel_pures'. 

    iApply brel_alloc_r. iIntros (l0) "Hl0". brel_pures'.
    iApply brel_alloc_r. iIntros (l1) "Hl1". brel_pures'.
    
    iApply brel_effect_l. iIntros (IDEALl) "!> Hideall !>".
    iApply brel_effect_r. iIntros (IDEALr) "Hidealr !>".
    iApply brel_effect_r. iIntros (LEAK) "Hleakr !>".
    brel_pures'.

    iApply fupd_brel.
    iDestruct auth_alloc as ">(%γcrs&Hcrs)".
    iDestruct (auth_upd  (vgval (g ^+ t ^+ y ^+ x), vgval (g ^+ t ^+ x), vgval (g ^+ t ^+ y), vgval (g ^+ t))%V with "Hcrs") as ">Hcrs".
    iDestruct (auth_persist with "Hcrs") as ">Hcrs". 
    iDestruct "Hcrs" as "#Hcrs". 
    iModIntro.

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hcrsl").
    iApply (brel_add_label_r with "Hcrsr").

    iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum (CRSThy_to_sig CRSl CRSr) (CRSThyL_to_sig CRSl))) with "[Hff Hl0 Hl1 Hideall Hidealr Hleakr]"); try done.  

    (* CRS handler *)
    2 : { iLöb as "IH".
          iSplit; [iIntros (v1 v2) "!# H"; by brel_pures'|].
          iIntros (???????) "!# (%&[(->&->&HQ)| (->&HQ)]&HQQ) #Hkont".
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl".
            iApply brel_handle_os_r; [apply neutral_ectx; set_solver|].
            iIntros (rr) "Hrr".
            brel_pures'.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iApply (brel_cont_r with "[$]").
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum  (CRSThy_to_sig CRSl CRSr) (CRSThyL_to_sig CRSl))) with "[H]"); done.
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl". brel_pures'.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum  (CRSThy_to_sig CRSl CRSr) (CRSThyL_to_sig CRSl))) with "[H]"); done. }

    set recv := recvrow IDEALl IDEALr LEAK.
    set crs := crsrow CRSl CRSr γcrs.
    iSpecialize ("Hff" $! recv crs).
    iAssert ((((𝟙 -{ crs }-> ((𝔾 × 𝔾) × 𝔾) × 𝔾)) × (𝔹 -{ recv }-> Option 𝔾))%T
               (λ: <>, do: CRSl #(), λ: "b", do: IDEALl InjL "b")%V
               (λ: <>, do: CRSr #(), λ: "b", do: IDEALr InjL "b")%V) as "Hgg".
    { repeat (iExists _,_,_,_; do 2 (iSplit; [by iPureIntro|]); iSplit); rewrite /sem_ty_mbang //=; iIntros (??) "!#".
      - iIntros "(->&->)". brel_pures'. iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
        iSplitL; last (iIntros (??) "!# H"; iApply "H").
        do 2 (iSplit; first by iPureIntro).
        iIntros (?) "Hcrs'". iDestruct (auth_agree with "Hcrs Hcrs'") as "<- /=". 
        iApply brel_value. iIntros "$ !>". 
        do 3 
          (iExists _,_,_,_;
                         do 2 (iSplit; first by iPureIntro);
                         iSplit; last (iExists _; iSplit; by iPureIntro)).
        iExists _; iSplit; by iPureIntro. 
      - iIntros "(%&->&->)". brel_pures'.
        iApply brel_introduction'; first constructor.
        iExists _,_,[],[],_. do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
        iSplitL; last (iIntros (??) "!# H"; iApply "H").
        iExists _.
        do 2 (iSplit; first by iPureIntro). simpl.
        iSplitL; [iApply brel_value; iIntros "$ !>"; iExists _,_; by iLeft|].
        iIntros (?); brel_pures'; iApply brel_value; iIntros "$ !>"; iExists _,_; iRight; repeat iSplit; try done; iExists _; done. }
    
    iDestruct ("Hff" with "Hgg") as "Hfbrel". (* rewrite /sem_row_union //=. *)
    iDestruct (brel_introduction_mono with "[][$Hfbrel]") as "Hfb".
    { iApply to_iThy_le_trans.
      - iApply to_iThy_le_intro'. apply submseteq_swap.
      - iApply to_iThy_le_trans.
        + iSplit.
          * iApply iThy_le_trans; first iApply (iThy_le_to_iThy_sum [CRSl] [CRSr]).
            iApply iThy_le_trans; last iApply (iThy_le_sum_to_iThy [CRSl] [CRSr] ((iThySum (CRSThy_to_sig CRSl CRSr) (CRSThyL_to_sig CRSl)))).
            iApply iThy_le_sum_l. iIntros (???) "!# (%&%&%&%&%&?&?&?&?&H&?)". iExists e1',e2',k1,k2,_. iFrame. 
          * iSplit; iModIntro; [iIntros "#Hvalid"; iApply valid_to_iThy_bot; 
                                by (iDestruct (valid_to_iThy_bot with "Hvalid") as "?")
                               | (iIntros (Hdistinct); iPureIntro)]; simpl.
            apply distinct_to_iThy_bot. by apply distinct_to_iThy_bot in Hdistinct. 
        + iApply to_iThy_le_intro'; apply submseteq_swap. }
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hideall").
    iApply (brel_add_label_r with "Hleakr").
    iApply (brel_add_label_r with "Hidealr").


    iApply brel_learn. iIntros ((HdistinctL&HdistinctR)) "_ /=". 
    unfold sem_row_flip_mbang. 
    rewrite iLblSig_to_iLblThy_proj.
    rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. 

    iApply (brel_exhaustion' OS (f1 _) (f2 _) with "[$Hfb]"); [done|set_solver|].
    iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
    iIntros (k1' k2' e1' e2' Q Hk1' Hk2') "(%&->&->&(HQNone & HQSome)) Hkont".
    iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
    iIntros (cl) "!> Hcl". brel_pures'.
    iApply (brel_handle_os_r [_] (k2')). 
    { apply neutral_ectx; set_solver. }
    
    iIntros (cr) "Hcr".
    brel_pures'.
    iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|simpl].
    iIntros (cleak) "Hleak".
    brel_pures'.

    iApply brel_learn. iIntros (Hdistinct) "_".

    iApply (brel_introduction' [CRSl]). { repeat constructor. }
    iExists _, _, [AppRCtx _], [HandleCtx _ _ _ _ _; HandleCtx _ _ _ _ _; AppRCtx _], _.  iSplit; [done|].
    iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|].
    iSplit; [done|]. iSplit; [iPureIntro|].
    { eapply distinct_submseteq in Hdistinct; [|apply submseteq_swap].
         eapply (distinct_r_app_NeutralEctx _ _ _ _ [([CRSr],_,iThyMono iThyBot)]); [(destruct Hdistinct as [_ Hd]; apply Hd)| |constructor].
         set_solver. }
    iSplit; last (iModIntro; iIntros (??) "H"; done).
    iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
    iLeft. do 2 (iSplit; [done|]). iIntros (?) "Hcrs'".
    iDestruct (auth_agree with "[$][$]") as "->". iClear "Hcrs'".
    brel_pures'.

     (* Should be refactored into one branch *)
    destruct b.
    - epose proof brel_couple_rand_rand as h'.
      unshelve iApply (h' _ _ (f_ring (Fp_of_fin y)) (f_bij_ring (Fp_of_fin y))); try done.
      { by apply Fp_of_fin_ne_zero_2. }
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
        by apply Rcomplements.SSR_leq. }
      iIntros (α Hα).
      brel_pures'. rewrite -Nat2Z.inj_mul. brel_pures'.
      rewrite -expgM. rewrite ssrnat.multE. rewrite (ssrnat.mulnC _ y).
      rewrite -!(@expg_mod _ n (ssrnat.muln y (f_ring (Fp_of_fin y) α))).
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      rewrite !crs_fin_cancel; try done.
      2 : { by apply Fp_of_fin_ne_zero_2. }
      2 : { apply Rcomplements.SSR_leq. lia. }
      rewrite !expg_mod. 
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
       { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hsend". simpl. 
        iApply "Hsend". iExists _,_,_,_. 
        do 2 (iSplit; first done).
        iSplit; iExists _; iSplit; done. }
      simpl.
      iIntros (??) "(->&->)".
      brel_pures'.
      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hrecv". simpl. 
        by iApply "Hrecv". }
      simpl.
      iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])". 

      (* Protocol done loop *)
      { brel_pures'.
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures'.
        iApply (brel_load_r with "[$Hl0]"). iIntros "Hl0". brel_pures.
        iApply (brel_cont_r with "[$]").
        iClear "Hl0 Hl1 HQSome".
        iApply (brel_exhaustion' OS (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|].
        iLöb as "IH". 
        iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
        iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome)) Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl". 
        iApply (brel_handle_os_r _ k2''); [apply neutral_ectx;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures'.
        iApply (brel_cont_l with "[$]"). iModIntro. 
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hfill"); [set_solver|set_solver|].
        by iApply "IH". }

      iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
      iDestruct "H1" as "(%&%&%&%&(->&->&(%c0&->&->)&(%d0&->&->)))".
      iDestruct "H2" as "(%&%&%&%&(->&->&(%c1&->&->)&(%d1&->&->)))".
      brel_pures_r.
      repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      brel_pures_l. repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      brel_pures'.
  
      iApply (brel_handle_os_r [_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "HrS". brel_pures'.
      unfold store_if_none.
      iApply (brel_load_r with "Hl0"). iIntros "Hl0".
      iApply (brel_store_r with "Hl0"). iIntros "Hl0".
      brel_pures'.
      iApply (brel_load_r with "Hl1"). iIntros "Hl1".
      iApply (brel_store_r with "Hl1"). iIntros "Hl1".
      brel_pures'.
      iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver |].
      iIntros (rL) "HrL". brel_pures'.
      iApply (brel_cont_r with "[$]").
      brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_load_r with "[$Hl0]"). iIntros "Hl0". 
      iApply (brel_cont_r with "[$]").
      iApply (brel_cont_l with "[$]"). iModIntro.
      iDestruct ("Hkont" with "HQSome") as "Hkont".
      rewrite -!(@expg_mod _ n (ssrnat.muln y (f_ring (Fp_of_fin y) α))).
      2 : { apply vgG_expg_n. }
      rewrite !crs_fin_cancel; try done.
      2 : { by apply Fp_of_fin_ne_zero_2. }
      2 : { apply Rcomplements.SSR_leq. lia. }
      rewrite expg_mod.
      2 : { apply vgG_expg_n. }
      
      iApply (brel_exhaustion' OS (fill k1' _) (fill k2' _) with "Hkont"); [done|set_solver|].
      iClear "HQNone Hl1 Hl0".
      iLöb as "IH".
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
      iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome)) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl". 
      iApply (brel_handle_os_r _ (k2'')); [apply neutral_ectx;set_solver|].
      iIntros (rr) "Hrr". 
      brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQNone") as "Hfill".
      iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hfill"); [set_solver|set_solver|].
      by iApply "IH".
    - iApply brel_couple_rand_rand; first done. iIntros (α Hα).
      brel_pures'. rewrite -Nat2Z.inj_mul. brel_pures'.

      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hsend". simpl. 
        iApply "Hsend". iExists _,_,_,_. 
        do 2 (iSplit; first done).
        rewrite !expgnA. rewrite expgnAC.
        rewrite (expgnAC _ α y). rewrite (expgnAC _ x y).
        iSplit; iExists _; iSplit; done. }
      simpl. 
      iIntros (??) "(->&->)".
      brel_pures'.

      iApply (brel_bind [_] [_;_;_] _ (to_iThyIfMono OS (iLblSig_to_iLblThy θ))).
      { iApply (traversable_ectx_labels _ _ [IDEALl] [IDEALr; LEAK] iThyBot); try set_solver. 
        eapply distinct_submseteq; last by split. 
        unfold sem_row_flip_mbang. 
        rewrite iLblSig_to_iLblThy_proj.
        rewrite iThyIfMono_iLblSig_to_iThyIfMono //=. solve_submseteq. }
      { iApply to_iThy_le_intro'. solve_submseteq. }
      iApply (brel_mono OS); first iApply to_iThy_le_refl.
      { iUnfold sem_ty_arr, sem_ty_mbang in "Hrecv". simpl. 
        by iApply "Hrecv". }
      simpl.
      iIntros (??) "(%&%&[(->&->&->&->)|(->&->&H)])".
            
      (* Protocol done loop *)
      { brel_pures'.
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures'.
        iApply (brel_load_r with "[$Hl1]"). iIntros "Hl1". brel_pures.
        iApply (brel_cont_r with "[$]").
        iClear "Hl0 Hl1 HQSome".
        iApply (brel_exhaustion' OS (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) with "Hfill"); [set_solver|set_solver|].
        iLöb as "IH". 
        iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
        iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome)) Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl". 
        iApply (brel_handle_os_r _ (k2'')); [apply neutral_ectx; set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures'.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hfill"); [set_solver|set_solver|].
        by iApply "IH". }
      
      iDestruct "H" as "(%&%&%&%&->&->&H1&H2)".
      iDestruct "H1" as "(%&%&%&%&(->&->&(%c0&->&->)&(%d0&->&->)))".
      iDestruct "H2" as "(%&%&%&%&(->&->&(%c1&->&->)&(%d1&->&->)))".
      brel_pures_r.
      repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      brel_pures_l. repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      brel_pures'.
  
      iApply (brel_handle_os_r [_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "HrS". brel_pures'.
      unfold store_if_none.
      iApply (brel_load_r with "Hl0"). iIntros "Hl0".
      iApply (brel_store_r with "Hl0"). iIntros "Hl0".
      brel_pures'.
      iApply (brel_load_r with "Hl1"). iIntros "Hl1".
      iApply (brel_store_r with "Hl1"). iIntros "Hl1".
      brel_pures'.
      iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|].
      iIntros (rL) "HrL". brel_pures'.
      iApply (brel_cont_r with "[$]").
      brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_load_r with "[$Hl1]"). iIntros "Hl1". 
      iApply (brel_cont_r with "[$]").
      iApply (brel_cont_l with "[$]"). iModIntro.
      iDestruct ("Hkont" with "HQSome") as "Hkont".
  
      iApply (brel_exhaustion' OS (fill k1' _) (fill k2' _) with "Hkont"); [done|set_solver|].
      iClear "HQNone Hl1 Hl0".
      iLöb as "IH".
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
      iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome)) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl". 
      iApply (brel_handle_os_r _ (k2'')); [apply neutral_ectx;set_solver| ].
      iIntros (rr) "Hrr". 
      brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "HQNone") as "Hfill".
      iApply (brel_exhaustion' OS (fill _ _) (fill _ _) with "Hfill"); [set_solver|set_solver|].
      by iApply "IH". 
      Unshelve. done.
  Qed.

End handlee_verification.    
    
