From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances definition sem_types.
From clutch.clutch Require ElGamal_bijection.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_mut_sender_corrupt ot_bijection.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.
Import ElGamal_bijection.bij_nat.

Import valgroup_notation.
Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (CRS Leak Sender Receiver channel : label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

    (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  Program Definition SenderTheory : iThy Σ :=
    λ e1 e2, (λne Q, ∃ m0 m1 : vgG,
                ⌜ e1 = do: Sender (m0, m1)%V ⌝%E ∗
                ⌜ e2 = do: Sender (m0, m1)%V ⌝%E ∗
                (Q #()%V #()%V)
             )%I.
  Next Obligation. solve_proper. Qed.


  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  Program Definition SendBobImpl γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,            
                ∃ v1 v2 v1' v2': val, (* Consider moving (u,v) into first message branch to allow for more general behaviour *)
                   ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (v1, v2)%V) ∗ ⌜(v1, v2) = (v1', v2')⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                            (⌜ e1 = do: channel (SendV ((v1, v2), alice)) ⌝%E ∗
                             ⌜ e2 = do: channel (SendV ((v1',v2'), alice)) ⌝%E)  ∗ 
                            (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImpl γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                 ⌜ e1 = do: channel (RecvV alice) ⌝%E ∗
                 ⌜ e2 = do: channel (RecvV alice) ⌝%E ∗
                 ▷ (Q NONEV NONEV ∧ (∀ u v : vgG, own γauth (to_dfrac_agree DfracDiscarded (u, v)%V) -∗ Q (SOMEV (u,v)) (SOMEV (u, v))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImpl γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m' : val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                             (⌜ e1 = do: channel (SendV (m, bob)) ⌝%E ∗
                              ⌜ e2 = do: channel (SendV (m', bob)) ⌝%E)  ∗ 
                             ▷ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBobImpl γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV bob) ⌝%E ∗
                (* Added a later, since RHS doesn't take a step *)
                ▷ (Q NONEV NONEV ∗ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed.



  Program Definition CRSThy {γcrs}: iThy Σ :=
    λ e1 e2, (λne Q,
                (⌜ e2 = do: CRS #()%V ⌝%E ∗ ⌜ e1 = do: CRS #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) (Val crs))))%I.
  Next Obligation. solve_proper. Qed.

  (* allows the real protocol (LHS) to throw additional CRS operations *)
  Program Definition CRSThyL {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e1 = do: CRS #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) e2)))%I.
  Next Obligation. solve_proper. Qed.

  Definition LblAdv γcrs γtokb γfracb γauthb btokN := [([CRS],[CRS], @CRSThy γcrs);([channel], [channel],
                                                                           (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvBobImpl γauthb)));
                                                                         ([Sender],[Sender;Receiver;Leak],SenderTheory)].
  Definition LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := [([channel],[channel], (iThySum (iThySum (SendAliceImpl γtoka γfraca γautha atokN) (RecvBobImpl γauthb))
                                                                        (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvAliceImpl γautha))))].

  Lemma fcrs_dh_ideal (f1 f2 : val) γcrs L:
    ↯ (1 / n) -∗
    own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    BREL f1 #()%V ≤ f2 #()%V <| ([CRS],[CRS], @CRSThy γcrs) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }} -∗
    BREL F_CRS CRS f1 ≤ (reduction CRS DH_rand) f2 <| ([CRS],[CRS],iThyBot) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}.
  Proof. 
    iIntros "Herr Hcrs Hff".
    unfold F_CRS, reduction, DH_rand. brel_pures.
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (t Ht) "!>". brel_exp_l. brel_exp_r.
    brel_pures. 
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. admit. (* TODO: prove t != 0 *) }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (a Ha). brel_pures.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. admit. (* TODO: prove t != 0 *) }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (b Hb). brel_pures.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. admit. (* TODO: prove t != 0 *) }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (c Hc). brel_pures.

    repeat brel_exp_r. 
    iApply fupd_brel.
    iDestruct (auth_upd (vgval (g ^+ c), vgval (g ^+ b), vgval (g ^+ a), vgval (g ^+ t))%V with "Hcrs") as ">Hcrs".
    iDestruct (auth_persist with "Hcrs") as ">Hcrs". 
    iDestruct "Hcrs" as "#Hcrs". 
    iModIntro.
    
    brel_pures.
    iApply (brel_exhaustion (f1 #()%V) (f2 #()%V) with "Hff"); [done|done|].
    iLöb as "IH".
    iSplit; [iIntros (??) "!# ->"; by brel_pures|].
    iIntros (?????) "!# %Hk1' %Hk2 (->&->&HQ) #HQkont".
    iApply brel_handle_os_l; [apply neutral_ectx;constructor|]. iIntros (ul) "!> Hul".
    iApply brel_handle_os_r; [apply neutral_ectx;constructor|]. iIntros (ur) "Hur".
    brel_pures. 
    iApply (brel_cont_l with "[$]"). iModIntro.
    iApply (brel_cont_r with "[$]"). 
    
    iDestruct ("HQ" with "Hcrs") as "HQ".
    iDestruct ("HQkont" with "HQ") as "Hkont".
    
    repeat brel_exp_r. rewrite -!expgM. 
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ c))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ b))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ a))).
    rewrite g_nontriv.
    rewrite !crs_fin_cancel //.
    3,5,7: rewrite Rcomplements.SSR_leq; lia.
    2,3,4 : admit.
    rewrite !expg_mod; try (rewrite -g_nontriv; apply expg_order).
    
    iApply (brel_exhaustion _ _ [_] [_] with "Hkont"); [done|done|].
    iApply "IH".
Admitted.     


  
  Lemma OT_real_DH
    (f1 f2 : val) γcrs γtoka γtokb γfraca γfracb γautha γauthb L :
    Sender ≠ Receiver →
    channel ≠ Sender →
    (* Receiver ≠ Leak →
       Leak ≠ CRS →
       CRS ≠ channel → *)
    let AuthChannel := LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
    let Adv := LblAdv γcrs γtokb γfracb γauthb btokN in
    token γtokb -∗
    own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    BREL f1 #()%V ≤ f2 #()%V <| (Adv ++ L)|> {{ (λ v1 v2, ⌜v1 = #()%V ∧ v2 = #()%V⌝) }} -∗
    
    ↯ (1 / n) -∗

    BREL F_CRS CRS (OT_Real_Sender_corrupt CRS Receiver channel  f1) 
      ≤ (reduction CRS DH_rand) (OT_Real_Sender_corrupt CRS Receiver channel f2)
      <| (([CRS],[CRS], iThyBot) :: ([Sender],[Sender; Receiver; Leak],iThyBot) :: AuthChannel ++ L) |>  {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}. 
  Proof. 
    iIntros (????) "Htoken Hcrs Hauth Hff Herr".
    unfold OT_Real_Sender_corrupt. brel_pures.
    iApply (fcrs_dh_ideal with "[$][$Hcrs]").
    (* Prove that OT_Real_Sender_corrupt is related to it self *)
  Admitted.

End handlee_verification.    
    
