From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances sem_types.
From clutch.clutch Require ElGamal_bijection.
From clutch.prob_eff_lang.probblaze.examples.ot Require Import definition_mut_sender_corrupt ot_bijection.
From mathcomp Require Import ssrbool.
Import fingroup.
Import fingroup.fingroup.
Import finset cyclic.
Import ElGamal_bijection.bij_nat.

Import valgroup_notation.
Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (CRS Leak Sender Receiver channel : label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S (S n'')).
  Context `{n_prime : is_true (prime.prime n)}.

    (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  Program Definition ReceiverTheory : iThy Σ :=
    λ e1 e2, (λne Q, ∃ b : bool,
                ⌜ e1 = do: Receiver #b ⌝%E ∗
                ⌜ e2 = do: Receiver #b ⌝%E ∗
                ((Q NONEV NONEV) ∗ (∀ m : val, Q (SOMEV m) (SOMEV m)) ∗ (Q #()%V #()%V) )  
             )%I.
  Next Obligation. solve_proper. Qed.


  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  Program Definition SendBobImpl γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,            
                ∃ v1 v2 v1' v2': val, (* Consider moving (u,v) into first message branch to allow for more general behaviour *)
                   ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (v1, v2)%V) ∗ ⌜(v1, v2) = (v1', v2')⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                            (⌜ e1 = do: channel (SendV ((v1, v2), alice)) ⌝%E ∗
                             ⌜ e2 = do: channel (SendV ((v1',v2'), alice)) ⌝%E)  ∗ 
                            (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImpl γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                 ⌜ e1 = do: channel (RecvV alice) ⌝%E ∗
                 ⌜ e2 = do: channel (RecvV alice) ⌝%E ∗
                 ▷ (Q NONEV NONEV ∧ (∀ u v : vgG, own γauth (to_dfrac_agree DfracDiscarded (u, v)%V) -∗ Q (SOMEV (u,v)) (SOMEV (u, v))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImpl γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m' : val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                             (⌜ e1 = do: channel (SendV (m, bob)) ⌝%E ∗
                              ⌜ e2 = do: channel (SendV (m', bob)) ⌝%E)  ∗ 
                             ▷ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBobImpl γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV bob) ⌝%E ∗
                (* Added a later, since RHS doesn't take a step. Conjunction is because a one-shot cont is resumed in either branch *)
                ▷ (Q NONEV NONEV ∧ (∀ c0 d0 c1 d1 : vgG, own γauth (to_dfrac_agree DfracDiscarded ((c0, d0), (c1, d1))%V) -∗ Q (SOMEV ((c0,d0),(c1,d1))) (SOMEV ((c0,d0),(c1,d1)))))
             )%I.
  Next Obligation. solve_proper. Qed.



  Program Definition CRSThy {γcrs}: iThy Σ :=
    λ e1 e2, (λne Q,
                (⌜ e2 = do: CRS #()%V ⌝%E ∗ ⌜ e1 = do: CRS #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) (Val crs))))%I.
  Next Obligation. solve_proper. Qed.

  (* allows the real protocol (LHS) to throw additional CRS operations *)
  Program Definition CRSThyL {γcrs} : iThy Σ :=
    λ e1 e2, (λne Q, 
                (⌜ e1 = do: CRS #()%V ⌝%E ∗ (∀ crs, own γcrs (to_dfrac_agree DfracDiscarded crs) -∗ Q (Val crs) e2)))%I.
  Next Obligation. solve_proper. Qed.

  Definition LblAdv γcrs γtokb γfracb γauthb btokN := [([CRS],[CRS], @CRSThy γcrs);([channel], [channel],
                                                                           (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvBobImpl γauthb)));
                                                                         ([Receiver],[Sender;Receiver;Leak],ReceiverTheory)].
  Definition LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := [([channel],[channel], (iThySum (iThySum (SendAliceImpl γtoka γfraca γautha atokN) (RecvBobImpl γauthb))
                                                                        (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvAliceImpl γautha))))].

  Lemma Fp_of_fin_ne_zero_2 (t : fin n) :
      t ≠ nat_to_fin (Nat.lt_0_succ (S n'')) → ~~ (@eqtype.eq_op (fintype.fintype_ordinal__canonical__eqtype_Equality (S (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg)))))))) (Fp_of_fin t) (@nmodule.Algebra.zero (zmodp.fintype_ordinal__canonical__Algebra_BaseAddUMagma (S (zmodp.Zp_trunc (prime.pdiv (S (S (@n'' vg vgg))))))))) = true.
  Proof using n_prime.
    intros Ht. 
    eapply eqtype.contraNneq.
    2 : { apply negb_true_iff. done. }
    intros. unfold Fp_of_fin in H.  
    have Hnat := f_equal (@fintype.nat_of_ord _) H.
    rewrite /= zmodp.Zp_nat /= in Hnat.
    have Hfp : S (S (zmodp.Zp_trunc (prime.pdiv n))) = n. { rewrite zmodp.Fp_cast; done. }
    rewrite Hfp in Hnat.
    have Hlt := fin_to_nat_lt t.
    rewrite div.modn_small in Hnat. 2: apply Rcomplements.SSR_leq; exact Hlt.
    exfalso. apply Ht.
    apply fin_to_nat_inj. rewrite Hnat fin_to_nat_to_fin //.
  Qed.

  Lemma vgG_expg_n (x : vgG) : (x ^+ n)%g = 1%g.
  Proof.
    rewrite -g_nontriv.
    assert (∃ ck : fin n, x = (g ^+ ck)%g) as (ck & ->) by apply log_g.
    by rewrite expgAC expg_order expg1n.
  Qed.

  Lemma fcrs_dh_ideal (f1 f2 : val) γcrs L:
    ↯ (1 / n) -∗
    own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    BREL f1 #()%V ≤ f2 #()%V <| ([CRS],[CRS], @CRSThy γcrs) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }} -∗
    BREL F_CRS CRS f1 ≤ (reduction CRS DH_rand) f2 <| ([CRS],[CRS],iThyBot) :: L |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}.
  Proof using n_prime G. 
    iIntros "Herr Hcrs Hff".
    unfold F_CRS, reduction, DH_rand. brel_pures.
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (t Ht) "!>".
    apply not_elem_of_cons in Ht as [Ht _].
    brel_exp_l. brel_exp_r.
    brel_pures. 
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by apply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (a Ha). brel_pures.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by apply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (b Hb). brel_pures.
    epose proof brel_couple_rand_rand as h'.
    iApply (h' _ _ (f_ring (Fp_of_fin t))).
    1 : { unshelve eapply f_bij_ring; first done. by apply Fp_of_fin_ne_zero_2. }
    1 : { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
          by apply Rcomplements.SSR_leq. }
    clear h'.
    iIntros (c Hc). brel_pures.

    repeat brel_exp_r. 
    iApply fupd_brel.
    iDestruct (auth_upd (vgval (g ^+ c), vgval (g ^+ b), vgval (g ^+ a), vgval (g ^+ t))%V with "Hcrs") as ">Hcrs".
    iDestruct (auth_persist with "Hcrs") as ">Hcrs". 
    iDestruct "Hcrs" as "#Hcrs". 
    iModIntro.
    
    brel_pures.
    iApply (brel_exhaustion (f1 #()%V) (f2 #()%V) with "Hff"); [done|done|].
    iLöb as "IH".
    iSplit; [iIntros (??) "!# ->"; by brel_pures|].
    iIntros (?????) "!# %Hk1' %Hk2 (->&->&HQ) #HQkont".
    iApply brel_handle_os_l; [apply neutral_ectx;constructor|]. iIntros (ul) "!> Hul".
    iApply brel_handle_os_r; [apply neutral_ectx;constructor|]. iIntros (ur) "Hur".
    brel_pures. 
    iApply (brel_cont_l with "[$]"). iModIntro.
    iApply (brel_cont_r with "[$]"). 
    
    iDestruct ("HQ" with "Hcrs") as "HQ".
    iDestruct ("HQkont" with "HQ") as "Hkont".
    
    repeat brel_exp_r. rewrite -!expgM. 
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ c))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ b))).
    rewrite -(expg_mod_order g (ssrnat.muln _ (_ _ a))).
    rewrite g_nontriv.
    rewrite !crs_fin_cancel //.
    3,5,7: rewrite Rcomplements.SSR_leq; lia.
    2,3,4 : by apply Fp_of_fin_ne_zero_2.
    rewrite !expg_mod; try (rewrite -g_nontriv; apply expg_order).
    
    iApply (brel_exhaustion _ _ [_] [_] with "Hkont"); [done|done|].
    iApply "IH".
Qed.    


  
  Lemma OT_real_DH
    (f1 f2 : val) γcrs γtoka γtokb γfraca γfracb γautha γauthb L :
    Sender ≠ Receiver →
    channel ≠ Sender →
    (* Receiver ≠ Leak →
       Leak ≠ CRS →
       CRS ≠ channel → *)
    let AuthChannel := LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
    let Adv := LblAdv γcrs γtokb γfracb γauthb btokN in
    token γtoka -∗
    own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    BREL f1 #()%V ≤ f2 #()%V <| (Adv ++ L)|> {{ (λ v1 v2, ⌜v1 = #()%V ∧ v2 = #()%V⌝) }} -∗
    
    ↯ (1 / n) -∗

    BREL F_CRS CRS (OT_Real_Sender_corrupt CRS Receiver channel  f1) 
      ≤ (reduction CRS DH_rand) (OT_Real_Sender_corrupt CRS Receiver channel f2)
      <| (([CRS],[CRS], iThyBot) :: ([Receiver],[Sender; Receiver; Leak],iThyBot) :: AuthChannel ++ L) |>  {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}. 
  Proof. 
    iIntros (????) "Htoken Hcrs Hauth Hff Herr".
    unfold OT_Real_Sender_corrupt. brel_pures.
    iApply (fcrs_dh_ideal with "[$][$Hcrs]").
    (* Prove that OT_Real_Sender_corrupt is related to it self *)
    (* Also consider changing the types, if it is necessary *)
  Admitted.


  
  Lemma DH_OT_sim  (f1 f2 : val) m0 m1 γcrs γtoka γtokb γfraca γfracb γautha γauthb L :
    let AuthChannel := LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
    let Adv := LblAdv γcrs γtokb γfracb γauthb btokN in
    token γtoka -∗
    own γcrs (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    m0 ↦ₛ NONEV -∗
    m1 ↦ₛ NONEV -∗
    ↯ (1 / n) -∗
    BREL f1 #()%V ≤ f2 #()%V <| (Adv ++ L)|> {{ (λ v1 v2, ⌜v1 = #()%V ∧ v2 = #()%V⌝) }} -∗
    BREL (reduction CRS DH_real) (OT_Real_Sender_corrupt CRS Receiver channel f1) 
      ≤ (OT_SIM_FOT channel CRS Sender Receiver Leak m0 m1) f2 <| to_iThyIfMono OS (([CRS],[CRS], iThyBot) :: ([Receiver],[Sender; Receiver; Leak],iThyBot) :: AuthChannel ++ L) |>  {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}.
  Proof using n_prime G.  
    iIntros (??) "Htok Hcrs Hauth Hlm0 Hlm1 Herr Hff".
    rewrite /reduction /OT_Real_Sender_corrupt /OT_SIM_FOT /DH_real /OT_SIM /F_OT //=.
    brel_pures.
    iApply brel_couple_rand_rand; first done. iIntros (t Ht). brel_pures'.
    set H0fin :=  Fin.of_nat_lt (Nat.lt_0_succ (S n'')).
    iApply (brel_couple_couple_avoid _ _ [H0fin]); [apply NoDup_singleton|done|].
    iFrame. iIntros (y Hy) "!>".
    apply not_elem_of_cons in Hy as [Hy _]. brel_pures'.
    (* iApply brel_couple_rand_rand; first done. iIntros (y Hy). brel_pures'. (* should be non-zero *) *)
    iApply brel_couple_rand_rand; first done. iIntros (x Hx). brel_pures'. 
    rewrite -Nat2Z.inj_mul. 
    rewrite /OT_SIM_Sender_corrupt_logic /mutual_handlers_composition.mut_handler_constructor.
    brel_pures'.
    rewrite expgnA.

    iApply fupd_brel.
    iDestruct (auth_upd  (vgval (g ^+ t ^+ y ^+ x), vgval (g ^+ t ^+ x), vgval (g ^+ t ^+ y), vgval (g ^+ t))%V with "Hcrs") as ">Hcrs".
    iDestruct (auth_persist with "Hcrs") as ">Hcrs". 
    iDestruct "Hcrs" as "#Hcrs". 
    iModIntro.

    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∗ own γautha (to_dfrac_agree (DfracOwn 1) #()%V) ∨ own γfraca DfracDiscarded)%I with "[Htok Hauth]") as "#Hinvt".
    { iNext; iLeft;iFrame. }
    iModIntro.
    
    (* CRS *)
    iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum CRSThy CRSThyL)) with "[Hff Hlm0 Hlm1]"); [done|done| |].

    (* CRS handler *)
    2 : { iLöb as "IH".
          iSplit; [iIntros (v1 v2) "!# H"; by brel_pures'|].
          iIntros (???????) "!# (%&[(->&->&HQ)| (->&HQ)]&HQQ) #Hkont".
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl".
            iApply brel_handle_os_r; [apply neutral_ectx; set_solver|].
            iIntros (rr) "Hrr".
            brel_pures'.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iApply (brel_cont_r with "[$]").
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum CRSThy CRSThyL)) with "[H]"); done.
          - iApply brel_handle_os_l; [apply neutral_ectx; set_solver|].
            iIntros (rl) "!> Hrl". brel_pures'.
            iApply (brel_cont_l with "[$]"). iModIntro.
            iDestruct ("HQ" with "Hcrs") as "HQ'".
            iDestruct ("HQQ" with "HQ'") as "HQ".
            iDestruct ("Hkont" with "HQ") as "H".
            iApply (brel_exhaustion _ _ [_] [_] (iThyMono (iThySum CRSThy CRSThyL)) with "[H]"); done. }

     (* Manipulation of theories *)
    iApply brel_introduction_mono. { iApply to_iThy_le_intro'. eapply submseteq_swap. }
    iDestruct (brel_introduction_mono _ with "[][$Hff]") as "Hff".
    { iApply to_iThy_le_trans.
      (* add CRSThyL to the row of ff just to match the row of the context in the rest of the proof. It's fine since we've already factored out the CRS handler *)
      - iSplit.
        { iApply iThy_le_trans; first iApply (iThy_le_to_iThy_sum [CRS] [CRS]).
          iApply iThy_le_trans; last iApply (iThy_le_sum_to_iThy [CRS] [CRS] ((iThySum CRSThy CRSThyL))).
          iApply iThy_le_sum_l. iIntros (???) "!# (%&%&%&%&%&?&?&?&?&H&?)". iExists e1',e2',k1,k2,_. iFrame. }
        iSplit; iModIntro; [iIntros "#Hvalid"; iApply valid_to_iThy_bot; by (iDestruct (valid_to_iThy_bot with "Hvalid") as "?")| (iIntros (Hdistinct); iPureIntro)]; simpl.
        apply distinct_to_iThy_bot. by apply distinct_to_iThy_bot in Hdistinct. 
      - iApply to_iThy_le_intro'. eapply submseteq_trans; last first.
           +  eapply submseteq_skip. eapply submseteq_swap.
           +  eapply submseteq_swap. }

     iDestruct (brel_introduction_mono _ (AuthChannel ++ [([Receiver],[Sender;Receiver;Leak], ReceiverTheory); ([CRS], [CRS], iThySum CRSThy CRSThyL)] ++ L) with "[][$Hff]") as "Hff". 
    {  iSplit.
       + iApply iThy_le_trans; [iApply iThy_le_to_iThy_sum|].
         iApply iThy_le_trans; [|iApply iThy_le_sum_to_iThy].
         iApply iThy_le_sum_l. iIntros (???) "!#  (%&%&%&%&%&?&?&H)". iExists _,_,_,_,_. iFrame.
         iDestruct "H" as "(?&?&HX&#HSQ)". iFrame. iSplitL "HX"; [|iApply "HSQ"].
         iDestruct "HX" as "[HX | HX]"; [iRight;iLeft;done|iLeft;iRight;done].
       + iSplit; iModIntro; [iApply valid_submseteq'|iIntros (Hdistinct'); iPureIntro; eapply distinct_submseteq'; last done]; simpl;
           try rewrite !labels_l_cons; try rewrite !labels_r_cons; set_solver.
    }
    iDestruct (brel_introduction_mono _ with "[][$Hff]") as "Hff".
    { iApply to_iThy_le_intro'. eapply submseteq_trans; first eapply submseteq_swap.
      eapply submseteq_skip. eapply submseteq_swap. }
    iApply brel_learn. iIntros ((HdistinctL&HdistinctR)) "_ /=".  
    
    iApply (brel_exhaustion' OS (f1 #()%V) (f2 #()%V) with "[$Hff]"); [done|set_solver|].
    iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
    iIntros (k1' k2' e1' e2' Q Hk1' Hk2') "(%&->&->&(HQNone & HQSome & _)) Hkont".
    iApply brel_handle_os_l; [apply neutral_ectx;set_solver|].
    iIntros (cl) "!> Hcl". brel_pures'.
    iApply (brel_handle_os_r [_] ([HandleCtx _ _ _ _ _] ++ k2')). 
    { simpl. eapply (not_elem_of_app [_]); split.
      - unfold distinct_r, labels_r in *. simpl in *.
        apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
        apply NoDup_cons_1_1.
        eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq.
      - apply neutral_ectx; set_solver.
    }                  
    iIntros (cr) "Hcr".
    brel_pures'.
    iApply (brel_handle_os_r [] [AppRCtx _]); [set_solver|simpl].
    iIntros (cleak) "Hleak".
    brel_pures'.
    iApply (brel_introduction' [CRS]). { repeat constructor. }
    iExists _, _, [AppRCtx _], [], _.  iSplit; [done|].
    iSplit; [iPureIntro; apply AppRCtx_NeutralEctx; apply NeutralEctx_nil|].
    iSplit; [done|]. iSplit; [iPureIntro; apply NeutralEctx_nil|].
    iSplit; last (iModIntro; iIntros (??) "H"; done).
    iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
    iRight. iSplit; [done|]. iIntros (?) "Hcrs'".
    iDestruct (auth_agree with "[$][$]") as "->". iClear "Hcrs'".
    brel_pures'.

    (* Should be refactored into one branch *)
    destruct b.
    - epose proof brel_couple_rand_rand as h'.
      unshelve iApply (h' _ _ (f_ring (Fp_of_fin y)) (f_bij_ring (Fp_of_fin y))); try done.
      { by apply Fp_of_fin_ne_zero_2. }
      { intros n Hlt. apply Rcomplements.SSR_leq. unshelve eapply f_lt_ring; first done.
        by apply Rcomplements.SSR_leq. }
      iIntros (α Hα).
      brel_pures'. rewrite -Nat2Z.inj_mul. brel_pures'.
      rewrite -expgM. rewrite ssrnat.multE. rewrite (ssrnat.mulnC _ y).
      rewrite -!(@expg_mod _ n (ssrnat.muln y (f_ring (Fp_of_fin y) α))).
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.
      rewrite !crs_fin_cancel; try done.
      2 : { by apply Fp_of_fin_ne_zero_2. }
      2 : { apply Rcomplements.SSR_leq. lia. }
      rewrite !expg_mod. 
      2,3 : (try rewrite (expgnAC _ x n)); rewrite (expgnAC _ t n);
            by rewrite -g_nontriv expg_order !expg1n.

      iApply (brel_introduction' [channel]); [repeat constructor|].
      iExists _,_,[AppRCtx _],[HandleCtx _ _ _ _ _ ;HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _;AppRCtx _],_.
      iSplit; [by iPureIntro|]. 
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton; set_solver| ].
      iSplit; [by iPureIntro|].
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton; apply NoDup_cons_1_1| ].
      { unfold distinct_r, labels_r in *. simpl in *.
        apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
        apply (submseteq_NoDup _ [Sender; Receiver; Leak; CRS; channel]);
        [solve_submseteq | exact HdistinctR]. }
      iSplitL; [|iIntros (??) "!# H"; iApply "H"].
      iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
      iLeft. iLeft. 
      iExists _,_.
      iSplitR.
      { iMod (inv_acc with "Hinvt") as "([>(Htok & Hagree) | >#Hfrac] & Hclose)"; try done.
        - iModIntro. iLeft. iIntros "#Hfrac".
          iMod (auth_upd (vgval (g ^+ t ^+ α), vgval (g ^+ t ^+ x ^+ α))%V
                 with "Hagree") as "Hagree".
          iMod (auth_persist with "Hagree") as "#Hagree".
          iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#".
          by iModIntro.
        - iRight. iFrame "#".
          iModIntro. iApply "Hclose". iNext.
          by iRight. }
      iSplit; [iSplit;done|].
      iModIntro. simpl.
      brel_pures'.
      
      iApply (brel_introduction' [channel]); [repeat constructor|].
      iExists _,_,[AppRCtx _],[HandleCtx _ _ _ _ _ ;HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _;AppRCtx _],_.
      iSplit; [by iPureIntro|]. 
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton; set_solver| ].
      iSplit; [by iPureIntro|].
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton| ].
      { unfold distinct_r, labels_r in *. simpl in *.
        apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _].
        apply NoDup_cons_1_1.
        apply (submseteq_NoDup _ [Sender; Receiver; Leak; CRS; channel]);
          [solve_submseteq | exact HdistinctR]. }
      iSplitL; [|iIntros (??) "!# H"; iApply "H"].
      iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
      iLeft. iRight.
      do 2 (iSplit; [done|]).
      iModIntro.
      iSplit.

      (* Protocol done loop *)
      { brel_pures'.
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures'.
        iApply (brel_load_r with "[$Hlm0]"). iIntros "Hlm0". brel_pures.
        iApply (brel_cont_r with "[$]").
        iClear "Hlm0 Hlm1 HQSome".
        iApply (brel_exhaustion' OS (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) _ _ _ _
                  (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
        iLöb as "IH". 
        iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
        iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome & Hdone)) Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl". 
        iApply (brel_handle_os_r _ ([HandleCtx _ _ _ _ _] ++ k2'')).
        { simpl. eapply (not_elem_of_app [_]); split.
          - unfold distinct_r, labels_r in *. simpl in *.
            apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
            apply NoDup_cons_1_1.
            eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq.
          - apply neutral_ectx; set_solver.
        } 
        iIntros (rr) "Hrr". 
        brel_pures'.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "Hdone") as "Hfill".
          iApply (brel_exhaustion' OS (fill _  #()%V) (fill _ #()%V) _ _ _ _
                  (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
        by iApply "IH". }

      iIntros (c0 d0 c1 d1) "#Hauth". 
      brel_pures_r. 
      repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      (* do 5 (first [brel_exp_r|brel_mult_r|brel_inv_r]). *)
      brel_pures_l. repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      brel_pures'.
      iApply (brel_handle_os_r [_;_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "HrS". brel_pures'.
      unfold store_if_none.
      iApply (brel_load_r with "Hlm0"). iIntros "Hlm0".
      iApply (brel_store_r with "Hlm0"). iIntros "Hlm0".
      brel_pures'.
      iApply (brel_load_r with "Hlm1"). iIntros "Hlm1".
      iApply (brel_store_r with "Hlm1"). iIntros "Hlm1".
      brel_pures'.
      iApply (brel_handle_os_r [] [HandleCtx _ _ _ _ _; AppRCtx _]); [simpl |].
      { unfold distinct_r, labels_r in *. simpl in *.
        apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _].
        apply NoDup_cons_1_1.
        eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq. }
      iIntros (rL) "HrL". brel_pures'.
      iApply (brel_cont_r with "[$]").
      brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_load_r with "[$Hlm0]"). iIntros "Hlm0". 
      iApply (brel_cont_r with "[$]").
      iApply (brel_cont_l with "[$]"). iModIntro.
      iDestruct ("Hkont" with "HQSome") as "Hkont".
      rewrite -!(@expg_mod _ n (ssrnat.muln y (f_ring (Fp_of_fin y) α))).
      2 : { apply vgG_expg_n. }
      rewrite !crs_fin_cancel; try done.
      2 : { by apply Fp_of_fin_ne_zero_2. }
      2 : { apply Rcomplements.SSR_leq. lia. }
      rewrite expg_mod.
      2 : { apply vgG_expg_n. }
      
      iApply (brel_exhaustion' OS (fill k1' _) (fill k2' _) with "Hkont"); [done|set_solver|].
      iClear "HQNone Hlm1 Hlm0".
      iLöb as "IH".
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
      iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome & Hdone)) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl". 
      iApply (brel_handle_os_r _ ([HandleCtx _ _ _ _ _] ++ k2'')).
      { simpl. eapply (not_elem_of_app [_]); split.
        - unfold distinct_r, labels_r in *. simpl in *.
          apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
          apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq.
        - apply neutral_ectx; set_solver.
      } 

      iIntros (rr) "Hrr". 
      brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "Hdone") as "Hfill".
      iApply (brel_exhaustion' OS (fill _  #()%V) (fill _ #()%V) _ _ _ _
                (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
      by iApply "IH".

    - iApply brel_couple_rand_rand; first done. iIntros (α Hα).
      brel_pures'. rewrite -Nat2Z.inj_mul. brel_pures'.
             
      iApply (brel_introduction' [channel]); [repeat constructor|].
      iExists _,_,[AppRCtx _],[HandleCtx _ _ _ _ _ ;HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _;AppRCtx _],_.
      iSplit; [by iPureIntro|]. 
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton; set_solver| ].
      iSplit; [by iPureIntro|].
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton; simpl| ]. (* from brel_learn *)
       { unfold distinct_r, labels_r in *. simpl in *.
        apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _].
        apply NoDup_cons_1_1.
        eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq. }
       
      iSplitL; [|iIntros (??) "!# H"; iApply "H"].
      iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
      iLeft. iLeft. 
      iExists _,_.
      iSplitR.
      { iMod (inv_acc with "Hinvt") as "([>(Htok & Hagree) | >#Hfrac] & Hclose)"; try done.
        - iModIntro. iLeft. iIntros "#Hfrac".
          iMod (auth_upd (vgval (g ^+ t ^+ y ^+ α), vgval (g ^+ t ^+ y ^+ x ^+ α))%V
                 with "Hagree") as "Hagree".
          iMod (auth_persist with "Hagree") as "#Hagree".
          iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#".
          by iModIntro.
        - iRight. iFrame "#".
          iModIntro. iApply "Hclose". iNext.
          by iRight. }
      rewrite !expgnA. rewrite expgnAC.
      rewrite (expgnAC _ α y). rewrite (expgnAC _ x y).
      iSplit; [iSplit;done|].  
      iModIntro. simpl.
      brel_pures'.
      
      iApply (brel_introduction' [channel]); [repeat constructor|].
      iExists _,_,[AppRCtx _],[HandleCtx _ _ _ _ _ ;HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _;AppRCtx _],_.
      iSplit; [by iPureIntro|]. 
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton; set_solver| ].
      iSplit; [by iPureIntro|].
      iSplit; [iPureIntro; apply NeutralEctx_ectx_labels_singleton| ]. (* from brel_learn *)
       { unfold distinct_r, labels_r in *. simpl in *.
        apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _].
        apply NoDup_cons_1_1.
        eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq. }
      iSplitL; [|iIntros (??) "!# H"; iApply "H"].
      iExists _. iSplitL; last (iIntros (??) "!> H"; iApply "H").
      iLeft. iRight. simpl.
      do 2 (iSplit; [done|]).
      iModIntro.
      iSplit.

      (* Protocol done loop *)
      { brel_pures'.
        iDestruct ("Hkont" with "HQNone") as "Hfill".
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        brel_pures'.
        iApply (brel_load_r with "[$Hlm1]"). iIntros "Hlm1". brel_pures.
        iApply (brel_cont_r with "[$]").
        iClear "Hlm0 Hlm1 HQSome".
        iApply (brel_exhaustion' OS (fill _ (InjLV #()%V)) (fill _ (InjLV #()%V)) _ _ _ _
                  (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
        iLöb as "IH". 
        iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
        iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome & Hdone)) Hkont".
        iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
        iIntros (rl) "!> Hrl". 
        iApply (brel_handle_os_r _ ([HandleCtx _ _ _ _ _] ++ k2'')).
        { simpl. eapply (not_elem_of_app [_]); split.
          - unfold distinct_r, labels_r in *. simpl in *.
            apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
            apply NoDup_cons_1_1.
            eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq.
          - apply neutral_ectx; set_solver.
        } 

        iIntros (rr) "Hrr". 
        brel_pures'.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        iDestruct ("Hkont" with "Hdone") as "Hfill".
          iApply (brel_exhaustion' OS (fill _  #()%V) (fill _ #()%V) _ _ _ _
                  (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
        by iApply "IH". }

      iIntros (c0 d0 c1 d1) "#Hauth". 
      brel_pures.
      repeat (first [brel_exp_l|brel_mult_l|brel_inv_l]).
      do 5 (first [brel_exp_r|brel_mult_r|brel_inv_r]).
      brel_pures'.
      iApply (brel_handle_os_r [_;_] [AppRCtx _]); [set_solver|].
      iIntros (rS) "HrS". brel_pures'.
      unfold store_if_none.
      iApply (brel_load_r with "Hlm0"). iIntros "Hlm0".
      iApply (brel_store_r with "Hlm0"). iIntros "Hlm0".
      brel_pures'.
      iApply (brel_load_r with "Hlm1"). iIntros "Hlm1".
      iApply (brel_store_r with "Hlm1"). iIntros "Hlm1".
      brel_pures'.
      iApply (brel_handle_os_r [] [HandleCtx _ _ _ _ _; AppRCtx _]). 
      {  unfold distinct_r, labels_r in *. simpl in *.
         apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
         apply NoDup_cons_1_1.
         eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq.
      }  

      iIntros (rL) "HrL". brel_pures'.
      iApply (brel_cont_r with "[$]").
      brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_cont_r with "[$]"). brel_pures'.
      iApply (brel_load_r with "[$Hlm1]"). iIntros "Hlm1". 
      iApply (brel_cont_r with "[$]").
      iApply (brel_cont_l with "[$]"). iModIntro.
      iDestruct ("Hkont" with "HQSome") as "Hkont".

      iApply (brel_exhaustion' OS (fill k1' _) (fill k2' _) with "Hkont"); [done|set_solver|].
      iClear "HQNone Hlm1 Hlm0".
      iLöb as "IH".
      iSplit; [iIntros (v1 v2) "(->&->)"; by brel_pures|].
      iIntros (k1'' k2'' ?????) "(%&->&->&(HQNone & HQSome & Hdone)) Hkont".
      iApply brel_handle_os_l; [apply neutral_ectx;set_solver| ].
      iIntros (rl) "!> Hrl". 
      iApply (brel_handle_os_r _ ([HandleCtx _ _ _ _ _] ++ k2'')).
      { simpl. eapply (not_elem_of_app [_]); split.
        - unfold distinct_r, labels_r in *. simpl in *.
          apply (NoDup_app [Sender; Receiver; Leak;CRS;channel]) in HdistinctR as [HdistinctR _]. 
          apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact HdistinctR; solve_submseteq.
        - apply neutral_ectx; set_solver.
      } 

      iIntros (rr) "Hrr". 
      brel_pures'.
      iApply (brel_cont_l with "[$]"). iModIntro.
      iApply (brel_cont_r with "[$]").
      iDestruct ("Hkont" with "Hdone") as "Hfill".
      iApply (brel_exhaustion' OS (fill _  #()%V) (fill _ #()%V) _ _ _ _
                (([CRS],[CRS], _) :: AuthChannel ++ L) with "Hfill"); [set_solver|set_solver|].
      by iApply "IH". 
  Qed. 


End handlee_verification.    
    
