From clutch.prob_eff_lang.probblaze Require Import advantage.
From iris.algebra Require Import excl.
From iris.algebra.lib Require Import dfrac_agree.
From clutch.prob_eff_lang.probblaze Require Import sem_def sem_types sem_judgement sem_row syntax semantics proofmode valgroup.
From clutch.prob_eff_lang.probblaze Require Import dhke_channel def_dhke. 

Section adv_dhke.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.
  Context {la1 la2 : label}.     (* can be removed once dhke_channel has been cleaned up *)

  Definition τ_DH := (∀ᵣ θ__L, (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option sem_ty_group)) -{ sem_row_union θₕ θ__L }-> 𝟙)%T 
                               ⊸ ((∀ᵣ θₗ, ((⊤ × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) ⊸ ((𝟙 + 𝟙) -{ θₗ }-> Option ⊤) -{ sem_row_union θₗ θ__L }-∘ 𝟙)))%T.

  Lemma adv_DHKE_DH_real A :
    (⊢ sem_val_typed A A (τ_DH → 𝔹)%T) →
    nonneg (advantage A (λ: "f", F_AUTH (DH_KE "f"))%V (λ: "f", F_AUTH (C "f" DH_real))%V #true) = 0%R.
  Proof using G cg inG0 inG1 inG2 la2 probblazeRGS0 vg vgg Σ. (* also debris from dhke_channel *)
    intros. eapply brel_advantage; first done. split.
    - apply F_AUTH_DH_KE_FAUTH_C_DH_real; eauto.
    - apply F_AUTH_C_DH_real_FAUTH_DH_KE; eauto.
  Qed. 

  Lemma adv_DH_rand_FKE A :
    (⊢ sem_val_typed A A (τ_DH → 𝔹)%T) →
    nonneg (advantage A (λ: "f", F_AUTH (C "f" DH_rand))%V (λ: "f", F_AUTH (DH_SIM (F_KE "f")))%V  #true) = 0%R.
  Proof using G cg inG0 inG1 inG2 la2 probblazeRGS0 vg vgg Σ. 
    intros. eapply brel_advantage; first done. split.
    - apply F_AUTH_C_DH_rand_FAUTH_DH_SIM_F_KE; eauto. 
    - apply F_AUTH_DH_SIM_F_KE_FAUTH_C_DH_rand; eauto.
  Qed. 

  Theorem adv_DHKE A (ε : R) :
    (⊢ sem_val_typed A A (τ_DH → 𝔹)%T) →
    advantage A (λ: "f", F_AUTH (C "f" DH_real))%V (λ: "f", F_AUTH (C "f" DH_rand))%V #true <= ε →
    advantage A (λ: "f", F_AUTH (DH_KE "f"))%V (λ: "f", F_AUTH (DH_SIM (F_KE "f")))%V #true <= ε.
  Proof using G cg inG0 inG1 inG2 la2 probblazeRGS0 vg vgg Σ. 
    intros HA HAadv.
    eapply advantage_triangle.
    - right. by apply adv_DHKE_DH_real.
    - eapply advantage_triangle. 
      + apply HAadv.
      + right. by apply adv_DH_rand_FKE.
      + done.
    - lra.
  Qed. 

End adv_dhke.
