From clutch.prob_eff_lang.probblaze Require Export notation valgroup.


Import fingroup.

Import fingroup.fingroup.

Import valgroup_notation.
Import valgroup_tactics.

Section def_implementation.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  (*Context (channel leakauth getKey: label).*)

  #[local] Notation n := (S n'').

  Definition sample : expr := λ: <>, rand #n.
  Definition samplelbl α : expr := λ: <>, (rand(α) #n).

  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.
  Definition pow : expr := rec: "pow" "b" "e" := if: "e" = #0 then #1 else "b" * ("pow" "b" ("e" - #1)).
  Definition modn : expr := rec: "mod" "a" := if: "a" < #n then "a" else "mod" ("a" - #n).

  Definition F_AUTH : val :=
  λ: "f" "effs",  
    let, ("doLeakSend", "doLeakRecv") := "effs" in
    let: "m1" := ref NONEV in
    let: "m2" := ref NONEV in
    effect "channel" 
    let: "doSend" := (λ: "m", do: (EffName "channel") (Send "m")) in  
    let: "doRecv" := (λ: "m", do: (EffName "channel") (Recv "m")) in
    handle: "f" ("doSend", "doRecv") with
    | effect (EffName "channel") "message", rec "k" as multi =>
        match: "message" with
        (* SEND *)
        | InjL "payload" =>
            let, ("m", "dst") := "payload" in
            match: "dst" with
              (* Alice *)
              InjL <> => match: !"m1" with (* Send only the first value. Discard all others.  *)
                         NONE => "m1" <- SOME "m";; ("doLeakSend" ("m", "dst"));; "k" #()%V
                       | SOME "x" => "k" #()%V 
                         end
            (* Bob *)
            | InjR <> => match: !"m2" with
                          NONE => "m2" <- SOME "m";; ("doLeakSend" ("m", "dst"));; "k" #()%V
                        | SOME "x" => "k" #()%V 
                        end
            end
        (* Recv *)
        | InjR "from" =>
            let: "r" := ("doLeakRecv" "from") in
             match: "r" with
               NONE => "k" NONEV
             | SOME "x" => match: "from" with
                             (* Alice *)
                             InjL <> => match: !"m2" with
                                          NONE => "k" NONEV
                                        | SOME "m" => "k" (SOME "m")
                                        end
                           (* Bob *)
                           | InjR <> => match: !"m1" with
                                          NONE => "k" NONEV
                                        | SOME "m" => "k" (SOME "m")
                                        end
                           end
             end
        end
    | return "y" => #()%V end.

  Definition DH_KE  : val :=
    λ: "f" "effs",
    let, ("doSend", "doRecv") := "effs" in
    let: "α" := alloc #n in
    let: "β" := alloc #n in
    let: "l1" := ref NONEV in
    let: "l2" := ref NONEV in
    effect "getKey"  
    let: "doGK" := (λ: "party", do: (EffName "getKey") "party") in
    handle: "f" "doGK" with
    | effect (EffName "getKey") "p", rec "k" as multi =>
        match: "p" with
          (* Alice *)
          InjL <> =>
            (* Sample *)
            let: "a" :=
              (match: !"l1" with
                NONE => let: "a" := (samplelbl "α" #()%V) in "l1" <- SOME "a";; "a"
              | SOME "a" => "a"
               end) in
            (* Compute gA *)
            let: "gA" := g^"a" in
            (* Send gA *)
            ("doSend" ("gA", bob));;
            (* Receive gB *)
            let: "r" := ("doRecv" bob) in
            match: "r" with
              NONE => "k" NONEV
            | SOME "gB" =>
                (* Compute key *)
                let: "key" := "gB"^"a" in
                "k" (SOME "key")
            end
        (* Bob *)
        | InjR <> =>
            let: "r" := ("doRecv" alice) in
            match: "r" with
              NONE => "k" NONE
            | SOME "gA" =>
                let: "b" :=
                  match: !"l2" with
                    NONE => let: "b" := (samplelbl "β" #()%V) in "l2" <- SOME "b";; "b"
                  | SOME "b" => "b"
                  end in
                let: "gB" := g^"b" in
                ("doSend" ("gB", alice));;

                let: "key" := "gA"^"b" in
                "k" (SOME "key")
            end
       end
   | return "y" => "y" end.

 Definition DH_SIM : val :=
 λ: "f" "effs",
   let, ("doSend", "doRecv") := "effs" in
   let: "α" := alloc #n in
    let: "β" := alloc #n in
    let: "l1" := ref NONEV in
    let: "l2" := ref NONEV in
    effect "leak"  
    let: "doLeakSend" := (λ: "m", do: (EffName "leak") (Send "m")) in
    let: "doLeakRecv" := (λ: "m", do: (EffName "leak") (Recv "m")) in
      handle: "f" ("doLeakSend", "doLeakRecv") with
    | effect (EffName "leak") "payload", rec "k" as multi =>
        match: "payload" with
        | InjL "dst" =>
            match: "dst" with
              InjL <> => let: "c" :=
                           (match: !"l1" with
                              NONE => let: "c" := (samplelbl "α" #()%V) in "l1" <- SOME "c";; "c"
                            | SOME "c" => "c"
                            end) in
                         let: "gC" := g^"c" in
                         "doSend" ("gC",bob);;
                         "k" #()%V
            | InjR <> => let: "c" :=
                           (match: !"l2" with
                              NONE => let: "c" := (samplelbl "β" #()%V) in "l2" <- SOME "c";; "c"
                            | SOME "c" => "c"
                            end) in
                         let: "gC" := g^"c" in
                         "doSend" ("gC", alice);;
                         "k" #()%V
            end
        | InjR "from" =>
            let: "r" := "doRecv" "from" in
             match: "r" with
               NONE => "k" NONE
             | SOME "x" => "k" (SOME #()%V)
             end
        end
    | return "y" => "y" end.

  
   Definition F_KE : val :=
     λ: "f" "effs",
       let, ("doLeakSend", "doLeakRecv") := "effs" in
       (* Magically share a presampled key *)
       let: "c" := (sample #()%V) in
       let: "key" := g^"c" in
       effect "getKey"  
         let: "doGK" := (λ: "party", do: (EffName "getKey") "party") in
         handle: "f" "doGK" with
     | effect (EffName "getKey") "p", rec "k" as multi =>
         match: "p" with
           (* Alice *)
           InjL <> =>
             (* Leak a send *)
             ("doLeakSend" bob);;
             (* Receive a dummy value *)
             let: "r" := ("doLeakRecv" bob) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "w" => "k" (SOME "key")
             end
         (* Bob  *)
         | InjR <> =>
             let: "r" := ("doLeakRecv" alice) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "w" => 
                 ("doLeakSend" alice);;
                 "k" (SOME "key")
             end
         end
     | return "y" => "y" end.


   Definition F_KE_lazy_alice : val :=
     λ: "f" "effs",
       let, ("doLeakSend", "doLeakRecv") := "effs" in
       (* Magically share a lazily sampled key *)
       let: "γ" := alloc #n in
       let: "key_opt" := ref NONEV in
       let: "sample_or_load" :=
         λ:<>, match: !"key_opt" with
           | NONE =>
               let: "c" := (samplelbl "γ" #()%V) in
               let: "key" := g^"c" in
               "key_opt" <- SOME "key" ;;
               "key"
           | SOME "key" => "key"
           end
       in

       effect "getKey"
         let: "doGK" := (λ: "party", do: (EffName "getKey") "party") in
         handle: "f" "doGK" with
     | effect (EffName "getKey") "p", rec "k" as multi =>
         match: "p" with
           (* Alice *)
           InjL <> =>
             let: "key" := "sample_or_load" #()%V in
             (* Leak a send *)
             ("doLeakSend" bob);;
             (* Receive a dummy value *)
             let: "r" := ("doLeakRecv" bob) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "w" =>
                 "k" (SOME "key")
             end
         (* Bob  *)
         | InjR <> =>
             let: "r" := ("doLeakRecv" alice) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "w" =>
                 ("doLeakSend" alice);;
                 match: !"key_opt" with
                 | NONE => "k" NONEV
                 | SOME "key" =>
                     "k" (SOME "key")
                 end
             end
         end
     | return "y" => "y" end.

   Definition F_KE_just_lazy : val :=
     λ: "f" "effs",
       let, ("doLeakSend", "doLeakRecv") := "effs" in
       (* Magically share a lazily sampled key *)
       let: "α" := alloc #n in
       let: "key_opt" := ref NONEV in
       let: "sample_or_load" :=
         λ:<>, match: !"key_opt" with
           | NONE =>
               let: "c" := (sample #()%V) in
               let: "key" := g^"c" in
               "key_opt" <- SOME "key" ;;
               "key"
           | SOME "key" => "key"
           end
       in

       effect "getKey"
         let: "doGK" := (λ: "party", do: (EffName "getKey") "party") in
         handle: "f" "doGK" with
     | effect (EffName "getKey") "p", rec "k" as multi =>
         match: "p" with
           (* Alice *)
           InjL <> =>
             (* Leak a send *)
             ("doLeakSend" bob);;
             (* Receive a dummy value *)
             let: "r" := ("doLeakRecv" bob) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "w" =>
                 let: "key" := "sample_or_load" #()%V in
                 "k" (SOME "key")
             end
         (* Bob  *)
         | InjR <> =>
             let: "r" := ("doLeakRecv" alice) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "w" =>
                 (* NB: we should be able to swap the next two lines without observable differences *)
                 ("doLeakSend" alice);;
                 let: "key" := "sample_or_load" #()%V in
                 "k" (SOME "key")
             end
         end
     | return "y" => "y" end.

  Definition C : val :=
   λ: "DH" "f" "effs",
     let, ("doSend", "doRecv") := "effs" in
    let, ("ga", "gb", "gc") := "DH" #()%V in
    effect "getKey" 
    let: "doGK" := (λ: "party", do: (EffName "getKey") "party") in
    handle: "f" "doGK" with
    | effect (EffName "getKey") "p", rec "k" as multi =>
        match: "p" with
          InjL <> =>
            ("doSend" ("ga", bob));;
            let: "r" := ("doRecv" bob) in
            match: "r" with
              NONE => "k" NONE
            | SOME "w" => "k" (SOME "gc")
            end
        | InjR <> =>
            let: "r" := ("doRecv" alice) in
            match: "r" with
              NONE => "k" NONE
            | SOME "w" =>
                ("doSend" ("gb", alice));;
                "k" (SOME "gc")
            end
        end
    | return "y" => "y" end.

  Definition DH_real : val :=
    λ: <>,
    let: "a" := sample #()%V in
    let: "b" := sample #()%V in
    (g^"a", g^"b", g^("a"*"b")).

  Definition DH_rand : val :=
    λ: <>,
    let: "a" := sample #()%V in
    let: "b" := sample #()%V in
    let: "c" := sample #()%V in
    ( g^"a", g^"b", g^"c").
 End def_implementation.
