From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import def_dhke.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement sem_def. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.
From clutch.prob_eff_lang.probblaze.examples.DH_KE Require Import dhke_channel_lazy_authchan.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (channel1 channel2 : label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').
  Import valgroup_notation.

  Local Notation authchan_row  := (authchan_row channel1 channel2).
  Local Notation authchan_rowL := (authchan_rowL channel1 channel2).
  Local Notation authchan_rowR := (authchan_rowR channel1 channel2).
  Local Notation θ := (θ (Σ:=Σ) (vg:=vg)).

  (* Verification of DH_KE ≤ C[DH_real] *)
  (*------------------------------------------------------------*)
  
  Lemma DH_KE_C_DH_real (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ):
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗ (* changed to a circ *)
    (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-∘ 𝟙)%T f1 f2 -∗

    BREL DH_KE f1 ≤ C_lazy DH_real f2 <|⊥|> {{ λ v1 v2, 
                                                 ∀ c1 c2 : label, let ac := authchan_rowL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                                                  BREL v1 ((λ: "m", do: c1 (Send "m")), (λ: "m", do: c1 (Recv "m")))%V ≤
                                                                    v2 ((λ: "m", do: c2 (Send "m")), (λ: "m", do: c2 (Recv "m")))%V 
                                                                    <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont) using G.
    iIntros "Htoka Htokb Ha Hb Hff". 
    unfold DH_KE, C_lazy. 
    brel_pures'. iModIntro. 
    iIntros (c1 c2). set (ac := authchan_rowL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
    brel_pures'.
    repeat simpl.
    unfold DH_real. brel_pures'.
    iApply brel_alloctape_l. iIntros (α) "!> Hα". brel_pures_l.
    iApply brel_alloctape_l. iIntros (β) "!> Hβ". brel_pures_l.
    iApply brel_alloc_l. iIntros (la) "!> Hla".
    iApply brel_alloc_l. iIntros (lb) "!> Hlb".
    
    iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame. simpl. iIntros (a) "Hα".
    iDestruct "Hβ" as (ms) "(%Hf' & Hβ)". apply map_eq_nil in Hf'. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame "Hβ". simpl. iIntros (b) "Hβ".
    
    brel_pures_r. rewrite -Nat2Z.inj_mul.
    brel_pures'.
    iApply brel_alloc_r. iIntros (lcs) "Hlcs". brel_pures_r.
    
    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>".
    brel_pures'.
    (* unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff". *)
    set (θ := θ gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    (* iDestruct "Hff" as "#Hff". *)
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    (* iDestruct "Hff" as "#Hff".  *)
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      - iSplit; first (iPureIntro; left; split; done); iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
          iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists].
      - iSplit; first (iPureIntro; right; split; done); iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
          iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply fupd_brel.
    set (ga := (g ^+ a)%g).
    iMod (auth_upd ((#la, #a)%V) with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    (* Store resources before induction *)
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.
    
    iApply (brel_na_alloc
              ((β ↪ (n; [b]) ∗ lb ↦ NONEV)
               ∨ (β ↪□ (n; [])
                  ∗ lb ↦□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ (n; [a]) ∗ la ↦ NONEV ∗ lcs ↦ₛ NONEV)
               ∨ (α ↪□ (n; [])
                  ∗ la ↦□ SOMEV #a
                  ∗ lcs ↦ₛ□ SOMEV (vgval (g ^+ (a * b)))))%I
              alphaN).
    iSplitL "Hα Hla Hlcs"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
    
    iDestruct (brel_introduction_mono _ ([([gk1],[gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].
    
    (* getKey can be called multiple times, why we need induction *)
    (* the token is given away at the first call, so we need to store it in an invariant that holds for all calls to getKey *)
    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures|].
    (* getKeyAlice or getKeyBob *)
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : {
      brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|]...
      (* bind the match ... end block and prove (by casing on the invariant) that in either case "a" will become the value a (from the tape or the reference read), then continue only with one branch *)
      (* in other words, prove a spec for sample_or_load *)
      iApply (brel_na_inv _ _ alphaN); first set_solver.
      iFrame "Hinva".
      iIntros "([(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> Hla". brel_pures_l.
        iApply (brel_rand_l _ [AppRCtx _;AppRCtx _]).
        iAssert (α ↪N (n; [fin_to_nat a]))%I with "[Hα]" as "Hα".
        { iExists [a]. simpl. iFrame. done. }
        iFrame. iIntros "!>Hα _". brel_pures_l.
        iApply (brel_store_l _ _ _ [AppRCtx _; AppRCtx _] with "[$]").
        iIntros "!> Hla". brel_pures'. 
        iApply (brel_exp_l [AppRCtx _]). brel_pures_l.
        
        iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "Hlcs"). iIntros "Hlcs". brel_pures_r.
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hlcs"). iIntros "Hlcs". brel_pures_r.
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iMod (ghost_map_elem_persist with "Hlcs") as "#Hlcs".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft. iExists _,_,_.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame "Hla". iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. iApply brel_value. iIntros "$ !>".
        brel_pures'.
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Hb'".
          iDestruct (auth_agree with "[$Hb] [$Hb']") as "<-". 
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> _". brel_pures. brel_exp_l. brel_pures_l.
        
        iApply (brel_load_r with "Hlcs"). iIntros "_". brel_pures'.
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft.
        iExists _,_,_.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures.
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH". }
    
    1 : {
      brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|].
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply brel_introduction'.
      { apply elem_of_cons. right. apply list_elem_of_here. }
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iRight. iRight.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      { iApply brel_value. iIntros "$ !>".
        brel_pures.
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
      iIntros (la' m) "(#Hb'&#Hla')".
      iDestruct (auth_agree with "[$Ha] [$Hb']") as "%Heq".
      inversion Heq. subst. rewrite H1.
      iApply brel_value. iIntros "$ !>".
      brel_pures.
      
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> Hlb". brel_pures_l.
        iApply (brel_rand_l _ [AppRCtx _; AppRCtx _]).
        iAssert (β ↪N (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
        { iExists [b]. simpl. iFrame. done. }
        iFrame. iIntros "!>Hβ _". brel_pures_l.
        iApply (brel_store_l _ _ _ [AppRCtx _; AppRCtx _] with "Hlb").
        iIntros "!> Hlb".
        brel_pures. iApply (brel_exp_l [AppRCtx _]). brel_pures.
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
        iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iRight; iFrame "#"|].
        
        iApply (brel_bind' [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy|].
        iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. iLeft.
        iExists _,_.
        iSplitL.
        { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        
        iApply brel_value. iIntros "$ !>".
        brel_pures. brel_pures_l.
        rewrite -expgM. rewrite -ssrnat.multE.
        rewrite -Nat.mul_comm.
        
        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_r with "Hlcs"). iIntros "_". brel_pures_r.
        iDestruct ("Hcont" with "Hsome") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH".
        
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l with "[$]").
        iIntros "!> _". brel_pures_l. brel_exp_l. brel_pures.
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. iLeft.
        iExists _,_.
        iSplitL.
        { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        rewrite -expgM. rewrite -ssrnat.multE.
        (* rewrite -Nat.mul_comm. *)
        
        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_r with "Hlcs"). iIntros "_". brel_pures'.
        iDestruct ("Hcont" with "Hsome") as "Hkk". 
        apply Nat2Z.inj in H1 as ->.
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
  Qed.

End handlee_verification.

