From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze.examples.DH_KE Require Import dhke_common.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement. 

Import fingroup.
Import fingroup.fingroup.

Import valgroup_tactics.
Import valgroup_notation.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').

  (* Verification of F_AUTH ≤ F_AUTH *)
  (*------------------------------------------------------------*)
  
  Lemma F_AUTH_F_AUTHL (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ send1 send2 recv1 recv2 : label, let ac := chan_rowL send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                              v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2, 
                                            (∀ᵣ θₗ, (((𝔾 × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ℕ)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont) using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))".
    (* iIntros (lc dsend1 dsend2) "#Hsend". 
       brel_pures'. iModIntro.
       iIntros (drecv1 drecv2) "#Hrecv".  *)
    brel_pures'.
    
    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ (la : loc) (a : nat) , l1 ↦□ SOMEV (vgval (g ^+ a)%g) ∗ l1' ↦ₛ□ SOMEV (vgval (g ^+ a)%g) ∗ token γtoka
                                           ∗ own γfraca DfracDiscarded
                                           ∗ own γautha (to_dfrac_agree DfracDiscarded (#la, #a)%V)
                                           ∗ la ↦□ SOMEV #a)
              ) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply brel_effect_l. iIntros (sendlabel1) "!> Hsend1".
    iApply brel_effect_r. iModIntro. iIntros (sendlabel2) "Hsend2 !>".
    iApply brel_effect_l. iIntros (recvlabel1) "!> Hrecv1".
    iApply brel_effect_r. iModIntro. iIntros (recvlabel2) "Hrecv2 !>".
    iSpecialize ("Hff" $! sendlabel1 sendlabel2 recvlabel1 recvlabel2).
    brel_pures'.
    
    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hsend1").
    iApply (brel_add_label_r with "Hsend2").

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hrecv1").
    iApply (brel_add_label_r with "Hrecv2").
    
    (* Peel the outer (recv) handler.  This leaves two goals: the send-handled
       body -- where the inner (send) handler is peeled in turn -- and the
       value/effect cases of the recv handler itself.  R has to be given
       explicitly, otherwise it stays an evar until the recv branch. *)
    iApply (brel_exhaustion _ _ [_] [_] _ _ _ (λ w1 w2, 𝟙%T w1 w2) with "[Hff]"); [done|done| |].

    (* SEND *)
    (*------------------------------------------------------------*)
    1 : {
      (* brel_exhaustion consumes the head of the row, so bring send to the front. *)
      iApply brel_introduction_mono; first (iApply to_iThy_le_intro'; apply submseteq_swap).
      iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
      { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'.
        etrans; [apply submseteq_swap|]. do 2 apply submseteq_skip.
        rewrite iLblSig_to_iLblThy_app. by apply submseteq_inserts_l. }
      iLöb as "IHsend".
      iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
      iIntros (?????) "!# %Hk1 %Hk2 [(%&%&%&Hupd&(->&->)&#HQ) | (%&%&Hupd&(->&->)&#HQ)] #Hkont".

      (* SendAliceImplL : Alice sends to Bob, stored in l1 *)
      1 : { iApply (brel_na_inv _ _ alphaN ); [set_solver|].
            iFrame "Hinva".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
              iMod (dfrac_persist with "Hfraca") as "#Hfraca".
              iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & #Hla & <-)".
              iModIntro.
              brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
              iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
              brel_pures.
              iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
              iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
              brel_pures.
              iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
              { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
                by apply submseteq_inserts_r. }

              iApply fupd_brel.
              iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
              iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
              iModIntro.
              iApply brel_na_close. iFrame.
              iSplitL "Htok Hauth"; [iNext; iRight; iExists _, _; iFrame "#"; iFrame|].

              iAssert (sem_val_typed (_, bob)%V (_,bob)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
              { iModIntro. iExists _,_,_,_.
                repeat (iSplit; first done).
                iSplit; first (iExists (g ^+ m)%g; done).
                iExists _,_. iLeft. done. }
              unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
              unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
              iDestruct ("Hsend" with "Hmm") as "Hsend1".
              iApply (brel_wand with "[$Hsend1]").
              iIntros (??) "!# (->&->)".
              brel_pures'.
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IHsend".

            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
              iApply brel_na_close. iFrame.
              iSplitL "Htoka"; [iNext; iRight; iExists _,_; iFrame; iFrame "#"|].
              brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
              iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hl1]"). iIntros "!> _".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$Hl1s]"). iIntros "_".
              brel_pures.
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IHsend". }

      (* SendBobImpl : Bob sends to Alice, stored in l2 *)
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
          by apply submseteq_inserts_r. }

        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

        iAssert (sem_val_typed (m, alice)%V (m,alice)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done).
          iSplit; first (iExists _; done).
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1".
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHsend".

      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHsend". }

    (* RECV *)
    (*------------------------------------------------------------*)
    iLöb as "IHrecv".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [(->&->&#(HNone & HSome)) | (->&->&#(HNone & HSome))] #Hkont".

    (* RecvAliceImplL : receive from Alice, i.e. read l1 *)
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver...
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
            by apply submseteq_inserts_r. }

          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1".
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "Hl1"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_".
              brel_pures.
              iDestruct ("HSome" with "[$Hautha $Hla]") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv". }

    (* RecvBobImpl : receive from Bob, i.e. read l2 *)
    brel_pures; [apply Hk1|apply Hk2|]; try set_solver...
    iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
    { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
      by apply submseteq_inserts_r. }

    iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
    { iModIntro. iExists _,_. iLeft. done. }
    unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
    unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
    iDestruct ("Hrecv" with "Hbob") as "Hrecv1".
    iApply (brel_wand with "[$Hrecv1]").
    iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

    + iDestruct ("Hkont" with "HNone") as "Hbrel".
      iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

    + iApply (brel_na_inv _ _ betaN); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
        iDestruct ("Hkont" with "HNone") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

      * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
        iApply (brel_load_l with "[$]"). iIntros "!> _".
        iApply (brel_load_r with "Hl2s"). iIntros "_".
        brel_pures.
        iDestruct ("HSome" with "Hauthb") as "HS".
        iDestruct ("Hkont" with "HS") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".
  Qed.

  Lemma F_AUTH_F_AUTHR (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ send1 send2 recv1 recv2 : label, let ac := chan_rowR send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                              v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2, 
                                            (∀ᵣ θₗ, (((𝔾 × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ℕ)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont) using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))".
    (* iIntros (lc dsend1 dsend2) "#Hsend". 
       brel_pures'. iModIntro.
       iIntros (drecv1 drecv2) "#Hrecv".  *)
    brel_pures'.
    
    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ (la : loc) (a : nat) , l1 ↦□ SOMEV (vgval (g ^+ a)%g) ∗ l1' ↦ₛ□ SOMEV (vgval (g ^+ a)%g) ∗ token γtoka
                                           ∗ own γfraca DfracDiscarded
                                           ∗ own γautha (to_dfrac_agree DfracDiscarded (#la, #a)%V)
                                           ∗ la ↦ₛ□ SOMEV #a)
              ) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply brel_effect_l. iIntros (sendlabel1) "!> Hsend1".
    iApply brel_effect_r. iModIntro. iIntros (sendlabel2) "Hsend2 !>".
    iApply brel_effect_l. iIntros (recvlabel1) "!> Hrecv1".
    iApply brel_effect_r. iModIntro. iIntros (recvlabel2) "Hrecv2 !>".
    iSpecialize ("Hff" $! sendlabel1 sendlabel2 recvlabel1 recvlabel2).
    brel_pures'.
    
    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hsend1").
    iApply (brel_add_label_r with "Hsend2").

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hrecv1").
    iApply (brel_add_label_r with "Hrecv2").
    
    (* Peel the outer (recv) handler.  This leaves two goals: the send-handled
       body -- where the inner (send) handler is peeled in turn -- and the
       value/effect cases of the recv handler itself.  R has to be given
       explicitly, otherwise it stays an evar until the recv branch. *)
    iApply (brel_exhaustion _ _ [_] [_] _ _ _ (λ w1 w2, 𝟙%T w1 w2) with "[Hff]"); [done|done| |].

    (* SEND *)
    (*------------------------------------------------------------*)
    1 : {
      (* brel_exhaustion consumes the head of the row, so bring send to the front. *)
      iApply brel_introduction_mono; first (iApply to_iThy_le_intro'; apply submseteq_swap).
      iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
      { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'.
        etrans; [apply submseteq_swap|]. do 2 apply submseteq_skip.
        rewrite iLblSig_to_iLblThy_app. by apply submseteq_inserts_l. }
      iLöb as "IHsend".
      iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
      iIntros (?????) "!# %Hk1 %Hk2 [(%&%&%&Hupd&(->&->)&#HQ) | (%&%&Hupd&(->&->)&#HQ)] #Hkont".

      (* SendAliceImplL : Alice sends to Bob, stored in l1 *)
      1 : { iApply (brel_na_inv _ _ alphaN ); [set_solver|].
            iFrame "Hinva".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
              iMod (dfrac_persist with "Hfraca") as "#Hfraca".
              iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & #Hla & <-)".
              iModIntro.
              brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
              iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
              brel_pures.
              iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
              iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
              brel_pures.
              iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
              { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
                by apply submseteq_inserts_r. }

              iApply fupd_brel.
              iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
              iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
              iModIntro.
              iApply brel_na_close. iFrame.
              iSplitL "Htok Hauth"; [iNext; iRight; iExists _, _; iFrame "#"; iFrame|].

              iAssert (sem_val_typed (_, bob)%V (_,bob)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
              { iModIntro. iExists _,_,_,_.
                repeat (iSplit; first done).
                iSplit; first (iExists (g ^+ m)%g; done).
                iExists _,_. iLeft. done. }
              unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
              unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
              iDestruct ("Hsend" with "Hmm") as "Hsend1".
              iApply (brel_wand with "[$Hsend1]").
              iIntros (??) "!# (->&->)".
              brel_pures'.
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IHsend".

            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
              iApply brel_na_close. iFrame.
              iSplitL "Htoka"; [iNext; iRight; iExists _,_; iFrame; iFrame "#"|].
              brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
              iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hl1]"). iIntros "!> _".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$Hl1s]"). iIntros "_".
              brel_pures.
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IHsend". }

      (* SendBobImpl : Bob sends to Alice, stored in l2 *)
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
          by apply submseteq_inserts_r. }

        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

        iAssert (sem_val_typed (m, alice)%V (m,alice)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done).
          iSplit; first (iExists _; done).
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1".
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHsend".

      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHsend". }

    (* RECV *)
    (*------------------------------------------------------------*)
    iLöb as "IHrecv".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [(->&->&#(HNone & HSome)) | (->&->&#(HNone & HSome))] #Hkont".

    (* RecvAliceImplL : receive from Alice, i.e. read l1 *)
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver...
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
            by apply submseteq_inserts_r. }

          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1".
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "Hl1"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_".
              brel_pures.
              iDestruct ("HSome" with "[$Hautha $Hla]") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv". }

    (* RecvBobImpl : receive from Bob, i.e. read l2 *)
    brel_pures; [apply Hk1|apply Hk2|]; try set_solver...
    iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
    { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
      by apply submseteq_inserts_r. }

    iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
    { iModIntro. iExists _,_. iLeft. done. }
    unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
    unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
    iDestruct ("Hrecv" with "Hbob") as "Hrecv1".
    iApply (brel_wand with "[$Hrecv1]").
    iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

    + iDestruct ("Hkont" with "HNone") as "Hbrel".
      iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

    + iApply (brel_na_inv _ _ betaN); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
        iDestruct ("Hkont" with "HNone") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

      * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
        iApply (brel_load_l with "[$]"). iIntros "!> _".
        iApply (brel_load_r with "Hl2s"). iIntros "_".
        brel_pures.
        iDestruct ("HSome" with "Hauthb") as "HS".
        iDestruct ("Hkont" with "HS") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".
  Qed.

  Lemma F_AUTH_F_AUTH (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ send1 send2 recv1 recv2 : label, let ac := chan_row send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                              v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2, 
                                            (∀ᵣ θₗ, (((𝔾 × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ℕ)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont) using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))".
    (* iIntros (lc dsend1 dsend2) "#Hsend". 
       brel_pures'. iModIntro.
       iIntros (drecv1 drecv2) "#Hrecv".  *)
    brel_pures'.
    
    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ gA , l1 ↦□ SOMEV gA ∗ l1' ↦ₛ□ SOMEV gA ∗ token γtoka
                         ∗ own γfraca DfracDiscarded
                         ∗ own γautha (to_dfrac_agree DfracDiscarded gA))) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply brel_effect_l. iIntros (sendlabel1) "!> Hsend1".
    iApply brel_effect_r. iModIntro. iIntros (sendlabel2) "Hsend2 !>".
    iApply brel_effect_l. iIntros (recvlabel1) "!> Hrecv1".
    iApply brel_effect_r. iModIntro. iIntros (recvlabel2) "Hrecv2 !>".
    iSpecialize ("Hff" $! sendlabel1 sendlabel2 recvlabel1 recvlabel2).
    brel_pures'.
    
    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hsend1").
    iApply (brel_add_label_r with "Hsend2").

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hrecv1").
    iApply (brel_add_label_r with "Hrecv2").
    
    (* Peel the outer (recv) handler.  This leaves two goals: the send-handled
       body -- where the inner (send) handler is peeled in turn -- and the
       value/effect cases of the recv handler itself.  R has to be given
       explicitly, otherwise it stays an evar until the recv branch. *)
    iApply (brel_exhaustion _ _ [_] [_] _ _ _ (λ w1 w2, 𝟙%T w1 w2) with "[Hff]"); [done|done| |].

    (* SEND *)
    (*------------------------------------------------------------*)
    1 : {
      (* brel_exhaustion consumes the head of the row, so bring send to the front. *)
      iApply brel_introduction_mono; first (iApply to_iThy_le_intro'; apply submseteq_swap).
      iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
      { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'.
        etrans; [apply submseteq_swap|]. do 2 apply submseteq_skip.
        rewrite iLblSig_to_iLblThy_app. by apply submseteq_inserts_l. }
      iLöb as "IHsend".
      iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
      iIntros (?????) "!# %Hk1 %Hk2 [(%&%&Hupd&(->&->)&#HQ) | (%&%&Hupd&(->&->)&#HQ)] #Hkont".

      (* SendAliceImplL : Alice sends to Bob, stored in l1 *)
      1 : { iApply (brel_na_inv _ _ alphaN ); [set_solver|].
            iFrame "Hinva".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%gA & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
              iMod (dfrac_persist with "Hfraca") as "#Hfraca".
              iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & <-)".
              iModIntro.
              brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
              iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
              brel_pures.
              iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
              iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
              brel_pures.
              iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
              { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
                by apply submseteq_inserts_r. }

              iApply fupd_brel.
              iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
              iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
              iModIntro.
              iApply brel_na_close. iFrame.
              iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

              iAssert (sem_val_typed (m, bob)%V (m,bob)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
              { iModIntro. iExists _,_,_,_.
                repeat (iSplit; first done).
                iSplit; first (iExists _; done).
                iExists _,_. iLeft. done. }
              unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
              unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
              iDestruct ("Hsend" with "Hmm") as "Hsend1".
              iApply (brel_wand with "[$Hsend1]").
              iIntros (??) "!# (->&->)".
              brel_pures'.
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IHsend".

            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
              iApply brel_na_close. iFrame.
              iSplitL "Htoka"; [iNext; iRight; iExists gA; iFrame; iFrame "#"|].
              brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
              iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hl1]"). iIntros "!> _".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$Hl1s]"). iIntros "_".
              brel_pures.
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IHsend". }

      (* SendBobImpl : Bob sends to Alice, stored in l2 *)
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
          by apply submseteq_inserts_r. }

        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

        iAssert (sem_val_typed (m, alice)%V (m,alice)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done).
          iSplit; first (iExists _; done).
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1".
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHsend".

      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHsend". }

    (* RECV *)
    (*------------------------------------------------------------*)
    iLöb as "IHrecv".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [(->&->&#(HNone & HSome)) | (->&->&#(HNone & HSome))] #Hkont".

    (* RecvAliceImplL : receive from Alice, i.e. read l1 *)
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver...
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
            by apply submseteq_inserts_r. }

          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1".
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%gA & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "Hl1"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_".
              brel_pures.
              iDestruct ("HSome" with "Hautha") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv". }

    (* RecvBobImpl : receive from Bob, i.e. read l2 *)
    brel_pures; [apply Hk1|apply Hk2|]; try set_solver...
    iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
    { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
      by apply submseteq_inserts_r. }

    iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
    { iModIntro. iExists _,_. iLeft. done. }
    unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
    unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
    iDestruct ("Hrecv" with "Hbob") as "Hrecv1".
    iApply (brel_wand with "[$Hrecv1]").
    iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

    + iDestruct ("Hkont" with "HNone") as "Hbrel".
      iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

    + iApply (brel_na_inv _ _ betaN); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
        iDestruct ("Hkont" with "HNone") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".

      * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
        iApply (brel_load_l with "[$]"). iIntros "!> _".
        iApply (brel_load_r with "Hl2s"). iIntros "_".
        brel_pures.
        iDestruct ("HSome" with "Hauthb") as "HS".
        iDestruct ("Hkont" with "HS") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IHrecv".
  Qed.

End handlee_verification.
