From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import dhke_common.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.
Import valgroup_notation.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').
  Import valgroup_notation.
  Local Notation gkleakr := (gkleakr (Σ:=Σ) (vg:=vg)).

  (* Verification of C[DH_rand] ≤ DH_SIM[F_KE] *)
  (*--------------------------------------------------*)  

  Lemma C_DH_rand_DH_SIM_F_KE f1 f2 γtoka γtokb γfraca γfracb γautha γauthb L :
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-∘ 𝟙)%T f1 f2 -∗
    BREL C_lazy DH_rand f1 ≤ DH_SIM (F_KE_lazy_alice f2) <|⊥|> 
      {{ λ v1 v2, ∀ send1 send2 recv1 recv2 : label, let ac := chan_row send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                   BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                     v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                     <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont; brel_pures') using G inG0 inG1 inG2.
    iIntros "Htoka Htokb Ha Hb Hff". 
    unfold DH_SIM, F_KE_lazy_alice, C_lazy, DH_rand...
    iModIntro. 
    iIntros (send1 send2 recv1 recv2)...
    set (ac := chan_row send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).

    brel_alloctape_r α as "Hα"...
    brel_alloctape_r β as "Hβ"...
    rewrite Nat2Z.id.
    brel_alloc_r la as "Hla"...
    brel_alloc_r lb as "Hlb"...

    iAssert (α ↪ₛN (n; []))%I with "[Hα]" as "Hα".
    { iExists []. iSplit; done. }
    iApply brel_couple_UT; first done. iFrame "Hα". iIntros (a ?) "!> Hα".
    iAssert (β ↪ₛN (n; []))%I with "[Hβ]" as "Hβ".
    { iExists []. iSplit; done. }
    iApply brel_couple_UT; first done. iFrame "Hβ". iIntros (b ?) "!> Hβ"...
    
    brel_effect_r leaksend as "Hleaksend"...
    brel_effect_r leakrecv as "Hleakrecv"...
    
    brel_alloctape_r γ as "Hγ"...
    rewrite Nat2Z.id.
    iAssert (γ ↪ₛN (n; []))%I with "[Hγ]" as "Hγ".
    { iExists []. iSplit; done. }
    iApply brel_couple_UT; first done. iFrame "Hγ". iIntros (c ?) "!> Hγ"...
    brel_alloc_l lcs as "Hlcs".
    brel_alloc_r lc as "Hlc"...

    brel_effect_l gk1 as "Hgk1".
    brel_effect_r gk2 as "Hgk2"...
    
    iApply fupd_brel.
    iMod (auth_upd (vgval (g ^+ a)%g) with "Ha") as "Ha".
    iMod (auth_upd (vgval (g ^+ b)%g) with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.
    
    iApply (brel_na_alloc
              ((β ↪ₛN (n; [b]) ∗ lb ↦ₛ NONEV)
               ∨ (β ↪ₛ□ (n; [])
                  ∗ lb ↦ₛ□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ₛN (n; [a]) ∗ γ ↪ₛN (n; [c]) ∗ la ↦ₛ NONEV ∗ lc ↦ₛ NONEV ∗ lcs ↦ NONEV)
               ∨ (α ↪ₛ□ (n; [])
                  ∗ la ↦ₛ□ SOMEV #a
                  ∗ γ ↪ₛ□ (n; [])
                  ∗ lc ↦ₛ□ SOMEV (vgval (g ^+ c)%g)
                  ∗ lcs ↦□ SOMEV (vgval (g ^+ c)%g)))%I
              alphaN).
    iSplitL "Hα Hla Hγ Hlc Hlcs"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ gkleakr leaksend leakrecv gk1 gk2 }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
        iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    rewrite /sem_val_typed /=. 
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
    iApply (brel_add_label_r with "Hleakrecv").
    iApply (brel_add_label_r with "Hleaksend").
    
    iDestruct (brel_introduction_mono _ ([([gk1],[leaksend;leakrecv;gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. solve_submseteq. }
    iApply (brel_exhaustion with "[$]"); [done|set_solver|].
    
    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures'|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : {
      brel_pures'; [apply Hk2;set_solver|apply Hk1; set_solver|]...
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hα & Hγ & Hla & Hlc & Hlcs) | #(Hα & Hla & Hγ & Hlc & Hlcs)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _;CaseCtx _ _] with "Hlcs"). iIntros "!> Hlcs"...
        brel_store_l...
        brel_load_r...
        brel_rand_r...
        iApply (brel_exp_r [HandleCtx _ _ _ _ _; HandleCtx _ _ _ _ _;AppRCtx _;AppRCtx _])...
        brel_store_r... 1 : set_solver.
        brel_load_r...
        brel_rand_r...
        brel_store_r...
        iApply (brel_exp_r [HandleCtx _ _ _ _ _; AppRCtx _])...
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iMod (ghost_map_elem_persist with "Hlc") as "#Hlc".
        iMod (ghost_map_elem_persist with "Hlcs") as "#Hlcs".
        iDestruct "Hγ" as (ns) "(%Hf & Hγ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hγ") as "#Hγ".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].

        iApply brel_learn. iIntros ((Hdl&Hdr)) "_".

        (* Send (gA, bob) *)
        iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
        iExists _, _, [AppRCtx _], [HandleCtx _ _ _ _ _; AppRCtx _], _.
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          label_not_in_singleton Hdr. }
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. 
        iExists _, _.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.

        brel_pures'; first label_not_in_singleton Hdr.

        (* Recv bob (either none or some) *)
        iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
        iExists _, _, [AppRCtx _], [AppRCtx _], _.
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          label_not_in_singleton Hdr. }
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL...
        
        (* Recv bob = None *)
        + iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-"...
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"].
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_l...
        brel_load_r... 1 : set_solver.
        brel_load_r...

        iApply brel_learn. iIntros ((Hdl&Hdr)) "_".

        (* Send (gA, bob) *)
        iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
        iExists _, _, [AppRCtx _], [HandleCtx _ _ _ _ _; AppRCtx _], _.
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          label_not_in_singleton Hdr. }
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft.
        iExists _, _.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro.
        brel_pures'; first label_not_in_singleton Hdr.

        (* Recv bob (either none or some) *)
        iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
        iExists _, _, [AppRCtx _], [AppRCtx _], _.
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          label_not_in_singleton Hdr. }
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL...
        
        (* Recv bob = None *)
        + iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"]. }
    
    1 : {
      iApply brel_learn. iIntros ((Hdl&Hdr)) "_".
      brel_pures'; [split; [apply neutral_ectx;set_solver|label_not_in_singleton Hdr]|apply Hk1; set_solver|].

      (* Recv alice (either none or some) *)
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iLeft.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL...
      
      (* Recv alice = None *)
      + iApply brel_value. iIntros "$ !>"...
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"].
        
      + iIntros (m) "Ha'".
        iDestruct (auth_agree with "[$Ha] [$Ha']") as "<-".
        iApply brel_value. iIntros "$ !>"...
        1 : set_solver.
        iApply (brel_na_inv _ _ betaN ); [set_solver|].
        iFrame "Hinvb". 
        iIntros "([(>Hβ & >Hlb) | (#>Hβ & #>Hlb)] & Hclose)".
        * iApply (brel_load_r _ _ _ _ [HandleCtx _ _ _ _ _; AppRCtx _; CaseCtx _ _] with "Hlb").
          iIntros "Hlb"...
          brel_rand_r...
          brel_store_r...
          iApply (brel_exp_r [HandleCtx _ _ _ _ _; AppRCtx _])...
          
          iApply fupd_brel.
          iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
          iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
          iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
          iModIntro.
          iApply brel_na_close. iFrame.
          iSplitL; [iNext; iRight; iFrame "#"|].
          
          (* Send (gB, alice) *)
          iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
          iExists _, _, [AppRCtx _], [HandleCtx _ _ _ _ _; AppRCtx _], _.
          iSplit; first done; iSplit; [iPureIntro; apply _|].
          iSplit; first done.
          iSplit.
          { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
            label_not_in_singleton Hdr. }
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight. 
          iExists _,_.
          iSplitL; first (iApply send_upd; by iFrame "#").
          iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
          iModIntro...

          iApply (brel_na_inv _ _ alphaN ); [set_solver|].
          iFrame "Hinva". 
          iIntros "(>[(Hα & Hla & Hγ & Hlc & Hlcs) | #(Hα & Hla & Hγ & Hlc & Hlcs)] & Hclose)".
          
          { iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hlcs]"). iIntros "!> Hlcs"...
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
            
            iDestruct ("Hcont" with "Hnone") as "Hkk".
            iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"]. }
          
          { iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hlcs]"). iIntros "!> _"...
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
            iDestruct ("Hcont" with "Hsome") as "Hkk".
            iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"]. }
          
        * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
          brel_load_r...
          
          (* Send (gB, alice) *)
          iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
          iExists _, _, [AppRCtx _], [HandleCtx _ _ _ _ _; AppRCtx _], _.
          iSplit; first done; iSplit; [iPureIntro; apply _|].
          iSplit; first done.
          iSplit.
          { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
            label_not_in_singleton Hdr. }
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight.
          iExists _,_.
          iSplitL; first (iApply send_upd; by iFrame "#").
          iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
          iModIntro...

          iApply (brel_na_inv _ _ alphaN ); [set_solver|].
          iFrame "Hinva". 
          iIntros "(>[(Hα & Hla & Hγ & Hlc & Hlcs) | #(Hα & Hla & Hγ & Hlc & Hlcs)] & Hclose)".
          
          { iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hlcs]"). iIntros "!> Hlcs"...
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
            
            iDestruct ("Hcont" with "Hnone") as "Hkk".
            iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"]. }
          
          { iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hlcs]"). iIntros "!> _"...
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
            iDestruct ("Hcont" with "Hsome") as "Hkk".
            iApply (brel_exhaustion with "[$]"); [done|set_solver|iApply "IH"]. } }
  Qed.

End handlee_verification.

