From iris.proofmode Require Import base.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Export agree excl auth frac excl_auth.
From iris.algebra.lib Require Export dfrac_agree.
From clutch.prob_eff_lang.probblaze Require Export logic notation sem_def tactics.
From clutch.prob_eff_lang.probblaze.examples.DH_KE Require Export valgroup def_dhke.

Export fingroup.fingroup.
Export valgroup_tactics valgroup_notation.

Section resources.
  Context `{!probblazeRGS Σ}.
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  Definition token γ := own γ (Excl ()).
  
  (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".


  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.

End resources.

Section lemmas.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.
  #[local] Notation n := (S n'').

  Lemma send_upd P n γtok γfrac :
    P ∗
    invariants.inv n (token γtok ∨ own γfrac DfracDiscarded) ⊢
    (|={⊤,⊤ ∖ ↑n}=>
       (own γfrac DfracDiscarded ={⊤ ∖ ↑n,⊤}=∗ token γtok ∗ P)
        ∨ (|={⊤ ∖ ↑n,⊤}=> own γfrac DfracDiscarded)).
  Proof. 
    iIntros "(HP&#Hinv)".
    iMod (inv_acc with "Hinv") as "([>Htok | >#Hfrac] & Hclose)"; try done.
    - iModIntro. iLeft.
      iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". 
      by iModIntro. 
    - iModIntro. iRight. iFrame "#".
      iApply "Hclose". iNext.
      by iRight.
  Qed. 

 (* A spec for sample_or_read for alice *)
  Lemma sample_or_read_store E α (s : string) a c la lcs K K' L R :
    (α ↪ (n; [a]) ∗ la ↦ InjLV #()%V ∗ lcs ↦ₛ InjLV #()%V ∨ α ↪□ (n; []) ∗ la ↦□ InjRV #a ∗ lcs ↦ₛ□ InjRV (vgval (g ^+ c))) -∗
    (la ↦□ InjRV #a -∗
       α ↪□ (n; []) -∗
       lcs ↦ₛ□ InjRV (vgval (g ^+ c)) -∗ 
       BREL fill K #a ≤ fill K' #()%V @ E <|L|> {{ R }}) -∗ 
    BREL fill K (match: ! #la with InjL <> => let: s := #()%V;; rand(#lbl:α) #n in #la <- InjR s;; s | InjR s => s end) 
      ≤ fill K' (match: ! #lcs with InjL <> => #lcs <- InjR (vgval (g ^+ c)) | InjR "key" => #()%V end) @ E <|L|> {{ R }}.
  Proof with (try rewrite fill_app //=; brel_pures'). 
    iIntros "[(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] Hkont".
    (* first run *)
    - brel_load_l...
      (* TAPES : stems from the fact that some lemmas uses fin-tapes other nat-tapes -- should be unified *)
      iAssert (α ↪N (n; [fin_to_nat a]))%I with "[Hα]" as "Hα". 
      { iExists [a]. simpl. iFrame. done. }
      brel_rand_l...
      rewrite decide_True; last done...
      brel_store_l...
      brel_load_r...
      brel_store_r...
      
      iApply fupd_brel.
      iMod (ghost_map_elem_persist with "Hla") as "#Hla".
      (* TAPES : stems from the fact that some lemmas uses fin-tapes other nat-tapes -- should be unified *)
      iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
      iMod (ghost_map_elem_persist with "Hα") as "#Hα".
      iMod (ghost_map_elem_persist with "Hlcs") as "#Hlcs".
      iModIntro.
      by iApply "Hkont".
    - brel_load_l...
      rewrite decide_True; last done...
      brel_load_r...
      by iApply "Hkont".
  Qed. 

 (* A spec for sample_or_read for alice *)
  Lemma sample_or_read_store_spec E α (s : string) a c la lcs K K' L R :
    (α ↪ₛN (n; [a]) ∗ la ↦ₛ InjLV #()%V ∗ lcs ↦ InjLV #()%V ∨ α ↪ₛ□ (n; []) ∗ la ↦ₛ□ InjRV #a ∗ lcs ↦□ InjRV (vgval (g ^+ c))) -∗
    (la ↦ₛ□ InjRV #a -∗
       α ↪ₛ□ (n; []) -∗
       lcs ↦□ InjRV (vgval (g ^+ c)) -∗ 
       BREL fill K #()%V ≤ fill K' #a @ E <|L|> {{ R }}) -∗ 
    BREL fill K (match: ! #lcs with InjL <> => #lcs <- InjR (vgval (g ^+ c)) | InjR "key" => #()%V end) 
      ≤ fill K' (match: ! #la with InjL <> => let: s := #()%V;; rand(#lbl:α) #n in #la <- InjR s;; s | InjR s => s end) @ E <|L|> {{ R }}.
  Proof with (try rewrite fill_app //=; brel_pures'). 
    iIntros "[(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] Hkont".
    (* first run *)
    - brel_load_r...
      brel_rand_r...
      rewrite decide_True; last done...
      brel_store_r...
      brel_load_l...
      brel_store_l...
      
      iApply fupd_brel.
      iMod (ghost_map_elem_persist with "Hla") as "#Hla".
      (* TAPES : stems from the fact that some lemmas uses fin-tapes other nat-tapes -- should be unified *)
      iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
      iMod (ghost_map_elem_persist with "Hα") as "#Hα".
      iMod (ghost_map_elem_persist with "Hlcs") as "#Hlcs".
      iModIntro.
      by iApply "Hkont".
    - brel_load_r...
      rewrite decide_True; last done...
      brel_load_l...
      by iApply "Hkont".
  Qed.

 (* A spec for sample_or_read for bob *)
  Lemma sample_or_read E β (s : string) b lb K e L R :
    (β ↪ (n; [b]) ∗ lb ↦ InjLV #()%V ∨ β ↪□ (n; []) ∗ lb ↦□ InjRV #b) -∗
    (lb ↦□ InjRV #b -∗
     β ↪□ (n; []) -∗
     BREL fill K #b ≤ e @ E <|L|> {{ R }}) -∗ 
    BREL fill K (match: ! #lb with InjL <> => let: s := #()%V;; rand(#lbl:β) #n in #lb <- InjR s;; s | InjR s => s end) 
      ≤ e @ E <|L|> {{ R }}.
  Proof with (try rewrite fill_app //=; brel_pures'). 
    iIntros "[(Hβ & Hlb) | #(Hβ & Hlb)] Hkont".
    - brel_load_l... 
      (* TAPES : stems from the fact that some lemmas uses fin-tapes other nat-tapes -- should be unified *)
      iAssert (β ↪N (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
      { iExists [b]. simpl. iFrame. done. }
      brel_rand_l...
      rewrite decide_True; last done...
      brel_store_l...

      iApply fupd_brel.
      iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
      (* TAPES : stems from the fact that some lemmas uses fin-tapes other nat-tapes -- should be unified *)
      iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
      iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
      iModIntro.
      by iApply "Hkont".
    - brel_load_l...
      rewrite decide_True; last done...
      by iApply "Hkont".
  Qed.

(* A spec for sample_or_read for bob *)
  Lemma sample_or_read_spec E β (s : string) b lb K e L R :
    (β ↪ₛN (n; [b]) ∗ lb ↦ₛ InjLV #()%V ∨ β ↪ₛ□ (n; []) ∗ lb ↦ₛ□ InjRV #b) -∗
    (lb ↦ₛ□ InjRV #b -∗
     β ↪ₛ□ (n; []) -∗
     BREL e ≤ fill K #b @ E <|L|> {{ R }}) -∗ 
    BREL e
      ≤ fill K (match: ! #lb with InjL <> => let: s := #()%V;; rand(#lbl:β) #n in #lb <- InjR s;; s | InjR s => s end)  @ E <|L|> {{ R }}.
  Proof with (try rewrite fill_app //=; brel_pures'). 
    iIntros "[(Hβ & Hlb) | #(Hβ & Hlb)] Hkont".
    - brel_load_r... 
      brel_rand_r...
      rewrite decide_True; last done...
      brel_store_r...

      iApply fupd_brel.
      iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
      (* TAPES : stems from the fact that some lemmas uses fin-tapes other nat-tapes -- should be unified *)
      iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
      iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
      iModIntro.
      by iApply "Hkont".
    - brel_load_r...
      rewrite decide_True; last done...
      by iApply "Hkont".
  Qed.

End lemmas.

Section theories.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  Program Definition GetKey gk1 gk2: iThy Σ :=
    λ e1 e2, (λne Q,
                ((⌜ e1 = do: gk1 (InjLV #()%V) ⌝%E ∗
                  ⌜ e2 = do: gk2 (InjLV #()%V) ⌝%E) ∨
                   (⌜ e1 = do: gk1 (InjRV #()%V) ⌝%E ∗
                    ⌜ e2 = do: gk2 (InjRV #()%V) ⌝%E)) ∗
                □ (Q NONEV NONEV ∗ ∀ key : vgG, Q (SOMEV key) (SOMEV key) )
             )%I.
  Next Obligation. solve_proper. Qed.

  (* Theories for the implementations *)
  (*------------------------------------------------------------*)

 Program Definition Send dst c1 c2 γtok γfrac ι P : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m': vgG, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ (□ (P m)) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                              (⌜ e1 = do: c1 (m, dst)%V ⌝%E ∗
                               ⌜ e2 = do: c2 (m', dst)%V ⌝%E)  ∗ 
                              □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition Recv from c1 c2 P : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 from ⌝%E ∗
                ⌜ e2 = do: c2 from ⌝%E ∗
                □ (Q NONEV NONEV ∗ (∀ m : vgG, (P m) -∗ Q (SOMEV (vgval m)) (SOMEV (vgval m))))
             )%I.
  Next Obligation. solve_proper. Qed.

  (* semantic types *)
  (*------------------------------------------------------------*)

  Import valgroup_notation.

  Program Definition gkmono (gk1 gk2 : label) :=  {| pmono_prot_car := GetKey gk1 gk2; pmono_prot_prop := _ |}.
  Next Obligation.
    intros ??. iIntros (????) "#HΦ ([(->&->)|(->&->)] & #(H1&H2))"; repeat iSplit; [by iLeft| |by iRight|]; iModIntro; iSplitL; try iIntros (?); by iApply "HΦ".
  Qed. 

  Definition gk (gk1 gk2 : label) := @SemSig Σ (gkmono gk1 gk2) (gk1,gk2).
  
  Program Definition θ gk1 gk2 := SemRow [([gk1],[gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  
  Program Definition gkleakl leaks leakr gk1 gk2 := SemRow [([leaks;leakr;gk1],[gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition gkleakr leaks leakr gk1 gk2 := SemRow [([gk1],[leaks;leakr;gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

 Program Definition send_new_mono send1 send2 γtoka atokN γtokb btokN γfraca γfracb P P' :=
    {| pmono_prot_car := iThySum (Send bob send1 send2 γtoka γfraca atokN P) (Send alice send1 send2 γtokb γfracb btokN P'); pmono_prot_prop := _|}.
  Next Obligation.
    intros ??????????. 
    iIntros (????) "#HΦ [H|H]".
    1 : iLeft. 2: iRight.
    all : iDestruct "H" as (??) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
  Qed.   

  Program Definition recv_new_mono recv1 recv2 P P' :=
    {| pmono_prot_car := iThySum (Recv alice recv1 recv2 P) (Recv bob recv1 recv2 P'); pmono_prot_prop := _|}.
  Next Obligation.
    intros ????. 
    iIntros (????) "#HΦ [H|H]".
    1 : iLeft. 2: iRight.
    all : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (m) "H"); iApply "HΦ"; try iApply ("H2" $! m); done.
  Qed.   

  Definition send_new_sig  (send1 send2 : label) γtoka atokN γtokb btokN γfraca γfracb P P' := 
    @SemSig Σ (send_new_mono send1 send2 γtoka atokN γtokb btokN γfraca γfracb P P') (send1, send2).
  Definition recv_new_sig  (recv1 recv2 : label) P P' := @SemSig Σ (recv_new_mono recv1 recv2 P P') (recv1, recv2).

 Program Definition chan_new_row P P' γtoka atokN γtokb btokN γfraca γfracb send1 send2 recv1 recv2 := 
    SemRow [
        ([recv1],[recv2],recv_new_sig recv1 recv2 P P');
        ([send1],[send2], send_new_sig send1 send2 γtoka atokN γtokb btokN γfraca γfracb P P')] _.
  Next Obligation.
    intros ????????????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

End theories.

Ltac label_not_in_singleton Hdl := 
  apply NoDup_cons_1_1;
  eapply submseteq_NoDup; last exact Hdl;
  solve_submseteq. 
