From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import dhke_common.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.
Import valgroup_notation.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').
  Import valgroup_notation.
  Local Notation θ := (θ (Σ:=Σ) (vg:=vg)).

  (* Verification of DH_KE ≤ C[DH_real] *)
  (*------------------------------------------------------------*)
  
  Lemma DH_KE_C_DH_real (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ):
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗ (* changed to a circ *)
    (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-∘ 𝟙)%T f1 f2 -∗

    BREL DH_KE f1 ≤ C_lazy DH_real f2 <|⊥|> {{ λ v1 v2, 
                                                 ∀ send1 send2 recv1 recv2 : label, let ac := chan_rowL send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                                                  BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                                                    v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                                                    <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont;brel_pures') using G.
    iIntros "Htoka Htokb Ha Hb Hff". 
    unfold DH_KE, C_lazy...
    iModIntro. 
    iIntros (send1 send2 recv1 recv2). 
    set (ac := chan_rowL send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb)...
    unfold DH_real...
    brel_alloctape_l α as "Hα"...
    brel_alloctape_l β as "Hβ"...
    brel_alloc_l la as "Hla"...
    brel_alloc_l lb as "Hlb"...
    rewrite Nat2Z.id.
    
    iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq. 
    iApply brel_couple_TU; [done|]. iFrame. simpl. iIntros (a) "Hα".
    iDestruct "Hβ" as (ms) "(%Hf' & Hβ)". apply map_eq_nil in Hf'. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame "Hβ". simpl. iIntros (b) "Hβ"...
    
    rewrite -Nat2Z.inj_mul...
    brel_alloc_r lcs as "Hlcs"...
        
    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>"...

    (* rewrite /sem_ty_arr /sem_ty_mbang //=. *)
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ gk1 gk2 }-> (Option 𝔾))%T) as "Hgg".
    (* TODO: refactor this goal into a better proof script *)
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=.
      iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor.
      all : iExists _,_,[],[],_;
                              do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                              iSplit; try (iIntros (??) "!# H"; iApply "H");
                              iSplit; first (iPureIntro; (left + right); split; done);
                              iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>";
                              iExists _,_; [iLeft; by iPureIntro | iRight; iPureIntro; repeat (split; first done); by eexists]. }

    
    rewrite /sem_val_typed //=. 
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply fupd_brel.
    iMod (auth_upd ((#la, #a)%V) with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    (* Store resources before induction *)
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.
    
    iApply (brel_na_alloc
              ((β ↪ (n; [b]) ∗ lb ↦ NONEV)
               ∨ (β ↪□ (n; [])
                  ∗ lb ↦□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ (n; [a]) ∗ la ↦ NONEV ∗ lcs ↦ₛ NONEV)
               ∨ (α ↪□ (n; [])
                  ∗ la ↦□ SOMEV #a
                  ∗ lcs ↦ₛ□ SOMEV (vgval (g ^+ (a * b)))))%I
              alphaN).
    iSplitL "Hα Hla Hlcs"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
    
    iDestruct (brel_introduction_mono _ ([([gk1],[gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by do 2 apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].
    
    (* getKey can be called multiple times, why we need induction *)
    (* the token is given away at the first call, so we need to store it in an invariant that holds for all calls to getKey *)
    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures|].
    (* getKeyAlice or getKeyBob *)
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : {
      brel_pures'; [apply Hk2; set_solver|apply Hk1; set_solver|]...
      (* bind the match ... end block and prove (by casing on the invariant) that in either case "a" will become the value a (from the tape or the reference read), then continue only with one branch *)
      (* in other words, prove a spec for sample_or_load *)
      iApply (brel_na_inv _ _ alphaN); first set_solver.
      iFrame "Hinva".
      iIntros "([(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] & Hclose)".
      - brel_load_l...
        iAssert (α ↪N (n; [fin_to_nat a]))%I with "[Hα]" as "Hα".
        { iExists [a]. simpl. iFrame. done. }
        brel_rand_l; iIntros "Halt"...
        brel_store_l...
        iApply (brel_exp_l [AppRCtx _])... 
        brel_load_r...
        brel_store_r...
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iMod (ghost_map_elem_persist with "Hlcs") as "#Hlcs".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
        
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iExists _,_,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
                
        iModIntro. iApply brel_value. iIntros "$ !>"...
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Hb'".
          iDestruct (auth_agree with "[$Hb] [$Hb']") as "<-". 
          iApply brel_value. iIntros "$ !>"...
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH".
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_l...
        brel_load_r...
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft.
        iExists _,_,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>"...
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>"...
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>"...
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH". }
    
    1 : {
      brel_pures'; [apply Hk2; set_solver|apply Hk1; set_solver|].
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply (brel_introduction' [recv1]); [repeat constructor|].
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iLeft.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      { iApply brel_value. iIntros "$ !>"...
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion with "[$]"); [done|done|].
        iApply "IH". }
      iIntros (la' m) "(#Hb'&#Hla')".
      iDestruct (auth_agree with "[$Ha] [$Hb']") as "%Heq".
      inversion Heq as [(Hla&Ha)]. rewrite Ha //=.
      iApply brel_value. iIntros "$ !>"...
      
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> Hlb". brel_pures_l.
        iAssert (β ↪N (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
        { iExists [b]. simpl. iFrame. done. }
        brel_rand_l. iIntros "_"...
        brel_store_l...
        iApply (brel_exp_l [AppRCtx _])...
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
        iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iRight; iFrame "#"|].
        
        iApply (brel_bind' [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        iExists _,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        
        iApply brel_value. iIntros "$ !>"...
        rewrite -expgM. rewrite -ssrnat.multE.
        
        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_r...
        iDestruct ("Hcont" with "Hsome") as "Hkk".
        iApply (brel_exhaustion with "[$]"); [done|done|].
        iApply "IH".
        
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_l...
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        iExists _,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        
        iApply brel_value. iIntros "$ !>"...
        rewrite -expgM. rewrite -ssrnat.multE.
        
        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlcs) | (#Hα & #Hla & #Hlcs)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_r...
        iDestruct ("Hcont" with "Hsome") as "Hkk". 
        apply Nat2Z.inj in Ha as ->.
        iApply (brel_exhaustion with "[$]"); [done|done|].
        iApply "IH". }
  Qed.

End handlee_verification.

