From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import def_dhke.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement sem_def. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.
From clutch.prob_eff_lang.probblaze.examples.DH_KE Require Import dhke_channel_lazy_authchan.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').
  Import valgroup_notation.
  Local Notation gkleakl := (gkleakl (Σ:=Σ) (vg:=vg)).

  Lemma DH_SIM_F_KE_C_DH_rand (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb L :
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-∘ 𝟙)%T f1 f2 -∗
    BREL DH_SIM (F_KE_lazy_alice f1) ≤ C_lazy DH_rand f2 <|⊥|> 
      {{ λ v1 v2, ∀ send1 send2 recv1 recv2 : label, let ac := chan_row send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                   BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                     v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                     <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont; brel_pures') using G inG0 inG1 inG2.
    iIntros "Htoka Htokb Ha Hb Hff". 
    unfold DH_SIM, F_KE_lazy_alice, C_lazy. 
    brel_pures'. iModIntro. 
    iIntros (send1 send2 recv1 recv2). set (ac := chan_row send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
    brel_pures'.
    
    iApply brel_alloctape_l. iIntros (α) "!> Hα"... 
    iApply brel_alloctape_l. iIntros (β) "!> Hβ"... 
    iApply brel_alloc_l. iIntros (la) "!> Hla".
    iApply brel_alloc_l. iIntros (lb) "!> Hlb".
    
    unfold DH_rand... 
    
    iApply brel_effect_l. iIntros (leaksend) "!> Hleaksend !>"... 
    iApply brel_effect_l. iIntros (leakrecv) "!> Hleakrecv !>"... 
    iApply brel_alloctape_l. iIntros (γ) "!> Hγ"... 
    iApply brel_alloc_l. iIntros (lc) "!> Hlc"... 
    
    iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame. simpl. iIntros (a) "Hα".
    iDestruct "Hβ" as (ms) "(%Hf' & Hβ)". apply map_eq_nil in Hf'. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame "Hβ". simpl. iIntros (b) "Hβ".
    iDestruct "Hγ" as (ns) "(%Hf & Hγ)". apply map_eq_nil in Hf. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame "Hγ". simpl. iIntros (c) "Hγ"...
    iApply brel_alloc_r. iIntros (lcs) "Hlcs"... 
    
    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>"...
    
    iApply fupd_brel.
    iMod (auth_upd (vgval (g ^+ a)%g) with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.
    
    iApply (brel_na_alloc
              ((β ↪ (n; [b]) ∗ lb ↦ NONEV)
               ∨ (β ↪□ (n; [])
                  ∗ lb ↦□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ (n; [a]) ∗ la ↦ NONEV ∗ γ ↪ (n; [c]) ∗ lc ↦ NONEV ∗ lcs ↦ₛ NONEV)
               ∨ (α ↪□ (n; [])
                  ∗ la ↦□ SOMEV #a 
                  ∗ γ ↪□ (n; [])
                  ∗ lc ↦□ SOMEV (vgval (g ^+ c)%g)
                  ∗ lcs ↦ₛ□ SOMEV (vgval (g ^+ c)%g)))%I
              alphaN).
    iSplitL "Hα Hla Hγ Hlc Hlcs"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    (* unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff". *)
    set (θ := gkleakl leaksend leakrecv gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    (* iDestruct "Hff" as "#Hff". *)
    unfold sem_ty_arr. simpl.
    (* iDestruct "Hff" as "#Hff".  *)
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
        iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_l with "Hleakrecv").
    iApply (brel_add_label_l with "Hleaksend").
    iApply (brel_add_label_r with "Hgk2").
    
    iDestruct (brel_introduction_mono _ ([([leaksend;leakrecv;gk1],[gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by do 2 apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [set_solver|done|].
    
    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures'|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : { 
      brel_pures'; [apply Hk2; set_solver| apply Hk1;set_solver|]...
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hα & Hla & Hγ & Hlc & Hlcs) | #(Hα & Hla & Hγ & Hlc & Hlcs)] & Hclose)".
      - iApply (brel_load_l _ _ _ [HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _; AppRCtx _; CaseCtx _ _] with "[$]"). iIntros "!> Hlc"... 
        iAssert (γ ↪N (n; [fin_to_nat c]))%I with "[Hγ]" as "Hγ".
        { iExists [c]. simpl. iFrame. done. }
        brel_rand_l. iIntros "_"...
        iApply (brel_exp_l [HandleCtx _ _ _ _ _; HandleCtx _ _ _ _ _; AppRCtx _;AppRCtx _])...
        brel_store_l.
        brel_load_r; brel_pures_r.
        brel_store_r... { set_solver. }
        brel_load_l...
        iAssert (α ↪N (n; [fin_to_nat a]))%I with "[Hα]" as "Hα".
        { iExists [a]. simpl. iFrame. done. }
        brel_rand_l. iIntros "_"...
        brel_store_l...
        iApply (brel_exp_l [HandleCtx _ _ _ _ _; AppRCtx _])... 
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iMod (ghost_map_elem_persist with "Hlc") as "#Hlc".
        iDestruct "Hγ" as (ns) "(%Hf & Hγ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hγ") as "#Hγ".
        iMod (ghost_map_elem_persist with "Hlcs") as "#Hlcs".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        iApply brel_learn. iIntros ((Hdl&Hdr)) "_".

        (* Send (gA, bob) *)
        iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
        iExists _, _, [HandleCtx _ _ _ _ _; AppRCtx _], [AppRCtx _ ], _. 
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact Hdl.
          solve_submseteq. }
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. simpl.
        iExists ((g ^+ a)%g),  ((g ^+ a)%g).
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        
        brel_pures'. 
        { apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact Hdl.
          solve_submseteq. }

        (* Recv bob (either none or some) *)
        iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
        iExists _, _, [AppRCtx _], [AppRCtx _], _. 
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact Hdl.
          solve_submseteq. }
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + brel_pures'.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          brel_pures'.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_l.
        brel_load_r...  { set_solver. }
        brel_load_l...
        iApply brel_learn. iIntros ((Hdl&Hdr)) "_".        

        (* Send (gA, bob) *)
        iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
        iExists _, _, [HandleCtx _ _ _ _ _;AppRCtx _], [AppRCtx _], _. 
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact Hdl.
          unfold labels_r. 
          solve_submseteq. }
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft.
        iExists _, _.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. 
        brel_pures'. 
        { apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact Hdl.
          solve_submseteq. }
        
        (* Recv bob (either none or some) *)
        iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
        iExists _, _, [AppRCtx _], [AppRCtx _], _. 
        iSplit; first done.
        iSplit.
        { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
          apply NoDup_cons_1_1.
          eapply submseteq_NoDup; last exact Hdl.
          solve_submseteq. }
        iSplit; first done; iSplit; [iPureIntro; apply _|].
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"]. 
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + brel_pures'.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          brel_pures'.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"]. }
    
    1 : {
      iApply brel_learn. iIntros ((Hdl&Hdr)) "_". 
      brel_pures'; [apply Hk2; set_solver|split; [apply neutral_ectx;set_solver|simpl]|].
      { apply NoDup_cons_1_1.
        eapply submseteq_NoDup; last exact Hdl.
        solve_submseteq. }
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply (brel_introduction' [recv1] [recv2]); [repeat constructor|].
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iLeft.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      - iApply brel_value. iIntros "$ !>".
        brel_pures'.
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
      - iIntros (m) "Ha'".
        iDestruct (auth_agree with "[$Ha] [$Ha']") as "<-".
        iApply brel_value. iIntros "$ !>".
        brel_pures';[set_solver|]...
        
        iApply (brel_na_inv _ _ betaN ); [set_solver|].
        iFrame "Hinvb". 
        iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)". 
        + iApply (brel_load_l _ _ _ [HandleCtx _ _ _ _ _; AppRCtx _; CaseCtx _ _] with "[$]").
          iIntros "!> Hlb"... 
          iAssert (β ↪N (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
          { iExists [b]. simpl. iFrame. done. }
          brel_rand_l. iIntros "_"... 
          brel_store_l...
          iApply (brel_exp_l [HandleCtx _ _ _ _ _; AppRCtx _])...
          
          iApply fupd_brel.
          iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
          iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
          iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
          iModIntro.
          iApply brel_na_close. iFrame.
          iSplitL; [iRight; iFrame "#"|].
          
          iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
          iExists _, _, [HandleCtx _ _ _ _ _; AppRCtx _], [AppRCtx _], _. 
          iSplit; first done.
          iSplit.
          { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
            apply NoDup_cons_1_1.
            eapply submseteq_NoDup; last exact Hdl.
            solve_submseteq. }
          iSplit; first done; iSplit; [iPureIntro; apply _|].
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight.
          iExists _,_.
          iSplitL.
          { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
            - iModIntro. iLeft.
              iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
              by iModIntro. 
            - iModIntro. iRight. iFrame "#".
              iApply "Hclose". iNext.
              by iRight. }
          iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
          iModIntro...
          
          iApply (brel_na_inv _ _ alphaN ); [set_solver|].
          iFrame "Hinva". 
          iIntros "(>[(Hα & Hla & Hγ & Hlc & Hlcs) | #(Hα & Hla & Hγ & Hlc & Hlcs)] & Hclose)".
          
          * iApply (brel_load_l _ _ _ [HandleCtx _ _ _ _ _; HandleCtx _ _ _ _ _; CaseCtx _ _] with "[$]"). iIntros "!> Hlc"... 
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].

            iDestruct ("Hcont" with "Hnone") as "Hkk".
            iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
            
          * iApply (brel_load_l _ _ _ [HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _; CaseCtx _ _] with "[$]"). iIntros "!> _"... 
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
            
            iDestruct ("Hcont" with "Hsome") as "Hkk".
            iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
            
        + iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
          brel_load_l...
                    
          iApply (brel_introduction' [send1] [send2]); [repeat constructor|].
          iExists _, _, [HandleCtx _ _ _ _ _; AppRCtx _], [AppRCtx _], _. 
          iSplit; first done.
          iSplit.
          { iPureIntro. apply NeutralEctx_ectx_labels_singleton. simpl.
            apply NoDup_cons_1_1.
            eapply submseteq_NoDup; last exact Hdl.
            solve_submseteq. }
          iSplit; first done; iSplit; [iPureIntro; apply _|].
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight.
          iExists _,_.
          iSplitL.
          { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
            - iModIntro. iLeft.
              iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
              by iModIntro. 
            - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
          iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
          iModIntro...
          
          iApply (brel_na_inv _ _ alphaN ); [set_solver|].
          iFrame "Hinva". 
          iIntros "(>[(Hα & Hla & Hγ & Hlc & Hlcs) | #(Hα & Hla & Hγ & Hlc & Hlcs)] & Hclose)".
          
          * iApply (brel_load_l _ _ _ [HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _; CaseCtx _ _] with "[$]"). iIntros "!> Hlc"...
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
            
            iDestruct ("Hcont" with "Hnone") as "Hkk".
            iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"].
            
          * iApply (brel_load_l _ _ _ [HandleCtx _ _ _ _ _;HandleCtx _ _ _ _ _; CaseCtx _ _] with "[$]"). iIntros "!> _"...
            brel_load_r...
            iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
            
            iDestruct ("Hcont" with "Hsome") as "Hkk".
            iApply (brel_exhaustion _ _ [_;_;_] [_] with "[$]"); [set_solver|done|iApply "IH"]. }
      Qed.

End handlee_verification.

