From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import def_dhke.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement sem_def. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (channel1 channel2 : label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').

  (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  Program Definition GetKey gk1 gk2: iThy Σ :=
    λ e1 e2, (λne Q,
                ((⌜ e1 = do: gk1 (InjLV #()%V) ⌝%E ∗
                  ⌜ e2 = do: gk2 (InjLV #()%V) ⌝%E) ∨
                   (⌜ e1 = do: gk1 (InjRV #()%V) ⌝%E ∗
                    ⌜ e2 = do: gk2 (InjRV #()%V) ⌝%E)) ∗
                □ (Q NONEV NONEV ∗ ∀ key : vgG, Q (SOMEV key) (SOMEV key) )
             )%I.
  Next Obligation. solve_proper. Qed.

  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  Program Definition SendBobImpl c1 c2 γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m': val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                              (⌜ e1 = do: c1 (SendV (m, alice)) ⌝%E ∗
                               ⌜ e2 = do: c2 (SendV (m', alice)) ⌝%E)  ∗ 
                              □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImplL c1 c2 γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV alice) ⌝%E ∗
                □ (Q NONEV NONEV ∗ (∀ (l : loc) (m : nat), (own γauth (to_dfrac_agree DfracDiscarded (#l, #m)%V) ∗ l ↦□ SOMEV #m) -∗ Q (SOMEV (vgval (g ^+ m)%g)) (SOMEV (vgval (g ^+ m)%g))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImplR c1 c2 γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV alice) ⌝%E ∗
                □ (Q NONEV NONEV ∗ (∀ (l : loc) (m : nat), (own γauth (to_dfrac_agree DfracDiscarded (#l, #m)%V) ∗ l ↦ₛ□ SOMEV #m) -∗ Q (SOMEV (vgval (g ^+ m)%g)) (SOMEV (vgval (g ^+ m)%g))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImpl c1 c2 γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV alice) ⌝%E ∗
                □ (Q NONEV NONEV ∗ (∀ m, (own γauth (to_dfrac_agree DfracDiscarded m)) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImplL c1 c2 γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ (l : loc) (m m' : nat), ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (#l, #m)%V)
                                                                                                            ∗ l ↦□ SOMEV #m ∗ ⌜(g ^+ m)%g = (g ^+ m')%g⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                                           (⌜ e1 = do: c1 (SendV (vgval (g ^+ m)%g, bob)) ⌝%E ∗
                                            ⌜ e2 = do: c2 (SendV (vgval (g ^+ m')%g, bob)) ⌝%E)  ∗ 
                                           □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  (* Changes the pointer and which message that is stored -- could probably be generalized to any persistent knowledge, but you would need to change the definition of the theories, to define SendAliceImplL and RecvAliceImplL at the same time, and then quantify over the persistent predicate *)
  Program Definition SendAliceImplR c1 c2 γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ (l : loc) (m m' : nat), ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (#l, #m)%V)
                                                                                                            ∗ l ↦ₛ□ SOMEV #m ∗ ⌜(g ^+ m)%g = (g ^+ m')%g⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                                           (⌜ e1 = do: c1 (SendV (vgval (g ^+ m)%g, bob)) ⌝%E ∗
                                            ⌜ e2 = do: c2 (SendV (vgval (g ^+ m')%g, bob)) ⌝%E)  ∗ 
                                           □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImpl c1 c2 γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ (m m' : val), ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                                 (⌜ e1 = do: c1 (SendV (m, bob)) ⌝%E ∗
                                  ⌜ e2 = do: c2 (SendV (m', bob)) ⌝%E)  ∗ 
                                 □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.


  Program Definition RecvBobImpl c1 c2 γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV bob) ⌝%E ∗
                □ (Q NONEV NONEV ∗ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed. 

  (* Tactic Notation "foldkont" ident(k) open_constr(kctx) :=
    match goal with
    | |- context[KontV ?kont] =>
        unify kont kctx ; set (k := KontV kont)
    end.

  Tactic Notation "foldkont" ident(k) := foldkont k _.

  Tactic Notation "foldkont" := let k := fresh "kont" in foldkont k.*)

  (* semantic types *)
  (*------------------------------------------------------------*)

  Definition sem_ty_group : sem_ty Σ := (λ v1 v2, ∃ g : vgG, ⌜ v1 = g ⌝ ∗ ⌜ v2 = g ⌝)%I.
  Notation "'𝔾'" := sem_ty_group. 

  Program Definition gkmono (gk1 gk2 : label) :=  {| pmono_prot_car := GetKey gk1 gk2; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. iIntros (????) "#HΦ ([(->&->)|(->&->)] & #(H1&H2))"; repeat iSplit; [by iLeft| |by iRight|]; iModIntro; iSplitL; try iIntros (?); by iApply "HΦ".
  Qed. 

  Definition gk (gk1 gk2 : label) := @SemSig Σ (gkmono gk1 gk2) (gk1,gk2).
  
  Program Definition θ gk1 gk2 := SemRow [([gk1],[gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  
  Program Definition gkleakl leak gk1 gk2 := SemRow [([leak;gk1],[gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition gkleakr leak gk1 gk2 := SemRow [([gk1],[leak;gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  
  Program Definition authchan_mono c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := 
    {| pmono_prot_car := (iThySum (iThySum (SendAliceImpl c1 c2 γtoka γfraca γautha atokN) (RecvBobImpl c1 c2 γauthb))
                            (iThySum (SendBobImpl c1 c2 γtokb γfracb γauthb btokN) (RecvAliceImpl c1 c2 γautha))); pmono_prot_prop := _|}.
  Next Obligation.
    intros ??????????. 
    iIntros (????) "#HΦ [[H| H]|[H|H]]".
    1 : iLeft;iLeft. 2: iLeft; iRight.
    3 : iRight;iLeft. 4: iRight;iRight.
    1,3 : iDestruct "H" as (??) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
    all : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (m) "#H"); iApply "HΦ"; try iApply ("H2" $! m); done.
  Qed.   

  Program Definition authchan_monoL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := 
    {| pmono_prot_car := (iThySum (iThySum (SendAliceImplL c1 c2 γtoka γfraca γautha atokN) (RecvBobImpl c1 c2 γauthb))
                            (iThySum (SendBobImpl c1 c2 γtokb γfracb γauthb btokN) (RecvAliceImplL c1 c2 γautha))); pmono_prot_prop := _|}.
  Next Obligation.
    intros ??????????. 
    iIntros (????) "#HΦ [[H| H]|[H|H]]".
    1 : iLeft;iLeft. 2: iLeft; iRight.
    3 : iRight;iLeft. 4: iRight;iRight.
    1 : iDestruct "H" as (???) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
    2 : iDestruct "H" as (??) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
    1 : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (m) "#H"); iApply "HΦ"; try iApply ("H2" $! m); done.
    1 : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (l m) "#H"); iApply "HΦ"; try iApply ("H2" $! l m); done.
  Qed.   

  Program Definition authchan_monoR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := 
    {| pmono_prot_car := (iThySum (iThySum (SendAliceImplR c1 c2 γtoka γfraca γautha atokN) (RecvBobImpl c1 c2 γauthb))
                            (iThySum (SendBobImpl c1 c2 γtokb γfracb γauthb btokN) (RecvAliceImplR c1 c2 γautha))); pmono_prot_prop := _|}.
  Next Obligation.
    intros ??????????. 
    iIntros (????) "#HΦ [[H| H]|[H|H]]".
    1 : iLeft;iLeft. 2: iLeft; iRight.
    3 : iRight;iLeft. 4: iRight;iRight.
    1 : iDestruct "H" as (???) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
    2 : iDestruct "H" as (??) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
    1 : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (m) "#H"); iApply "HΦ"; try iApply ("H2" $! m); done.
    1 : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (l m) "#H"); iApply "HΦ"; try iApply ("H2" $! l m); done.
  Qed. 

  Definition authchan c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := @SemSig Σ (authchan_mono c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb) (channel1, channel2).
  Program Definition authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := SemRow [([c1],[c2], authchan c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb)] _.
  Next Obligation.
    intros ??????????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Definition authchanL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := @SemSig Σ (authchan_monoL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb) (channel1, channel2).
  Program Definition authchan_rowL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := SemRow [([c1],[c2], authchanL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb)] _.
  Next Obligation.
    intros ??????????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Definition authchanR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := @SemSig Σ (authchan_monoR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb) (channel1, channel2).
  Program Definition authchan_rowR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := SemRow [([c1],[c2], authchanR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb)] _.
  Next Obligation.
    intros ??????????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  


  (* Verification of F_AUTH ≤ F_AUTH *)
  (*------------------------------------------------------------*)
  
  Lemma F_AUTH_F_AUTHL (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ c1 c2 : label, let ac := authchan_rowL c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 ((λ: "m", do: c1 (Send "m")), (λ: "m", do: c1 (Recv "m")))%V ≤
                                              v2 ((λ: "m", do: c2 (Send "m")), (λ: "m", do: c2 (Recv "m")))%V 
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2, 
                                            (∀ᵣ θₗ, (((⊤ × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ⊤)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont) using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))".
    (* iIntros (lc dsend1 dsend2) "#Hsend". 
       brel_pures'. iModIntro.
       iIntros (drecv1 drecv2) "#Hrecv".  *)
    brel_pures'.
    
    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ (la : loc) (a : nat) , l1 ↦□ SOMEV (vgval (g ^+ a)%g) ∗ l1' ↦ₛ□ SOMEV (vgval (g ^+ a)%g) ∗ token γtoka
                                           ∗ own γfraca DfracDiscarded
                                           ∗ own γautha (to_dfrac_agree DfracDiscarded (#la, #a)%V)
                                           ∗ la ↦□ SOMEV #a)
              ) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply brel_effect_l. iIntros (chan1) "!> Hchan1".
    iApply brel_effect_r. iModIntro. iIntros (chan2) "Hchan2 !>".
    iSpecialize ("Hff" $! chan1 chan2).
    
    brel_pures'.
    
    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hchan1").
    iApply (brel_add_label_r with "Hchan2").
    
    iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
    { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'. apply submseteq_skip. rewrite iLblSig_to_iLblThy_app. 
      by apply submseteq_inserts_l. }
    iLöb as "IH".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [[(%&%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]| [(%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]] #Hkont".
    1 : {
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfraca") as "#Hfraca".
        iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & #Hla & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
          by apply submseteq_inserts_r. }
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
        iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists _, _; iFrame "#"; iFrame|].
        
        iAssert (sem_val_typed (_, bob)%V (_,bob)%V (⊤ × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done). 
          iExists _,_. iLeft. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1". 
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        
        (* iApply brel_introduction'. { apply list_elem_of_further. apply list_elem_of_here. }
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iLeft. iRight.
           iExists _.
           do 2 (iSplit; try (iPureIntro; done)).
           iModIntro.
           iApply brel_value. iIntros "$ !>".
           brel_pures. *)
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htoka"; [iNext; iRight; iExists _,_; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hl1]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IH". }
    
    1 : { brel_pures; [apply Hk1|apply Hk2|]; try set_solver...
          iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
            by apply submseteq_inserts_r. }
          
          iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
          { iModIntro. iExists _,_. iLeft. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
          iDestruct ("Hrecv" with "Hbob") as "Hrecv1". 
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.
          (* iIntros (??) "!# (->&->)".
             brel_pures'.
             
             iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
             iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
             iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
             iRight. iRight. do 2 (iSplit; try (iPureIntro; done)).
             iModIntro.
             iSplit; last first. *)
          
          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
          + iApply (brel_na_inv _ _ betaN); [set_solver|].
            iFrame "Hinvb". 
            iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "[$]"). iIntros "!> _".
              iApply (brel_load_r with "Hl2s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "Hauthb") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : {
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
          by apply submseteq_inserts_r. }
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].
        
        iAssert (sem_val_typed (m, alice)%V (m,alice)%V (⊤ × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done). 
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1". 
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        
        (* iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here| ].
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iLeft. iLeft.
           iExists _.
           do 2 (iSplit; try (iPureIntro; done)).
           iModIntro.
           iApply brel_value. iIntros "$ !>".
           brel_pures. *)
        
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
            by apply submseteq_inserts_r. }
          
          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1". 
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.
          
          
          (* iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
             iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
             iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
             iRight. iLeft. do 2 (iSplit; try (iPureIntro; done)).
             iModIntro.
             iSplit; last first. *)
          
          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#". 
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "Hl1"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "[$Hautha $Hla]") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". } 
  Qed.

  Lemma F_AUTH_F_AUTHR (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ c1 c2 : label, let ac := authchan_rowR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 ((λ: "m", do: c1 (Send "m")), (λ: "m", do: c1 (Recv "m")))%V ≤
                                              v2 ((λ: "m", do: c2 (Send "m")), (λ: "m", do: c2 (Recv "m")))%V 
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2, 
                                            (∀ᵣ θₗ, (((⊤ × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ⊤)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont) using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))".
    (* iIntros (lc dsend1 dsend2) "#Hsend". 
       brel_pures'. iModIntro.
       iIntros (drecv1 drecv2) "#Hrecv".  *)
    brel_pures'.
    
    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ (la : loc) (a : nat) , l1 ↦□ SOMEV (vgval (g ^+ a)%g) ∗ l1' ↦ₛ□ SOMEV (vgval (g ^+ a)%g) ∗ token γtoka
                                           ∗ own γfraca DfracDiscarded
                                           ∗ own γautha (to_dfrac_agree DfracDiscarded (#la, #a)%V)
                                           ∗ la ↦ₛ□ SOMEV #a)
              ) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply brel_effect_l. iIntros (chan1) "!> Hchan1".
    iApply brel_effect_r. iModIntro. iIntros (chan2) "Hchan2 !>".
    iSpecialize ("Hff" $! chan1 chan2).
    
    brel_pures'.
    
    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hchan1").
    iApply (brel_add_label_r with "Hchan2").
    
    iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
    { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'. apply submseteq_skip. rewrite iLblSig_to_iLblThy_app. 
      by apply submseteq_inserts_l. }
    iLöb as "IH".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [[(%&%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]| [(%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]] #Hkont".
    1 : {
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfraca") as "#Hfraca".
        iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & #Hla & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
          by apply submseteq_inserts_r. }
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
        iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists _, _; iFrame "#"; iFrame|].
        
        iAssert (sem_val_typed (_, bob)%V (_,bob)%V (⊤ × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done). 
          iExists _,_. iLeft. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1". 
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        
        (* iApply brel_introduction'. { apply list_elem_of_further. apply list_elem_of_here. }
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iLeft. iRight.
           iExists _.
           do 2 (iSplit; try (iPureIntro; done)).
           iModIntro.
           iApply brel_value. iIntros "$ !>".
           brel_pures. *)
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htoka"; [iNext; iRight; iExists _,_; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$Hl1]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$Hl1s]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IH". }
    
    1 : { brel_pures; [apply Hk1|apply Hk2|]; try set_solver...
          iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
            by apply submseteq_inserts_r. }
          
          iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
          { iModIntro. iExists _,_. iLeft. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
          iDestruct ("Hrecv" with "Hbob") as "Hrecv1". 
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.
          (* iIntros (??) "!# (->&->)".
             brel_pures'.
             
             iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
             iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
             iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
             iRight. iRight. do 2 (iSplit; try (iPureIntro; done)).
             iModIntro.
             iSplit; last first. *)
          
          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
          + iApply (brel_na_inv _ _ betaN); [set_solver|].
            iFrame "Hinvb". 
            iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "[$]"). iIntros "!> _".
              iApply (brel_load_r with "Hl2s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "Hauthb") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : {
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
          by apply submseteq_inserts_r. }
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].
        
        iAssert (sem_val_typed (m, alice)%V (m,alice)%V (⊤ × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done). 
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1". 
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        
        (* iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here| ].
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iLeft. iLeft.
           iExists _.
           do 2 (iSplit; try (iPureIntro; done)).
           iModIntro.
           iApply brel_value. iIntros "$ !>".
           brel_pures. *)
        
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
            by apply submseteq_inserts_r. }
          
          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1". 
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.
          
          
          (* iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
             iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
             iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
             iRight. iLeft. do 2 (iSplit; try (iPureIntro; done)).
             iModIntro.
             iSplit; last first. *)
          
          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#". 
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%la & %a & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha & #Hla)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "Hl1"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "[$Hautha $Hla]") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". } 
  Qed.

  Lemma F_AUTH_F_AUTH (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ c1 c2 : label, let ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 ((λ: "m", do: c1 (Send "m")), (λ: "m", do: c1 (Recv "m")))%V ≤
                                              v2 ((λ: "m", do: c2 (Send "m")), (λ: "m", do: c2 (Recv "m")))%V 
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2, 
                                            (∀ᵣ θₗ, (((⊤ × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ⊤)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont) using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))".
    (* iIntros (lc dsend1 dsend2) "#Hsend". 
       brel_pures'. iModIntro.
       iIntros (drecv1 drecv2) "#Hrecv".  *)
    brel_pures'.

    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ gA , l1 ↦□ SOMEV gA∗ l1' ↦ₛ□ SOMEV gA ∗ token γtoka
                         ∗ own γfraca DfracDiscarded
                         ∗ own γautha (to_dfrac_agree DfracDiscarded gA))) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".

    iApply brel_effect_l. iIntros (chan1) "!> Hchan1".
    iApply brel_effect_r. iModIntro. iIntros (chan2) "Hchan2 !>".
    iSpecialize ("Hff" $! chan1 chan2).

    brel_pures'.

    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hchan1").
    iApply (brel_add_label_r with "Hchan2").
    
    iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
    { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'. apply submseteq_skip. rewrite iLblSig_to_iLblThy_app. 
      by apply submseteq_inserts_l. }
    iLöb as "IH".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [[(%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]| [(%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]] #Hkont".
    1 : {
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%gA & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfraca") as "#Hfraca".
        iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
          by apply submseteq_inserts_r. }
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
        iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

        iAssert (sem_val_typed (m, bob)%V (m,bob)%V (⊤ × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done). 
          iExists _,_. iLeft. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1". 
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        
        (* iApply brel_introduction'. { apply list_elem_of_further. apply list_elem_of_here. }
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iLeft. iRight.
           iExists _.
           do 2 (iSplit; try (iPureIntro; done)).
           iModIntro.
           iApply brel_value. iIntros "$ !>".
           brel_pures. *)
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htoka"; [iNext; iRight; iExists gA; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IH". }
    
    1 : { brel_pures; [apply Hk1|apply Hk2|]; try set_solver...
          iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
            by apply submseteq_inserts_r. }
          
          iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
          { iModIntro. iExists _,_. iLeft. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
          iDestruct ("Hrecv" with "Hbob") as "Hrecv1". 
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.
          (* iIntros (??) "!# (->&->)".
             brel_pures'.
             
             iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
             iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
             iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
             iRight. iRight. do 2 (iSplit; try (iPureIntro; done)).
             iModIntro.
             iSplit; last first. *)
          
          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
          + iApply (brel_na_inv _ _ betaN); [set_solver|].
            iFrame "Hinvb". 
            iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "[$]"). iIntros "!> _".
              iApply (brel_load_r with "Hl2s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "Hauthb") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : {
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
          by apply submseteq_inserts_r. }

        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

        iAssert (sem_val_typed (m, alice)%V (m,alice)%V (⊤ × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done). 
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1". 
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        
        (* iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here| ].
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iLeft. iLeft.
           iExists _.
           do 2 (iSplit; try (iPureIntro; done)).
           iModIntro.
           iApply brel_value. iIntros "$ !>".
           brel_pures. *)
        
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. apply submseteq_cons. rewrite iLblSig_to_iLblThy_app. 
            by apply submseteq_inserts_r. }
          
          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1". 
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.


          (* iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
             iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
             iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
             iRight. iLeft. do 2 (iSplit; try (iPureIntro; done)).
             iModIntro.
             iSplit; last first. *)
          
          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#". 
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%gA & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "[$]"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "Hautha") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". } 
  Qed. 

End handlee_verification.

