From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import def_dhke.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement sem_def. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.
From clutch.prob_eff_lang.probblaze.examples.DH_KE Require Import dhke_channel_lazy_authchan.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (channel1 channel2 : label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').
  Import valgroup_notation.

  Local Notation authchan_row  := (authchan_row channel1 channel2).
  Local Notation authchan_rowL := (authchan_rowL channel1 channel2).
  Local Notation authchan_rowR := (authchan_rowR channel1 channel2).
  Local Notation θ := (θ (Σ:=Σ) (vg:=vg)).


  Lemma C_DH_real_DH_KE (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb L :
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-∘ 𝟙)%T f1 f2 -∗

    BREL C_lazy DH_real f1 ≤ DH_KE f2 <|⊥|> {{ λ v1 v2, 
                                                 ∀ c1 c2 : label, let ac := authchan_rowR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                                                  BREL v1 ((λ: "m", do: c1 (Send "m")), (λ: "m", do: c1 (Recv "m")))%V ≤
                                                                    v2 ((λ: "m", do: c2 (Send "m")), (λ: "m", do: c2 (Recv "m")))%V 
                                                                    <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof using G.
    iIntros "Htoka Htokb Ha Hb Hff". 
    unfold DH_KE, C_lazy. 
    brel_pures'. iModIntro. 
    iIntros (c1 c2). set (ac := authchan_rowR c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
    brel_pures'.
    iApply brel_alloctape_r. iIntros (α) "Hα". brel_pures_r.
    
    iApply brel_alloctape_r. iIntros (β) "Hβ". brel_pures_r.
    
    iApply brel_alloc_r. iIntros (la) "Hla". brel_pures_r.
    
    iApply brel_alloc_r. iIntros (lb) "Hlb". brel_pures_r. 
    brel_pures'. unfold DH_real. brel_pures'.
    iApply brel_couple_UT. 1: auto. iFrame "Hα". simpl. iSplit => //. iIntros (a ?) "!> Hα".
    iApply brel_couple_UT. 1: auto. iFrame "Hβ". simpl. iSplit => //. iIntros (b ?) "!> Hβ".
    
    brel_pures_l. rewrite -Nat2Z.inj_mul.
    do 3 brel_exp_l.
    brel_pures_l.
    
    iApply brel_alloc_l. iIntros (lc) "!> Hlc". brel_pures_l.
    
    iApply fupd_brel.
    iMod (auth_upd (#la, #a)%V with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.    
    iApply (brel_na_alloc
              ((β ↪ₛN (n; [b]) ∗ lb ↦ₛ NONEV)
               ∨ (β ↪ₛ□ (n; [])
                  ∗ lb ↦ₛ□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ₛN (n; [a]) ∗ la ↦ₛ NONEV ∗ lc ↦ NONEV)
               ∨ (α ↪ₛ□ (n; [])
                  ∗ la ↦ₛ□ SOMEV #a 
                  ∗ lc ↦□ SOMEV (vgval (g ^+ (a * b))%g)))%I
              alphaN).
    iSplitL "Hα Hla Hlc"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>".
    brel_pures'.
    (* unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff". *)
    set (θ := θ gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    (* iDestruct "Hff" as "#Hff". *)
    unfold sem_ty_arr. simpl.
    (* iDestruct "Hff" as "#Hff".  *)
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
        iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
    
    iDestruct (brel_introduction_mono _ ([([gk1],[gk2],GetKey gk1 gk2)] ++  (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].
    
    iLöb as "IH".
    
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : {
      brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|].
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "([(>Hα & >Hla & >Hlc) | (#>Hα & #>Hla & #>Hlc)] & Hclose)".
      - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "Hla").
        iIntros "Hla". brel_pures_r.
        (* iAssert (α ↪ₛN (n; [a]))%I with "[Hα]" as "Hα".
            { iExists [a]. simpl. iFrame. done. } *)
        iApply (brel_rand_r _ [AppRCtx _; AppRCtx _] with "Hα").
        iIntros "Hα _". brel_pures_r.
        iApply (brel_store_r _ _ _ _[AppRCtx _; AppRCtx _] with "Hla").
        iIntros "Hla".
        brel_pures_r. 
        iApply (brel_exp_r [AppRCtx _]). brel_pures_r.

        iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "Hlc"). iIntros "!> Hlc".
        brel_pures_l.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "Hlc"). iIntros "!> Hlc". brel_pures_l.
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iMod (ghost_map_elem_persist with "Hlc") as "#Hlc".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply brel_introduction'.
        { apply elem_of_cons. right. apply list_elem_of_here. }
        
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft. 
        iExists _,_,_.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro.
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        
        (* Recv bob (either none or some) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply brel_introduction'.
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures. brel_exp_r.
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_r with "Hla"). iIntros "_". brel_pures.
        brel_exp_r. brel_pures.

        iApply (brel_load_l with "Hlc"). iIntros "!> _". brel_pures_l.
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply brel_introduction'.
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft.
        iExists _,_,_.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply brel_introduction'.
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures. brel_exp_r. brel_pures.
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH". }
    
    1 : {
      brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|].
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply brel_introduction'.
      { apply elem_of_cons. right. apply list_elem_of_here. }
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iRight. iRight.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      { iApply brel_value. iIntros "$ !>".
        brel_pures.
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
      iIntros (la' m) "(#Hb'&#Hla')".
      iDestruct (auth_agree with "[$Ha] [$Hb']") as "%Heq".
      inversion Heq as [(Heq1&Heq2)]. subst. rewrite Heq2.
      iApply brel_value. iIntros "$ !>".
      brel_pures.
      
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)".
      - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "Hlb". brel_pures_r.
        (* iAssert (β ↪ₛN (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
            { iExists _. simpl. iFrame. done. } *)
        iApply (brel_rand_r _ [AppRCtx _; AppRCtx _] with "[$]").
        iIntros "Hβ _". brel_pures_r.
        iApply (brel_store_r _ _ _ _[AppRCtx _; AppRCtx _] with "Hlb").
        iIntros "Hlb".
        brel_pures_r. 
        iApply (brel_exp_r [AppRCtx _]). brel_pures_r.
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
        iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        (* Send (gB, alice) *)
        iApply (brel_bind' [_] [_]); [by iApply traversable_to_iThy|].
        iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. iLeft. 
        iExists _,_.
        iSplitL.
        { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        rewrite -expgM. rewrite -ssrnat.multE.
        rewrite -Nat.mul_comm.

        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlc) | (#Hα & #Hla & #Hlc)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l with "Hlc"). iIntros "!> _". brel_pures'.
        iDestruct ("Hcont" with "Hsome") as "Hkk". 
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH".
        
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_r with "Hlb"). iIntros "_". brel_pures.
        brel_exp_r. brel_pures.
        
        (* Send (gB, alice) *)
        iApply (brel_bind' [AppRCtx _] [AppRCtx _]); [by iApply traversable_to_iThy|].
        iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. iLeft.
        iExists _,_.
        iSplitL.
        { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. 
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        rewrite -expgM. rewrite -ssrnat.multE.

        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlc) | (#Hα & #Hla & #Hlc)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l with "Hlc"). iIntros "!> _". brel_pures'.
        iDestruct ("Hcont" with "Hsome") as "Hkk". 
        apply Nat2Z.inj in Heq2 as ->.
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
  Qed.

End handlee_verification.

