From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import dhke_common.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.
Import valgroup_notation.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').
  Local Notation θ := (θ (Σ:=Σ) (vg:=vg)).

  Lemma C_DH_real_DH_KE (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb L :
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-∘ 𝟙)%T f1 f2 -∗

    BREL C_lazy DH_real f1 ≤ DH_KE f2 <|⊥|> {{ λ v1 v2, 
                                                 ∀ send1 send2 recv1 recv2 : label, let ac := chan_rowR send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                                                  BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                                                    v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V 
                                                                    <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont; brel_pures') using G.
    iIntros "Htoka Htokb Ha Hb Hff". 
    unfold DH_KE, C_lazy...
    iModIntro. 
    iIntros (send1 send2 recv1 recv2). 
    set (ac := chan_rowR send1 send2 recv1 recv2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb)...
    
    brel_alloctape_r α as "Hα"...
    brel_alloctape_r β as "Hβ"...
    brel_alloc_r la as "Hla"...
    brel_alloc_r lb as "Hlb"...
    
    rewrite /DH_real Nat2Z.id.
    iApply brel_couple_UT. 1: auto. iFrame "Hα". iSplit => //. iIntros (a ?) "!> Hα".
    iApply brel_couple_UT. 1: auto. iFrame "Hβ". iSplit => //. iIntros (b ?) "!> Hβ"...
    rewrite -Nat2Z.inj_mul...    
    brel_alloc_l lc as "Hlc"...
    
    iApply fupd_brel.
    iMod (auth_upd (#la, #a)%V with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.    
    iApply (brel_na_alloc
              ((β ↪ₛN (n; [b]) ∗ lb ↦ₛ NONEV)
               ∨ (β ↪ₛ□ (n; [])
                  ∗ lb ↦ₛ□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ₛN (n; [a]) ∗ la ↦ₛ NONEV ∗ lc ↦ NONEV)
               ∨ (α ↪ₛ□ (n; [])
                  ∗ la ↦ₛ□ SOMEV #a 
                  ∗ lc ↦□ SOMEV (vgval (g ^+ (a * b))%g)))%I
              alphaN).
    iSplitL "Hα Hla Hlc"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    brel_effect_l gk1 as "Hgk1".
    brel_effect_r gk2 as "Hgk2"...

    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ gk1 gk2 }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
        iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    rewrite /sem_val_typed /=.
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
    
    iDestruct (brel_introduction_mono _ ([([gk1],[gk2],GetKey gk1 gk2)] ++  (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by do 2 apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].
    
    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : {
      brel_pures'; [apply Hk2; set_solver|apply Hk1; set_solver|].
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "([(>Hα & >Hla & >Hlc) | (#>Hα & #>Hla & #>Hlc)] & Hclose)".
      - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "Hla").
        iIntros "Hla"...
        brel_rand_r...
        brel_store_r...
        iApply (brel_exp_r [AppRCtx _])... 
        brel_load_l...
        brel_store_l...
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iMod (ghost_map_elem_persist with "Hlc") as "#Hlc".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1]); [repeat constructor|]. 
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. 
        iExists _,_,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        iApply brel_value. iIntros "$ !>"...
        
        (* Recv bob (either none or some) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [recv1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>"...
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>"...
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH".
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_r...
        brel_load_l...
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft.
        iExists _,_,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>"...
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [recv1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL...
        
        (* Recv bob = None *)
        + iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH".
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>"...
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion with "[$]"); [done|done|].
          iApply "IH". }
    
    1 : {
      brel_pures'; [apply Hk2; set_solver|apply Hk1; set_solver|].
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply (brel_introduction' [recv1]); [repeat constructor|].
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iLeft.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      { iApply brel_value. iIntros "$ !>"...
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
      iIntros (la' m) "(#Hb'&#Hla')".
      iDestruct (auth_agree with "[$Ha] [$Hb']") as "%Heq".
      inversion Heq as [(Heq1&Heq2)]. subst. rewrite Heq2.
      iApply brel_value. iIntros "$ !>"...
      
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)".
      - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "Hlb"... 
        brel_rand_r...
        brel_store_r... 
        iApply (brel_exp_r [AppRCtx _])... 
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
        iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        (* Send (gB, alice) *)
        iApply (brel_bind' [_] [_]); [by iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. 
        iExists _,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        iApply brel_value. iIntros "$ !>"...
        rewrite -expgM. rewrite -ssrnat.multE.

        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlc) | (#Hα & #Hla & #Hlc)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_l...
        iDestruct ("Hcont" with "Hsome") as "Hkk". 
        iApply (brel_exhaustion with "[$]"); [done|done|].
        iApply "IH".
        
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_r...
        
        (* Send (gB, alice) *)
        iApply (brel_bind' [AppRCtx _] [AppRCtx _]); [by iApply traversable_to_iThy|].
        iApply (brel_introduction' [send1]); [repeat constructor|].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight.
        iExists _,_.
        iSplitL; first (iApply send_upd; by iFrame "#").
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. 
        iApply brel_value. iIntros "$ !>"...
        rewrite -expgM. rewrite -ssrnat.multE.

        iApply (brel_na_inv _ _ alphaN); first set_solver.
        iFrame "Hinva".
        iIntros "(>[(Hα & Hla & Hlc) | (#Hα & #Hla & #Hlc)] & Hclose)".
        { iDestruct (ghost_map_elem_agree with "[$Hla] [$Hla']") as "%Hcontra".
          inversion Hcontra. }
        iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        brel_load_l...
        iDestruct ("Hcont" with "Hsome") as "Hkk". 
        apply Nat2Z.inj in Heq2 as ->.
        iApply (brel_exhaustion with "[$]"); [done|done|].
        iApply "IH". }
  Qed.

End handlee_verification.

