From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import primitive_laws proofmode
  spec_rules spec_ra
  class_instances.
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze.examples.DH_KE Require Import dhke_common.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement.

Import fingroup.
Import fingroup.fingroup.

Import valgroup_tactics.
Import valgroup_notation.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').

  (* Verification of F_AUTH ≤ F_AUTH against the *modular* channel theory
     [chan_new_row], i.e. [Send]/[Recv] quantified over predicates on the
     transmitted message instead of a fixed [own γauth _] resource.

     Both predicates stay completely abstract here.  F_AUTH only has to move the
     persistent knowledge [□ P m] that a [Send] hands over into its own
     na-invariant, and hand it back out at the matching [Recv].  That is what
     used to be the fixed [own γauth (to_dfrac_agree DfracDiscarded _)] of
     [chan_row] / [chan_rowL] / [chan_rowR]; a client recovers each of those
     three by instantiating [P] and [P'].

     Bookkeeping.  F_AUTH keeps one reference per direction, and
     [send_new_mono] / [recv_new_mono] pair them up as follows:

       [l1] (F_AUTH's "m1") : Alice's message, i.e. the one addressed to Bob.
            written by [Send bob] (γtoka, γfraca, atokN), read by [Recv alice],
            described by [P];              na-invariant [alphaN].

       [l2] (F_AUTH's "m2") : Bob's message, i.e. the one addressed to Alice.
            written by [Send alice] (γtokb, γfracb, btokN), read by [Recv bob],
            described by [P'];             na-invariant [betaN].

     The [Timeless] side conditions are needed to open the na-invariants: the
     invariant carries [□ P m], and stripping the guarding later requires it to
     be timeless.  All intended instantiations (which are built from [own _ _]
     and persistent points-tos) satisfy this. *)
  (*------------------------------------------------------------*)

  Lemma F_AUTH_F_AUTH_new (f1 f2 : expr) γtoka γtokb γfraca γfracb
    (P P' : vgG → iProp Σ)
    `{!∀ m : vgG, Timeless (P m), !∀ m : vgG, Timeless (P' m)} (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2,
                           ∀ send1 send2 recv1 recv2 : label, let ac := chan_new_row P P' γtoka atokN γtokb btokN γfraca γfracb send1 send2 recv1 recv2 in
                                            BREL v1 ((λ: "m", do: send1 "m"), (λ: "m", do: recv1 "m"))%V ≤
                                              v2 ((λ: "m", do: send2 "m"), (λ: "m", do: recv2 "m"))%V
                                              <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH f1 ≤ F_AUTH f2 <| ⊥ |> {{ λ v1 v2,
                                            (∀ᵣ θₗ, (((𝔾 × (𝟙 + 𝟙)) -{ θₗ }-> 𝟙) × ((𝟙 + 𝟙) -{ θₗ }-> Option ℕ)) -{ sem_row_union θₗ L }-∘ 𝟙)%T v1 v2 }}.
  Proof with (repeat foldkont;brel_pures') using G.
    iIntros "Hfraca Hfracb Hff".

    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff".
    unfold F_AUTH...
    iModIntro.
    iIntros (sendrecv). iIntros (sr1 sr2) "(%send1&%send2&%recv1&%recv2&->&->&(#Hsend&#Hrecv))"...
    
    brel_alloc_l l1 as "Hl1"...
    brel_alloc_l l2 as "Hl2"...
    brel_alloc_r l1' as "Hl1s"...
    brel_alloc_r l2' as "Hl2s"...

    (* Alice's message: written by [Send bob], read by [Recv alice], carries [P]. *)
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ mA : vgG, l1 ↦□ SOMEV mA ∗ l1' ↦ₛ□ SOMEV mA ∗ token γtoka
                         ∗ own γfraca DfracDiscarded
                         ∗ □ (P mA))) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".

    (* Bob's message: written by [Send alice], read by [Recv bob], carries [P']. *)
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ mB : vgG, l2 ↦□ SOMEV mB ∗ l2' ↦ₛ□ SOMEV mB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ □ (P' mB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".

    brel_effect_l sendl1 as "Hsend1".
    brel_effect_r sendl2 as "Hsend2".
    brel_effect_l recvl1 as "Hrecv1".
    brel_effect_r recvl2 as "Hrecv2"...
    iSpecialize ("Hff" $! sendl1 sendl2 recvl1 recvl2).

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hsend1").
    iApply (brel_add_label_r with "Hsend2").

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hrecv1").
    iApply (brel_add_label_r with "Hrecv2").

    (* Peel the outer (recv) handler.  This leaves two goals: the send-handled
       body -- where the inner (send) handler is peeled in turn -- and the
       value/effect cases of the recv handler itself.  R has to be given
       explicitly, otherwise it stays an evar until the recv branch. *)
    iApply (brel_exhaustion _ _ [_] [_] _ _ _ (λ w1 w2, 𝟙%T w1 w2) with "[Hff]"); [done|done| |].

    (* SEND *)
    (*------------------------------------------------------------*)
    1 : {
      (* brel_exhaustion consumes the head of the row, so bring send to the front. *)
      iApply brel_introduction_mono; first (iApply to_iThy_le_intro'; apply submseteq_swap).
      iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
      { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'.
        etrans; [apply submseteq_swap|]. do 2 apply submseteq_skip.
        rewrite iLblSig_to_iLblThy_app. by apply submseteq_inserts_l. }
      iLöb as "IHsend".
      iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
      iIntros (?????) "!# %Hk1 %Hk2 [(%&%&Hupd&(->&->)&#HQ) | (%&%&Hupd&(->&->)&#HQ)] #Hkont".

      (* [Send bob] : Alice sends to Bob, F_AUTH stores it in l1 *)
      1 : { iApply (brel_na_inv _ _ alphaN ); [set_solver|].
            iFrame "Hinva".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%mA & #Hl1 & #Hl1s & Htoka & #Hfraca & #HPa)] & Hclose)".
            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
              iMod (dfrac_persist with "Hfraca") as "#Hfraca".
              iMod ("Hupd" with "Hfraca") as "(Htok & HP & <-)".
              iModIntro. 
              brel_pures'; [apply Hk2|apply Hk1|]; try (set_unfold; tauto).
              brel_load_l...
              brel_load_r...
              brel_store_l...
              brel_store_r...
              iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
              { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
                by apply submseteq_inserts_r. }

              iApply fupd_brel.
              iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
              iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
              iModIntro.
              iApply brel_na_close. iFrame.
              iSplitL "Htok HP"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

              iAssert (sem_val_typed (m, bob)%V (m, bob)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
              { iModIntro. iExists _,_,_,_.
                repeat (iSplit; first done).
                iSplit; first (iExists _; done).
                iExists _,_. iLeft. done. }
              unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
              unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
              iDestruct ("Hsend" with "Hmm") as "Hsend1".
              iApply (brel_wand with "[$Hsend1]").
              iIntros (??) "!# (->&->)"...
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHsend".

            - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
              1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
              iApply brel_na_close. iFrame.
              iSplitL "Htoka"; [iNext; iRight; iExists mA; iFrame; iFrame "#"|].
              brel_pures'; [apply Hk2|apply Hk1|]; try (set_unfold; tauto).
              brel_load_l...
              brel_load_r...
              iDestruct ("Hkont" with "HQ") as "Hbrel".
              iApply (brel_exhaustion with "[$]"); [done| done|]. iApply "IHsend". }

      (* [Send alice] : Bob sends to Alice, F_AUTH stores it in l2 *)
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%mB & #Hl2 & #Hl2s & Htokb & #Hfracb & #HPb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & HP & <-)".
        iModIntro.
        brel_pures'; [apply Hk2|apply Hk1|]; try (set_unfold; tauto).
        brel_load_l...
        brel_load_r...
        brel_store_l...
        brel_store_r...
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| |].
        { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
          by apply submseteq_inserts_r. }

        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok HP"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].

        iAssert (sem_val_typed (m, alice)%V (m, alice)%V (𝔾 × (𝟙 + 𝟙))%T) as "Hmm".
        { iModIntro. iExists _,_,_,_. repeat (iSplit; first done).
          iSplit; first (iExists _; done).
          iExists _,_. iRight. done. }
        unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hsend" as "#Hsend".
        unfold sem_val_typed. simpl. iDestruct "Hmm" as "#Hmm".
        iDestruct ("Hsend" with "Hmm") as "Hsend1".
        iApply (brel_wand with "[$Hsend1]").
        iIntros (??) "!# (->&->)".
        brel_pures'.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHsend".

      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists mB; iFrame; iFrame "#"|].
        brel_pures'; [apply Hk2| apply Hk1|]; try (set_unfold; tauto).
        brel_load_l...
        brel_load_r...
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHsend". }

    (* RECV *)
    (*------------------------------------------------------------*)
    iLöb as "IHrecv".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [(->&->&#(HNone & HSome)) | (->&->&#(HNone & HSome))] #Hkont".

    (* [Recv alice] : receive from Alice, i.e. read l1 *)
    1 : { brel_pures'; [apply Hk2| apply Hk1|]; try (set_unfold; tauto)...
          iApply (brel_bind [_] [_]); [by iApply traversable_to_iThy| |].
          { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
            by apply submseteq_inserts_r. }

          iAssert (sem_val_typed (alice)%V (alice)%V ((𝟙 + 𝟙))%T) as "Halice".
          { iModIntro. iExists _,_. iRight. done. }
          unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
          unfold sem_val_typed. simpl. iDestruct "Halice" as "#Halice".
          iDestruct ("Hrecv" with "Halice") as "Hrecv1".
          iApply (brel_wand with "[$Hrecv1]").
          iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

          + iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHrecv".

          + iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "Hinva".
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%mA & #Hl1 & #Hl1s & Htoka & #Hfraca & #HPa)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              brel_load_r...
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHrecv".

            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              brel_load_l...
              brel_load_r...
              iDestruct ("HSome" with "HPa") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".

              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHrecv". }

    (* [Recv bob] : receive from Bob, i.e. read l2 *)
    brel_pures'; [apply Hk2|apply Hk1|]; try (set_unfold; tauto).
    iApply (brel_bind [_] [_]); [iApply traversable_to_iThy| |].
    { iApply to_iThy_le_intro'. do 2 apply submseteq_cons. rewrite iLblSig_to_iLblThy_app.
      by apply submseteq_inserts_r. }

    iAssert (sem_val_typed (bob)%V (bob)%V ((𝟙 + 𝟙))%T) as "Hbob".
    { iModIntro. iExists _,_. iLeft. done. }
    unfold sem_ty_arr, sem_ty_mbang. simpl. iDestruct "Hrecv" as "#Hrecv".
    unfold sem_val_typed. simpl. iDestruct "Hbob" as "#Hbob".
    iDestruct ("Hrecv" with "Hbob") as "Hrecv1".
    iApply (brel_wand with "[$Hrecv1]").
    iIntros (??) "!# (%&%&[(->&->&->&->)|(->&->&_)])"; brel_pures'.

    + iDestruct ("Hkont" with "HNone") as "Hbrel".
      iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHrecv".

    + iApply (brel_na_inv _ _ betaN); [set_solver|].
      iFrame "Hinvb".
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%mB & #Hl2 & #Hl2s & Htokb & #Hfracb & #HPb)] & Hclose)".
      * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        brel_load_r...
        iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
        iDestruct ("Hkont" with "HNone") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHrecv".

      * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
        brel_load_l...
        brel_load_r...
        iDestruct ("HSome" with "HPb") as "HS".
        iDestruct ("Hkont" with "HS") as "Hbrel".

        (* First call is done. Can call getKey1 or getKey2 again. *)
        iApply (brel_exhaustion with "[$]"); [done|done|]. iApply "IHrecv".
  Qed.

End handlee_verification.
