From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.
From clutch Require Import stdpp_ext.
From clutch.prob_eff_lang.probblaze Require Import logic primitive_laws proofmode
  spec_rules spec_ra 
  class_instances. 
From clutch.prob_eff_lang.probblaze Require Import tactics.
From clutch.prob_eff_lang.probblaze Require Import def_dhke.
From clutch.prob_eff_lang.probblaze Require Import sem_types sem_row sem_sig sem_judgement sem_def. 

Import fingroup.

Import fingroup.fingroup.

Import valgroup_tactics.

Section handlee_verification.
  Context `{!probblazeRGS Σ}.
  Context (channel1 channel2 getKey1 getKey2 leakauth1 leakauth2: label).
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {G : clutch_group (vg:=vg) (cg:=cg)}.
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.

  #[local] Notation n := (S n'').

  (* Names and resources used in the theories *)
  (*------------------------------------------------------------*)
  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition token γ := own γ (Excl ()).

  
  Lemma token_alloc : ⊢ |==> ∃ γ, token γ.
  Proof.
    iApply own_alloc. 
    constructor.
  Qed.

  Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.


  (* Theories for the client *)
  (*------------------------------------------------------------*)
  
  Program Definition GetKey1 : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: getKey1 (InjL #()%V) ⌝%E ∗
                ⌜ e2 = do: getKey2 (InjL #()%V) ⌝%E ∗
                □ (Q NONEV NONEV ∗ ∀ key : vgG, Q (SOMEV key) (SOMEV key) )
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition GetKey2 : iThy Σ :=
     λ e1 e2, (λne Q,
                ⌜ e1 = do: getKey1 (InjR #()%V) ⌝%E ∗
                ⌜ e2 = do: getKey2 (InjR #()%V) ⌝%E ∗
                □ (Q NONEV NONEV ∗ ∀ key : vgG, Q (SOMEV key) (SOMEV key) )
             )%I.
  Next Obligation. solve_proper. Qed.

  Definition T : iThy Σ := iThyTraverse [getKey1] [getKey2] (iThySum GetKey1 GetKey2).

 
  Program Definition GetKey gk1 gk2: iThy Σ :=
    λ e1 e2, (λne Q,
                ((⌜ e1 = do: gk1 (InjLV #()%V) ⌝%E ∗
                ⌜ e2 = do: gk2 (InjLV #()%V) ⌝%E) ∨
                (⌜ e1 = do: gk1 (InjRV #()%V) ⌝%E ∗
                 ⌜ e2 = do: gk2 (InjRV #()%V) ⌝%E)) ∗
                □ (Q NONEV NONEV ∗ ∀ key : vgG, Q (SOMEV key) (SOMEV key) )
             )%I.
  Next Obligation. solve_proper. Qed.

  (* Theories for auth channel interacting with the environment *)
  (*------------------------------------------------------------*)
  Program Definition SendBob : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m : val,
                ⌜ e1 = do: leakauth1 (SendV (m, bob)) ⌝%E ∗
                  ⌜ e2 = do: leakauth2 (SendV (m, bob)) ⌝%E ∗
                   □ Q (Val #()%V) (Val #()%V)
             )%I. 
  Next Obligation. solve_proper. Qed.

  Program Definition SendAlice : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m : val, 
                  ⌜ e1 = do: leakauth1 (SendV (m, alice)) ⌝%E ∗
                  ⌜ e2 = do: leakauth2 (SendV (m, alice)) ⌝%E ∗
                  □ Q (Val #()%V) (Val #()%V)
             )%I. 
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBobAuth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: leakauth1 (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: leakauth2 (RecvV bob) ⌝%E ∗
                □ ((∀ b1 b2 : nat, Q (SOMEV #b1) (SOMEV #b2)) ∧ Q NONEV NONEV)
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceAuth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: leakauth1 (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: leakauth2 (RecvV alice) ⌝%E ∗
                □ ((∀ b1 b2 : nat, Q (SOMEV #b1) (SOMEV #b2)) ∧ Q NONEV NONEV)
             )%I.
  Next Obligation. solve_proper. Qed.

  Definition Y : iThy Σ := iThyTraverse [channel1] [channel2] (iThySum (iThySum SendAlice SendBob) (iThySum RecvAliceAuth RecvBobAuth)).

  Definition LblEnv := [([leakauth1], [leakauth2], iThySum (iThySum SendAlice SendBob) (iThySum RecvAliceAuth RecvBobAuth))].

  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  Program Definition SendBobImpl c1 c2 γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m': val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                            (⌜ e1 = do: c1 (SendV (m, alice)) ⌝%E ∗
                             ⌜ e2 = do: c2 (SendV (m', alice)) ⌝%E)  ∗ 
                            □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceImpl c1 c2 γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                 ⌜ e1 = do: c1 (RecvV alice) ⌝%E ∗
                 ⌜ e2 = do: c2 (RecvV alice) ⌝%E ∗
                 □ (Q NONEV NONEV ∗ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceImpl c1 c2 γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m' : val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                             (⌜ e1 = do: c1 (SendV (m, bob)) ⌝%E ∗
                              ⌜ e2 = do: c2 (SendV (m', bob)) ⌝%E)  ∗ 
                             □ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBobImpl c1 c2 γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: c1 (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: c2 (RecvV bob) ⌝%E ∗
                □ (Q NONEV NONEV ∗ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed. 

  (* Definition X γtoka atokN γtokb btokN γfraca γfracb γautha γauthb : iThy Σ := iThyTraverse [channel1] [channel2]
                                                                        (iThySum (iThySum (SendAliceImpl γtoka γfraca γautha atokN) (RecvBobImpl γauthb))
                                                                           (iThySum (SendBobImpl γtokb γfracb γauthb btokN) (RecvAliceImpl γautha))). *)
 
  Definition LblAuthChannel (c1 c2 : label) γtoka atokN γtokb btokN γfraca γfracb γautha γauthb : iLblThy Σ :=
    [([c1],[c2], (iThySum (iThySum (SendAliceImpl c1 c2 γtoka γfraca γautha atokN) (RecvBobImpl c1 c2 γauthb))
                                (iThySum (SendBobImpl c1 c2 γtokb γfracb γauthb btokN) (RecvAliceImpl c1 c2 γautha))))].

  Definition LblAdv : iLblThy Σ :=  [([getKey1],[getKey2], (iThySum GetKey1 GetKey2))].

 (* Tactic Notation "foldkont" ident(k) open_constr(kctx) :=
    match goal with
    | |- context[KontV ?kont] =>
        unify kont kctx ; set (k := KontV kont)
    end.

  Tactic Notation "foldkont" ident(k) := foldkont k _.

  Tactic Notation "foldkont" := let k := fresh "kont" in foldkont k.*)

  (* semantic types *)
  (*------------------------------------------------------------*)

  Definition sem_ty_group : sem_ty Σ := (λ v1 v2, ∃ g : vgG, ⌜ v1 = g ⌝ ∗ ⌜ v2 = g ⌝)%I.
  Notation "'𝔾'" := sem_ty_group. 

  Program Definition gkmono (gk1 gk2 : label) :=  {| pmono_prot_car := GetKey gk1 gk2; pmono_prot_prop := _ |}. 
  Next Obligation.
    intros ??. iIntros (????) "#HΦ ([(->&->)|(->&->)] & #(H1&H2))"; repeat iSplit; [by iLeft| |by iRight|]; iModIntro; iSplitL; try iIntros (?); by iApply "HΦ".
  Qed. 

  Definition gk (gk1 gk2 : label) := @SemSig Σ (gkmono gk1 gk2) (gk1,gk2).
  
  Program Definition θ gk1 gk2 := SemRow [([gk1],[gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ??.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  
  Program Definition gkleakl leak gk1 gk2 := SemRow [([leak;gk1],[gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 

  Program Definition gkleakr leak gk1 gk2 := SemRow [([gk1],[leak;gk2],gk gk1 gk2)] _.
  Next Obligation.
    intros ???.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
  
  Program Definition authchan_mono c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := 
    {| pmono_prot_car := (iThySum (iThySum (SendAliceImpl c1 c2 γtoka γfraca γautha atokN) (RecvBobImpl c1 c2 γauthb))
                                (iThySum (SendBobImpl c1 c2 γtokb γfracb γauthb btokN) (RecvAliceImpl c1 c2 γautha))); pmono_prot_prop := _|}.
  Next Obligation.
    intros ??????????. 
    iIntros (????) "#HΦ [[H| H]|[H|H]]".
    1 : iLeft;iLeft. 2: iLeft; iRight.
    3 : iRight;iLeft. 4: iRight;iRight.
    1,3 : iDestruct "H" as (??) "(Himpl&%&#H)"; iExists _,_; iFrame; iSplit; first done; iModIntro; by iApply "HΦ".
    all : iDestruct "H" as "($&$&#(H1&H2))"; iModIntro; iSplitL; try (iIntros (m) "#H"); iApply "HΦ"; try iApply ("H2" $! m); done.
  Qed.   

  Definition authchan c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := @SemSig Σ (authchan_mono c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb) (channel1, channel2).
  Program Definition authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb := SemRow [([c1],[c2], authchan c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb)] _.
  Next Obligation.
    intros ??????????.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 
 
  Program Definition leakchan_mono  := 
    {| pmono_prot_car := iThySum (iThySum SendAlice SendBob) (iThySum RecvAliceAuth RecvBobAuth); pmono_prot_prop := _|}.
  Next Obligation.
    iIntros (????) "#HΦ [[H| H]|[H|H]]".
    1 : iLeft;iLeft. 2: iLeft; iRight.
    3 : iRight;iLeft. 4: iRight;iRight.
    1,2 : iDestruct "H" as (?) "(->&->&#HQ)"; iExists _; do 2 (iSplit; first done); iModIntro; by iApply "HΦ".
    all : iDestruct "H" as "(->&->&#H)"; do 2 (iSplit; [done|]); iModIntro; iSplit; [iIntros (??)|]; iApply "HΦ"; [iDestruct "H" as "(H&_)"|iDestruct "H" as "(_&H)"]; done.
  Qed.   

  Definition leakchan := @SemSig Σ leakchan_mono (leakauth1,leakauth2).
  Program Definition leakchan_row := SemRow [([leakauth1],[leakauth2], leakchan)] _.
  Next Obligation.
    iIntros (????) "#HΦ % % % ($&H)". iDestruct "H" as (?????) "(->&%&->&%&HX&#H)".
    iExists _,_,_,_,_. 
    repeat (iSplit; first done). iIntros (??) "!# HS". iApply "HΦ". by iApply "H". 
  Qed. 


  (* Verification of DH_KE ≤ C[DH_real] *)
  (*------------------------------------------------------------*)
  
  Lemma DH_KE_C_DH_real (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ):
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    sem_val_typed f1 f2 (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-> 𝟙)%T -∗

    BREL DH_KE f1 ≤ C f2 DH_real <|⊥|> {{ λ v1 v2, 
                           ∀ c1 c2 : label, let ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 (λ: "m", do: c1 (Send "m"))%V (λ: "m", do: c1 (Recv "m"))%V ≤
                                                 v2 (λ: "m", do: c2 (Send "m"))%V (λ: "m", do: c2 (Recv "m"))%V 
                                                 <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont) using G.
    iIntros "Htoka Htokb Ha Hb #Hff". 
    unfold DH_KE, C. 
    brel_pures'. iModIntro. 
    iIntros (c1 c2). set (ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
    brel_pures'.
    repeat simpl.
    unfold DH_KE. unfold C. unfold DH_real. brel_pures.
    iApply brel_alloctape_l. iIntros (α) "!> Hα". brel_pures_l.
    iApply brel_alloctape_l. iIntros (β) "!> Hβ". brel_pures_l.
    iApply brel_alloc_l. iIntros (la) "!> Hla".
    iApply brel_alloc_l. iIntros (lb) "!> Hlb".
  
    iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame. simpl. iIntros (a) "Hα".
    iDestruct "Hβ" as (ms) "(%Hf' & Hβ)". apply map_eq_nil in Hf'. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame "Hβ". simpl. iIntros (b) "Hβ".
  
    brel_pures_r. rewrite -Nat2Z.inj_mul.
    brel_pures'.
  
    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>".
    brel_pures'.
    unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff".
    set (θ := θ gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    iDestruct "Hff" as "#Hff".
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    iDestruct "Hff" as "#Hff". 
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
       - iSplit; first (iPureIntro; left; split; done); iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
             iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists].
       - iSplit; first (iPureIntro; right; split; done); iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
             iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
  
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply fupd_brel.
    set (ga := (g ^+ a)%g).
    iMod (auth_upd (vgval (g ^+ a)%g) with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
  
    (* Store resources before induction *)
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.
    
    iApply (brel_na_alloc
              ((β ↪ (n; [b]) ∗ lb ↦ NONEV)
               ∨ (β ↪□ (n; [])
                  ∗ lb ↦□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ (n; [a]) ∗ la ↦ NONEV)
               ∨ (α ↪□ (n; [])
                  ∗ la ↦□ SOMEV #a))%I
              alphaN).
    iSplitL "Hα Hla"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
  
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
  
    iDestruct (brel_introduction_mono _ ([([gk1],[gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].
  
    (* getKey can be called multiple times, why we need induction *)
    (* the token is given away at the first call, so we need to store it in an invariant that holds for all calls to getKey *)
    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures|].
    (* getKeyAlice or getKeyBob *)
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
  
    1 : {
      brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|]...
      (* bind the match ... end block and prove (by casing on the invariant) that in either case "a" will become the value a (from the tape or the reference read), then continue only with one branch *)
      (* in other words, prove a spec for sample_or_load *)
      iApply (brel_na_inv _ _ alphaN); first set_solver.
      iFrame "Hinva".
      iIntros "([(Hα & Hla) | (#Hα & #Hla)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> Hla". brel_pures_l.
        iApply (brel_rand_l _ [AppRCtx _;AppRCtx _]).
        iAssert (α ↪N (n; [fin_to_nat a]))%I with "[Hα]" as "Hα".
        { iExists [a]. simpl. iFrame. done. }
        iFrame. iIntros "!>Hα _". brel_pures_l.
        iApply (brel_store_l _ _ _ [AppRCtx _; AppRCtx _] with "[$]").
        iIntros "!> Hla". brel_pures'. 
        iApply (brel_exp_l [AppRCtx _]). brel_pures_l.
  
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
  
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft. iExists _, _.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. iApply brel_value. iIntros "$ !>".
        brel_pures'.
  
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
  
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
  
        (* Recv bob = Some gB *)
        + iIntros (m) "Hb'".
          iDestruct (auth_agree with "[$Hb] [$Hb']") as "<-". 
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
  
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> _". brel_pures. brel_exp_l. brel_pures_l.
  
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft.
        iExists _, _.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
  
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH".
  
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures.
          rewrite -expgM. rewrite -ssrnat.multE.
          rewrite -Nat.mul_comm.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
          iApply "IH". }
  
    1 : {
      brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|].
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply brel_introduction'.
      { apply elem_of_cons. right. apply list_elem_of_here. }
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iRight. iRight.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      { iApply brel_value. iIntros "$ !>".
        brel_pures.
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
      iIntros (m) "Hb'".
      iDestruct (auth_agree with "[$Ha] [$Hb']") as "<-".
      iApply brel_value. iIntros "$ !>".
      brel_pures.
      
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
        iIntros "!> Hlb". brel_pures_l.
        iApply (brel_rand_l _ [AppRCtx _; AppRCtx _]).
        iAssert (β ↪N (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
        { iExists [b]. simpl. iFrame. done. }
        iFrame. iIntros "!>Hβ _". brel_pures_l.
        iApply (brel_store_l _ _ _ [AppRCtx _; AppRCtx _] with "Hlb").
        iIntros "!> Hlb".
        brel_pures. iApply (brel_exp_l [AppRCtx _]). brel_pures.
  
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
        iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iRight; iFrame "#"|].
  
        iApply (brel_bind' [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy|].
        iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. iLeft.
        iExists _,_.
        iSplitL.
        { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
  
        iApply brel_value. iIntros "$ !>".
        brel_pures. brel_pures_l.
        rewrite -expgM. rewrite -ssrnat.multE.
        rewrite -Nat.mul_comm.
  
        iDestruct ("Hcont" with "Hsome") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH".
  
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l with "[$]").
        iIntros "!> _". brel_pures_l. brel_exp_l. brel_pures.
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iRight. iLeft.
        iExists _,_.
        iSplitL.
        { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
  
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        rewrite -expgM. rewrite -ssrnat.multE.
        rewrite -Nat.mul_comm.
        iDestruct ("Hcont" with "Hsome") as "Hkk".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
        iApply "IH". }
  Qed.
  

  Lemma C_DH_real_DH_KE (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb L :
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    sem_val_typed f1 f2 (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-> 𝟙)%T -∗

    BREL C f1 DH_real ≤ DH_KE f2 <|⊥|> {{ λ v1 v2, 
                           ∀ c1 c2 : label, let ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 (λ: "m", do: c1 (Send "m"))%V (λ: "m", do: c1 (Recv "m"))%V ≤
                                                 v2 (λ: "m", do: c2 (Send "m"))%V (λ: "m", do: c2 (Recv "m"))%V 
                                                 <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof using G.
    iIntros "Htoka Htokb Ha Hb #Hff". 
    unfold DH_KE, C. 
    brel_pures'. iModIntro. 
    iIntros (c1 c2). set (ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
    brel_pures'.
    iApply brel_alloctape_r. iIntros (α) "Hα". brel_pures_r.
  
    iApply brel_alloctape_r. iIntros (β) "Hβ". brel_pures_r.
  
    iApply brel_alloc_r. iIntros (la) "Hla". brel_pures_r.
  
    iApply brel_alloc_r. iIntros (lb) "Hlb". brel_pures_r. 
    brel_pures'. unfold DH_real. brel_pures'.
    iApply brel_couple_UT. 1: auto. iFrame "Hα". simpl. iSplit => //. iIntros (a ?) "!> Hα".
    iApply brel_couple_UT. 1: auto. iFrame "Hβ". simpl. iSplit => //. iIntros (b ?) "!> Hβ".
    
    brel_pures_l. rewrite -Nat2Z.inj_mul.
    do 3 brel_exp_l.
    brel_pures_l.
        
    iApply fupd_brel.
    set (ga := (g ^+ a)%g).
    iMod (auth_upd (vgval (g ^+ a)%g) with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
  
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.    
    iApply (brel_na_alloc
              ((β ↪ₛN (n; [b]) ∗ lb ↦ₛ NONEV)
               ∨ (β ↪ₛ□ (n; [])
                  ∗ lb ↦ₛ□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ₛN (n; [a]) ∗ la ↦ₛ NONEV)
               ∨ (α ↪ₛ□ (n; [])
                  ∗ la ↦ₛ□ SOMEV #a))%I
              alphaN).
    iSplitL "Hα Hla"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
  
    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>".
    brel_pures'.
    unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff".
    set (θ := θ gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    iDestruct "Hff" as "#Hff".
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    iDestruct "Hff" as "#Hff". 
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
             iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
  
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 
    
    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
  
    iDestruct (brel_introduction_mono _ ([([gk1],[gk2],GetKey gk1 gk2)] ++  (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].
  
    iLöb as "IH".
    
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
     1 : {
       brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|].
       iApply (brel_na_inv _ _ alphaN ); [set_solver|].
       iFrame "Hinva". 
       iIntros "([(>Hα & >Hla) | (#>Hα & #>Hla)] & Hclose)".
       - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "Hla").
         iIntros "Hla". brel_pures_r.
         (* iAssert (α ↪ₛN (n; [a]))%I with "[Hα]" as "Hα".
            { iExists [a]. simpl. iFrame. done. } *)
         iApply (brel_rand_r _ [AppRCtx _; AppRCtx _] with "Hα").
         iIntros "Hα _". brel_pures_r.
         iApply (brel_store_r _ _ _ _[AppRCtx _; AppRCtx _] with "Hla").
         iIntros "Hla".
         brel_pures_r. 
         iApply (brel_exp_r [AppRCtx _]). brel_pures_r.
     
         iApply fupd_brel.
         iMod (ghost_map_elem_persist with "Hla") as "#Hla".
         iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
         iMod (ghost_map_elem_persist with "Hα") as "#Hα".
         iModIntro.
         iApply brel_na_close. iFrame.
         iSplitL; [iNext; iRight; iFrame "#"|].
         
         (* Send (gA, bob) *)
         iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
         iApply brel_introduction'.
         { apply elem_of_cons. right. apply list_elem_of_here. }
         
         iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
         iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
         iLeft. iLeft. 
         iExists _, _.
         iSplitL.
         { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
           - iModIntro. iLeft.
             iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
             by iModIntro.
           - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
         iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
         iModIntro.
         iApply brel_value. iIntros "$ !>".
         brel_pures.
         
         (* Recv bob (either none or some) *)
         iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
         iApply brel_introduction'.
         { apply elem_of_cons. right. apply list_elem_of_here. }
         iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
         iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
         iLeft. iRight.
         do 2 (iSplit; try (iPureIntro; done)).
         iModIntro.
         iSplitL.
                 
         (* Recv bob = None *)
         + iApply brel_value. iIntros "$ !>".
           brel_pures.
           iDestruct ("Hcont" with "Hnone") as "Hkk".
           iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
           iApply "IH".
           
         (* Recv bob = Some gB *)
         + iIntros (m) "Ha'".
           iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
           iApply brel_value. iIntros "$ !>".
           brel_pures. brel_exp_r.
           rewrite -expgM. rewrite -ssrnat.multE.
           rewrite -Nat.mul_comm.
           iDestruct ("Hcont" with "Hsome") as "Hkk".
           iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
           iApply "IH".
  
       - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
         iApply (brel_load_r with "Hla"). iIntros "_". brel_pures.
         brel_exp_r. brel_pures.
         
         (* Send (gA, bob) *)
         iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
         iApply brel_introduction'.
         { apply elem_of_cons. right. apply list_elem_of_here. }
         iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
         iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
         iLeft. iLeft.
         iExists _, _.
         iSplitL.
         { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
           - iModIntro. iLeft.
             iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
             by iModIntro. 
           - iModIntro. iRight. iFrame "#".
             iApply "Hclose". iNext.
             by iRight. }
         iSplit; first (iSplit; try (iPureIntro; done)).
         iModIntro.
         iApply brel_value. iIntros "$ !>".
         brel_pures.
         
         iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
         iApply brel_introduction'.
         { apply elem_of_cons. right. apply list_elem_of_here. }
         iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
         iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
         iLeft. iRight.
         do 2 (iSplit; try (iPureIntro; done)).
         iModIntro.
         iSplitL.
  
         (* Recv bob = None *)
         + iApply brel_value. iIntros "$ !>".
           brel_pures.
           iDestruct ("Hcont" with "Hnone") as "Hkk".
           iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
           iApply "IH".
  
         (* Recv bob = Some gB *)
         + iIntros (m) "Ha'".
           iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
           iApply brel_value. iIntros "$ !>".
           brel_pures. brel_exp_r. brel_pures.
           rewrite -expgM. rewrite -ssrnat.multE.
           rewrite -Nat.mul_comm.
           iDestruct ("Hcont" with "Hsome") as "Hkk".
           iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
           iApply "IH". }
  
     1 : {
       brel_pures; [apply Hk1; set_solver|apply Hk2; set_solver|].
       iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
       iApply brel_introduction'.
       { apply elem_of_cons. right. apply list_elem_of_here. }
       iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
       iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
       iRight. iRight.
       do 2 (iSplit; try (iPureIntro; done)).
       iModIntro.
       iSplitL.
       { iApply brel_value. iIntros "$ !>".
         brel_pures.
         iDestruct ("Hcont" with "Hnone") as "Hkk".
         iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
         iApply "IH". }
       iIntros (m) "Hb'".
       iDestruct (auth_agree with "[$Ha] [$Hb']") as "<-".
       iApply brel_value. iIntros "$ !>".
       brel_pures.
  
       iApply (brel_na_inv _ _ betaN ); [set_solver|].
       iFrame "Hinvb". 
       iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)".
       - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
         iIntros "Hlb". brel_pures_r.
         (* iAssert (β ↪ₛN (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
            { iExists _. simpl. iFrame. done. } *)
         iApply (brel_rand_r _ [AppRCtx _; AppRCtx _] with "[$]").
         iIntros "Hβ _". brel_pures_r.
         iApply (brel_store_r _ _ _ _[AppRCtx _; AppRCtx _] with "Hlb").
         iIntros "Hlb".
         brel_pures_r. 
         iApply (brel_exp_r [AppRCtx _]). brel_pures_r.
         iApply fupd_brel.
         iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
         iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
         iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
         iModIntro.
         iApply brel_na_close. iFrame.
         iSplitL; [iNext; iRight; iFrame "#"|].
  
         (* Send (gB, alice) *)
         iApply (brel_bind' [_] [_]); [by iApply traversable_to_iThy|].
         iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
         iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
         iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
         iRight. iLeft. 
         iExists _,_.
         iSplitL.
         { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
           - iModIntro. iLeft.
             iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
             by iModIntro. 
           - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
         iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
         iModIntro.
         iApply brel_value. iIntros "$ !>".
         brel_pures.
         rewrite -expgM. rewrite -ssrnat.multE.
         rewrite -Nat.mul_comm.
  
         iDestruct ("Hcont" with "Hsome") as "Hkk".
         iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
         iApply "IH".
         
       - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
         iApply (brel_load_r with "Hlb"). iIntros "_". brel_pures.
         brel_exp_r. brel_pures.
         
         (* Send (gB, alice) *)
         iApply (brel_bind' [AppRCtx _] [AppRCtx _]); [by iApply traversable_to_iThy|].
         iApply brel_introduction'. { apply elem_of_cons. right. apply list_elem_of_here. }
         iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
         iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
         iRight. iLeft.
         iExists _,_.
         iSplitL.
         { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
           - iModIntro. iLeft.
             iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
             by iModIntro. 
           - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
         iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
         
         iModIntro. 
         iApply brel_value. iIntros "$ !>".
         brel_pures.
         rewrite -expgM. rewrite -ssrnat.multE.
         rewrite -Nat.mul_comm.
  
         iDestruct ("Hcont" with "Hsome") as "Hkk".
         iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|].
         iApply "IH". }
  Qed.
     
     
     
     (* Verification of F_AUTH ≤ F_AUTH *)
     (*------------------------------------------------------------*)
     
  Lemma F_AUTH_F_AUTH (f1 f2 : expr) γtoka γtokb γfraca γfracb γautha γauthb (L : sem_row Σ) :
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|⊥|> {{λ v1 v2, 
                           ∀ c1 c2 : label, let ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 (λ: "m", do: c1 (Send "m"))%V (λ: "m", do: c1 (Recv "m"))%V ≤
                                                 v2 (λ: "m", do: c2 (Send "m"))%V (λ: "m", do: c2 (Recv "m"))%V 
                                                 <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }} -∗
    BREL F_AUTH leakauth1 f1 ≤ F_AUTH leakauth2 f2 <| ⊥ |> {{ λ v1 v2, (𝟙 -{ sem_row_union leakchan_row L }-∘ 𝟙)%T v1 v2 }}.
  Proof using G. 
    iIntros "Hfraca Hfracb Hff". 
    
    iApply (brel_bind _ _ _ [] _ _ f1 f2); [iApply traversable_to_iThy_nil|iApply to_iThy_le_bot|].
    assert (to_iThyIfMono OS [] = []) as <- by done.
    iApply (brel_mono OS _ _ ⊥ [] with "[][$Hff]"); [iApply to_iThy_le_bot|simpl].
    clear f1 f2.
    iIntros (f1 f2) "Hff". 
    unfold F_AUTH.
    brel_pures'. iModIntro.
    iIntros (??) "(->&->)".
    brel_pures'.

    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. 
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. 
  
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ gA , l1 ↦□ SOMEV gA∗ l1' ↦ₛ□ SOMEV gA ∗ token γtoka
                         ∗ own γfraca DfracDiscarded
                         ∗ own γautha (to_dfrac_agree DfracDiscarded gA))) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
  
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".

    iApply brel_effect_l. iIntros (chan1) "!> Hchan1".
    iApply brel_effect_r. iModIntro. iIntros (chan2) "Hchan2 !>".
    iSpecialize ("Hff" $! chan1 chan2).

    brel_pures'.

    (* unfold sem_ty_arr. 
       set (ac := authchan_row chan1 chan2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
       iAssert ((BREL f1 (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan1 InjR "m")%V ≤ f2 (λ: "m", do: chan2 InjL "m")%V (λ: "m", do: chan2 InjR "m")%V <|(iLblSig_to_iLblThy (sem_row_union ac L))|> {{(λ u1 u2 : val, 𝟙%T u1 u2)}})%I) with "[Hff]" as "Hff".
       { iSpecialize ("Hff" $! (λ: "m", do: chan1 InjL "m")%V (λ: "m", do: chan2 InjL "m")%V).
         unfold sem_ty_mbang. simpl. 
         iApply (brel_bind [AppLCtx _] [AppLCtx _] _ []); [iApply traversable_to_iThy_nil |iApply to_iThy_le_bot|].
         iApply (brel_wand with "[Hff]"). 
         - iApply "Hff". iIntros (??) "!# Hww". brel_pures'.
           iApply brel_introduction'; first constructor.
           admit.
         - iIntros (??) "!# H". simpl.
            iApply "H". iIntros (??) "!# Hww". brel_pures'.
            iApply brel_introduction'; first constructor.
            iExists _,_,[],[],_.
            do 2 (iSplit;[done|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]).
            iSplitL; last (iIntros (??) "!# H"; iApply "H").
            iDestruct "Hww" as (??) "[(->&->&->&->)|(->&->&->&->)]".
            + iLeft. iRight.
              do 2 (iSplit; first done).
              iModIntro. iSplitL.
              * iApply brel_value. iIntros "$ !>". iExists _,_. iLeft. admit.
              * iIntros (?) "Hm". iApply brel_value. iIntros "$ !>".
                iExists _,_. iRight.
                repeat (iSplit; first done).
                
       
            admit. } *)

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hchan1").
    iApply (brel_add_label_r with "Hchan2").
    
    iApply (brel_exhaustion _ _ [_] [_] with "[Hff]"); [done|done| |].
    { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iLöb as "IH".
    iSplit; [iIntros (v1 v2) "!# (->&->)"; by brel_pures|].
    iIntros (?????) "!# %Hk1 %Hk2 [[(%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]| [(%&%&Hupd&(->&->)&#HQ) | (->&->&#(HNone & HSome))]] #Hkont".
    1 : {
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%gA & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfraca") as "#Hfraca".
        iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| iApply to_iThy_le_refl|].
                
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
        iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].
  
        iApply brel_introduction'. { apply list_elem_of_further. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        iExists _.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
  
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htoka"; [iNext; iRight; iExists gA; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done| done|]. iApply "IH". }
  
    1 : { brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
          iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
          iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
          iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight. iRight. do 2 (iSplit; try (iPureIntro; done)).
          iModIntro.
          iSplit; last first.
  
          + iApply brel_value. iIntros "$ !>".
            iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
  
          + iIntros (b1 b2). iApply brel_value. iIntros "$ !>".
            brel_pures.
            iApply (brel_na_inv _ _ betaN); [set_solver|].
            iFrame "Hinvb". 
            iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "[$]"). iIntros "!> _".
              iApply (brel_load_r with "Hl2s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "Hauthb") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
          
    1 : {
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        brel_pures; [apply Hk1|apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy|iApply to_iThy_le_refl|].
  
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].
  
        iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here| ].
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft.
        iExists _.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iApply brel_value. iIntros "$ !>".
        brel_pures.
  
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
  
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "_".
        brel_pures.
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
  
    1 : { brel_pures; [apply Hk1| apply Hk2|]; try set_solver.
          iApply (brel_bind' [_] [_]); [by iApply traversable_to_iThy|].
          iApply brel_introduction'; [apply list_elem_of_further; apply list_elem_of_here|].
          iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight. iLeft. do 2 (iSplit; try (iPureIntro; done)).
          iModIntro.
          iSplit; last first.
  
          + iApply brel_value. iIntros "$ !>".
            iDestruct ("Hkont" with "HNone") as "Hbrel".
            iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
  
          + iIntros (b1 b2). iApply brel_value. iIntros "$ !>".
            brel_pures.
            iApply (brel_na_inv _ _ alphaN); [set_solver|].
            iFrame "#". 
            iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%gA & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
            * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
              iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
              brel_pures.
              iApply brel_na_close. iFrame. iSplitL; [iLeft; iFrame|].
              iDestruct ("Hkont" with "HNone") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
              
            * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"; iFrame|].
              iApply (brel_load_l with "[$]"). iIntros "!> _".
              iApply (brel_load_r with "Hl1s"). iIntros "_". 
              brel_pures.
              iDestruct ("HSome" with "Hautha") as "HS".
              iDestruct ("Hkont" with "HS") as "Hbrel".
              
              (* First call is done. Can call getKey1 or getKey2 again. *)
              iApply (brel_exhaustion _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". } 
  Qed. 

  (* Verification of F_AUTH[DH_KE] ≤ F_AUTH[C[DH_real]] *)
  (*------------------------------------------------------------*)


  Lemma F_AUTH_DH_KE_FAUTH_C_DH_real :
    ⊢ sem_val_typed (λ: "f", F_AUTH leakauth1 (DH_KE "f"))%V (λ: "f", F_AUTH leakauth2 (C "f" DH_real))%V  
                         (∀ᵣ θ__L, (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ θ__L }-> 𝟙)%T ⊸ (𝟙 -{ sem_row_union leakchan_row θ__L }-∘ 𝟙))%T.
  Proof using G channel1 channel2 inG0 inG1 inG2. (* TODO: remove channel1 channel2 from context *)
    iModIntro. iIntros (L).
    iIntros (f1 f2) "#Hff".
    brel_pures'.
    iApply fupd_brel.
    iMod token_alloc as (γtoka) "Htoka".
    iMod token_alloc as (γtokb) "Htokb".
    iMod (auth_alloc (#()%V)) as (γautha) "Hautha".
    iMod (auth_alloc (#()%V)) as (γauthb) "Hauthb".
    iMod dfrac_alloc as (γfraca) "Hfraca".
    iMod dfrac_alloc as (γfracb) "Hfracb".                         
    iModIntro.
    iApply (brel_wand with "[Htoka Htokb Hautha Hauthb Hfraca Hfracb][]").
    - iApply (F_AUTH_F_AUTH with "[$][$]").
      iApply (DH_KE_C_DH_real with "[$][$][$][$]").
      by iModIntro. 
    - iIntros (??) "!# $".
  Qed. 
    
  (* Verification of F_AUTH[C[DH_real]] ≤ F_AUTH[DH_KE] *)
  (*------------------------------------------------------------*)
  Lemma F_AUTH_C_DH_real_FAUTH_DH_KE :
     ⊢ sem_val_typed (λ: "f", F_AUTH leakauth1 (C "f" DH_real))%V (λ: "f", F_AUTH leakauth2 (DH_KE "f"))%V  
                         (∀ᵣ θ__L, (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ θ__L }-> 𝟙)%T ⊸ (𝟙 -{ sem_row_union leakchan_row θ__L }-∘ 𝟙))%T.
  Proof using G channel1 channel2 inG0 inG1 inG2.
    iModIntro. iIntros (L).
    iIntros (f1 f2) "#Hff".
    brel_pures'.
    iApply fupd_brel.
    iMod token_alloc as (γtoka) "Htoka".
    iMod token_alloc as (γtokb) "Htokb".
    iMod (auth_alloc (#()%V)) as (γautha) "Hautha".
    iMod (auth_alloc (#()%V)) as (γauthb) "Hauthb".
    iMod dfrac_alloc as (γfraca) "Hfraca".
    iMod dfrac_alloc as (γfracb) "Hfracb".                         
    iModIntro.
    iApply (brel_wand with "[Htoka Htokb Hautha Hauthb Hfraca Hfracb][]").
    - iApply (F_AUTH_F_AUTH with "[$][$]").
      iApply (C_DH_real_DH_KE with "[$][$][$][$]").
      by iModIntro. 
    - iIntros (??) "!# $".
  Qed.       
  
  (* Move this to a new file *)
  (* Verification of DH_SIM[F_KE] ≤ C[DH_rand] *)
  (*--------------------------------------------------*)
  
  Lemma DH_SIM_F_KE_C_DH_rand (f1 f2 : val) γtoka γtokb γfraca γfracb γautha γauthb L :
    token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    sem_val_typed f1 f2 (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-> 𝟙)%T -∗
    BREL DH_SIM (F_KE f1) ≤ C f2 DH_rand <|⊥|> 
      {{ λ v1 v2, ∀ c1 c2 : label, let ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                            BREL v1 (λ: "m", do: c1 (Send "m"))%V (λ: "m", do: c1 (Recv "m"))%V ≤
                                                 v2 (λ: "m", do: c2 (Send "m"))%V (λ: "m", do: c2 (Recv "m"))%V 
                                                 <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
  Proof with (repeat foldkont) using G inG0 inG1 inG2.
    iIntros "Htoka Htokb Ha Hb #Hff". 
    unfold DH_SIM, F_KE, C. 
    brel_pures'. iModIntro. 
    iIntros (c1 c2). set (ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
    brel_pures'.

    iApply brel_alloctape_l. iIntros (α) "!> Hα". brel_pures_l.
    iApply brel_alloctape_l. iIntros (β) "!> Hβ". brel_pures_l.
    iApply brel_alloc_l. iIntros (la) "!> Hla".
    iApply brel_alloc_l. iIntros (lb) "!> Hlb".

    unfold DH_rand. brel_pures'.
    
    iApply brel_effect_l. iIntros (leak) "!> Hleak !>". brel_pures'.

    iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame. simpl. iIntros (a) "Hα".
    iDestruct "Hβ" as (ms) "(%Hf' & Hβ)". apply map_eq_nil in Hf'. simplify_eq.
    iApply brel_couple_TU; [done|]. iFrame "Hβ". simpl. iIntros (b) "Hβ".
    brel_pures'.

    iApply brel_couple_rand_rand; first done. iIntros (c Hc).
    brel_pures'.

    iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
    iApply brel_effect_r. iIntros (gk2) "Hgk2 !>".
    brel_pures'.
    
    iApply fupd_brel.
    iMod (auth_upd (vgval (g ^+ a)%g) with "Ha") as "Ha".
    iMod (auth_upd (vgval $ g ^+ b)%g with "Hb") as "Hb".
    iMod (auth_persist with "Ha") as "#Ha".
    iMod (auth_persist with "Hb") as "#Hb".
    iModIntro.
    
    iApply fupd_brel.
    iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
    { iNext; iLeft;iFrame. }
    iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
    { iNext; iFrame. }
    iModIntro.
    
    iApply (brel_na_alloc
              ((β ↪ (n; [b]) ∗ lb ↦ NONEV)
               ∨ (β ↪□ (n; [])
                  ∗ lb ↦□ SOMEV #b)
              )%I
              betaN).
    iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_na_alloc
              ((α ↪ (n; [a]) ∗ la ↦ NONEV)
               ∨ (α ↪□ (n; [])
                  ∗ la ↦□ SOMEV #a))%I
              alphaN).
    iSplitL "Hα Hla"; [iNext; iFrame; iLeft; iFrame|].
    iIntros "#Hinva".
    
    unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff".
    set (θ := gkleakl leak gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    iDestruct "Hff" as "#Hff".
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    iDestruct "Hff" as "#Hff". 
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
             iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_l with "Hleak").
    iApply (brel_add_label_r with "Hgk2").
  
    iDestruct (brel_introduction_mono _ ([([leak;gk1],[gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].

    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures'|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".
    
    1 : { 
      brel_pures'; [apply Hk2; set_solver|split; [apply Hk1|];set_solver|]...
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hα & Hla) | #(Hα & Hla)] & Hclose)".
      - iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]"). iIntros "!> Hla". brel_pures'.
        iApply (brel_rand_l _ [AppRCtx _; AppRCtx _]).
        iAssert (α ↪N (n; [fin_to_nat a]))%I with "[Hα]" as "Hα".
        { iExists [a]. simpl. iFrame. done. }
        iFrame. iIntros "!>Hα _". brel_pures_l.
        iApply (brel_store_l _ _ _ [AppRCtx _; AppRCtx _] with "Hla").
        iIntros "!> Hla". brel_pures'.
        iApply (brel_exp_l [AppRCtx _]). brel_pures_l.
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft. simpl.
        iExists (vgval (g ^+ a)%g),  (vgval (g ^+ a)%g).
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
               
        iApply brel_value. iIntros "$ !>". brel_pures';[set_solver|]...
        
        (* Recv bob (either none or some) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
               
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"].
    
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_l with "Hla"). iIntros "!> _". brel_pures'.
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft.
        iExists _, _.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro. 
          - iModIntro. iRight. iFrame "#".
            iApply "Hclose". iNext.
            by iRight. }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. 
        iApply brel_value. iIntros "$ !>".
        brel_pures';[set_solver|].

        (* Recv bob (either none or some) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"]. }
    
    1 : {
      brel_pures'; [apply Hk2; set_solver|split; [apply Hk1|];set_solver|]...
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply (brel_introduction' [c1] [c2]).
      { apply elem_of_cons. right. apply list_elem_of_here. }
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iRight. iRight.
      do 2 (iSplit; try (iPureIntro; done)).
      iModIntro.
      iSplitL.
      - iApply brel_value. iIntros "$ !>".
        brel_pures'.
        iDestruct ("Hcont" with "Hnone") as "Hkk".
        iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"].
      - iIntros (m) "Ha'".
        iDestruct (auth_agree with "[$Ha] [$Ha']") as "<-".
        iApply brel_value. iIntros "$ !>".
        brel_pures';[set_solver|]...
        
        iApply (brel_na_inv _ _ betaN ); [set_solver|].
        iFrame "Hinvb". 
        iIntros "(>[(Hβ & Hlb) | #(Hβ & Hlb)] & Hclose)". 
        + iApply (brel_load_l _ _ _ [AppRCtx _; CaseCtx _ _] with "[$]").
          iIntros "!> Hlb". brel_pures_l.
          iApply (brel_rand_l _ [AppRCtx _; AppRCtx _]).
          iAssert (β ↪N (n; [fin_to_nat b]))%I with "[Hβ]" as "Hβ".
          { iExists [b]. simpl. iFrame. done. }
          iFrame. iIntros "!>Hβ _". brel_pures_l.
          iApply (brel_store_l _ _ _ [AppRCtx _; AppRCtx _] with "Hlb").
          iIntros "!> Hlb".
          brel_pures_l. 
          iApply (brel_exp_l [AppRCtx _]). brel_pures_l.
          
          iApply fupd_brel.
          iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
          iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
          iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
          iModIntro.
          iApply brel_na_close. iFrame.
          iSplitL; [iRight; iFrame "#"|].
          
          iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
          iApply (brel_introduction' [c1] [c2]).
          { apply elem_of_cons. right. apply list_elem_of_here. }
          iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight. iLeft.
          iExists _,_.
          iSplitL.
          { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
            - iModIntro. iLeft.
              iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
              by iModIntro. 
            - iModIntro. iRight. iFrame "#".
              iApply "Hclose". iNext.
              by iRight. }
          iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
          iModIntro.
          
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"].
          
        + iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
          iApply (brel_load_l with "Hlb"). iIntros "!> _". brel_pures'.
          
          iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
          iApply (brel_introduction' [c1] [c2]).
          { apply elem_of_cons. right. apply list_elem_of_here. }
          iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
          iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
          iRight. iLeft.
          iExists _,_.
          iSplitL.
          { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
            - iModIntro. iLeft.
              iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
              by iModIntro. 
            - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
          iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
          iModIntro.
          
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          iApply (brel_exhaustion _ _ [_;_] [_] with "[$]"); [done|done|iApply "IH"]. }
  Qed.
  
   

  (* Verification of C[DH_rand] ≤ DH_SIM[F_KE] *)
  (*--------------------------------------------------*)  

   Lemma C_DH_rand_DH_SIM_F_KE f1 f2 γtoka γtokb γfraca γfracb γautha γauthb L :
     token γtoka -∗
    token γtokb -∗
    own γautha (to_dfrac_agree (DfracOwn 1) #()%V) -∗
    own γauthb (to_dfrac_agree (DfracOwn 1) #()%V) -∗
     sem_val_typed f1 f2 (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ L }-> 𝟙)%T -∗
     BREL C f1 DH_rand ≤ DH_SIM (F_KE f2) <|⊥|> 
       {{ λ v1 v2, ∀ c1 c2 : label, let ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb in
                                    BREL v1 (λ: "m", do: c1 (Send "m"))%V (λ: "m", do: c1 (Recv "m"))%V ≤
                                      v2 (λ: "m", do: c2 (Send "m"))%V (λ: "m", do: c2 (Recv "m"))%V 
                                      <| (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L) |> {{ (λ w1 w2, 𝟙%T w1 w2) }} }}.
   Proof with (repeat foldkont) using G inG0 inG1 inG2.
     iIntros "Htoka Htokb Ha Hb #Hff". 
     unfold DH_SIM, F_KE, C. 
     brel_pures'. iModIntro. 
     iIntros (c1 c2). set (ac := authchan_row c1 c2 γtoka atokN γtokb btokN γfraca γfracb γautha γauthb).
     unfold DH_rand.
     brel_pures'.

     iApply brel_alloctape_r. iIntros (α) "Hα". brel_pures_r.
     iApply brel_alloctape_r. iIntros (β) "Hβ". brel_pures_r.
     iApply brel_alloc_r. iIntros (la) "Hla". brel_pures_r.
     iApply brel_alloc_r. iIntros (lb) "Hlb". brel_pures_r. 
     iAssert (α ↪ₛN (n; []))%I with "[Hα]" as "Hα".
     { iExists []. iSplit; done. }
     iApply brel_couple_UT; first done. iFrame "Hα". iIntros (a ?) "!> Hα".
     iAssert (β ↪ₛN (n; []))%I with "[Hβ]" as "Hβ".
     { iExists []. iSplit; done. }
     iApply brel_couple_UT; first done. iFrame "Hβ". iIntros (b ?) "!> Hβ". simpl.
     brel_pures'.

     iApply brel_effect_r. iIntros (leak) "Hleak !>". brel_pures'.

     iApply brel_couple_rand_rand; first done. iIntros (c Hc).
     brel_pures'.

     iApply brel_effect_l. iIntros (gk1) "!> Hgk1 !>".
     iApply brel_effect_r. iIntros (gk2) "Hgk2 !>".
     brel_pures'.

     iApply fupd_brel.
     iMod (auth_upd (vgval (g ^+ a)%g) with "Ha") as "Ha".
     iMod (auth_upd (vgval (g ^+ b)%g) with "Hb") as "Hb".
     iMod (auth_persist with "Ha") as "#Ha".
     iMod (auth_persist with "Hb") as "#Hb".
     iModIntro.
     
     iApply fupd_brel.
     iMod (inv_alloc atokN _ (token γtoka ∨ own γfraca DfracDiscarded)%I with "[Htoka]") as "#Hinvta".
     { iNext; iLeft;iFrame. }
     iMod (inv_alloc btokN _ (token γtokb ∨ own γfracb DfracDiscarded)%I with "[Htokb]") as "#Hinvtb".
     { iNext; iFrame. }
     iModIntro.
     
     iApply (brel_na_alloc
               ((β ↪ₛN (n; [b]) ∗ lb ↦ₛ NONEV)
                ∨ (β ↪ₛ□ (n; [])
                   ∗ lb ↦ₛ□ SOMEV #b)
               )%I
               betaN).
     iSplitL "Hβ Hlb"; [iNext; iFrame; iLeft; iFrame|].
     iIntros "#Hinvb".
     
     iApply (brel_na_alloc
               ((α ↪ₛN (n; [a]) ∗ la ↦ₛ NONEV)
                ∨ (α ↪ₛ□ (n; [])
                   ∗ la ↦ₛ□ SOMEV #a))%I
               alphaN).
     iSplitL "Hα Hla"; [iNext; iFrame; iLeft; iFrame|].
     iIntros "#Hinva".
     
     unfold sem_val_typed. simpl. iDestruct "Hff" as "#Hff".
    set (θ := gkleakr leak gk1 gk2).
    iSpecialize ("Hff" $! θ).  
    iDestruct "Hff" as "#Hff".
    unfold sem_ty_arr, sem_ty_mbang. simpl.
    iDestruct "Hff" as "#Hff". 
    iAssert (sem_val_typed (λ: "party", do: gk1 "party")%V (λ: "party", do: gk2 "party")%V ((𝟙 + 𝟙)%T -{ θ }-> (Option 𝔾))%T) as "Hgg".
    { iModIntro. rewrite /sem_ty_arr /sem_ty_mbang //=. iIntros (??) "!# #(%&%&[(->&->&->&->)|(->&->&->&->)])";
        brel_pures';
        iApply brel_introduction'; try constructor;
        iExists _,_,[],[],_; do 2 (iSplit; [by iPureIntro|]; iSplit; [iPureIntro; apply NeutralEctx_nil|]);
                          iSplit; try (iIntros (??) "!# H"; iApply "H").
      1 : iSplit; first (iPureIntro; left; split; done).
      2 : iSplit; first (iPureIntro; right; split; done).
      all : iModIntro; iSplitL; last iIntros (key); brel_pures'; iApply brel_value; iIntros "$ !>"; 
             iExists _,_; [iLeft; by iPureIntro| iRight; iPureIntro; repeat (split; first done); by eexists]. }
    unfold sem_val_typed. simpl. iDestruct "Hgg" as "#Hgg".
    iSpecialize ("Hff" with "Hgg"). 

    iApply brel_new_theory.
    iApply (brel_add_label_l with "Hgk1").
    iApply (brel_add_label_r with "Hgk2").
    iApply (brel_add_label_r with "Hleak").
  
    iDestruct (brel_introduction_mono _ ([([gk1],[leak;gk2],GetKey gk1 gk2)] ++ (iLblSig_to_iLblThy ac) ++ (iLblSig_to_iLblThy L)) with "[][$Hff]") as "Hf".
    { iApply to_iThy_le_intro'. apply submseteq_skip. by apply submseteq_cons. }
    iApply (brel_exhaustion with "[$]"); [done|done|].

    iLöb as "IH".
    
    iSplit; [iIntros (v1 v2) "!# (-> & ->)"; by brel_pures'|].
    
    iIntros (?????) "!# %Hk1 %Hk2 ([(-> & ->)|(-> & ->)] & #(Hnone & Hsome)) #Hcont".

    1 : {
      brel_pures'; [split; [apply Hk2|];set_solver|apply Hk1; set_solver|]...
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hα & Hla) | #(Hα & Hla)] & Hclose)".
      - iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "Hla").
        iIntros "Hla". brel_pures_r.
        iApply (brel_rand_r _ [AppRCtx _; AppRCtx _] with "Hα").
        iIntros "Hα _". brel_pures_r.
        iApply (brel_store_r _ _ _ _[AppRCtx _; AppRCtx _] with "Hla").
        iIntros "Hla".
        brel_pures_r. 
        iApply (brel_exp_r [AppRCtx _]). brel_pures_r.
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hla") as "#Hla".
        iDestruct "Hα" as (ns) "(%Hf & Hα)". apply map_eq_nil in Hf. simplify_eq.
        iMod (ghost_map_elem_persist with "Hα") as "#Hα".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL; [iNext; iRight; iFrame "#"|].
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft. 
        iExists _, _.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro.
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        iModIntro.
        
        iApply brel_value. iIntros "$ !>".
        brel_pures'; [set_solver|].
        
        (* Recv bob (either none or some) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }        
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.

        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"].
          
      - iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
        iApply (brel_load_r with "Hla"). iIntros "_". brel_pures'.
        
        (* Send (gA, bob) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iLeft.
        iExists _, _.
        iSplitL.
        { iMod (inv_acc with "Hinvta") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
          - iModIntro. iLeft.
            iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
            by iModIntro.
          - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
        iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
        
        iModIntro. iApply brel_value. iIntros "$ !>".
        brel_pures'; [set_solver|].

        (* Recv bob (either none or some) *)
        iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
        iApply (brel_introduction' [c1] [c2]).
        { apply elem_of_cons. right. apply list_elem_of_here. }          
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iLeft. iRight.
        do 2 (iSplit; try (iPureIntro; done)).
        iModIntro.
        iSplitL.
        
        (* Recv bob = None *)
        + iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hnone") as "Hkk".
          iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"].
          
        (* Recv bob = Some gB *)
        + iIntros (m) "Ha'".
          iDestruct (auth_agree with "[$Hb] [$Ha']") as "<-".
          iApply brel_value. iIntros "$ !>".
          brel_pures'.
          iDestruct ("Hcont" with "Hsome") as "Hkk".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"]. }
    
     1 : {
       brel_pures'; [split; [apply Hk2|];set_solver|apply Hk1; set_solver|]...
       
       (* Recv alice (either none or some) *)
       iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
       iApply (brel_introduction' [c1] [c2]).
       { apply elem_of_cons. right. apply list_elem_of_here. }
       iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
       iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
       iRight. iRight.
       do 2 (iSplit; try (iPureIntro; done)).
       iModIntro.
       iSplitL.
       
       (* Recv alice = None *)
       + iApply brel_value. iIntros "$ !>".
         brel_pures'.
         iDestruct ("Hcont" with "Hnone") as "Hkk".
         iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"].
         
       + iIntros (m) "Ha'".
         iDestruct (auth_agree with "[$Ha] [$Ha']") as "<-".
         iApply brel_value. iIntros "$ !>".
         brel_pures'; [set_solver|].
         iApply (brel_na_inv _ _ betaN ); [set_solver|].
         iFrame "Hinvb". 
         iIntros "([(>Hβ & >Hlb) | (#>Hβ & #>Hlb)] & Hclose)".
         * iApply (brel_load_r _ _ _ _ [AppRCtx _; CaseCtx _ _] with "Hlb").
           iIntros "Hlb". brel_pures_r.
           iApply (brel_rand_r _ [AppRCtx _; AppRCtx _] with "Hβ").
           iIntros "Hβ _". brel_pures_r.
           iApply (brel_store_r _ _ _ _[AppRCtx _; AppRCtx _] with "Hlb").
           iIntros "Hlb".
           brel_pures'.
           iApply (brel_exp_r [AppRCtx _]). brel_pures_r.
           
           iApply fupd_brel.
           iMod (ghost_map_elem_persist with "Hlb") as "#Hlb".
           iDestruct "Hβ" as (ns) "(%Hf & Hβ)". apply map_eq_nil in Hf. simplify_eq.
           iMod (ghost_map_elem_persist with "Hβ") as "#Hβ".
           iModIntro.
           iApply brel_na_close. iFrame.
           iSplitL; [iNext; iRight; iFrame "#"|].
           
           (* Send (gB, alice) *)
           iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
           iApply (brel_introduction' [c1] [c2]).
           { apply elem_of_cons. right. apply list_elem_of_here. }
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iRight. iLeft. 
           iExists _,_.
           iSplitL.
           { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
             - iModIntro. iLeft.
               iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
               by iModIntro. 
             - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
           iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
           iModIntro.
           
           iApply brel_value. iIntros "$ !>".
           brel_pures'.
           
           iDestruct ("Hcont" with "Hsome") as "Hkk".
           iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"].
           
         * iApply brel_na_close. iFrame. iSplitL; [iRight; iFrame "#"|].
           iApply (brel_load_r with "Hlb"). iIntros "_". brel_pures'.
           
           (* Send (gB, alice) *)
           iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
           iApply (brel_introduction' [c1] [c2]).
           { apply elem_of_cons. right. apply list_elem_of_here. }
           iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
           iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
           iRight. iLeft.
           iExists _,_.
           iSplitL.
           { iMod (inv_acc with "Hinvtb") as "([>Htok | >#Hfrac'] & Hclose)"; try done.
             - iModIntro. iLeft.
               iIntros. iFrame. iMod ("Hclose" with "[$]") as "_". iFrame "#". 
               by iModIntro. 
             - iModIntro. iRight. by iMod ("Hclose" with "[$]") as "_". }
           iSplit; first ( do 2 (iSplit; try (iPureIntro; done))).
           
           iModIntro. iApply brel_value. iIntros "$ !>".
           brel_pures'.
           iDestruct ("Hcont" with "Hsome") as "Hkk".
           iApply (brel_exhaustion _ _ [_] [_;_] with "[$]"); [done|done|iApply "IH"]. }
   Qed.
 
   
  (* Verification of F_AUTH[DH_SIM[F_KE]] ≤ F_AUTH[C[DH_rand]] *)
  (*------------------------------------------------------------*)
  Lemma F_AUTH_DH_SIM_F_KE_FAUTH_C_DH_rand :
     ⊢ sem_val_typed (λ: "f", F_AUTH leakauth1 (DH_SIM (F_KE "f")))%V (λ: "f", F_AUTH leakauth2 (C "f" DH_rand))%V  
                         (∀ᵣ θ__L, (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ θ__L }-> 𝟙)%T ⊸ (𝟙 -{ sem_row_union leakchan_row θ__L }-∘ 𝟙))%T.
  Proof using G channel1 channel2 inG0 inG1 inG2.
    iModIntro. iIntros (L).
    iIntros (f1 f2) "#Hff".
    brel_pures'.
    iApply fupd_brel.
    iMod token_alloc as (γtoka) "Htoka".
    iMod token_alloc as (γtokb) "Htokb".
    iMod (auth_alloc (#()%V)) as (γautha) "Hautha".
    iMod (auth_alloc (#()%V)) as (γauthb) "Hauthb".
    iMod dfrac_alloc as (γfraca) "Hfraca".
    iMod dfrac_alloc as (γfracb) "Hfracb".                         
    iModIntro.
    iApply (brel_wand with "[Htoka Htokb Hautha Hauthb Hfraca Hfracb][]").
    - iApply (F_AUTH_F_AUTH with "[$][$]"). 
      iApply (DH_SIM_F_KE_C_DH_rand with "[$][$][$][$]").
      by iModIntro. 
    - iIntros (??) "!# $".
  Qed.
    
  (* Verification of F_AUTH[C[DH_rand]] ≤ F_AUTH[DH_SIM[F_KE]] *)
  (*------------------------------------------------------------*)
  Lemma F_AUTH_C_DH_rand_FAUTH_DH_SIM_F_KE :
    ⊢ sem_val_typed (λ: "f", F_AUTH leakauth1 (C "f" DH_rand))%V (λ: "f", F_AUTH leakauth2 (DH_SIM (F_KE "f")))%V  
        (∀ᵣ θ__L, (∀ᵣ θₕ, ((sem_ty_sum 𝟙 𝟙) -{ θₕ }-> (Option 𝔾)) -{ sem_row_union θₕ θ__L }-> 𝟙)%T ⊸ (𝟙 -{ sem_row_union leakchan_row θ__L }-∘ 𝟙))%T.
  Proof using channel1 channel2 G inG0 inG1 inG2.
    iModIntro. iIntros (L).
    iIntros (f1 f2) "#Hff".
    brel_pures'.
    iApply fupd_brel.
    iMod token_alloc as (γtoka) "Htoka".
    iMod token_alloc as (γtokb) "Htokb".
    iMod (auth_alloc (#()%V)) as (γautha) "Hautha".
    iMod (auth_alloc (#()%V)) as (γauthb) "Hauthb".
    iMod dfrac_alloc as (γfraca) "Hfraca".
    iMod dfrac_alloc as (γfracb) "Hfracb".                         
    iModIntro.
    iApply (brel_wand with "[Htoka Htokb Hautha Hauthb Hfraca Hfracb][]").
    - iApply (F_AUTH_F_AUTH with "[$][$]"). 
      iApply (C_DH_rand_DH_SIM_F_KE with "[$][$][$][$]").
      by iModIntro. 
    - iIntros (??) "!# $".
  Qed.

End handlee_verification.

                
