From clutch.prob_eff_lang.probblaze Require Export notation logic valgroup proofmode.
From iris.proofmode Require Import base proofmode classes.
From iris.base_logic.lib Require Import  na_invariants.
From iris.algebra Require Import agree excl auth frac excl_auth.
From iris.algebra.lib Require Import dfrac_agree.

Import fingroup.
Import valgroup_tactics.

Section definition.

  Definition Send (e : expr) := InjL e.
  Definition Recv (e : expr) := InjR e.
  Definition SendV (v : val) := InjLV v.
  Definition RecvV (v : val) := InjRV v.
  Definition bob := InjLV #()%V.
  Definition alice := InjRV #()%V.



  Definition F_AUTH (channel : label) f : expr :=
    let: "m1" := ref NONEV in
    let: "m2" := ref NONEV in

    handle: f with
    | effect channel "message", rec "k" =>
        match: "message" with
        (* SEND *)
        | InjL "payload" =>
            let, ("m", "dst") := "payload" in
            match: "dst" with
              (* Alice *)
              InjL <> => match: !"m1" with (* Send only the first value. Discard all others.  *)
                         NONE => "m1" <- SOME "m";; (do: channel (Send ("m", "dst")));; "k" #()%V
                       | SOME "x" => "k" #()%V 
                         end
            (* Bob *)
            | InjR <> => match: !"m2" with
                          NONE => "m2" <- SOME "m";; (do: channel (Send ("m", "dst")));; "k" #()%V
                        | SOME "x" => "k" #()%V 
                        end
            end
        (* Recv *)
        | InjR "from" =>
            let: "r" := (do: channel (Recv "from")) in
             match: "r" with
               NONE => "k" NONEV
             | SOME "x" => match: "from" with
                             (* Alice *)
                             InjL <> => match: !"m2" with
                                          NONE => "k" NONEV
                                        | SOME "m" => "k" (SOME "m")
                                        end
                           (* Bob *)
                           | InjR <> => match: !"m1" with
                                          NONE => "k" NONEV
                                        | SOME "m" => "k" (SOME "m")
                                        end
                           end
             end
        end
    | return "y" => #()%V end.

End definition.


Section theories.
  Context `{!probblazeRGS Σ}.
  Variable (channel : label).
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)

  
  (* Resources *)
  (*------------------------------------------------------------*)

  Definition token γ := own γ (Excl ()).

   Lemma token_agree γ : ⊢ token γ -∗ token γ -∗ False.
  Proof.
    iIntros "Ha Hb". 
    iDestruct (own_valid_2 with "Ha Hb") as "%Hvalid".
    done.
  Qed.

  Lemma auth_alloc v : ⊢ |==> ∃ γ, own γ (to_dfrac_agree (DfracOwn 1) v).
  Proof.
    iApply own_alloc.
    constructor; done.
  Qed.
  
  Lemma auth_upd v' γ v : ⊢ own γ (to_dfrac_agree (DfracOwn 1) v) -∗ |==>  own γ (to_dfrac_agree (DfracOwn 1) v').
  Proof.
    iApply own_update.
    apply cmra_update_exclusive.
    constructor; done.
  Qed.

  Lemma auth_agree γ q q' v v' :
    ⊢ own γ (to_dfrac_agree q v) -∗ own γ (to_dfrac_agree q' v') -∗ ⌜ v = v' ⌝.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    by apply dfrac_agree_op_valid in H as (?&H). 
  Qed.

  Lemma auth_persist γ q v : ⊢ own γ (to_dfrac_agree q v) -∗ |==> own γ (to_dfrac_agree DfracDiscarded v).
  Proof.
    iApply own_update.
    by apply dfrac_agree_persist.
  Qed.

  Lemma dfrac_alloc : ⊢ |==> ∃ γ, own γ (DfracOwn 1).
  Proof.
    iApply own_alloc.
    done.
  Qed.                               
  
  Lemma dfrac_persist γ (q : dfrac) : ⊢ own γ q -∗ |==> own γ DfracDiscarded.
  Proof.
    iApply own_update.
    apply dfrac_discard_update.
  Qed.

  Lemma dfrac_contra γ (q : dfrac) : ⊢ own γ q -∗ own γ (DfracOwn 1) -∗ False.
  Proof.
    iIntros "H1 H2".
    iDestruct (own_op with "[$H1 $H2]") as "H".
    iDestruct (own_valid with "H") as "%H".
    iPureIntro.
    eapply exclusive_r; eauto using dfrac_full_exclusive.
  Qed.
  
  (* Theories for the implementations *)
  (*------------------------------------------------------------*)
  
  Program Definition SendBobAuth γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,            
                ∃ v1 v2 v1' v2': val, (* Consider moving (u,v) into first message branch to allow for more general behaviour *)
                  ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded (v1, v2)%V) ∗ ⌜(v1, v2) = (v1', v2')⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                   (⌜ e1 = do: channel (SendV ((v1, v2), bob)) ⌝%E ∗
                    ⌜ e2 = do: channel (SendV ((v1',v2'), bob)) ⌝%E)  ∗ 
                   (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAliceAuth γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV alice) ⌝%E ∗
                ▷ (Q NONEV NONEV ∧ (∀ u v : val, own γauth (to_dfrac_agree DfracDiscarded (u, v)%V) -∗ Q (SOMEV (u,v)) (SOMEV (u, v))))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition SendAliceAuth γtok γfrac γauth ι : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m m' : val, ((|={⊤, ⊤ ∖ ↑ι }=> ((own γfrac DfracDiscarded -∗ (|={⊤ ∖ ↑ι, ⊤}=> token γtok ∗ own γauth (to_dfrac_agree DfracDiscarded m) ∗ ⌜m = m'⌝)) ∨ |={⊤ ∖ ↑ι , ⊤}=> own γfrac DfracDiscarded)) ∗  
                               (⌜ e1 = do: channel (SendV (m, alice)) ⌝%E ∗
                                ⌜ e2 = do: channel (SendV (m', alice)) ⌝%E)  ∗ 
                               ▷ (Q (Val #()%V) (Val #()%V)))
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBobAuth γauth : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV bob) ⌝%E ∗
                (* Added a later, since RHS doesn't take a step *)
                ▷ (Q NONEV NONEV ∧ (∀ m, own γauth (to_dfrac_agree DfracDiscarded m) -∗ Q (SOMEV m) (SOMEV m)))
             )%I.
  Next Obligation. solve_proper. Qed.

  (* Theories for auth channel interacting with the environment *)
  (*------------------------------------------------------------*)
  Program Definition SendBob : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m : val,
                  ⌜ e1 = do: channel (SendV (m, bob)) ⌝%E ∗
                  ⌜ e2 = do: channel (SendV (m, bob)) ⌝%E ∗
                  Q (Val #()%V) (Val #()%V)
             )%I. 
  Next Obligation. solve_proper. Qed.

  Program Definition SendAlice : iThy Σ :=
    λ e1 e2, (λne Q,
                ∃ m : val, 
                  ⌜ e1 = do: channel (SendV (m, alice)) ⌝%E ∗
                  ⌜ e2 = do: channel (SendV (m, alice)) ⌝%E ∗
                  Q (Val #()%V) (Val #()%V)
             )%I. 
  Next Obligation. solve_proper. Qed.

  Program Definition RecvBob : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV bob) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV bob) ⌝%E ∗
                ((∀ b1 b2 : nat, Q (SOMEV #b1) (SOMEV #b2)) ∧ Q NONEV NONEV)
             )%I.
  Next Obligation. solve_proper. Qed.

  Program Definition RecvAlice : iThy Σ :=
    λ e1 e2, (λne Q,
                ⌜ e1 = do: channel (RecvV alice) ⌝%E ∗
                ⌜ e2 = do: channel (RecvV alice) ⌝%E ∗
                ((∀ b1 b2 : nat, Q (SOMEV #b1) (SOMEV #b2)) ∧ Q NONEV NONEV)
             )%I.
  Next Obligation. solve_proper. Qed.

  Definition LblEnv := [([channel], [channel], iThySum (iThySum SendAlice RecvAlice) (iThySum SendBob RecvBob))].

  Definition X γtoka atokN γtokb btokN γfraca γfracb γautha γauthb : iThy Σ := iThyTraverse [channel] [channel]
                                                                     (iThySum (iThySum (SendAliceAuth γtokb γfracb γauthb btokN) (RecvBobAuth γauthb))
                                                                        (iThySum (SendBobAuth γtoka γfraca γautha atokN) (RecvAliceAuth γautha))).
 
  Definition LblAuthChannel γtoka atokN γtokb btokN γfraca γfracb γautha γauthb : iLblThy Σ :=
    [([channel],[channel], (iThySum (iThySum (SendAliceAuth γtokb γfracb γauthb btokN) (RecvBobAuth γauthb))
                                (iThySum (SendBobAuth γtoka γfraca γautha atokN) (RecvAliceAuth γautha))))].
  
End theories.

Section verification.
  Context `{!probblazeRGS Σ}.
  Context {channel : label}.
  Context `{!inG Σ (exclR unitO), !inG Σ dfracO, !inG Σ (dfrac_agreeR valO)}.
  Context {vg : val_group}.           (* A group on a subset of values. *)
  Context {cg : clutch_group_struct}. (* Implementations of the vg group operations *)
  Context {vgg : @val_group_generator vg}.   (* G is generated by g. *)
  Context {γtoka γtokb γfraca γfracb γautha γauthb : gname}.

  Definition alphaN : namespace := nroot .@ "alpha".
  Definition betaN : namespace := nroot .@ "beta".
  Definition atokN : namespace := nroot .@ "atokN".
  Definition btokN : namespace := nroot .@ "btokN".

  Definition LblThy := @LblAuthChannel _  _ channel _ _ _ γtoka atokN γtokb btokN γfraca γfracb γautha γauthb.

   (* Verification of F_AUTH ≤ F_AUTH *)
     (*------------------------------------------------------------*)
     
  Lemma F_AUTH_F_AUTH f1 f2 L :
    is_closed_expr ∅ f1 →
    is_closed_expr ∅ f2 →
    own γfraca (DfracOwn 1) -∗
    own γfracb (DfracOwn 1) -∗
    BREL f1 ≤ f2 <|LblThy ++  L|> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }} -∗
    BREL F_AUTH channel f1 ≤ F_AUTH channel  f2 <|to_iThyIfMono OS (LblEnv channel ++  L) |> {{ (λ v1 v2, ⌜ v1 = v2 ⌝) }}.
  Proof.
    iIntros (Hf1closed Hf2closed) "Hfraca Hfracb Hff".
    iApply brel_alloc_l. iIntros (l1) "!> Hl1".
    iApply brel_alloc_l. iIntros (l2) "!> Hl2".
    brel_pures_l. do 2 rewrite subst_is_closed_empty; try done.
    iApply brel_alloc_r. iIntros (l1') "Hl1s".
    iApply brel_alloc_r. iIntros (l2') "Hl2s".
    brel_pures_r. do 2 rewrite subst_is_closed_empty; try done.
    
    iApply (brel_na_alloc
              ((l1 ↦ NONEV ∗ l1'  ↦ₛ NONEV ∗ own γfraca (DfracOwn 1))
               ∨ (∃ u v : val , l1 ↦□ SOMEV (u,v) ∗ l1' ↦ₛ□ SOMEV (u,v) ∗ token γtoka
                         ∗ own γfraca DfracDiscarded
                         ∗ own γautha (to_dfrac_agree DfracDiscarded (u,v)%V))) alphaN).
    iSplitL "Hl1 Hl1s Hfraca"; [iNext; iLeft; iFrame|].
    iIntros "#Hinva".
    
    iApply (brel_na_alloc
              ((l2 ↦ NONEV ∗ l2'  ↦ₛ NONEV ∗ own γfracb (DfracOwn 1))
               ∨ (∃ gB , l2 ↦□ SOMEV gB∗ l2' ↦ₛ□ SOMEV gB ∗ token γtokb
                         ∗ own γfracb DfracDiscarded
                         ∗ own γauthb (to_dfrac_agree DfracDiscarded gB))) betaN).
    iSplitL "Hl2 Hl2s Hfracb"; [iNext; iLeft; iFrame|].
    iIntros "#Hinvb".
    
    iApply (brel_exhaustion' OS _ _ [_] [_] with "[Hff]"); [done|done| |].
    { iApply (brel_introduction_mono with "[][$]"). iApply to_iThy_le_intro'.
      unfold LblThy, LblAuthChannel. simpl. done. }
    iLöb as "IH".
    iSplit; [iIntros (v1 v2) "->"; by brel_pures|].
    iIntros (?????) "%Hk1 %Hk2 [[(%&%&Hupd&(->&->)&HQ) | (->&->&HNoneHSome)]| [(%&%&%&%&Hupd&(->&->)&HQ) | (->&->&HNoneHSome)]] Hkont".

    1 : {
      iApply (brel_na_inv _ _ betaN ); [set_solver|].
      iFrame "Hinvb". 
      iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfracb") as "#Hfracb".
        iMod ("Hupd" with "Hfracb") as "(Htok & Hauth & <-)".
        iModIntro.
        iApply (brel_handle_os_l []); [apply Hk1;set_solver|].
        iIntros (rl) "!> Hrl".
        iApply (brel_handle_os_r []); [apply Hk2;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures.
        
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl2"). iIntros "!> Hl2".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "[$]"). iIntros "!> Hl2".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl2s"). iIntros "Hl2s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy|iApply to_iThy_le_refl|].
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl2s") as "#Hl2s".
        iMod (ghost_map_elem_persist with "Hl2") as "#Hl2".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists m; iFrame "#"; iFrame|].
        
        iApply brel_introduction'; first apply list_elem_of_here.
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iExists _.
        iSplitL; last (iIntros (??) "!> H"; iApply "H").
        iLeft. iLeft.
        iExists _.
        do 2 (iSplit; try (iPureIntro; done)).
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]"). 
        
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfracb") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htokb"; [iNext; iRight; iExists gB; iFrame; iFrame "#"|].
        iApply (brel_handle_os_l []); [apply Hk1;set_solver|].
        iIntros (rl) "!> Hrl".
        iApply (brel_handle_os_r []); [apply Hk2;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures. 
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl2"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl2s"). iIntros "_".
        brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]"). 
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }

    1 : {
      iApply (brel_handle_os_l []); [apply Hk1;set_solver|].
      iIntros (rl) "!> Hrl".
      iApply (brel_handle_os_r []); [apply Hk2;set_solver|].
      iIntros (rr) "Hrr". 
      brel_pures.
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply brel_introduction'; [apply list_elem_of_here|].
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iExists _.
      iSplitL; last (iIntros (??) "!> H"; iApply "H").
      iRight. iRight. do 2 (iSplit; try (iPureIntro; done)).
      iSplit; last first.
      
      + iApply brel_value. iIntros "$ !>". brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        iDestruct "HNoneHSome" as "(HNone&_)".
        iDestruct ("Hkont" with "HNone") as "Hbrel".
        iApply (brel_exhaustion' OS _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
            
      + iIntros (b1 b2). iApply brel_value. iIntros "$ !>".
        brel_pures.
        iApply (brel_na_inv _ _ betaN); [set_solver|].
        iFrame "Hinvb". 
        iIntros "(>[(Hl2 & Hl2s & Hfracb) | (%gB & #Hl2 & #Hl2s & Htokb & #Hfracb & #Hauthb)] & Hclose)".
        * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl2".
          iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl2s".
          brel_pures.
          
          iApply brel_na_close. iFrame. iSplitL "Hl2 Hl2s Hfracb"; [iLeft; iFrame|].
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]"). 

          iDestruct "HNoneHSome" as "(HNone&_)".
          iDestruct ("Hkont" with "HNone") as "Hbrel".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
          
        * iApply brel_na_close. iFrame. iSplitL "Htokb"; [iRight; iFrame "#"; iFrame|].
          iApply (brel_load_l with "Hl2"). iIntros "!> _".
          iApply (brel_load_r with "Hl2s"). iIntros "_". 
          brel_pures.
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]"). 

          iDestruct "HNoneHSome" as "(_&HSome)".
          iDestruct ("HSome" with "Hauthb") as "HS".
          iDestruct ("Hkont" with "HS") as "Hbrel".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    
    1 : {
      iApply (brel_na_inv _ _ alphaN ); [set_solver|].
      iFrame "Hinva". 
      iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%u & %v & #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        2 : { by iDestruct (dfrac_contra with "[Hupd][$]") as "Hcontra". }
        iMod (dfrac_persist with "Hfraca") as "#Hfraca".
        iMod ("Hupd" with "Hfraca") as "(Htok & Hauth & %Heq)".
        inversion Heq.
        iModIntro.
        iApply (brel_handle_os_l []); [apply Hk1;set_solver|].
        iIntros (rl) "!> Hrl".
        iApply (brel_handle_os_r []); [apply Hk2;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures.
              
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_store_l _ _ _ [AppRCtx _] with "Hl1"). iIntros "!> Hl1".
        iApply (brel_store_r _ _ _ _ [AppRCtx _] with "Hl1s"). iIntros "Hl1s".
        brel_pures.
        iApply (brel_bind [AppRCtx _] [AppRCtx _]); [iApply traversable_to_iThy| iApply to_iThy_le_refl|].
        
        iApply fupd_brel.
        iMod (ghost_map_elem_persist with "Hl1s") as "#Hl1s".
        iMod (ghost_map_elem_persist with "Hl1") as "#Hl1".
        iModIntro.
        iApply brel_na_close. iFrame.
        iSplitL "Htok Hauth"; [iNext; iRight; iExists v1', v2'; iFrame "#"; iFrame|].
        
        iApply brel_introduction'; first apply list_elem_of_here.
        iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
        iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
        iExists _.
        iSplitL; last (iIntros (??) "!> H"; iApply "H").
        iRight. iLeft.
        iExists _.
        do 2 (iSplit; try (iPureIntro; done)).
        iApply brel_value. iIntros "$ !>".
        brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]"). 
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        iApply (brel_exhaustion' OS _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
     
      - iApply fupd_brel. iMod "Hupd" as "[Hupd | Hupd]"; [|iMod "Hupd"; iModIntro].
        1 : { iMod ("Hupd" with "Hfraca") as "(Hcontra & _)". by iDestruct (token_agree with "[$][$]") as "Hcontra". }
        iApply brel_na_close. iFrame.
        iSplitL "Htoka"; [iNext; iRight; iExists _,_; iFrame; iFrame "#"|].
        iApply (brel_handle_os_l []); [apply Hk1;set_solver|].
        iIntros (rl) "!> Hrl".
        iApply (brel_handle_os_r []); [apply Hk2;set_solver|].
        iIntros (rr) "Hrr". 
        brel_pures.
        iApply (brel_load_l _ _ _ [CaseCtx _ _] with "Hl1"). iIntros "!> _".
        iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "Hl1s"). iIntros "_".
        brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]"). 
        iDestruct ("Hkont" with "HQ") as "Hbrel".
        
        iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done| done|]. iApply "IH". }

    1 : {
      iApply (brel_handle_os_l []); [apply Hk1;set_solver|].
      iIntros (rl) "!> Hrl".
      iApply (brel_handle_os_r []); [apply Hk2;set_solver|].
      iIntros (rr) "Hrr". 
      brel_pures.
      iApply (brel_bind' [_] [_]); [iApply traversable_to_iThy|].
      iApply brel_introduction'; [apply list_elem_of_here|].
      iExists _, _, [], [], _. do 2 (iSplit; [done|]; iSplit; [iPureIntro; apply _|]).
      iSplitL; [|by iIntros "!>" (??) "H"; iApply "H"].
      iExists _.
      iSplitL; last (iIntros (??) "!> H"; iApply "H").
      iLeft. iRight. do 2 (iSplit; try (iPureIntro; done)).
      iSplit; last first.
      
      + iApply brel_value. iIntros "$ !>". brel_pures.
        iApply (brel_cont_l with "[$]"). iModIntro.
        iApply (brel_cont_r with "[$]").
        iDestruct "HNoneHSome" as "(HNone&_)".
        iDestruct ("Hkont" with "HNone") as "Hbrel".
        iApply (brel_exhaustion' OS _ _  [_] [_] with "[$]"); [done|done|]. iApply "IH".
        
      + iIntros (b1 b2). iApply brel_value. iIntros "$ !>".
        brel_pures.
        iApply (brel_na_inv _ _ alphaN); [set_solver|].
        iFrame "#". 
        iIntros "(>[(Hl1 & Hl1s & Hfraca) | (%u&%v& #Hl1 & #Hl1s & Htoka & #Hfraca & #Hautha)] & Hclose)".
        * iApply (brel_load_l _ _ _ [CaseCtx _ _] with "[$]"). iIntros "!> Hl1".
          iApply (brel_load_r _ _ _ _ [CaseCtx _ _] with "[$]"). iIntros "Hl1s".
          brel_pures.
          
          iApply brel_na_close. iFrame. iSplitL "Hl1 Hl1s Hfraca"; [iLeft; iFrame|].
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]"). 

          iDestruct "HNoneHSome" as "(HNone&_)".
          iDestruct ("Hkont" with "HNone") as "Hbrel".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH".
          
        * iApply brel_na_close. iFrame. iSplitL "Htoka"; [iRight; iFrame "#"; iFrame|].
          iApply (brel_load_l with "Hl1"). iIntros "!> _".
          iApply (brel_load_r with "Hl1s"). iIntros "_". 
          brel_pures.
          iApply (brel_cont_l with "[$]"). iModIntro.
          iApply (brel_cont_r with "[$]"). 

          iDestruct "HNoneHSome" as "(_&HSome)".
          iDestruct ("HSome" with "Hautha") as "HS".
          iDestruct ("Hkont" with "HS") as "Hbrel".
          
          (* First call is done. Can call getKey1 or getKey2 again. *)
          iApply (brel_exhaustion' OS _ _ [_] [_] with "[$]"); [done|done|]. iApply "IH". }
    Qed.
  
End verification. 
